// SPDX-License-Identifier: AGPL-3.0-only
// Actual AU lifetime gates and separately marked protocol startup controls.
#pragma once
#include <atomic>
#include <future>
#include <unistd.h>

static Json lifetimeInstance(Json fx,const std::string& id,const char* mode=nullptr) {
    fx["id"]=id;if(mode)fx["description"]["name"]=mode;
    for(auto& p:fx["parameters"]){const auto sdk=p.at("sdk_id");p["id"]=digest(id+":parameter:"+(sdk.is_null()?"unaddressable-index:"+std::to_string(p.at("index").get<int>()):sdk.get<std::string>()));}
    return fx;
}
static double lifecycleMs(std::chrono::steady_clock::time_point start){return std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();}
static bool lifecycleWait(const std::function<bool()>& f,int ms){const auto until=std::chrono::steady_clock::now()+std::chrono::milliseconds(ms);do{if(f())return true;std::this_thread::sleep_for(std::chrono::milliseconds(1));}while(std::chrono::steady_clock::now()<until);return f();}
static fs::path lifecycleRoot(const fs::path& parent,const fs::path& original,const Json& session,const Json& fx,const char* name) {
    auto path=parent/name;fs::create_directories(path);const auto state=fx.at("state").at("path").get<std::string>();fs::create_directories((path/state).parent_path());fs::copy_file(original/state,path/state);
    for(const auto& source:session.at("sources")){const auto file=source.at("path").get<std::string>();fs::create_directories((path/file).parent_path());fs::copy_file(original/file,path/file);}return path;
}
static bool heldStartup(const fs::path& root) {
    const auto jobs=root/".plugin-runtime";if(!fs::exists(jobs))return false;
    for(const auto& d:fs::directory_iterator(jobs))if(fs::is_regular_file(d.path()/"held.json")){
        const auto j=readJson(d.path()/"held.json");return j.at("test_worker")==true && j.at("owner_pid")==pluginOwnerPid() && ::kill(j.at("pid").get<int>(),0)==0;
    }return false;
}
template<class Run>static void pluginLifecycleTests(Run run,const Json& session,const Json& fx,const fs::path& original,const fs::path& root,const fs::path& catalog,const fs::path& fixtureWorker) {
    check(drainPluginRetirements(1500),"Earlier retirement did not quiesce");
    run("PLUGIN-LIFETIME-01",[&]{auto folder=lifecycleRoot(root,original,session,fx,"lifetime-before");auto resources=std::make_shared<PluginResources>();PluginPreparation p;p.cancelled=[]{return true;};const auto hash=sha256(folder/fx.at("state").at("path").get<std::string>());
        fails("graph_cancelled",[&]{resources->acquire(fx,folder,48000,PluginProcessingMode::Realtime,&p);});check(resources->metrics().at("workers")==0 && !fs::exists(folder/".plugin-runtime") && hash==sha256(folder/fx.at("state").at("path").get<std::string>()),"Pre-admission cancel touched state or spawned a worker");return Json{{"cancel_before_spawn",true},{"state_unchanged",true},{"no_mock_audio_result",true}};});
    run("PLUGIN-LIFETIME-02",[&]{auto folder=lifecycleRoot(root,original,session,fx,"lifetime-startup");auto resources=std::make_shared<PluginResources>(8,64*1024*1024,fixtureWorker);auto fixture=lifetimeInstance(fx,"held-startup","_test_prepare_hold");std::atomic<bool> cancel{false},done{false};std::string code;PluginPreparation p;p.cancelled=[&]{return cancel.load();};
        std::thread loader([&]{try{resources->acquire(fixture,folder,48000,PluginProcessingMode::Realtime,&p);}catch(const Error& e){code=e.code;}done.store(true);});
        const bool live=lifecycleWait([&]{return heldStartup(folder);},5000);const auto began=std::chrono::steady_clock::now();cancel.store(true);const bool prompt=lifecycleWait([&]{return done.load();},100);loader.join();const auto returned=lifecycleMs(began);
        check(live && prompt && returned<=100 && code=="graph_cancelled","Held startup cancellation was slow or silently successful");check(drainPluginRetirements(1500) && resources->metrics().at("workers")==0,"Cancelled child reservation/mapping not released after reaping");return Json{{"test_worker",true},{"confirmed_live_owned_fixture",live},{"cancel_return_ms",returned},{"budget_ms",100},{"actual_exit_receipt",resources->metrics().at("recent_retirements")},{"state_unchanged",true}};});
    run("PLUGIN-LIFETIME-03",[&]{auto folder=lifecycleRoot(root,original,session,fx,"lifetime-deadline");auto resources=std::make_shared<PluginResources>(8,64*1024*1024,fixtureWorker);PluginPreparation p;p.deadline=std::chrono::steady_clock::now()+std::chrono::milliseconds(100);
        fails("plugin_admission_timeout",[&]{resources->acquire(lifetimeInstance(fx,"deadline","_test_prepare_hold"),folder,48000,PluginProcessingMode::Realtime,&p);});check(drainPluginRetirements(1500) && resources->metrics().at("workers")==0,"Expired admission leaked a native child");return Json{{"test_worker",true},{"shortened_deadline_control_ms",100},{"production_graph_budget_ms",10000},{"deadline_error_not_success",true}};});
    run("PLUGIN-LIFETIME-04",[&]{auto folder=lifecycleRoot(root,original,session,fx,"lifetime-eight-au");auto resources=std::make_shared<PluginResources>();std::vector<std::shared_ptr<PluginStream>> streams;PluginPreparation p;std::vector<int> pids;const auto startup=std::chrono::steady_clock::now();
        for(int i=0;i<8;++i){auto instance=lifetimeInstance(fx,"actual-lifetime-"+std::to_string(i));streams.push_back(resources->acquire(instance,folder,48000,PluginProcessingMode::Realtime,&p));const auto m=streams.back()->metrics();pids.push_back(m.at("owned_pid"));check(m.at("prepared").at("parameters").size()==fx.at("parameters").size() && ::kill(pids.back(),0)==0,"Genuine SDK child not ready/live");}
        const auto startupMs=lifecycleMs(startup);check(startupMs<=10000,"Eight actual AU startup exceeded aggregate budget");for(auto pid:pids)check(::kill(pid,SIGSTOP)==0,"Cannot pause the owned genuine SDK child");
        std::this_thread::sleep_for(std::chrono::milliseconds(75));for(auto pid:pids)check(::kill(pid,0)==0,"Supervisor killed a merely stopped genuine SDK child before retirement");
        const auto retired=std::chrono::steady_clock::now();streams.clear();const auto releaseMs=lifecycleMs(retired);check(releaseMs<=50,"Last-owner release synchronously waited for the plugin SDK");
        // A genuine independent resident uses the production realtime sample path
        // while the other eight supervisors are retiring. Initial pipeline only.
        auto activeResources=std::make_shared<PluginResources>(1);auto active=activeResources->acquire(lifetimeInstance(fx,"concurrent-live-au"),folder,48000,PluginProcessingMode::Realtime);
        bool processed=true;{RtAuditScope scope;for(int i=0;i<256;++i){double l=.02,r=.02;processed&=active->sample(l,r,i,true,false);}}check(processed,"Concurrent startup callback path failed");
        check(drainPluginRetirements(std::max(0,1500-static_cast<int>(lifecycleMs(retired)))),"Eight paused SDK children not concurrently reaped within budget");const auto elapsed=lifecycleMs(retired);check(elapsed<=1500,"Eight paused SDK retirement exceeded budget");const auto m=resources->metrics();check(m.at("workers")==0 && m.at("retiring_workers")==0 && m.at("quarantined_workers")==0 && m.at("recent_retirements").size()==8,"Reservations released early/leaked or lost retirement receipts");
        for(const auto& r:m.at("recent_retirements"))check(r.at("retirement_status")=="failed" && r.at("process_exit").at("reaped")==true && r.at("process_exit").at("signal")==SIGKILL && r.at("reservation_released")==true,"Forced SDK stop treated as normal DSP teardown");
        active.reset();check(drainPluginRetirements(1500),"Concurrent actual AU shutdown leaked");return Json{{"genuine_au_instances",8},{"external_fault_injection","SIGSTOP owned actual SDK children"},{"startup_ms",startupMs},{"startup_budget_ms",10000},{"last_owner_release_ms",releaseMs},{"ui_budget_ms",50},{"all_reaped_ms",elapsed},{"retire_budget_ms",1500},{"forced_exit_not_success",true},{"retirements",m.at("recent_retirements")},{"concurrent_scope","one 256-frame real parent sample startup scope; pipeline not yet audible; full device gates separate"},{"manual_desktop",false}};});
    run("PLUGIN-LIFETIME-05",[&]{auto folder=lifecycleRoot(root,original,session,fx,"lifetime-idempotent");auto resources=std::make_shared<PluginResources>();auto s=resources->acquire(lifetimeInstance(fx,"actual-idempotent"),folder,48000,PluginProcessingMode::Offline);const auto first=s->close();check(s->close()==first,"Successful close retry lost validated teardown receipt");s.reset();check(drainPluginRetirements(1500) && resources->metrics().at("workers")==0,"Normally closed actual SDK reservation leaked");
        auto controls=std::make_shared<PluginResources>(1,64*1024*1024,fixtureWorker);auto bad=controls->acquire(lifetimeInstance(fx,"crash-close","_test_after_response_crash"),folder,48000,PluginProcessingMode::Offline);fails("plugin_shutdown",[&]{bad->close();});fails("plugin_shutdown",[&]{bad->close();});bad.reset();check(drainPluginRetirements(1500),"Failed final response was not retired");return Json{{"genuine_normal_receipt_idempotent",true},{"test_worker_for_failure",true},{"failed_close_retry_remains_failure",true}};});
    run("PLUGIN-LIFETIME-06",[&]{auto folder=lifecycleRoot(root,original,session,fx,"lifetime-gui");auto changed=session;changed["tracks"][0]["processors"][0]["description"]["name"]="_test_prepare_hold";Commands c(changed,folder,catalog);auto resources=std::make_shared<PluginResources>(8,64*1024*1024,fixtureWorker);AudioEngine engine({},resources);engine.publishSession(c.query(),folder);check(lifecycleWait([&]{return heldStartup(folder);},5000),"Engine held startup never reached a live fixture child");
        const auto queried=std::chrono::steady_clock::now();const auto before=engine.metrics();const auto queryMs=lifecycleMs(queried);check(queryMs<=50 && before.at("preparing_graph_request").get<std::uint64_t>()>0,"GUI query blocked on SDK admission");double commitMs=0;NativeRoutingEditor editor([&](Json ops){const auto t=std::chrono::steady_clock::now();apply(c,std::move(ops),Actor::Gui);engine.publishSession(c.query(),folder);commitMs=lifecycleMs(t);},catalog);editor.update(c.query(),"audio");bool issued=false;
        for(auto* child:editor.getChildren())if(auto* button=dynamic_cast<juce::TextButton*>(child);button && button->getButtonText()=="Remove processor"){check(button->isEnabled(),"Actual native removal control disabled");button->onClick();issued=true;break;}
        check(issued && commitMs<=50 && c.query().at("tracks")[0].at("processors").empty(),"Native command failed or waited for SDK teardown");
        const bool ready=lifecycleWait([&]{const auto m=engine.metrics();return m.at("prepared_graph_request")==m.at("graph_request") && m.at("cancelled_preparations").get<std::uint64_t>()>0;},100);check(ready,"Superseded admission blocked/latest graph was not published within cancellation budget");
        const auto m=engine.metrics();check(m.at("prepared_session_revision")==c.query().at("revision") && m.at("last_cancelled_request").get<std::uint64_t>()<m.at("prepared_graph_request").get<std::uint64_t>(),"Stale graph replaced the human edit");
        c.undo();check(c.query().at("tracks")[0].at("processors")[0]==changed.at("tracks")[0].at("processors")[0],"Runtime cancellation rewrote Undo/session plugin references");check(drainPluginRetirements(1500),"Superseded fixture did not quiesce");return Json{{"actual_native_widget_callback",true},{"test_worker_for_startup_only",true},{"query_ms",queryMs},{"commit_publish_ms",commitMs},{"ui_budget_ms",50},{"cancelled_request",m.at("last_cancelled_request")},{"latest_prepared_request",m.at("prepared_graph_request")},{"human_edit_undo_preserved",true},{"manual_desktop",false},{"real_model",false}};});
    run("PLUGIN-LIFETIME-07",[&]{auto folder=lifecycleRoot(root,original,session,fx,"lifetime-engine-close");auto changed=session;changed["tracks"][0]["processors"][0]["description"]["name"]="_test_prepare_hold";auto resources=std::make_shared<PluginResources>(8,64*1024*1024,fixtureWorker);auto engine=std::make_unique<AudioEngine>(EngineConfig{},resources);engine->publishSession(changed,folder);check(lifecycleWait([&]{return heldStartup(folder);},5000),"Engine close control never reached held admission");const auto t=std::chrono::steady_clock::now();engine.reset();const auto returned=lifecycleMs(t);check(returned<=100 && drainPluginRetirements(1500) && resources->metrics().at("workers")==0,"Engine destruction waited on SDK or released a live mapping");return Json{{"test_worker",true},{"engine_return_ms",returned},{"budget_ms",100},{"no_device_open",true},{"full_app_quit_and_storage_stall_unqualified",true}};});
    run("PLUGIN-LIFETIME-08",[&]{auto folder=lifecycleRoot(root,original,session,fx,"lifetime-cancel-retry");auto changed=session;changed["tracks"][0]["processors"][0]["description"]["name"]="_test_prepare_hold";auto resources=std::make_shared<PluginResources>(8,64*1024*1024,fixtureWorker);AudioEngine engine({},resources);engine.publishSession(changed,folder);check(lifecycleWait([&]{return heldStartup(folder);},5000),"Explicit cancel control never reached held admission");const auto t=std::chrono::steady_clock::now();engine.cancelPreparation();const bool cancelled=lifecycleWait([&]{auto m=engine.metrics();return m.at("preparing_graph_request")==0 && m.at("cancelled_preparations").get<std::uint64_t>()>0;},100);const auto returned=lifecycleMs(t);check(cancelled && returned<=100,"Explicit preparation cancellation stayed pending");
        changed["tracks"][0]["processors"]=Json::array();++changed["revision"].get_ref<Json::number_unsigned_t&>();engine.publishSession(changed,folder);check(lifecycleWait([&]{auto m=engine.metrics();return m.at("prepared_graph_request")==m.at("graph_request");},100),"Fresh publication failed after cancellation");check(drainPluginRetirements(1500),"Explicitly cancelled child did not retire");return Json{{"test_worker",true},{"explicit_cancel_return_ms",returned},{"budget_ms",100},{"fresh_publication_allowed",true},{"committed_session_not_edited_by_cancel",true}};});
}
