// SPDX-License-Identifier: AGPL-3.0-only
// Genuine SDK parameter/audio gates; explicit malformed protocol controls.
#pragma once
template<class Run>static void pluginParameterTests(Run run,const Json& session,const Json& fx,const fs::path& original,const fs::path& root,const fs::path& catalogPath,const fs::path& fixtureWorker,PluginCatalog& catalog) {
    run("PLUGIN-PARAM-01",[&]{const std::string hash="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";check(pluginControlText(pluginControlToken(hash))==hash,"Control token lost SHA256 bits");auto other=hash;other.back()='0';check(pluginControlToken(other)!=pluginControlToken(hash),"Last token bits were ignored");fails("plugin_control",[&]{pluginControlToken(hash.substr(0,63));});fails("plugin_control",[&]{pluginControlToken(std::string(64,'g'));});
        auto folder=lifecycleRoot(root,original,session,fx,"parameters-reuse");auto resources=std::make_shared<PluginResources>(1);auto stream=resources->acquire(fx,folder,48000,PluginProcessingMode::Realtime);auto changed=fx;changed["parameters"][0]["value"]=.6;check(sessionPluginRuntimeToken(fx)==sessionPluginRuntimeToken(changed) && sessionPluginAudioToken(fx)!=sessionPluginAudioToken(changed),"Desired parameter state changed runtime identity or lost audio provenance");check(resources->acquire(changed,folder,48000,PluginProcessingMode::Realtime)==stream,"Parameter edit replaced actual SDK process");const auto pid=stream->metrics().at("owned_pid");stream->close();stream.reset();check(drainPluginRetirements(1500),"Actual parameter reuse child did not retire");return Json{{"real_plugin",true},{"all_256_token_bits",true},{"same_sdk_instance",true},{"owned_pid",pid},{"actual_parameter_delivery_gate","PLUGIN-PARAM-02"}};});
    run("PLUGIN-PARAM-02",[&]{auto folder=lifecycleRoot(root,original,session,fx,"parameters-audio");Commands c(session,folder,catalogPath);const auto known=root/"parameter-known.wav";constexpr int frames=65536;std::vector<float> input(frames);
        for(int i=0;i<frames;++i)input[i]=static_cast<float>(.04*std::sin(2*std::numbers::pi*200*i/48000)+.04*std::sin(2*std::numbers::pi*8000*i/48000));
        {auto writer=createBwfWriter(known,48000,2,0);const float* channels[]{input.data(),input.data()};check(writer->writeFromFloatArrays(channels,2,frames) && writer->flush(),"Known actual PCM write failed");}const auto hash=sha256(known),stateHash=sha256(folder/fx.at("state").at("path").get<std::string>());
        const auto lowFile=root/"parameter-low.wav",highFile=root/"parameter-high.wav";check(catalog.processFile(fx.at("catalog_plugin_id"),known,lowFile,Json::array({{{"id","0"},{"normalized",.05}}})).at("status")=="succeeded","Low actual SDK reference failed");check(catalog.processFile(fx.at("catalog_plugin_id"),known,highFile,Json::array({{{"id","0"},{"normalized",.6}}})).at("status")=="succeeded","High actual SDK reference failed");const auto low=readAudio(lowFile),high=readAudio(highFile);check(difference(low,high)>2e-6,"Actual parameter did not change reference PCM");
        apply(c,Json::array({{{"command","delete_clip"},{"clip_id","clip"}},{{"command","import_audio"},{"track_id","audio"},{"path",known.string()},{"position",0},{"source_id","long-source"},{"clip_id","long-clip"}}}));const auto baseline=c.query();
        auto resources=std::make_shared<PluginResources>(1);auto engine=std::make_unique<AudioEngine>(EngineConfig{},resources);engine->publishSession(baseline,folder);
        check(lifecycleWait([&]{const auto m=engine->metrics();return m.at("prepared_session_revision")==baseline.at("revision");},10000),"Actual initial graph admission failed");const int pid=resources->metrics().at("instances")[0].at("owned_pid");
        std::vector<float> live((frames+pluginPipeline)*2);std::atomic<Frame> produced{0};std::atomic<bool> finished{false},failed{false};Json changes=Json::array();Json issued;
        auto publish=[&](const Json& receipt,std::chrono::steady_clock::time_point began){const auto snapshot=c.query();const auto& current=snapshot.at("tracks")[0].at("processors")[0];const auto published=std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now().time_since_epoch()).count();engine->publishSession(snapshot,folder);changes.push_back({{"receipt",receipt},{"token",sessionPluginAudioToken(current)},{"commit_publish_ms",lifecycleMs(began)},{"published_ns",published}});};
        NativeRoutingEditor editor([&](Json ops){const auto began=std::chrono::steady_clock::now();issued=ops;publish(apply(c,ops,Actor::Gui),began);},catalogPath);editor.update(c.query(),"audio");engine->play(0);
        // The NRT GUI/JSON observer never supplies or stalls the audio cadence.
        // This exercises the production graph mailbox/source reader, not a
        // hand-maintained mixer or a fake device. Physical HAL remains separate.
        std::jthread driver([&](std::stop_token stop){std::array<float,64> l{},r{};float* outputs[]{l.data(),r.data()};auto next=std::chrono::steady_clock::now();const auto deadline=next+std::chrono::seconds(5);
            while(!stop.stop_requested() && std::chrono::steady_clock::now()<deadline){const auto at=engine->position();{RtAuditScope scope;engine->process(nullptr,0,outputs,2,64);}const auto end=engine->position();
                if(end>at){if(end-at!=64 || end>frames+pluginPipeline){failed.store(true);break;}for(int i=0;i<64;++i){live[(at+i)*2]=l[i];live[(at+i)*2+1]=r[i];}produced.store(end,std::memory_order_release);}
                if(engine->state()==PlaybackState::Failed){failed.store(true);break;}if(end>=frames+pluginPipeline)break;
                next+=std::chrono::nanoseconds(64ll*1000000000/48000);std::this_thread::sleep_until(next);
            }finished.store(true,std::memory_order_release);
        });
        int phase=0;while(!finished.load(std::memory_order_acquire)) {
            const auto at=produced.load(std::memory_order_acquire);
            if(phase==0 && at>=21824){bool slider=false,button=false;for(auto* child:editor.getChildren())if(auto* v=dynamic_cast<juce::Slider*>(child);v && v->getTextValueSuffix()==" normalized"){v->setValue(.6,juce::dontSendNotification);slider=true;}
                for(auto* child:editor.getChildren())if(auto* v=dynamic_cast<juce::TextButton*>(child);v && v->getButtonText()=="Apply plugin value"){v->onClick();button=true;}check(slider && button,"Actual native parameter callback missing");editor.update(c.query(),"audio");phase=1;
            }else if(phase==1 && at>=43712){const auto began=std::chrono::steady_clock::now();publish(c.undo(),began);editor.update(c.query(),"audio");phase=2;}
            const auto metrics=engine->metrics();const auto& actual=metrics.at("routing").at("plugins").at("instances")[0];check(actual.at("owned_pid")==pid && actual.at("fault")==0,"Parameter edit replaced/faulted actual SDK child");
            if(!changes.empty() && !changes.back().contains("output")){auto& change=changes.back();const auto& control=actual.at("parameter_control");if(control.at("sdk_snapshot_verified")==true && control.at("output_snapshot_verified")==true && control.at("acknowledged_token")==change.at("token") && control.at("returned_output_token")==change.at("token") && control.at("sdk_applied_ns").get<std::int64_t>()>=change.at("published_ns").get<std::int64_t>()){change["output"]=control;change["publication_to_instance_output_ms"]=(control.at("returned_ns").get<std::int64_t>()-change.at("published_ns").get<std::int64_t>())/1e6;}}
            editor.measured(metrics);if(!changes.empty() && changes.back().contains("output")){bool displayed=false;for(auto* child:editor.getChildren())if(auto* label=dynamic_cast<juce::Label*>(child);label && label->getText().startsWith("Plugin readback:"))displayed=label->getText().contains("output verified") && label->getText().contains(phase==1?"0.600000":"0.050000");check(displayed,"Native widget displayed stale/unverified SDK values");}
            juce::MessageManager::getInstance()->runDispatchLoopUntil(1);
        }
        driver.join();const auto audio=engine->metrics();check(!failed.load() && produced.load()==frames+pluginPipeline && changes.size()==2,"Independent production driver did not finish actual audio");
        // Persist measured diagnostics before asserting fixed timing budgets.
        atomicWrite(folder/"parameter-timing.json",Json{{"changes",changes},{"engine",audio}}.dump(2),false);
        for(const auto& change:changes)check(change.contains("output") && change.at("commit_publish_ms").get<double>()<=50 && change.at("publication_to_instance_output_ms").get<double>()>=0 && change.at("publication_to_instance_output_ms").get<double>()<=50,"Actual parameter/readback output budget failed; inspect parameter-timing.json");
        const Frame highAt=changes[0].at("output").at("sdk_input_sample"),undoAt=changes[1].at("output").at("sdk_input_sample");double maximumError=0;std::array<std::uint64_t,3> compared{};
        for(Frame source=8192;source<frames;++source){const int current=source<highAt?0:source<undoAt?1:2;const Frame start=current==0?0:current==1?highAt:undoAt;if(source<start+8192)continue;const auto& reference=current==1?high:low;for(int ch=0;ch<2;++ch)maximumError=std::max(maximumError,static_cast<double>(std::abs(live[(source+pluginPipeline)*2+ch]-reference[source*2+ch])));++compared[current];}
        check(maximumError<=2e-6 && std::all_of(compared.begin(),compared.end(),[](auto n){return n>=8192;}),"Live changed/Undo actual PCM differs from independent SDK references");
        Commands ai(baseline,root/"parameters-ai",catalogPath);const auto proposal=validateModelProposal(ai,Json{{"operations",issued}},ai.query().at("revision"),uuid());ai.approve(proposal);ai.commit(proposal);auto guiAfter=c.query();c.redo();auto actualAfter=c.query(),aiAfter=ai.query();actualAfter.erase("revision");aiAfter.erase("revision");check(actualAfter==aiAfter,"GUI and AI Actor produced different actual parameter targets");c.undo();auto restored=c.query();restored["revision"]=guiAfter.at("revision");check(restored==guiAfter,"Redo/Undo changed restored parameter state");
        c.save(folder/"session.ndaw");check(loadSession(folder/"session.ndaw")==c.query(),"Live parameter session did not reopen exactly");engine.reset();check(drainPluginRetirements(1500),"Actual parameter runtime retirement failed");const auto final=resources->metrics();check(final.at("retirement_failures")==0,"Acknowledged live parameters failed genuine SDK final readback");
        check(sha256(known)==hash && sha256(folder/fx.at("state").at("path").get<std::string>())==stateHash,"Live parameters overwrote original media or opaque state");return Json{{"real_plugin",true},{"actual_native_widget_callback",true},{"same_pid",pid},{"changed_real_pcm",true},{"pcm_max_error",maximumError},{"pcm_tolerance",2e-6},{"compared_frames",compared},{"changes",changes},{"sdk_change_input_samples",{highAt,undoAt}},{"save_reopen_undo",true},{"gui_ai_actor_equivalence",true},{"real_model",false},{"runtime",final},{"scope","independent paced 64-frame production AudioEngine/streaming/graph mailbox with genuine AU and file references; NRT native observer is separate; physical HAL and desktop mouse gates separate; no arbitrary vendor automation/smoothing claim"}};});
    run("PLUGIN-PARAM-03",[&]{Json receipts=Json::array();for(const char* kind:{"invalid_index","duplicate_index","nan_value"}) {auto folder=lifecycleRoot(root,original,session,fx,(std::string("parameters-bad-")+kind).c_str());auto resources=std::make_shared<PluginResources>();auto stream=resources->acquire(fx,folder,48000,PluginProcessingMode::Realtime);auto control=stream->controlSnapshot(fx);check(!control.values.empty(),"No actual SDK parameter");if(std::string(kind)=="invalid_index")control.values[0].index=pluginParameterLimit;else if(std::string(kind)=="duplicate_index")control.values.push_back(control.values[0]);else control.values[0].normalized=std::numeric_limits<float>::quiet_NaN();
            bool initial=true;{RtAuditScope scope;for(int i=0;i<256;++i){double l=.02,r=.02;initial&=stream->sample(l,r,i,true,false,nullptr,&control);}}check(initial && lifecycleWait([&]{return stream->failed();},1000),"Malformed actual SDK control was accepted");const auto m=stream->metrics();check(m.at("fault")==9 && m.at("parameter_control").at("sdk_snapshot_verified")==false && m.at("parameter_control").at("output_snapshot_verified")==false,"Bad control appeared acknowledged or returned");fails("plugin_shutdown",[&]{stream->close();});receipts.push_back({{"kind",kind},{"real_sdk_child",true},{"fault",m.at("fault")},{"false_success",false},{"process_exit",stream->metrics().at("process_exit")}});stream.reset();check(drainPluginRetirements(1500),"Malformed SDK control child not reaped");}return Json{{"controls",receipts},{"real_plugin",true},{"scope","internal malformed IPC fault injection into genuine worker; domain callers cannot address unenumerated indexes"}};});
    run("PLUGIN-PARAM-04",[&]{auto folder=lifecycleRoot(root,original,session,fx,"parameters-ack-control");auto fixture=lifetimeInstance(fx,"ack-mismatch","_test_control_mismatch");auto resources=std::make_shared<PluginResources>(1,64*1024*1024,fixtureWorker);auto stream=resources->acquire(fixture,folder,48000,PluginProcessingMode::Offline);bool rejected=false;for(int i=0;i<pluginPipeline+1;++i){double l=.02,r=.02;if(!stream->sample(l,r,i,true,false)){rejected=true;break;}}check(rejected && stream->metrics().at("fault")==9 && stream->metrics().at("parameter_control").at("output_snapshot_verified")==false,"Wrong last token word accepted as current audio");fails("plugin_shutdown",[&]{stream->close();});return Json{{"test_worker",true},{"mismatched_last_64_token_bits_rejected",true},{"scope","explicit ACK protocol negative control; no genuine DSP acceptance"}};});
    run("PLUGIN-PARAM-05",[&]{auto folder=lifecycleRoot(root,original,session,fx,"parameters-reset");auto resources=std::make_shared<PluginResources>();auto stream=resources->acquire(fx,folder,48000,PluginProcessingMode::Offline);Json receipts=Json::array();for(int round=0;round<3;++round){auto desired=fx;desired["parameters"][0]["value"]=round==1?.6:.05;auto control=stream->controlSnapshot(desired);
            for(int i=0;i<65+round*64;++i){double l=.02,r=.02;check(stream->sample(l,r,i,true,false,nullptr,&control),"Partial parameter quantum failed");}stream->reset();for(int i=0;i<4096;++i){double l=.02,r=.02;check(stream->sample(l,r,i,true,false,nullptr,&control),"Reset lost parameter snapshot");}const auto m=stream->metrics();const auto& c=m.at("parameter_control");check(c.at("sdk_snapshot_verified")==true && c.at("output_snapshot_verified")==true && c.at("acknowledged_token")==sessionPluginAudioToken(desired) && c.at("returned_output_token")==sessionPluginAudioToken(desired),"Reset published stale/missing actual parameter snapshot");receipts.push_back(c);}const auto close=stream->close();check(close.at("fault")==0,"Actual reset control final state rejected");return Json{{"real_plugin",true},{"partial_discard_and_resubmit_epochs",3},{"receipts",receipts},{"scope","NRT offline worker validates genuine parameter reset/readback; physical realtime budgets are separate"}};});
    run("PLUGIN-PARAM-06",[&]{auto folder=lifecycleRoot(root,original,session,fx,"parameters-lease");Commands c(session,folder,catalogPath);const auto ops=Json::array({{{"command","set_plugin_parameter"},{"track_id","audio"},{"processor_id",fx.at("id")},{"parameter_id","0"},{"normalized",.6}}});
        apply(c,Json::array({{{"command","set_track_arm"},{"track_id","audio"},{"record_armed",true}}}));const auto lease=c.beginCapture();fails("recording_busy",[&]{c.dryRun(ops,c.query().at("revision"),Actor::Gui,uuid());});apply(c,Json::array({{{"command","set_track_gain"},{"track_id","audio"},{"gain_db",-3}}}));c.endCapture(lease.at("lease_id"));
        auto stale=c.dryRun(ops,c.query().at("revision"),Actor::AI,uuid());c.approve(stale);apply(c,Json::array({{{"command","add_marker"},{"name","Human before AI"},{"position",100}}}));fails("version_conflict",[&]{c.commit(stale);});
        auto p=c.dryRun(ops,c.query().at("revision"),Actor::AI,uuid());c.approve(p);const auto receipt=c.commit(p);check(c.commit(p)==receipt,"Live control retry duplicated domain edit");apply(c,Json::array({{{"command","add_marker"},{"name","Human after AI"},{"position",200}}}));const auto markers=c.query().at("markers");c.undoTransaction(p.id);check(c.query().at("markers")==markers && c.query().at("tracks")[0].at("processors")[0].at("parameters")[0].at("value")==fx.at("parameters")[0].at("value"),"AI selective Undo erased later human edit or lost desired parameter");
        p=c.dryRun(ops,c.query().at("revision"),Actor::AI,uuid());c.approve(p);c.commit(p);auto human=ops;human[0]["normalized"]=.3;apply(c,human,Actor::Gui);fails("history_conflict",[&]{c.undoTransaction(p.id);});
        return Json{{"capture_lease_still_rejects_unqualified_live_plugin_parameters",true},{"unrelated_live_gain_allowed",true},{"stale_ai_plan_rejected",true},{"retry_idempotent",true},{"unrelated_later_human_marker_preserved",true},{"conflicting_later_human_parameter_rejected",true},{"real_model",false},{"scope","common domain/AI Actor history and capture policy; actual concurrent plugin/capture remains unexecuted"}};});
}
