// SPDX-License-Identifier: AGPL-3.0-only
#include "nativedaw/Audio.h"
#include "nativedaw/AI.h"
#include "nativedaw/NativeRoutingEditor.h"
#include "nativedaw/PluginPreview.h"
#include "nativedaw/RtAudit.h"
#include <iostream>
#include <numbers>
#include <thread>
#if JUCE_MAC
#include <signal.h>
#endif
using namespace ndaw;
static void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F>static void fails(const std::string& code,F f){try{f();}catch(const Error& e){if(e.code!=code)throw std::runtime_error("Expected "+code+", got "+e.code+": "+e.what());return;}throw std::runtime_error("Missing expected error: "+code);}
static Json apply(Commands& c,Json ops,Actor a=Actor::Cli){auto p=c.dryRun(ops,c.query().at("revision"),a,uuid());if(a==Actor::AI)c.approve(p);return c.commit(p);}
static std::vector<float> readAudio(const fs::path& path){juce::AudioFormatManager f;f.registerBasicFormats();std::unique_ptr<juce::AudioFormatReader> r(f.createReaderFor(juce::File(juce::String(path.string()))));check(r && r->numChannels==2 && r->usesFloatingPointData,"Actual float32 stereo file required");juce::AudioBuffer<float> b(2,static_cast<int>(r->lengthInSamples));check(r->read(&b,0,b.getNumSamples(),0,true,true),"Decode failed");std::vector<float> result;for(int i=0;i<b.getNumSamples();++i)for(int ch=0;ch<2;++ch)result.push_back(b.getSample(ch,i));return result;}
static double difference(const std::vector<float>& a,const std::vector<float>& b){check(a.size()==b.size(),"Frame/layout mismatch");double maximum=0;for(std::size_t i=0;i<a.size();++i){check(std::isfinite(a[i]) && std::isfinite(b[i]),"Non-finite actual PCM");maximum=std::max(maximum,static_cast<double>(std::abs(a[i]-b[i])));}return maximum;}
static Json legacyPlaylistShape(Json session,int version) {
    for(auto& track:session["tracks"]){track["clips"]=activeClips(track);track.erase("playlists");track.erase("active_playlist_id");track.erase("target_playlist_id");}
    session.erase("takes");session["schema_version"]=version;return session;
}
#if JUCE_MAC
#include "PluginLifecycleTests.h"
#include "PluginParameterTests.h"
#include "PluginStateTests.h"
#include "PluginEditorTests.h"
#endif
int main(int argc,char** argv) {
    juce::ScopedJuceInitialiser_GUI gui;if(argc!=2)return 2;const auto worker=fs::absolute(argv[1]);const auto root=fs::temp_directory_path()/("ndaw-plugin-session-"+uuid());fs::create_directories(root);
    Json checks=Json::array();int failures=0;auto run=[&](const char* id,auto f){try{checks.push_back({{"id",id},{"passed",true},{"receipt",f()}});}catch(const std::exception& e){++failures;checks.push_back({{"id",id},{"passed",false},{"error",e.what()}});}};
#if JUCE_MAC
    const auto input=root/"original.wav",catalogPath=root/"catalog";std::vector<float> original(8192*2);
    {auto writer=createBwfWriter(input,48000,2,0);std::array<float,8192> samples{};for(int i=0;i<8192;++i){samples[i]=static_cast<float>(.04*std::sin(2*std::numbers::pi*200*i/48000)+.04*std::sin(2*std::numbers::pi*8000*i/48000));original[i*2]=original[i*2+1]=samples[i];}const float* channels[]{samples.data(),samples.data()};check(writer->writeFromFloatArrays(channels,2,samples.size()) && writer->flush(),"Known PCM file creation failed");}
    const auto inputHash=sha256(input);PluginCatalog catalog(catalogPath);Json plugin;
    run("PLUGIN-PROJECT-00",[&]{auto receipt=catalog.scan("AudioUnit","AudioUnit:Effects/aufx,lpas,appl");check(receipt.at("status")=="verified","Actual Apple AU scan failed");plugin=receipt.at("entry").at("plugins")[0];return Json{{"real_plugin",true},{"name",plugin.at("name")},{"version",plugin.at("version")},{"parameters",plugin.at("parameters").size()}};});
    if(!plugin.is_null()) {
        auto initial=newSession("Plugin project tests");const auto setup=Json::array({{{"command","add_audio_track"},{"id","audio"},{"name","Actual PCM"}},{{"command","import_audio"},{"track_id","audio"},{"path",input.string()},{"position",0},{"source_id","source"},{"clip_id","clip"}}});
        auto insert=Json::array({{{"command","insert_plugin"},{"track_id","audio"},{"plugin_id",plugin.at("id")},{"id","plugin-instance"}}});
        Json session;fs::path projectRoot=root/"actual";
        run("PLUGIN-SESSION-01",[&]{Commands c(initial,projectRoot,catalogPath);apply(c,setup);const auto before=c.query();const auto plan=c.dryRun(insert,before.at("revision"),Actor::Gui,uuid());const auto& fx=plan.after.at("tracks")[0].at("processors")[0];const auto state=projectRoot/fx.at("state").at("path").get<std::string>();
            check(!fs::exists(state) && !plan.diff.empty(),"Preview changed storage or omitted diff");c.commit(plan);check(fs::is_regular_file(state) && sha256(state)==fx.at("state").at("sha256").get<std::string>(),"Opaque state was not transactionally captured");const auto after=c.query();c.undo();auto undone=c.query();undone["revision"]=before.at("revision");check(undone==before && fs::is_regular_file(state),"Undo deleted media/state or changed previous state");c.redo();session=c.query();session["revision"]=after.at("revision");check(session==after,"Redo changed stable plugin/parameter IDs/state");c.save(projectRoot/"session.ndaw");session=c.query();check(loadSession(projectRoot/"session.ndaw")==session,"Save/reopen changed plugin state");return Json{{"stable_plugin_and_parameter_ids",true},{"hash_bound_state",true},{"preview_commit_undo_redo_reopen",true},{"real_plugin",true}};});
        run("PLUGIN-SESSION-02",[&]{Commands c(loadSession(projectRoot/"session.ndaw"),projectRoot,catalogPath);auto ops=Json::array({{{"command","set_plugin_parameter"},{"track_id","audio"},{"processor_id","plugin-instance"},{"parameter_id","0"},{"normalized",.05}}});
            const auto inventory=c.pluginInventory();check(inventory.at("plugins").size()==1 && inventory.at("plugins")[0].at("id")==plugin.at("id"),"Model inventory invented/dropped actual plugin ID");const auto facts=modelFacts(c.query());const auto& modelFx=facts.at("tracks")[0].at("processors")[0];check(!modelFx.at("state").contains("path") && !modelFx.at("description").contains("description_xml") && !modelFx.at("description").contains("file_or_identifier") && modelFx.contains("parameter_value_scope"),"Private plugin paths leaked or desired state appeared measured");
            auto p=validateModelProposal(c,Json{{"operations",ops}},c.query().at("revision"),uuid());fails("approval_required",[&]{Scope scope;scope.mode=Permission::ScopedLowRisk;scope.targets.insert("audio");c.commit(p,scope);});fails("permission",[&]{Scope scope;scope.mode=Permission::ReadOnly;c.commit(p,scope);});
            c.approve(p);const auto receipt=c.commit(p);check(c.commit(p)==receipt,"AI retry duplicated plugin edit");auto unknown=ops;unknown[0]["parameter_id"]="warmth";fails("plugin_parameter",[&]{c.dryRun(unknown,c.query().at("revision"),Actor::AI,uuid());});
            auto stale=c.dryRun(Json::array({{{"command","set_track_gain"},{"track_id","audio"},{"gain_db",-3}}}),c.query().at("revision"),Actor::AI,uuid());apply(c,Json::array({{{"command","add_marker"},{"name","Human"},{"position",256}}}));c.approve(stale);fails("version_conflict",[&]{c.commit(stale);});
            apply(c,Json::array({{{"command","set_processor_lock"},{"track_id","audio"},{"processor_id","plugin-instance"},{"locked",true}}}));fails("locked",[&]{c.dryRun(ops,c.query().at("revision"),Actor::AI,uuid());});c.undo();c.save(projectRoot/"session.ndaw");session=c.query();
            return Json{{"actual_sdk_id_only",true},{"explicit_acceptance",true},{"idempotency_version_conflict_lock",true},{"real_model",false},{"scope","AI Actor/domain contract; no inference service"}};});
        run("PLUGIN-PDC-05",[&]{const auto direct=root/"direct.wav",rendered=root/"project.wav",reopened=root/"reopened.wav";const auto r=catalog.processFile(plugin.at("id"),input,direct,Json::array({{{"id","0"},{"normalized",.05}}}));check(r.at("status")=="succeeded","Actual reference AU file processing failed");
            const auto a=renderToFile(session,projectRoot,rendered,0,8192),b=renderToFile(loadSession(projectRoot/"session.ndaw"),projectRoot,reopened,0,8192);const auto pcm=readAudio(rendered);const auto directDifference=difference(pcm,readAudio(direct)),reopenDifference=difference(pcm,readAudio(reopened));check(directDifference<=2e-6 && reopenDifference<=2e-6,"Real SDK/IPC preroll, state or reopen changed aligned audio");
            check(a.at("routing").at("algorithmic_latency_frames")==1024 && a.at("plugins")[0].at("process_exit").at("reaped")==true && a.at("plugins")[0].at("fault")==0,"Actual latency/teardown verification missing");
            return Json{{"real_plugin",true},{"pipeline_latency",1024},{"sdk_latency",plugin.at("reported_latency_frames")},{"reference_pcm_max_error",directDifference},{"reopen_pcm_max_error",reopenDifference},{"frames",8192},{"original_hash_unchanged",sha256(input)==inputHash},{"scope","genuine zero-SDK-latency AU plus fixed IPC delay; other/nonzero-SDK-latency plugins unqualified"}};});
        run("PLUGIN-PDC-06",[&]{Commands c(session,root/"parallel",catalogPath); // Copy immutable source/state explicitly for the new project folder.
            for(const auto& src:session.at("sources")){const auto to=c.root()/src.at("path").get<std::string>();fs::create_directories(to.parent_path());fs::copy_file(projectRoot/src.at("path").get<std::string>(),to);}
            const auto state=session.at("tracks")[0].at("processors")[0].at("state").at("path").get<std::string>();fs::create_directories((c.root()/state).parent_path());fs::copy_file(projectRoot/state,c.root()/state);
            apply(c,Json::array({{{"command","set_track_gain"},{"track_id","audio"},{"gain_db",-6.020599913279624}},{{"command","add_audio_track"},{"id","dry"},{"name","Dry"}},{{"command","import_audio"},{"track_id","dry"},{"path",input.string()},{"position",0}},{{"command","set_track_gain"},{"track_id","dry"},{"gain_db",-6.020599913279624}}}));
            const auto receipt=renderToFile(c.query(),c.root(),root/"parallel.wav",0,8192);auto expected=readAudio(root/"project.wav");for(std::size_t i=0;i<expected.size();++i)expected[i]=static_cast<float>((expected[i]+original[i])*.5);const auto d=difference(expected,readAudio(root/"parallel.wav"));check(d<=2e-6,"Actual dry/SDK parallel path misaligned");
            bool compensated=false;for(const auto& route:receipt.at("routing").at("routes"))if(route.at("from")=="dry" && route.at("compensation_frames")==1024)compensated=true;check(compensated,"Dry route did not receive actual pipeline compensation");return Json{{"real_plugin",true},{"pcm_max_error",d},{"dry_compensation_frames",1024}};});
        run("GUI-PLUGIN-02",[&]{Commands c(initial,root/"gui",catalogPath);apply(c,setup);const auto before=c.query();Json issued=Json::array();NativeRoutingEditor editor([&](Json ops){auto p=c.dryRun(ops,c.query().at("revision"),Actor::Gui,uuid());for(const auto& op:p.operations)issued.push_back(op);c.commit(p);},catalogPath);editor.update(before,"audio");
            auto click=[&](const char* text){for(auto* child:editor.getChildren())if(auto* b=dynamic_cast<juce::TextButton*>(child);b && b->getButtonText()==text){check(b->isEnabled(),"Native plugin control disabled");b->onClick();return;}throw std::runtime_error("Native plugin control missing");};click("Insert AU/VST3");editor.update(c.query(),"audio");bool value=false;for(auto* child:editor.getChildren())if(auto* s=dynamic_cast<juce::Slider*>(child);s && s->getTextValueSuffix()==" normalized"){s->setValue(.05,juce::dontSendNotification);value=true;}check(value,"Actual parameter slider missing");click("Apply plugin value");editor.update(c.query(),"audio");
            Commands ai(before,root/"ai-equivalence",catalogPath); // its media is not needed for domain-equivalence, then copied before actual render
            const auto plan=validateModelProposal(ai,Json{{"operations",issued}},before.at("revision"),uuid());ai.approve(plan);ai.commit(plan);auto a=c.query(),b=ai.query();a.erase("revision");b.erase("revision");check(a==b,"GUI and AI commands produced different plugin state");
            const auto receipt=renderToFile(c.query(),c.root(),root/"gui-actual.wav",0,8192);check(difference(readAudio(root/"gui-actual.wav"),readAudio(root/"project.wav"))<=2e-6,"Native plugin callbacks were not connected to actual rendered audio");ai.undo();auto undone=ai.query();undone["revision"]=before.at("revision");check(undone==before,"AI Undo changed pre-GUI state");editor.resized();return Json{{"actual_native_callbacks",true},{"real_sdk_audio",true},{"gui_ai_plan_state_equivalence",true},{"ai_whole_task_undo",true},{"real_model",false},{"manual_mouse_workflow",false}};});
        run("PLUGIN-MISSING-01",[&]{const auto file=projectRoot/"session.ndaw";const auto hash=sha256(file);auto copy=session;auto& fx=copy["tracks"][0]["processors"][0];const auto old=fx;fx["description"]["file_or_identifier"]="/definitely-missing/ActualPlugin.vst3";fx["description"]["format"]="VST3";validateSession(copy);saveSession(root/"missing.ndaw",copy,false);check(loadSession(root/"missing.ndaw")==copy,"Missing module erased session content");fails("plugin_missing",[&]{RenderGraph graph(copy,projectRoot);});
            const auto state=projectRoot/old.at("state").at("path").get<std::string>();const auto backup=state.string()+".backup";fs::rename(state,backup);fails("plugin_state",[&]{RenderGraph graph(session,projectRoot);});fs::rename(backup,state);check(sha256(file)==hash && sha256(input)==inputHash,"Missing-plugin failure changed originals");
            Commands c(copy,root/"missing-edit",catalogPath);apply(c,Json::array({{{"command","remove_processor"},{"track_id","audio"},{"processor_id","plugin-instance"}}}));c.undo();check(c.query().at("tracks")[0].at("processors")[0]==fx,"Missing plugin Undo lost original state");return Json{{"original_reference_and_opaque_state_preserved",true},{"render_rejected",true},{"remove_undo_restores",true}};});
        run("MIGRATE-03",[&]{auto legacy=legacyPlaylistShape(initial,3);const auto file=root/"legacy-3.ndaw";atomicWrite(file,Json{{"format","NativeDAW"},{"session",legacy},{"checksum",digest(legacy.dump())}}.dump(),false);const auto hash=sha256(file);auto migrated=loadSession(file);auto expected=initial;check(migrated==expected && sha256(file)==hash,"Schema-3 migration changed content/original");return Json{{"schema_3_to_5",true},{"unchanged_previous_fields",true},{"original_not_overwritten",true}};});
        const auto fx=session.at("tracks")[0].at("processors")[0];
        run("PLUGIN-REAL-FAILURE-01",[&]{const auto state=projectRoot/fx.at("state").at("path").get<std::string>();const auto hash=sha256(state);auto resources=std::make_shared<PluginResources>();auto stream=resources->acquire(fx,projectRoot,48000,PluginProcessingMode::Realtime);const auto before=stream->metrics();const int pid=before.at("owned_pid");check(pid>0 && before.at("exited")==false,"No owned genuine SDK child");check(::kill(pid,SIGKILL)==0,"Cannot inject owned genuine child termination");
            const auto until=std::chrono::steady_clock::now()+std::chrono::seconds(1);while(!stream->failed() && std::chrono::steady_clock::now()<until)std::this_thread::sleep_for(std::chrono::milliseconds(1));check(stream->failed() && stream->metrics().at("fault")==5,"Genuine SDK process termination appeared usable");double l=.1,r=.1;{RtAuditScope scope;check(!stream->sample(l,r,0,true,false),"Dead genuine SDK child returned success");}fails("plugin_shutdown",[&]{stream->close();});const auto receipt=stream->metrics();check(receipt.at("process_exit").at("signal")==SIGKILL && receipt.at("process_exit").at("reaped")==true && sha256(state)==hash && sha256(input)==inputHash,"Genuine termination lost signal/state/original");return Json{{"real_sdk_instance",true},{"injected_signal",SIGKILL},{"process",receipt.at("process_exit")},{"references_state_and_original_preserved",true},{"scope","owned genuine AU child killed externally; not evidence of a spontaneous vendor DSP crash or successful reload/editor recovery"}};});
        run("PLUGIN-IPC-01",[&]{Json receipts=Json::array();for(const auto* name:{"_test_nan","_test_stale","_test_crash","_test_late"}){
            auto fixture=fx;fixture["id"]="fixture";for(auto& p:fixture["parameters"])p["id"]=digest(std::string("fixture:parameter:")+p.at("sdk_id").get<std::string>());fixture["description"]["name"]=name;auto resources=std::make_shared<PluginResources>(1,64*1024*1024,worker);const auto mode=std::string(name)=="_test_late"?PluginProcessingMode::Realtime:PluginProcessingMode::Offline;auto stream=resources->acquire(fixture,projectRoot,48000,mode);bool failed=false;
                auto samples=[&]{for(int i=0;i<pluginPipeline+1;++i){double l=.1,r=.2;if(!stream->sample(l,r,i,true,false)){failed=true;break;}}};
                if(mode==PluginProcessingMode::Realtime){RtAuditScope scope;samples();}else samples(); // Offline waits are deliberately NRT.
            check(failed,"Test worker bad/stale/late/crashed output accepted");const auto m=stream->metrics();const auto expected=std::string(name)=="_test_nan"?4:std::string(name)=="_test_stale"?3:std::string(name)=="_test_late"?1:5;check(m.at("fault")==expected,"Wrong shared fault classification");fails("plugin_shutdown",[&]{stream->close();});const auto after=stream->metrics();check(after.at("process_exit").at("reaped")==true,"Fault worker was not reaped");receipts.push_back({{"mode",name},{"fault",after.at("fault")},{"misses",after.at("deadline_misses")},{"process",after.at("process_exit")},{"test_worker",true}});}
            return Json{{"controls",receipts},{"scope","explicit protocol fault worker; not genuine DSP/audio acceptance"}};});
        run("PLUGIN-IPC-02",[&]{auto fixture=fx;fixture["description"]["name"]="_test_after_response_crash";auto resources=std::make_shared<PluginResources>(1,64*1024*1024,worker);auto stream=resources->acquire(fixture,projectRoot,48000,PluginProcessingMode::Offline);for(int i=0;i<2048;++i){double l=.1,r=.1;check(stream->sample(l,r,i,true,false),"Fixture failed before teardown");}fails("plugin_shutdown",[&]{stream->close();});check(stream->metrics().at("process_exit").at("status")=="crashed","Post-success-JSON signal accepted");return Json{{"crash_after_shutdown_response_rejected",true},{"test_worker",true}};});
        run("PLUGIN-IPC-03",[&]{auto fixture=fx;fixture["description"]["name"]="_test_heartbeat";auto resources=std::make_shared<PluginResources>(1,64*1024*1024,worker);auto stream=resources->acquire(fixture,projectRoot,48000,PluginProcessingMode::Realtime);const auto until=std::chrono::steady_clock::now()+std::chrono::milliseconds(1000);while(!stream->failed() && std::chrono::steady_clock::now()<until)std::this_thread::sleep_for(std::chrono::milliseconds(5));check(stream->failed() && stream->metrics().at("fault")==6,"Heartbeat-stalled worker remained usable");fails("plugin_shutdown",[&]{stream->close();});return Json{{"heartbeat_budget_ms",500},{"terminated_and_reaped",stream->metrics().at("process_exit").at("reaped")},{"test_worker",true}};});
        run("PLUGIN-IPC-04",[&]{auto fixture=fx;fixture["description"]["name"]="_test_normal";auto resources=std::make_shared<PluginResources>(1,64*1024*1024,worker);auto stream=resources->acquire(fixture,projectRoot,48000,PluginProcessingMode::Offline);check(stream==resources->acquire(fixture,projectRoot,48000,PluginProcessingMode::Offline),"Unchanged graph duplicated live SDK instance");auto changed=fixture;changed["parameters"][0]["value"]=.6;fails("plugin_resources",[&]{resources->acquire(changed,projectRoot,48000,PluginProcessingMode::Offline);});
            for(int round=0;round<12;++round){stream->reset();for(int i=0;i<3073;++i){double l=.1,r=.2;check(stream->sample(l,r,i,true,false),"Reset/epoch broke ownership");if(i>=pluginPipeline){check(std::abs(l-.1)<=1e-6 && std::abs(r-.2)<=1e-6,"Old-epoch samples leaked");}}}
            const auto receipt=stream->close();check(receipt.at("fault")==0 && receipt.at("process_exit").at("reaped")==true,"Normal fixture shutdown failed");stream.reset();check(drainPluginRetirements(1500),"Retirement drain timed out");check(resources->metrics().at("workers")==0,"Worker admission leaked");return Json{{"reset_epochs",12},{"unchanged_graph_reuses_instance",true},{"resource_admission_explicit",true},{"no_old_epoch_audio",true},{"test_worker",true}};});
        run("PLUGIN-PDC-07",[&]{auto s=session;auto& fixture=s["tracks"][0]["processors"][0];fixture["description"]["name"]="_test_latency32";fixture["description"]["reported_latency_frames"]=32;auto resources=std::make_shared<PluginResources>(2,64*1024*1024,worker);RoutingMixer mixer(s,{},projectRoot,PluginProcessingMode::Offline,resources);std::array<float,256> l{},r{};Frame emitted=0;double error=0;for(Frame at=0;at<8192+1056;at+=256){const int n=static_cast<int>(std::min<Frame>(256,8192+1056-at));mixer.begin(n);for(int i=0;i<n;++i)if(at+i<8192){mixer.add(0,1,i,original[(at+i)*2]);mixer.add(0,2,i,original[(at+i)*2+1]);}check(mixer.finish(n,l.data(),r.data()),"Reported-latency fixture failed");for(int i=0;i<n;++i)if(at+i>=1056){const auto source=at+i-1056;error=std::max(error,static_cast<double>(std::abs(l[i]-original[source*2])));++emitted;}}
            check(mixer.latency()==1056 && emitted==8192 && error<=2e-6,"Reported algorithmic plus IPC alignment failed");mixer.closeOfflinePlugins();return Json{{"reported_sdk_latency_fixture",32},{"ipc_latency",1024},{"frames",emitted},{"pcm_max_error",error},{"test_worker",true},{"scope","explicit delay protocol control; nonzero-latency genuine third-party plugin remains unqualified"}};});
        pluginLifecycleTests(run,session,fx,projectRoot,root,catalogPath,worker);
        pluginParameterTests(run,session,fx,projectRoot,root,catalogPath,worker,catalog);
        pluginStateTests(run,session,fx,projectRoot,root,catalogPath);
        pluginEditorTests(run,session,fx,projectRoot,root,catalogPath);
    }
#else
    checks.push_back({{"id","PLUGIN-PROJECT-PLATFORM"},{"executed",false},{"reason","No corresponding genuine plugin on this platform; Apple AU gate is macOS only"}});
#endif
#if NATIVEDAW_RT_AUDIT
    run("PLUGIN-RT-AUDIT-01",[&]{const auto audit=rtAuditMetrics();check(audit.at("scopes").get<std::uint64_t>()>0,"No audited RT scope");for(const auto* name:{"allocation","free","blocking_lock_wait","file_network","device_property_control"})check(audit.at(name)==0,"Plugin callback used prohibited API");return audit;});
#endif
    const auto result=Json{{"status",failures?"failed":"passed"},{"checks",checks},{"failures",failures},{"directory",root.string()},{"actual_model",false},{"manual_desktop",false},
        {"scope","genuine Apple AU session/offline/native-widget gates; explicit IPC fault controls separately labeled; physical device gates are separate"}};
    std::cout<<result.dump(2)<<'\n';// Keep private run/state/fault receipts for inspectable evidence; packaging excludes them.
    return failures?1:0;
}
