// SPDX-License-Identifier: AGPL-3.0-only
#pragma once
template<class Run>static void pluginStateTests(Run run,const Json& session,const Json& fx,const fs::path& original,const fs::path& root,const fs::path& catalogPath) {
    Json baseline,captureFacts;fs::path capturedRoot;
    run("PLUGIN-STATE-01",[&]{
        capturedRoot=lifecycleRoot(root,original,session,fx,"state-resident");Commands c(session,capturedRoot,catalogPath);
        apply(c,Json::array({{{"command","set_plugin_parameter"},{"track_id","audio"},{"processor_id",fx.at("id")},{"parameter_id","0"},{"normalized",.6}},{{"command","set_track_arm"},{"track_id","audio"},{"record_armed",true}}}));baseline=c.query();c.save(capturedRoot/"before-capture.ndaw");
        const auto stateHash=sha256(capturedRoot/fx.at("state").at("path").get<std::string>());const auto mediaHash=sha256(mediaPath(capturedRoot,baseline.at("sources")[0]));
        const auto beforeAudio=root/"state-before.wav";renderToFile(baseline,capturedRoot,beforeAudio,0,8192);
        auto resources=std::make_shared<PluginResources>(1);AudioEngine engine({},resources);engine.publishSession(baseline,capturedRoot);engine.play(0);
        std::atomic<bool> failed{false};std::jthread driver([&](std::stop_token stop){std::array<float,64> l{},r{};float* output[]{l.data(),r.data()};auto next=std::chrono::steady_clock::now();while(!stop.stop_requested()){ {RtAuditScope scope;engine.process(nullptr,0,output,2,64);}if(engine.state()==PlaybackState::Failed)failed.store(true);next+=std::chrono::nanoseconds(64ll*1000000000/48000);std::this_thread::sleep_until(next);}});
        check(lifecycleWait([&]{auto m=resources->metrics();return !m.at("instances").empty() && m.at("instances")[0].at("parameter_control").at("output_snapshot_verified")==true && engine.state()==PlaybackState::Stopped;},10000),"Genuine resident processing did not finish before state capture");
        const auto pid=resources->metrics().at("instances")[0].at("owned_pid");auto capture=engine.capturePluginState(baseline,capturedRoot,"audio",fx.at("id"));const auto timing=capture.facts().at("capture_timing");
        check(timing.at("callback_quiescence_ms").get<double>()<=250 && timing.at("preparer_ack_ms").get<double>()<=1500 && timing.at("sdk_capture_exit_reap_ms").get<double>()<=1500 && timing.at("complete_suspend_capture_ms").get<double>()<=4000,"Predeclared stopped capture budgets failed");
        check(capture.facts().at("owned_pid")==pid && capture.facts().at("process_exit").at("reaped")==true && capture.facts().at("process_exit").at("exit_code")==0,"Capture is not the actual normally reaped resident child");
        fails("plugin_capture_pending",[&]{engine.play(0);});fails("plugin_capture_pending",[&]{engine.publishSession(baseline,capturedRoot);});
        const auto began=std::chrono::steady_clock::now();captureFacts=c.retainPluginState(capture);const auto id=captureFacts.at("capture_id").get<std::string>();
        check(captureFacts.at("state_sha256")!=fx.at("state").at("sha256"),"Actual changed DSP state was replaced by the initial opaque state");
        const auto facts=c.pluginStateCaptures();check(facts.at("captures").size()==1 && facts.dump().find(".plugin-runtime")==std::string::npos && facts.dump().find("state.bin")==std::string::npos,"Model-facing state query leaked a private path");
        const auto ops=Json::array({{{"command","adopt_plugin_state"},{"track_id","audio"},{"processor_id",fx.at("id")},{"capture_id",id}}});
        auto plan=validateModelProposal(c,Json{{"operations",ops}},baseline.at("revision"),uuid());Scope low;low.mode=Permission::ScopedLowRisk;low.targets.insert("audio");fails("approval_required",[&]{c.commit(plan,low);});Scope ro;ro.mode=Permission::ReadOnly;fails("permission",[&]{c.commit(plan,ro);});
        check(c.query()==baseline && !plan.diff.empty(),"Captured state query/preview edited the project");c.approve(plan);const auto receipt=c.commit(plan);check(c.commit(plan)==receipt,"DSP adoption retry duplicated the transaction");const double commitMs=lifecycleMs(began);check(commitMs<=1000,"Retention/preview/commit exceeded 1000 ms");
        auto after=c.query();const auto& changed=after.at("tracks")[0].at("processors")[0];check(changed.at("state").at("sha256")==captureFacts.at("state_sha256") && changed.at("parameters")==baseline.at("tracks")[0].at("processors")[0].at("parameters"),"DSP adoption lost desired parameter IDs/values");
        // The ready receipt records SDK values immediately after opaque restore,
        // before every desired-value overlay. This cannot pass with initial bytes.
        auto restore=resources->acquire(changed,capturedRoot,48000,PluginProcessingMode::Offline);const auto prepared=restore->metrics().at("prepared");bool opaqueRestored=false;
        for(const auto& p:prepared.at("parameters_after_state_restore"))if(p.at("id")=="0")opaqueRestored=std::abs(p.at("value").get<double>()-.6)<=1e-6;
        check(opaqueRestored,"Captured opaque bytes did not restore actual changed SDK value before overlays");restore->close();restore.reset();check(drainPluginRetirements(1500),"Opaque restore worker did not retire");
        const auto afterAudio=root/"state-after.wav";renderToFile(after,capturedRoot,afterAudio,0,8192);const auto error=difference(readAudio(beforeAudio),readAudio(afterAudio));check(error<=2e-6,"Adopted DSP state changed actual finite audio unexpectedly");
        c.save(capturedRoot/"session.ndaw");check(loadSession(capturedRoot/"session.ndaw")==after,"Saved DSP capture did not reopen exactly");c.undo();check(c.query().at("tracks")[0].at("processors")[0].at("state")==fx.at("state"),"Whole-task Undo lost the previous opaque reference");c.redo();check(c.query().at("tracks")[0].at("processors")[0].at("state")==changed.at("state"),"Redo lost the captured opaque reference");
        engine.resumeAfterPluginCapture(c.query(),capturedRoot);check(lifecycleWait([&]{const auto m=resources->metrics();return !m.at("instances").empty() && m.at("instances")[0].at("parameter_control").at("output_snapshot_verified")==true;},10000),"Restored production graph did not acknowledge captured state");check(!failed.load(),"Stopped capture/recovery faulted the production engine");driver.request_stop();driver.join();
        check(sha256(capturedRoot/fx.at("state").at("path").get<std::string>())==stateHash && sha256(mediaPath(capturedRoot,baseline.at("sources")[0]))==mediaHash,"Capture overwrote original opaque state/media");
        return Json{{"real_plugin",true},{"actual_resident_pid",pid},{"capture",captureFacts},{"timing",timing},{"retention_preview_commit_ms",commitMs},{"sdk_opaque_restore_before_overlay",opaqueRestored},{"pcm_max_error",error},{"pcm_tolerance",2e-6},{"frames",8192},{"save_reopen_undo_redo",true},{"originals_immutable",true},{"real_model",false},{"scope","paced production engine + genuine AU private state/normal exit, common AI Actor permission/history; physical device and native desktop separately required"}};
    });
    run("PLUGIN-STATE-02",[&]{
        check(!captureFacts.is_null(),"Required genuine state capture is unavailable");const auto folder=lifecycleRoot(root,original,baseline,fx,"state-conflicts");fs::copy(capturedRoot/".plugin-state-captures",folder/".plugin-state-captures",fs::copy_options::recursive);
        Commands c(baseline,folder,catalogPath);const auto id=captureFacts.at("capture_id").get<std::string>();const auto ops=Json::array({{{"command","adopt_plugin_state"},{"track_id","audio"},{"processor_id",fx.at("id")},{"capture_id",id}}});
        auto p=c.dryRun(ops,c.query().at("revision"),Actor::AI,uuid());c.approve(p);apply(c,Json::array({{{"command","add_marker"},{"name","Human edit during state preview"},{"position",100}}}));const auto human=c.query();fails("version_conflict",[&]{c.commit(p);});fails("version_conflict",[&]{c.dryRun(ops,c.query().at("revision"),Actor::AI,uuid());});check(c.query()==human,"Stale capture overwrote the human edit");
        auto bad=ops;bad[0]["capture_id"]="../../outside";fails("plugin_capture_id",[&]{c.dryRun(bad,c.query().at("revision"),Actor::AI,uuid());});bad=ops;bad[0]["path"]="/untrusted/state.bin";fails("schema",[&]{c.dryRun(bad,c.query().at("revision"),Actor::AI,uuid());});
        const auto damaged=folder/".plugin-state-captures"/id/"state.bin";atomicWrite(damaged,"changed",true);fails("plugin_capture_state",[&]{readPluginStateCapture(folder,id);});check(c.pluginStateCaptures().at("captures").empty() && c.pluginStateCaptures().at("unavailable").size()==1,"Changed captured bytes appeared available");
        return Json{{"real_capture_receipt_reused_for_conflict_tests",true},{"stale_capture_and_preview_rejected",true},{"later_human_edit_preserved",true},{"model_path_rejected",true},{"changed_bytes_unavailable",true},{"real_model",false}};
    });
    run("PLUGIN-STATE-03",[&]{
        auto folder=lifecycleRoot(root,original,session,fx,"state-policy");Commands c(session,folder,catalogPath);AudioEngine engine;engine.publishSession(c.query(),folder);
        fails("unknown_object",[&]{engine.capturePluginState(c.query(),folder,"audio","absent");});engine.play(0);fails("plugin_capture_transport",[&]{engine.capturePluginState(c.query(),folder,"audio",fx.at("id"));});engine.stop();
        apply(c,Json::array({{{"command","set_track_monitor"},{"track_id","audio"},{"monitor_mode","input"}}}));engine.publishSession(c.query(),folder);fails("plugin_capture_monitor",[&]{engine.capturePluginState(c.query(),folder,"audio",fx.at("id"));});
        apply(c,Json::array({{{"command","set_processor_lock"},{"track_id","audio"},{"processor_id",fx.at("id")},{"locked",true}}}));fails("locked",[&]{engine.capturePluginState(c.query(),folder,"audio",fx.at("id"));});
        check(!engine.metrics().at("plugin_state_capture_suspended").get<bool>(),"Rejected policy suspended the audio engine");return Json{{"unknown_target_rejected",true},{"running_transport_rejected",true},{"input_monitor_rejected",true},{"locked_instance_rejected",true},{"no_suspension_after_rejection",true},{"scope","production policy checks; no physical monitor feedback or recording qualification inferred"}};
    });
    run("PLUGIN-STATE-04",[&]{
        auto folder=lifecycleRoot(root,original,session,fx,"state-stopped-child");Commands c(session,folder,catalogPath);auto resources=std::make_shared<PluginResources>(1);AudioEngine engine({},resources);engine.publishSession(c.query(),folder);engine.play(0);
        std::jthread driver([&](std::stop_token stop){std::array<float,64> l{},r{};float* output[]{l.data(),r.data()};auto next=std::chrono::steady_clock::now();while(!stop.stop_requested()){ {RtAuditScope scope;engine.process(nullptr,0,output,2,64);}next+=std::chrono::nanoseconds(64ll*1000000000/48000);std::this_thread::sleep_until(next);}});
        check(lifecycleWait([&]{const auto m=resources->metrics();return !m.at("instances").empty() && m.at("instances")[0].at("parameter_control").at("output_snapshot_verified")==true && engine.state()==PlaybackState::Stopped;},10000),"Actual fault-injection resident child was not ready");
        const auto m=resources->metrics();const int pid=m.at("instances")[0].at("owned_pid");check(::kill(pid,SIGSTOP)==0,"Cannot stop the owned genuine AU child");const auto began=std::chrono::steady_clock::now();
        fails("plugin_shutdown",[&]{engine.capturePluginState(c.query(),folder,"audio",fx.at("id"));});const auto elapsed=lifecycleMs(began);check(elapsed<=4000 && !fs::exists(folder/".plugin-state-captures") && c.query()==session,"Stopped child timeout was adopted or exceeded the stopped-capture budget");
        check(lifecycleWait([&]{const auto x=resources->metrics();return !x.at("instances").empty() && x.at("instances")[0].at("owned_pid")!=pid && x.at("instances")[0].at("parameter_control").at("output_snapshot_verified")==true;},10000),"Failed capture did not rebuild the original genuine project state");
        driver.request_stop();driver.join();const auto runtime=resources->metrics();check(runtime.at("retirement_failures").get<int>()>=1 && !engine.metrics().at("plugin_state_capture_suspended").get<bool>(),"Failed SDK capture appeared successful or left maintenance unresolved");
        return Json{{"real_sdk_child",true},{"injected_signal",SIGSTOP},{"owned_pid",pid},{"failure_wall_ms",elapsed},{"failed_state_not_adopted",true},{"original_project_rebuilt",true},{"runtime",runtime},{"scope","owned actual AU stopped during bounded snapshot/normal teardown; recovery is SDK reload, not an arbitrary vendor/editor crash qualification"}};
    });
    run("PLUGIN-STATE-05",[&]{
        check(!captureFacts.is_null(),"Required genuine capture unavailable");auto folder=lifecycleRoot(root,original,baseline,fx,"state-lease-history");fs::copy(capturedRoot/".plugin-state-captures",folder/".plugin-state-captures",fs::copy_options::recursive);
        const auto id=captureFacts.at("capture_id").get<std::string>();const auto ops=Json::array({{{"command","adopt_plugin_state"},{"track_id","audio"},{"processor_id",fx.at("id")},{"capture_id",id}}});const auto file=folder/"session.ndaw";Json receipt;Plan plan;
        {Commands c(baseline,folder,catalogPath);const auto lease=c.beginCapture();fails("recording_busy",[&]{c.dryRun(ops,c.query().at("revision"),Actor::Gui,uuid());});c.endCapture(lease.at("lease_id"));plan=c.dryRun(ops,c.query().at("revision"),Actor::AI,uuid());c.approve(plan);receipt=c.commit(plan);c.save(file);}
        {Commands reopened(loadSession(file),folder,catalogPath);check(reopened.commit(plan)==receipt && reopened.retryReceipt(plan.operations,plan.key)==receipt,"Restart duplicated DSP-state adoption");apply(reopened,Json::array({{{"command","add_marker"},{"name","Later human marker"},{"position",128}}}),Actor::Gui);const auto markers=reopened.query().at("markers");reopened.undoTransaction(plan.id);check(reopened.query().at("markers")==markers && reopened.query().at("tracks")[0].at("processors")[0].at("state")==fx.at("state"),"Selective AI state Undo lost later human edit or prior state");reopened.save(file);}
        return Json{{"capture_lease_adoption_rejected",true},{"receipt_survives_restart",true},{"selective_ai_undo_preserves_later_human_marker",true},{"real_model",false},{"scope","domain lease/history using actual host capture; no physical concurrent recording inferred"}};
    });
}
