// SPDX-License-Identifier: AGPL-3.0-only
#pragma once
#include "nativedaw/TrackGroups.h"
namespace track_group_tests {
inline Json group(const Json& s,const std::string& type="edit_mix",const std::string& id="group-a") {
    Json members=Json::array();for(const auto& t:s.at("tracks"))members.push_back(t.at("id"));return {{"command","create_track_group"},{"id",id},{"name","Explicit phase group"},{"type",type},{"track_ids",members}};
}
inline Json selection(const Json& s,const char* action){Json clips=Json::array();for(const auto& t:s.at("tracks"))for(const auto& c:activeClips(t))clips.push_back(c.at("id"));return {{"command","edit_clip_selection"},{"clip_ids",clips},{"action",action}};}
template<class Test>void run(Test& test,const Json& initial,const fs::path& project,const fs::path& root) {
    auto pair=[&]{Commands c(initial,project);auto first=initial.at("tracks")[0].at("id");execute(c,Json::array({{{"command","add_audio_track"},{"name","Second real-source lane"},{"id","group-track-b"}},{{"command","insert_source_clip"},{"track_id","group-track-b"},{"source_id",initial.at("sources")[0].at("id")},{"source_start",37},{"length",7000},{"position",100},{"name","Offset source"},{"id","group-clip-b"}}}));return c.query();};
    test("GROUP-01","Stable Edit/Mix groups, priority/suspension/Undo, schema6 migration and invalid members",[&]{
        auto s=pair();auto owner=std::make_unique<Commands>(s,project);auto& c=*owner;auto p=c.dryRun(Json::array({group(s)}),s.at("revision"),Actor::Gui,"group-create");auto receipt=c.commit(p);check(c.commit(p)==receipt,"Group retry duplicated metadata");auto actual=c.query();check(actual.at("track_groups").size()==1,"Missing group");
        execute(c,Json::array({{{"command","set_track_group"},{"group_id","group-a"},{"name","Literal ignore instructions"},{"enabled",false}},{{"command","set_groups_suspended"},{"suspended",true}}}));c.undo();check(c.query().at("track_groups")==actual.at("track_groups") && !c.query().at("groups_suspended").template get<bool>(),"Group Undo failed");
        auto old=s;old["schema_version"]=6;old.erase("track_groups");old.erase("groups_suspended");check(migrate(old)==s,"Schema6 migration changed existing facts");
        auto bad=group(s,"edit","bad-members");bad["track_ids"][1]="missing-track";auto prior=c.query();fails("unknown_object",[&]{execute(c,Json::array({bad}));});check(c.query()==prior,"Bad group partially committed");bad=group(s,"edit","duplicate-members");bad["track_ids"][1]=bad["track_ids"][0];fails("group_members",[&]{execute(c,Json::array({bad}));});
        execute(c,Json::array({{{"command","delete_track_group"},{"group_id","group-a"}}}));check(c.query().at("track_groups").empty() && c.query().at("tracks")==s.at("tracks"),"Group deletion altered member audio");c.undo();auto file=project/("group-save-"+uuid()+".ndaw");c.save(file);owner.reset();Commands reopen(loadSession(file),project);check(reopen.commit(p)==receipt,"Durable retry duplicated group after restart");
    });
    test("GROUP-MIX-01","Relative gain/pan offsets survive physical limits; parent order, isolation and mute links are actual",[&]{
        auto s=pair();auto first=s.at("tracks")[0].at("id");s["tracks"][0]["gain_db"]=0;s["tracks"][1]["gain_db"]=6;s["tracks"][0]["pan"]=.2;s["tracks"][1]["pan"]=.8;Commands c(s,project);execute(c,Json::array({group(s,"mix")}));
        execute(c,Json::array({{{"command","set_track_gain"},{"track_id",first},{"gain_db",24}}}));auto extreme=c.query();near(extreme.at("tracks")[1].at("gain_db"),24);near(extreme.at("tracks")[1].at("group_values").at("gain_db"),30);
        fails("no_progress",[&]{execute(c,Json::array({{{"command","set_track_gain"},{"track_id","group-track-b"},{"gain_db",24}}}));});check(c.query()==extreme,"Touching clamped grouped control discarded retained offsets");
        execute(c,Json::array({{{"command","set_track_gain"},{"track_id",first},{"gain_db",16}}}));near(c.query().at("tracks")[1].at("gain_db"),22);
        execute(c,Json::array({{{"command","set_track_gain"},{"track_id","group-track-b"},{"gain_db",20}}}));near(c.query().at("tracks")[0].at("gain_db"),14);
        execute(c,Json::array({{{"command","set_track_pan"},{"track_id",first},{"pan",.9}}}));near(c.query().at("tracks")[1].at("pan"),1);near(c.query().at("tracks")[1].at("group_values").at("pan"),1.5);
        execute(c,Json::array({{{"command","set_track_pan"},{"track_id",first},{"pan",.1}}}));near(c.query().at("tracks")[1].at("pan"),.7);
        execute(c,Json::array({{{"command","set_track_mute"},{"track_id",first},{"muted",true}}}));check(c.query().at("tracks")[1].at("muted").template get<bool>(),"Mute was only cosmetic");
        execute(c,Json::array({{{"command","set_track_gain"},{"track_id",first},{"gain_db",0},{"group_behavior","individual"}}}));near(c.query().at("tracks")[1].at("gain_db"),20);
        execute(c,Json::array({{{"command","add_audio_track"},{"id","group-track-c"},{"name","Third"}},{{"command","create_track_group"},{"id","group-parent-b"},{"name","Other overlap"},{"type","mix"},{"track_ids",Json::array({first,"group-track-c"})}}}));
        execute(c,Json::array({{{"command","set_track_gain"},{"track_id",first},{"gain_db",1}}}));near(c.query().at("tracks")[1].at("gain_db"),21);near(c.query().at("tracks")[2].at("gain_db"),0);
        execute(c,Json::array({{{"command","reorder_track_groups"},{"group_ids",Json::array({"group-parent-b","group-a"})}},{{"command","set_track_gain"},{"track_id",first},{"gain_db",2}}}));near(c.query().at("tracks")[1].at("gain_db"),21);near(c.query().at("tracks")[2].at("gain_db"),1);
        execute(c,Json::array({{{"command","set_groups_suspended"},{"suspended",true}},{{"command","set_track_pan"},{"track_id",first},{"pan",0}}}));near(c.query().at("tracks")[1].at("pan"),.7);
        auto corrupt=c.query();corrupt["tracks"][0]["group_values"]["gain_db"]=123;fails("group_values",[&]{validateSession(corrupt);});
    });
    test("GROUP-EDIT-01","Multi-clip/group scalar edits retain integer source phase and overlapping envelope PCM with atomic Undo",[&]{
        auto s=pair();auto first=s.at("tracks")[0].at("id");auto& a=activeClips(s["tracks"][0])[0];a["length"]=6000;a["fade_in"]=2000;a["fade_out"]=3000;auto& b=activeClips(s["tracks"][1])[0];b["fade_in"]=1500;addTransitionRamp(b,1000,2000,false,"equal_power","group-transition");Commands c(s,project);execute(c,Json::array({group(s,"edit")}));auto before=c.query();auto aid=a.at("id");
        auto p=c.dryRun(Json::array({{{"command","move_clip"},{"clip_id",aid},{"position",43}}}),before.at("revision"),Actor::Gui,"group-move");check(p.operations[0].at("resolved_clip_ids").size()==2,"Scalar command bypassed group");auto receipt=c.commit(p);check(c.commit(p)==receipt,"Move retry applied delta twice");check(activeClips(c.query().at("tracks")[1])[0].at("start")==143,"Group offset changed");c.undo();
        auto trim=selection(c.query(),"trim");trim["edge"]="left";trim["delta"]=173;execute(c,Json::array({trim}));auto trimmed=c.query();
        for(std::size_t k=0;k<2;++k){const auto& old=activeClips(before.at("tracks")[k])[0];const auto& next=activeClips(trimmed.at("tracks")[k])[0];GainEnvelope ga(old),gb(next);for(Frame i=0;i<next.at("length").template get<Frame>();++i)near(gb.at(i),ga.at(i+173),1e-14);check(next.at("source_start")==old.at("source_start").template get<Frame>()+173,"Trim source offset lost");}
        RenderGraph original(before,project),actual(trimmed,project);float al[128]{},ar[128]{},bl[128]{},br[128]{};original.render(3000,128,al,ar);actual.render(3000,128,bl,br);for(int i=0;i<128;++i){near(al[i],bl[i]);near(ar[i],br[i]);}c.undo();
        auto split=selection(c.query(),"split");split["position"]=2378;auto plan=c.dryRun(Json::array({split}),c.query().at("revision"),Actor::Gui,"group-split");check(plan.operations[0].at("split_clip_ids").size()==2,"Missing canonical split IDs");c.commit(plan);auto after=c.query();for(const auto& t:after.at("tracks"))check(activeClips(t).size()==2,"Split not atomic across tracks");RenderGraph splitGraph(after,project);original.render(2370,128,al,ar);splitGraph.render(2370,128,bl,br);for(int i=0;i<128;++i){near(al[i],bl[i]);near(ar[i],br[i]);}c.undo();
        auto gain=selection(c.query(),"gain");gain["delta_db"]=-3;execute(c,Json::array({gain}));auto gained=c.query();for(const auto& t:gained.at("tracks"))near(activeClips(t)[0].at("gain_db"),-3);c.undo();auto del=selection(c.query(),"delete");execute(c,Json::array({del}));auto deleted=c.query();for(const auto& t:deleted.at("tracks"))check(activeClips(t).empty(),"Batch deletion missed target");check(c.query().at("sources")==before.at("sources"),"Deletion removed source");c.undo();check(c.query().at("tracks")==before.at("tracks"),"Multi-edit Undo changed source facts");
    });
    test("GROUP-EDIT-02","Locked/partial targets, forged expansion, AI scope/revision and capture links reject atomically",[&]{
        auto s=pair();auto first=s.at("tracks")[0].at("id"),aid=activeClips(s.at("tracks")[0])[0].at("id");Commands c(s,project);execute(c,Json::array({group(s)}));auto before=c.query();
        auto invalid=selection(before,"move");invalid["delta"]=-101;fails("range",[&]{execute(c,Json::array({invalid}));});check(c.query()==before,"Failed move changed earlier member");
        invalid=selection(before,"split");invalid["position"]=50;fails("range",[&]{execute(c,Json::array({invalid}));});check(c.query()==before,"Failed split partially changed session");
        fails("group_targets",[&]{execute(c,Json::array({{{"command","set_track_gain"},{"track_id",first},{"gain_db",-1},{"affected_track_ids",Json::array({first})}}}));});
        fails("group_targets",[&]{execute(c,Json::array({{{"command","move_clip"},{"clip_id",aid},{"position",1},{"resolved_clip_ids",Json::array({aid})}}}));});
        execute(c,Json::array({{{"command","set_track_lock"},{"track_id","group-track-b"},{"locked",true}}}));auto locked=c.query();fails("locked",[&]{execute(c,Json::array({{{"command","set_track_gain"},{"track_id",first},{"gain_db",-1}}}));});check(c.query()==locked,"Locked mix only partially changed");c.undo();
        auto ai=validateModelProposal(c,Json{{"operations",Json::array({{{"command","set_track_gain"},{"track_id",first},{"gain_db",-1}}})}},c.query().at("revision"),"group-ai");Scope scope;scope.mode=Permission::ScopedLowRisk;scope.targets.insert(first);fails("approval_required",[&]{c.commit(ai,scope);});c.approve(ai);execute(c,Json::array({{{"command","add_marker"},{"name","Human edit"},{"position",1}}}));fails("version_conflict",[&]{c.commit(ai);});
        Json links{{"volume",true},{"pan",true},{"mute",true},{"record",true},{"monitor",true}};execute(c,Json::array({{{"command","set_track_group"},{"group_id","group-a"},{"links",links}},{{"command","set_track_arm"},{"track_id",first},{"record_armed",true}}}));check(c.query().at("tracks")[1].at("record_armed").template get<bool>(),"Record link not actual");execute(c,Json::array({{{"command","set_track_monitor"},{"track_id",first},{"monitor_mode","input"}}}));check(c.query().at("tracks")[1].at("monitor_mode")=="input","Monitor link not actual");auto lease=c.beginCapture();fails("recording_busy",[&]{execute(c,Json::array({{{"command","set_track_arm"},{"track_id",first},{"record_armed",false}}}));});c.endCapture(lease.at("lease_id"));
    });
    test("GROUP-COMP-01","Respect moves complete linked timing; explicit detach preserves every source/envelope and enables individual edits",[&]{
        auto s=pair();Commands c(s,project);auto op=linked_comp_tests::plan(s,33,"equal_power");execute(c,Json::array({op,{{"command","select_comp_set"},{"comp_set_id","linked-candidate"}}}));auto selected=c.query();auto aid=activeClips(selected.at("tracks")[0])[0].at("id");Frame start=activeClips(selected.at("tracks")[0])[0].at("start");execute(c,Json::array({{{"command","move_clip"},{"clip_id",aid},{"position",start+43}}}));for(std::size_t i=0;i<2;++i)for(std::size_t k=0;k<2;++k)check(activeClips(c.query().at("tracks")[i])[k].at("start")==activeClips(selected.at("tracks")[i])[k].at("start").template get<Frame>()+43,"Respect omitted linked piece");c.undo();
        execute(c,Json::array({{{"command","detach_comp_set"},{"comp_set_id","linked-candidate"}}}));auto detached=c.query();check(detached.at("comp_sets").empty() && detached.at("sources")==selected.at("sources"),"Detach removed media");for(std::size_t i=0;i<2;++i)check(activeClips(detached.at("tracks")[i])==activeClips(selected.at("tracks")[i]),"Detach altered actual PCM mapping");
        execute(c,Json::array({{{"command","move_clip"},{"clip_id",aid},{"position",start+1},{"group_behavior","individual"}}}));check(activeClips(c.query().at("tracks")[1])==activeClips(selected.at("tracks")[1]),"Individual edit altered partner");c.undo();c.undo();check(c.query().at("comp_sets")==selected.at("comp_sets"),"Detach Undo lost timing linkage");
    });
    test("GROUP-PHASE-01","Grouped source-aligned opposite PCM remains null through trim/gain/move and16-sample RT delay compensation",[&]{
        const auto stereo=root/"known-opposite-channel.wav";if(!fs::exists(stereo))fixture(stereo,48000,2);Commands c(initial,project);auto first=initial.at("tracks")[0].at("id");execute(c,Json::array({{{"command","add_audio_track"},{"id","group-phase-b"},{"name","Explicit opposite channel"}},{{"command","import_audio"},{"track_id","group-phase-b"},{"path",stereo.string()},{"position",37}},{{"command","set_track_pan"},{"track_id",first},{"pan",1}}}));auto s=c.query();auto bid=activeClips(s.at("tracks")[1])[0].at("id");execute(c,Json::array({{{"command","trim_clip"},{"clip_id",bid},{"source_start",37},{"length",7000}},group(s,"edit"),{{"command","insert_limiter"},{"track_id",first},{"id","group-phase-delay"},{"lookahead_frames",16},{"ceiling_db",0},{"release_ms",10}}}));s=c.query();auto move=selection(s,"move");move["delta"]=43;auto trim=selection(s,"trim");trim["edge"]="left";trim["delta"]=17;auto gain=selection(s,"gain");gain["delta_db"]=-3;execute(c,Json::array({move,trim,gain}));auto actual=c.query();RenderGraph offline(actual,project);float l[256]{},r[256]{};offline.render(1000,256,l,r);for(int i=0;i<256;++i){near(l[i],.04*std::sin(2*std::numbers::pi*997*(1000+i-43)/48000)*std::pow(10.,-3./20));near(r[i],0);}
        AudioEngine engine;engine.publishSession(actual,project);engine.play(1000);prime(engine);float rl[256]{},rr[256]{};float* out[]{rl,rr};allocations=deallocations=0;allocationGuard=true;engine.process(nullptr,0,out,2,256);allocationGuard=false;check(allocations==0 && deallocations==0,"Grouped graph callback allocated/freed");for(int i=0;i<256;++i){near(rl[i],i<16?0:l[i-16]);near(rr[i],0);}
    });
    test("GROUP-BOUNDS-01","Lower linked limits restore offsets; Take expansion, ignored fields and plan/metadata overflow reject",[&]{
        auto s=pair();auto first=s.at("tracks")[0].at("id");s["tracks"][0]["gain_db"]=0;s["tracks"][1]["gain_db"]=6;Commands c(s,project);execute(c,Json::array({group(s,"mix"),{{"command","set_track_gain"},{"track_id","group-track-b"},{"gain_db",-120}}}));near(c.query().at("tracks")[0].at("gain_db"),-120);near(c.query().at("tracks")[0].at("group_values").at("gain_db"),-126);
        execute(c,Json::array({{{"command","set_track_gain"},{"track_id","group-track-b"},{"gain_db",-110}}}));near(c.query().at("tracks")[0].at("gain_db"),-116);
        auto invalid=selection(c.query(),"delete");invalid["position"]=0;fails("schema",[&]{execute(c,Json::array({invalid}));});invalid=selection(c.query(),"move");invalid["delta"]=1;invalid["clip_ids"]=Json::array();for(int i=0;i<16385;++i)invalid["clip_ids"].push_back("over-budget-"+std::to_string(i));fails("audio_resources",[&]{execute(c,Json::array({invalid}));});
        invalid=group(s,"edit","large-metadata");invalid["track_ids"]=Json::array();for(int i=0;i<131073;++i)invalid["track_ids"].push_back("member-"+std::to_string(i));fails("audio_resources",[&]{execute(c,Json::array({invalid}));});
        Json takes=Json::array();auto before=c.query();for(const auto& t:before.at("tracks"))takes.push_back({{"command","create_take"},{"track_id",t.at("id")},{"clip_id",activeClips(t)[0].at("id")},{"name","Immutable actual interval"}});execute(c,takes);before=c.query();auto extend=selection(before,"trim");extend["edge"]="right";extend["delta"]=1;fails("invalid_session",[&]{execute(c,Json::array({extend}));});check(c.query()==before,"Rejected extension changed immutable Take source interval");
    });
    test("GROUP-AI-01","GUI and explicitly approved AI Actor replay the same canonical batch, PCM and whole Undo; no model substituted",[&]{
        auto s=pair();Commands gui(s,project);execute(gui,Json::array({group(s,"edit")}));auto before=gui.query();const auto other=root/"group-ai-equivalence";fs::create_directories(other);fs::copy(project/"media",other/"media",fs::copy_options::recursive);Commands ai(before,other);
        auto trim=selection(before,"trim");trim["edge"]="left";trim["delta"]=173;auto gain=selection(before,"gain");gain["delta_db"]=-1;auto split=selection(before,"split");split["position"]=2378;split["split_clip_ids"]=Json::object();for(const auto& id:split.at("clip_ids"))split["split_clip_ids"][id.template get<std::string>()]=id.template get<std::string>()+"-equivalent";
        auto p=gui.dryRun(Json::array({trim,gain,split}),before.at("revision"),Actor::Gui,"gui-equivalence");gui.commit(p);auto a=validateModelProposal(ai,Json{{"operations",p.operations}},before.at("revision"),"ai-equivalence");check(a.operations==p.operations,"AI changed canonical batch targets/children");ai.approve(a);auto receipt=ai.commit(a);check(ai.commit(a)==receipt,"Approved AI retry duplicated split");
        auto gs=gui.query(),as=ai.query();for(const char* key:{"tracks","sources","takes","track_groups"})check(gs.at(key)==as.at(key),"GUI/AI project state differs");RenderGraph g(gs,project),m(as,other);float gl[256]{},gr[256]{},al[256]{},ar[256]{};g.render(2300,256,gl,gr);m.render(2300,256,al,ar);for(int i=0;i<256;++i){near(gl[i],al[i],0);near(gr[i],ar[i],0);}gui.undo();ai.undo();check(gui.query().at("tracks")==before.at("tracks") && ai.query().at("tracks")==before.at("tracks"),"GUI/AI batch Undo differs");for(const auto& source:before.at("sources"))check(sha256(mediaPath(project,source))==source.at("sha256").template get<std::string>() && sha256(mediaPath(other,source))==source.at("sha256").template get<std::string>(),"Common command altered original PCM");
    });
}
}
