// SPDX-License-Identifier: AGPL-3.0-only
#pragma once
#include "nativedaw/EditSelection.h"
#include "nativedaw/NativeWorkstation.h"
namespace track_group_gui_tests {
template<class Test>void run(Test& test,const Json& initial,const fs::path& project,const fs::path& root,Json& benchmarks) {
    test("GUI-GROUP-01","Native group editor member selection invokes real revision-pinned domain transaction and Undo",[&]{
        Commands c(initial,project);execute(c,Json::array({{{"command","add_audio_track"},{"id","gui-group-b"},{"name","Second"}}}));auto before=c.query();bool submitted=false;NativeGroupEditor editor([&](Json ops,std::uint64_t revision,std::string sessionId){check(c.query().at("id")==sessionId,"Group UI session identity mismatch");auto p=c.dryRun(ops,revision,Actor::Gui,uuid());c.commit(p);submitted=true;});std::set<std::string> ids;for(const auto& t:before.at("tracks"))ids.insert(t.at("id"));editor.update(before,ids);editor.resized();
        for(auto* child:editor.getChildren())if(auto* b=dynamic_cast<juce::TextButton*>(child);b && b->getButtonText()=="Create")b->onClick();auto after=c.query();check(submitted && after.at("track_groups").size()==1 && after.at("tracks")==before.at("tracks"),"Native group Create did not commit actual facts");
        auto stale=editor.plan(true);fails("version_conflict",[&]{c.dryRun(Json::array({stale}),before.at("revision"),Actor::Gui,uuid());});c.undo();check(c.query().at("track_groups").empty(),"Native group Undo failed");
    });
    test("GUI-SELECTION-01","Cross-track sample selection, additive IDs and inline source rows share actual clip facts",[&]{
        Commands c(initial,project);execute(c,Json::array({{{"command","add_audio_track"},{"id","gui-select-b"},{"name","Second"}},{{"command","insert_source_clip"},{"track_id","gui-select-b"},{"source_id",initial.at("sources")[0].at("id")},{"source_start",37},{"length",7000},{"position",100},{"name","Source"},{"id","gui-clip-b"}}}));auto s=c.query();EditSelection selection;selection.range(s,s.at("tracks")[0].at("id"),"gui-select-b",173,2378);check(selection.tracks.size()==2 && selection.clips.size()==2 && selection.focusClip=="gui-clip-b","Range lost actual clip IDs/parent focus");
        auto op=selection.operation("move");op["delta"]=43;auto plan=c.dryRun(Json::array({op}),s.at("revision"),Actor::Gui,uuid());c.commit(plan);check(activeClips(c.query().at("tracks")[1])[0].at("start")==143,"Selection did not execute real batch command");c.undo();selection.single("gui-select-b","gui-clip-b",173,2378,true);check(selection.clips.size()==2,"Additive selection erased earlier clip");
        execute(c,Json::array({{{"command","create_playlist"},{"track_id","gui-select-b"},{"name","Actual source lane"},{"source_playlist_id",s.at("tracks")[1].at("active_playlist_id")},{"id","gui-source-pl"},{"clip_ids",Json::array({"gui-source-clip"})}}}));s=c.query();AudioEngine engine;desktop::Timeline timeline(engine);timeline.update(s,project);const int before=timeline.trackHeights().at("gui-select-b");timeline.toggleSourceLanes("gui-select-b");check(timeline.trackHeights().at("gui-select-b")==before+84 && activeClips(s.at("tracks")[1])[0].at("id")=="gui-clip-b","Inline source row changed playback or lost actual Playlist");
        selection.focusTrack=s.at("tracks")[0].at("id");selection.focusClip="gui-clip-b";selection.retain(s);check(activeClips(s.at("tracks")[0])[0].at("id")==selection.focusClip,"Focus borrowed a selected clip from another track");
        selection.focusTrack="gui-select-b";selection.focusClip="gui-clip-b";auto changed=s;activeClips(changed["tracks"][1])=Json::array();selection.retain(changed);check(selection.clips.size()==1 && !selection.clips.contains("gui-clip-b") && selection.focusTrack=="gui-select-b" && selection.focusClip.empty(),"Stale clip or another track's inspector focus survived deletion");
        selection.tracks.erase("gui-select-b");selection.focusTrack="removed-track";selection.retain(changed);check(s.at("tracks")[0].at("id")==selection.focusTrack && activeClips(s.at("tracks")[0])[0].at("id")==selection.focusClip,"Selection fallback lost the real clip parent");
    });
    test("GROUP-BENCH-01","Fixed128/256/512-track x4-clip group transaction and whole Undo meet declared Release budgets",[&]{
        Json receipts=Json::array();for(int count:{128,256,512}) {
            auto s=initial;const auto original=s.at("tracks")[0];const auto sourceClip=activeClips(original)[0];s["tracks"]=Json::array();Json selected=Json::array(),members=Json::array();
            for(int i=0;i<count;++i){auto t=original;const std::string id="bench-track-"+std::to_string(i);t["id"]=id;t["name"]=id;t["output"]["id"]=outputRouteId(id);t["processors"]=Json::array();t["sends"]=Json::array();t["playlists"]=Json::array();const auto pid=mainPlaylistId(id);t["active_playlist_id"]=pid;t["target_playlist_id"]=pid;Json clips=Json::array();for(int k=0;k<4;++k){auto clip=sourceClip;const std::string cid="bench-clip-"+std::to_string(i)+"-"+std::to_string(k);clip["id"]=cid;clip["start"]=k*8000;clip["source_start"]=k*8000;clip["length"]=7000;clip["fade_in"]=0;clip["fade_out"]=0;clips.push_back(clip);selected.push_back(cid);}t["playlists"].push_back({{"id",pid},{"name",id},{"role","main"},{"locked",false},{"clips",clips}});s["tracks"].push_back(t);members.push_back(id);}
            const auto p=root/("group-benchmark-"+std::to_string(count));fs::create_directories(p);Commands commands(s,p);execute(commands,Json::array({{{"command","create_track_group"},{"name","All benchmark tracks"},{"type","edit"},{"track_ids",members}}}));const auto before=commands.query();
            auto start=std::chrono::steady_clock::now();auto plan=commands.dryRun(Json::array({{{"command","edit_clip_selection"},{"clip_ids",selected},{"action","move"},{"delta",1}}}),before.at("revision"),Actor::Gui,"fixed-nudge");commands.commit(plan);const auto commitMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();start=std::chrono::steady_clock::now();commands.undo();const auto undoMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();check(commands.query().at("tracks")==before.at("tracks") && plan.operations[0].at("resolved_clip_ids").size()==count*4,"Benchmark dropped targets or failed Undo");
            receipts.push_back({{"tracks",count},{"clips_per_track",4},{"resolved_targets",count*4},{"plan_commit_ms",commitMs},{"undo_ms",undoMs},{"declared_release_budget_ms",1000}});
        }benchmarks=receipts;atomicWrite(root/"group-benchmark.json",receipts.dump(2),false);
#if defined(NDEBUG) && !defined(NATIVEDAW_RT_AUDIT)
        for(const auto& receipt:receipts)check(receipt.at("plan_commit_ms").get<double>()<=1000 && receipt.at("undo_ms").get<double>()<=1000,"Fixed Release group workload exceeded declared1000 ms budgets");
#endif
    });
}
}
