#include <nativedaw/v2/AudioAnalysis.h>
#include <nativedaw/v2/McpSession.h>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <thread>
using namespace ndaw::v2;
namespace {
int checks=0;Json evidence=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
void pump(int ms=10){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json op(const char* cmd,Json args){return {{"command",cmd},{"args",args}};}
Json commit(Commands& c,Json ops){return c.commit(c.makePlan("human",ops));}
void write(const juce::File& file,const juce::AudioBuffer<float>& audio,int rate=48000){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(rate).withNumChannels(audio.getNumChannels()).withBitsPerSample(32));if(!writer||!writer->writeFromAudioSampleBuffer(audio,0,audio.getNumSamples()))throw std::runtime_error("analysis fixture write failed");}
Json wait(Commands& c){const auto began=juce::Time::getMillisecondCounterHiRes();while(true){auto status=c.analysisStatus();if(!status["busy"].get<bool>())return status;if(juce::Time::getMillisecondCounterHiRes()-began>12000)throw std::runtime_error("analysis test exceeded preset 12 second budget");pump();}}
Json request(Commands& c,int64_t start,int64_t end,const std::string& key){return {{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]},{"start_samples",start},{"end_samples",end},{"request_key",key}};}
Json rpc(McpSession& session,const char* method,Json params=Json::object()){
    static int id=0;const int key=++id;std::vector<Json> out;std::thread p([&]{out=session.receive(Json{{"jsonrpc","2.0"},{"id",key},{"method",method},{"params",params}}.dump());});p.join();
    const auto began=juce::Time::getMillisecondCounterHiRes();while(out.empty()){if(juce::Time::getMillisecondCounterHiRes()-began>=5000)throw std::runtime_error("MCP analysis reply exceeded fixed five seconds");pump();std::thread q([&]{out=session.ready();});q.join();}return out.at(0);
}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-analysis-tests-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();
    juce::AudioBuffer<float> signal(2,192000);signal.clear();for(int n=0;n<signal.getNumSamples();++n){const float value=n>=24000&&n<28800?1.25f:n>=96000&&n<100800?-1.5f:.2f;signal.setSample(0,n,value);signal.setSample(1,n,-value);}
    auto measuredFile=folder.getChildFile("known-float.wav");write(measuredFile,signal);auto measured=analysis::measure(measuredFile,12345);
    check(measured["file_float"].get<bool>()&&measured["peak"]==1.5&&measured["over_full_scale_frames"]==9600,"float PCM preserves overs and exact known full-scale frame count");
    check(measured["events"].size()==2&&measured["events"][0]["start_samples"]==36345&&measured["events"][0]["end_samples"]==41145&&measured["events"][1]["start_samples"]==108345&&measured["events"][1]["end_samples"]==113145,"event positions map nonzero render origin into exact half-open session samples");
    const double quiet=double(.2f);const double energy=4800*1.25*1.25+4800*1.5*1.5+(192000-9600)*quiet*quiet;check(std::abs(measured["rms"].get<double>()-std::sqrt(energy/192000))<1e-12&&std::abs(measured["correlation"].get<double>()+1)<1e-12,"RMS and mean-adjusted stereo anti-correlation match independent known PCM");
    check(measured["lufs_i"].is_number()&&measured["lufs_m_max"].is_number()&&measured["lufs_s_max"].is_number()&&measured["true_peak_dbtp"].get<double>()>3.5,"real libebur128 I/M/S and true peak receive unclamped float PCM");evidence.push_back(measured);
    for(int n=0;n<192000;++n)for(int ch=0;ch<2;++ch)signal.setSample(ch,n,float(.1*std::sin(2*juce::MathConstants<double>::pi*1000*n/48000)));
    auto calibration=folder.getChildFile("stereo-1k-minus20.wav");write(calibration,signal);auto calibrated=analysis::measure(calibration,0);for(auto key:{"lufs_i","lufs_m_max","lufs_s_max"})check(std::abs(calibrated[key].get<double>()+20)<.05,"stereo -20dBFS 1 kHz sine matches preset -20 LUFS +/-0.05 reference");check(std::abs(calibrated["true_peak_dbtp"].get<double>()+20)<.02,"1 kHz true peak matches known -20 dBTP within preset 0.02 dB");evidence.push_back(calibrated);
    signal.clear();auto silent=folder.getChildFile("silent.wav");write(silent,signal);auto silence=analysis::measure(silent,0);check(silence["peak"]==0&&silence["lufs_i"].is_null()&&silence["true_peak_dbtp"].is_null()&&silence["correlation"].is_null()&&silence["events"].empty(),"silence has undefined loudness/correlation instead of invented measurements");
    signal.setSize(1,9600);signal.clear();auto shortFile=folder.getChildFile("short.wav");write(shortFile,signal);auto shortResult=analysis::measure(shortFile,0);check(shortResult["lufs_m_max"].is_null()&&shortResult["lufs_s_max"].is_null()&&shortResult["loudness_windows"]["short_term_count"]==0,"short intervals do not fabricate 400 ms or 3 second loudness windows");
    signal.setSize(1,1000);for(int n=0;n<1000;++n)signal.setSample(0,n,n%2?0:1.1f);auto dense=folder.getChildFile("dense.wav");write(dense,signal);auto limited=analysis::measure(dense,0);check(limited["events"].size()==128&&limited["event_count"]==500&&limited["events_omitted"]==372,"bounded event output explicitly retains total and omitted counts");
    fails([&]{analysis::measure(measuredFile,0,{[]{return true;},[]{}});},"measurement cancellation never returns successful evidence");
    signal.setSize(2,192000);for(int n=0;n<192000;++n){const float v=float(.8*std::sin(2*juce::MathConstants<double>::pi*10*n/48000));signal.setSample(0,n,v);signal.setSample(1,n,v);}
    auto source=folder.getChildFile("engine-source.wav");write(source,signal);const auto originalHash=Commands::mediaHash(source);
    Commands c(false);commit(c,Json::array({op("track.create",{{"name","Measured Master"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}}),op("track.gain",{{"track","$t"},{"db",6}})}));const auto track=c.query()["tracks"][0]["id"].get<std::string>();
    auto before=c.query();auto args=request(c,24013,168013,"native-analysis");auto submitted=c.analysisControl("master",args);check(submitted["busy"].get<bool>(),"L1 analysis returns a live background job rather than a fabricated completed result");auto retry=c.analysisControl("master",args);check(retry["request"]["artifact_id"]==submitted["request"]["artifact_id"],"identical live analysis retry shares the actual job");auto changed=args;changed["start_samples"]=24014;fails([&]{c.analysisControl("master",changed);},"same analysis key with different range cannot start another job");
    auto status=wait(c);check(status["state"]=="completed","Tracktion snapshot analysis completed");auto artifact=status["receipt"];check(artifact["current"].get<bool>()&&artifact["frames"]==144000&&artifact["file_float"].get<bool>()&&artifact["peak"].get<double>()>1.59&&artifact["over_full_scale_frames"].get<int64_t>()>0,"native Master float render retains real >0dBFS gain and exact selected length");
    Json expectedEvents=Json::array();int64_t eventStart=-1,expectedOver=0;const float knownGain=juce::Decibels::decibelsToGain(6.f);
    for(int64_t at=24013;at<168013;++at){const bool over=std::abs(signal.getSample(0,int(at))*knownGain)>=1.;if(over){++expectedOver;if(eventStart<0)eventStart=at;}else if(eventStart>=0){expectedEvents.push_back({eventStart,at});eventStart=-1;}}if(eventStart>=0)expectedEvents.push_back({eventStart,168013});
    check(artifact["over_full_scale_frames"]==expectedOver&&artifact["events"].size()==expectedEvents.size(),"native clipping risk count matches independent source PCM times known gain");for(size_t i=0;i<expectedEvents.size();++i)if(artifact["events"][i]["start_samples"]!=expectedEvents[i][0]||artifact["events"][i]["end_samples"]!=expectedEvents[i][1])throw std::runtime_error("native event boundary differs from independently predicted source gain");check(true,"every native event boundary matches independently predicted session sample");
    check(c.query()["revision"]==before["revision"]&&c.query()["tracks"]==before["tracks"]&&c.query()["position_samples"]==before["position_samples"],"render-only Edit uses the existing engine without changing active Edit facts history or cursor");
    check(artifact["binding"]["tap_point"]=="master"&&artifact["binding"]["processing_chain_hash"].get<std::string>().size()==64&&artifact["media"][0]["sha256"]==originalHash,"artifact binds actual Master tap, chain hash, IDs, media hash and session range");
    auto located=c.analysisControl("locate",{{"artifact_id",artifact["artifact_id"]},{"event_id",0}});check(c.query()["position_samples"]==located["event"]["start_samples"]&&located["event"]["start_samples"].get<int64_t>()>=24013,"real native Transport seeks to the measured event without offset drift");
    const auto saveFile=folder.getChildFile("measured.tracktionedit");c.save(saveFile);auto xml=juce::XmlDocument::parse(saveFile);check(xml&&xml->getChildByName("NATIVEDAW")->getChildByName("ANALYSISARTIFACTS"),"saved Edit retains derived artifact record independently of Undo");
    commit(c,Json::array({op("track.gain",{{"track",track},{"db",-12}})}));check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"processing chain edit invalidates prior measured evidence");fails([&]{c.analysisControl("locate",{{"artifact_id",artifact["artifact_id"]},{"event_id",0}});},"stale analysis cannot seek using old event locations");c.undo();check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"Undo is a newer revision and cannot silently revive old evidence");
    auto nextArgs=request(c,0,192000,"cancel-native");auto cancellable=c.analysisControl("master",nextArgs,"agent:test");fails([&]{c.analysisControl("cancel",{{"artifact_id",cancellable["request"]["artifact_id"]}},"agent:other");},"another Agent cannot cancel an owned analysis");c.analysisControl("cancel",{{"artifact_id",cancellable["request"]["artifact_id"]}},"agent:test");check(wait(c)["state"]=="cancelled","cancelled native job terminates and releases its graph on the message thread");
    CommandQueue queue(c);Scope readOnly;readOnly.mode=Permission::ReadOnly;auto client=queue.connect("agent:analysis",readOnly);McpSession session(client,Commands::registry());rpc(session,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","analysis-tests"},{"version","1"}}}});session.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());Json pageArgs=Json::object();bool found=false;do{auto page=rpc(session,"tools/list",pageArgs)["result"];for(const auto& t:page["tools"])if(t["name"]=="analyze_master")found=t["annotations"]["readOnlyHint"];pageArgs=page.contains("nextCursor")?Json{{"cursor",page["nextCursor"]}}:Json::object();}while(!pageArgs.empty());check(found,"MCP analysis tool schema is generated by the same L1 registry");
    auto protocol=rpc(session,"tools/call",{{"name","analyze_master"},{"arguments",request(c,24013,168013,"mcp-analysis")}});check(!protocol["result"]["isError"].get<bool>(),"read-only external Agent can request local evidence without edit permission");wait(c);auto external=rpc(session,"tools/call",{{"name","query_analysis"},{"arguments",Json::object()}})["result"]["structuredContent"]["result"];check(external["receipt"]["current"].get<bool>()&&external["receipt"]["over_full_scale_frames"].get<int64_t>()>0,"real MCP query returns actual measured Master evidence");evidence.push_back(external);
    juce::MemoryBlock originalBytes;check(source.loadFileAsData(originalBytes),"owned source bytes retained for fault injection");const auto originalTime=source.getLastModificationTime();auto bytes=static_cast<const char*>(originalBytes.getData());size_t dataOffset=0;for(size_t i=12;i+8<originalBytes.getSize()&&i<512;++i)if(std::memcmp(bytes+i,"data",4)==0){dataOffset=i+8;break;}check(dataOffset>0,"actual RIFF audio payload identified for byte mutation");
    {juce::FileOutputStream output(source);if(!output.openedOk()||!output.setPosition(int64_t(dataOffset))||!output.writeInt(0x3e800000))throw std::runtime_error("owned source fault injection failed");output.flush();}source.setLastModificationTime(originalTime);check(source.getSize()==int64_t(originalBytes.getSize())&&source.getLastModificationTime()==originalTime&&Commands::mediaHash(source)!=originalHash,"fault changes PCM while preserving size and timestamp");
    fails([&]{c.analysisControl("locate",{{"artifact_id",external["receipt"]["artifact_id"]},{"event_id",0}});},"deep media hash rejects stale location even when file size and timestamp are unchanged");check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"detected media hash mismatch permanently invalidates that artifact");if(!source.replaceWithData(originalBytes.getData(),originalBytes.getSize()))throw std::runtime_error("owned source restoration failed");source.setLastModificationTime(originalTime);
    auto rejected=rpc(session,"tools/call",{{"name","analyze_master"},{"arguments",{{"session_token",c.sessionToken()},{"base_revision",c.query()["revision"]},{"start_samples",0},{"end_samples",1},{"request_key","malicious"},{"path","/tmp/untrusted"}}}});check(rejected["result"]["isError"].get<bool>(),"unknown path fields cannot turn analysis into arbitrary file output");
    auto staleRequest=request(c,0,48000,"stale");commit(c,Json::array({op("track.rename",{{"track",track},{"name","New human name"}})}));fails([&]{c.analysisControl("master",staleRequest);},"analysis rejects a newer human revision at snapshot preparation");
    c.analysisControl("master",request(c,24013,168013,"interleaved"));commit(c,Json::array({op("track.gain",{{"track",track},{"db",-24}})}));auto interleaved=wait(c);check(interleaved["state"]=="completed"&&!interleaved["receipt"]["current"].get<bool>()&&interleaved["receipt"]["peak"].get<double>()>1.59&&c.query()["tracks"][0]["gain_db"].get<double>()<-23.9,"in-flight snapshot retains its measured sound and cannot overwrite a newer human gain");
    fails([&]{c.analysisControl("master",request(c,0,301*48000,"long"));},"explicit five-minute range budget rejects oversized work without silently trimming");
    c.analysisControl("master",request(c,0,48000,"switch"));c.open(saveFile);check(c.analysisStatus()["state"]=="idle","reopen cancels pending work and cannot treat saved evidence as a live current receipt");
    {Commands live(true);commit(live,Json::array({op("track.create",{{"name","Low-level priority probe"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}}),op("track.gain",{{"track","$t"},{"db",-24}})}));pump(150);auto priorityJob=live.analysisControl("master",request(live,0,192000,"play-priority"));live.analysisControl("pause",{{"artifact_id",priorityJob["request"]["artifact_id"]},{"paused",true}});pump(30);live.play();auto paused=live.analysisStatus();const auto at=live.query()["position_samples"].get<int64_t>();const auto deviceBefore=live.deviceStatus();pump(180);const auto deviceAfter=live.deviceStatus();paused=live.analysisStatus();check(paused["state"]=="paused"&&paused["busy"].get<bool>()&&live.query()["playing"].get<bool>()&&live.query()["position_samples"].get<int64_t>()>at&&deviceAfter["output_frames"].get<uint64_t>()>deviceBefore["output_frames"].get<uint64_t>()&&deviceAfter["output_maximum"].get<double>()>1e-3,"actual CoreAudio callbacks and low-level PCM advance while analysis worker is paused");auto resumeDuringPlay=live.analysisControl("pause",{{"artifact_id",priorityJob["request"]["artifact_id"]},{"paused",false}});check(resumeDuringPlay["pause"]["playback_requested"].get<bool>()&&resumeDuringPlay["pause"]["worker_parked"].get<bool>()&&!resumeDuringPlay["pause"]["user_requested"].get<bool>(),"manual resume cannot bypass actual CoreAudio playback priority");fails([&]{live.analysisControl("master",request(live,0,48000,"during-play"));},"new analysis cannot prepare a graph during playback");live.stop();auto resumed=wait(live);check(resumed["state"]=="completed"&&resumed["receipt"]["peak"].get<double>()<.051,"analysis resumes with the genuine low-level snapshot after playback stops");resumed["device_before_play_priority"]=deviceBefore;resumed["device_after_play_priority"]=deviceAfter;evidence.push_back(resumed);}
    check(Commands::mediaHash(source)==originalHash,"analysis, cancellation, locate, save and reopen preserve original source media bytes");
    const double elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"fixed analysis qualification completes within 60 seconds");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"evidence",evidence},{"scope","real native float render, decoded PCM and MCP; no listening or real-time safety claim"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<report.dump(2)<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
