#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;using namespace ndaw::desktop;
namespace {
int checks=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
void pump(int ms=30){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& parent,const juce::String& id){if(!parent.isVisible())return nullptr;if(parent.getComponentID()==id)return &parent;for(auto* child:parent.getChildren())if(auto* result=find(*child,id))return result;return nullptr;}
void click(juce::Component& parent,const char* id){auto* button=dynamic_cast<juce::Button*>(find(parent,id));if(!button||!button->isEnabled())throw std::runtime_error(std::string("unavailable native button: ")+id);auto before=button->onClick;bool delivered=false;button->onClick=[&]{delivered=true;before();};button->triggerClick();const auto deadline=juce::Time::getMillisecondCounterHiRes()+1000;while(!delivered&&juce::Time::getMillisecondCounterHiRes()<deadline)pump(5);button->onClick=before;check(delivered,"actual asynchronous native button callback delivered");pump();}
class Storage final:public te::PropertyStorage{public:explicit Storage(juce::File folder):PropertyStorage("Forma analysis UI"),folder(folder){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-analysis-ui-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();auto source=folder.getChildFile("real-float.wav");juce::AudioBuffer<float> data(2,192000);for(int n=0;n<192000;++n)for(int ch=0;ch<2;++ch)data.setSample(ch,n,float(.8*std::sin(2*juce::MathConstants<double>::pi*10*n/48000)));juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=source.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));if(!writer||!writer->writeFromAudioSampleBuffer(data,0,192000))throw std::runtime_error("GUI source write failed");writer.reset();const auto original=Commands::mediaHash(source);
    Workspace w(false,std::make_unique<Storage>(folder.getChildFile("prefs")));w.setVisible(true);w.prepareImport(source);pump();click(w,"plan.accept");auto facts=w.query();check(facts["tracks"].size()==1&&facts["tracks"][0]["clips"].size()==1,"native import preview commits real source to actual Edit");const std::string track=facts["tracks"][0]["id"];
    auto* gain=dynamic_cast<juce::Slider*>(find(w,"track.gain:"+juce::String{track}));check(gain!=nullptr,"native Edit gain is available");gain->setValue(6,juce::sendNotificationSync);pump();check(w.query()["tracks"][0]["gain_db"].get<double>()>5.9,"native gain writes through L1 to actual processing chain");
    const auto revision=w.query()["revision"];w.menuItemSelected(43,2);pump();auto* start=dynamic_cast<juce::TextEditor*>(find(w,"analysis.start_samples"));auto* end=dynamic_cast<juce::TextEditor*>(find(w,"analysis.end_samples"));check(start&&end,"View menu opens actual native Master analysis panel");start->setText("24013");end->setText("168013");click(w,"analysis.master.run");const auto deadline=juce::Time::getMillisecondCounterHiRes()+12000;while(w.queryAnalysis()["busy"].get<bool>()&&juce::Time::getMillisecondCounterHiRes()<deadline)pump(20);pump(300);auto status=w.queryAnalysis();check(status["state"]=="completed"&&status["receipt"]["current"].get<bool>()&&status["receipt"]["peak"].get<double>()>1.59,"native panel receives genuine selected Master analysis receipt");
    auto* summary=dynamic_cast<juce::TextEditor*>(find(w,"analysis.summary"));check(summary&&summary->getText().contains("True Peak")&&summary->getText().contains("24013")&&summary->getText().contains("当前工程证据"),"GUI exposes actual measurements, provenance and nonzero selected interval");
    check(w.query()["revision"]==revision,"analysis does not invent an editing transaction");const auto expected=status["receipt"]["events"][0]["start_samples"];click(w,"analysis.locate:0");check(w.query()["position_samples"]==expected&&!find(w,"analysis.panel"),"clicking actual measured event seeks native Transport and returns to Edit");
    gain=dynamic_cast<juce::Slider*>(find(w,"track.gain:"+juce::String{track}));gain->setValue(-12,juce::sendNotificationSync);pump();w.showAnalysis();pump(300);auto* stale=dynamic_cast<juce::Button*>(find(w,"analysis.locate:0"));summary=dynamic_cast<juce::TextEditor*>(find(w,"analysis.summary"));check(stale&&!stale->isEnabled()&&summary->getText().contains("历史快照"),"new human mix change disables stale event location in GUI");click(w,"analysis.close");click(w,"history.undo");check(w.query()["tracks"][0]["gain_db"].get<double>()>5.9&&!w.queryAnalysis()["receipt"]["current"].get<bool>(),"Undo affects human gain only and does not silently revive old analysis");
    w.showAnalysis();click(w,"analysis.master.run");click(w,"analysis.cancel");while(w.queryAnalysis()["busy"].get<bool>()&&juce::Time::getMillisecondCounterHiRes()<deadline+12000)pump(20);check(w.queryAnalysis()["state"]=="cancelled","native cancel action receives actual cancelled terminal state");click(w,"analysis.close");check(Commands::mediaHash(source)==original,"GUI analysis and locate preserve original media bytes");
    const double elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"native GUI qualification meets fixed sixty-second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"artifact",status["receipt"]},{"scope","real native JUCE callbacks and Tracktion analysis; desktop acceptance remains separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("GUI report write failed");}std::cout<<report.dump(2)<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
