#include "Workspace.h"
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;
namespace ndaw::v2 {class AudioDeviceTestAccess {public:static Commands& commands(ndaw::desktop::Workspace& w){return w.commands;}static void select(ndaw::desktop::Workspace& w,const std::string& id){w.refresh();w.select(id);}static bool inputDefaults(Commands& c){bool enabled=false;for(auto* input:c.engine.getDeviceManager().getWaveInputDevices())if(input->isEnabled()){enabled=true;if(input->getMonitorMode()!=te::InputDevice::MonitorMode::off||input->getChannels().getNumChannels()!=1||input->getBitDepth()!=24||input->getOutputFormat()!="WAV file")return false;}return enabled;}};}
namespace {
class Storage final : public te::PropertyStorage {public:explicit Storage(juce::File f):PropertyStorage("NativeDAW device qualification"),folder(std::move(f)){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
struct Scratch {juce::File folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-device-native-"+juce::Uuid().toString());~Scratch(){folder.deleteRecursively();}};
int checks=0;void check(bool ok,const char* msg){if(!ok)throw std::runtime_error(msg);++checks;std::cout<<"PASS "<<msg<<std::endl;}
template<class F>void fails(F f,const char* msg){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,msg);}
void settle(int ms=80){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* c:p.getChildren())if(auto* f=find(*c,id))return f;return nullptr;}
void click(juce::Component& root,const juce::String& id){auto* button=dynamic_cast<juce::Button*>(find(root,id));for(int n=0;n<40&&(!button||!button->isEnabled());++n){settle(25);button=dynamic_cast<juce::Button*>(find(root,id));}if(!button||!button->isEnabled())throw std::runtime_error("button unavailable: "+id.toStdString());auto action=button->onClick;auto executed=std::make_shared<bool>(false);juce::Component::SafePointer<juce::Button> safe(button);button->onClick=[action,executed]{if(action)action();*executed=true;};button->triggerClick();for(int n=0;n<40&&!*executed;++n)settle(25);if(safe)safe->onClick=action;if(!*executed)throw std::runtime_error("button callback deadline: "+id.toStdString());settle(25);}
void choose(juce::Component& root,const char* id,const juce::String& value){auto* combo=dynamic_cast<juce::ComboBox*>(find(root,id));if(!combo||!combo->isEnabled())throw std::runtime_error(std::string("combo unavailable: ")+id);for(int n=0;n<combo->getNumItems();++n)if(combo->getItemText(n)==value){combo->setSelectedId(combo->getItemId(n),juce::sendNotificationSync);settle();return;}throw std::runtime_error("actual device option unavailable: "+value.toStdString());}
Json request(Commands& c,const Json& setup){Json result=setup;result.erase("open");result.erase("running");result["base_setup_hash"]=c.audioDevices()["setup_hash"];return result;}
Json ready(Commands& c){auto receipt=c.audioDevices()["last_configuration"];for(int n=0;n<120&&receipt.is_object()&&receipt.value("state",std::string{})=="preparing";++n){settle(50);receipt=c.audioDevices()["last_configuration"];}if(receipt.is_object()&&receipt.value("state",std::string{})=="preparing")throw std::runtime_error("device preparation deadline");return receipt;}
Json configureAndWait(Commands& c,const Json& args){auto receipt=c.audioDeviceControl(args);return receipt["state"]=="preparing"?ready(c):receipt;}
Json operation(const char* id,Json args){return {{"command",id},{"args",args}};}
struct Restore {Commands& c;Json setup;~Restore(){try{c.stop();ready(c);auto r=configureAndWait(c,request(c,setup));if(r["state"]!="verified")std::cerr<<"DEVICE RESTORE FAILED "<<r.dump()<<std::endl;}catch(const std::exception& e){std::cerr<<"DEVICE RESTORE FAILED "<<e.what()<<std::endl;}}};
void tone(const juce::File& file){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> out=file.createOutputStream();auto writer=wav.createWriterFor(out,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture writer");juce::AudioBuffer<float> buffer(2,96000);for(int n=0;n<96000;++n)for(int ch=0;ch<2;++ch)buffer.setSample(ch,n,(ch?.0005f:.001f)*std::sin(float(2*juce::MathConstants<double>::pi*400*n/48000)));if(!writer->writeFromAudioSampleBuffer(buffer,0,96000))throw std::runtime_error("fixture write");}
}
Json qualifyRestart(){
    Scratch scratch;Json result;auto active=std::make_unique<Commands>(true,std::make_unique<Storage>(scratch.folder));const auto original=active->audioDevices()["actual"];
    struct Backup {std::unique_ptr<Commands>& active;Json original;juce::File folder;~Backup(){try{if(!active)active=std::make_unique<Commands>(true,std::make_unique<Storage>(folder));auto r=configureAndWait(*active,request(*active,original));if(r["state"]!="verified")std::cerr<<"DEVICE RESTORE FAILED "<<r.dump()<<std::endl;}catch(const std::exception& e){std::cerr<<"DEVICE RESTORE FAILED "<<e.what()<<std::endl;}}} backup{active,original,scratch.folder};
    auto changed=request(*active,original);changed["input"]="";changed["input_channels"]=Json::array();changed["sample_rate"]=44100;auto receipt=configureAndWait(*active,changed);check(receipt["state"]=="verified"&&receipt["preferences_saved"],"actual device choice is persisted to isolated on-disk preferences");
    active.reset();active=std::make_unique<Commands>(true,std::make_unique<Storage>(scratch.folder));auto reopened=active->audioDevices()["actual"];
    check(reopened["sample_rate"]==44100&&reopened["open"]&&reopened["running"],"fresh Engine restart honors persisted 44.1 kHz instead of forcing 48 kHz");check(reopened["buffer_frames"]==receipt["actual"]["buffer_frames"]&&reopened["output_channels"]==receipt["actual"]["output_channels"],"Engine restart restores persisted buffer and physical channels");check(active->query()["timeline_sample_rate"]==48000,"device and project sample domains remain distinct after restart");result={{"receipt",receipt},{"reopened",reopened},{"preferences","isolated temporary on-disk storage; production startup path"}};return result;
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{Json summary;{
    Scratch scratch;ndaw::desktop::Workspace w(true,std::make_unique<Storage>(scratch.folder));w.setVisible(true);w.setSize(1440,880);auto& c=AudioDeviceTestAccess::commands(w);auto initial=c.audioDevices();Restore restore{c,initial["actual"]};
    check(initial["actual"]["type"]=="CoreAudio"&&initial["actual"]["open"]&&initial["actual"]["running"],"actual CoreAudio device is open and running");
    click(w,"audio.settings.open");auto* panel=find(w,"audio.settings.panel");check(panel&&panel->getBounds()==w.getLocalBounds(),"native audio settings panel opens inside production workspace");
    auto* display=dynamic_cast<juce::Label*>(find(w,"audio.settings.actual"));check(display&&display->getText().contains(juce::String(initial["actual"]["output"].get<std::string>())),"panel reads actual output rather than fabricated device name");
    auto capabilities=c.audioCapabilities({{"type",initial["actual"]["type"]},{"output",initial["actual"]["output"]},{"input",""}});auto* rates=dynamic_cast<juce::ComboBox*>(find(w,"audio.settings.rate"));auto* buffers=dynamic_cast<juce::ComboBox*>(find(w,"audio.settings.buffer"));check(rates&&buffers&&rates->getNumItems()==int(capabilities["sample_rates"].size())&&buffers->getNumItems()==int(capabilities["buffer_sizes"].size()),"GUI enumerates actual native sample rates and buffer sizes");
    auto fixture=juce::File::getSpecialLocation(juce::File::tempDirectory).getNonexistentChildFile("ndaw-device-tone",".wav");tone(fixture);const auto originalHash=Commands::mediaHash(fixture);
    auto p=c.makePlan("human",Json::array({operation("track.create",{{"name","Device playback test"},{"ref","$audio"}}),operation("clip.import",{{"track","$audio"},{"path",fixture.getFullPathName().toStdString()},{"position_samples",0}})}));c.commit(p);const auto tracks=c.query()["tracks"],revision=c.query()["revision"];
    Json receipts=Json::array();const double alternate=initial["actual"]["sample_rate"]==44100?48000:44100;check(std::find(capabilities["sample_rates"].begin(),capabilities["sample_rates"].end(),Json(alternate))!=capabilities["sample_rates"].end(),"actual device supports alternate 44.1/48 kHz qualification");
    int frames=initial["actual"]["buffer_frames"]==128?256:128;check(std::find(capabilities["buffer_sizes"].begin(),capabilities["buffer_sizes"].end(),Json(frames))!=capabilities["buffer_sizes"].end(),"actual device supports chosen alternate buffer");
    choose(w,"audio.settings.input",ndaw::desktop::text("关闭音频输入"));choose(w,"audio.settings.rate",juce::String(alternate/1000.,alternate==44100?1:0)+" kHz");choose(w,"audio.settings.buffer",juce::String(frames)+ndaw::desktop::text(" 帧"));click(w,"audio.settings.apply");
    auto preparing=c.audioDevices();check(preparing["last_configuration"]["state"]=="preparing"&&!find(w,"audio.settings.apply")->isEnabled(),"driver confirmation remains pending until actual callback readiness");fails([&]{c.play();},"Play is rejected while native device preparation is pending");fails([&]{c.undo();},"Edit Undo cannot rebuild the graph during device preparation");check(!c.query()["playing"].get<bool>()&&!find(w,"transport.play")->isEnabled()&&c.query()["audio_configuration"]["state"]=="preparing","pending device state disables native playback and does not show false playback");ready(c);settle();
    auto changed=c.audioDevices();check(changed["last_configuration"]["state"]=="verified"&&changed["actual"]["sample_rate"]==alternate&&changed["actual"]["buffer_frames"]==frames,"GUI Apply changes and verifies actual CoreAudio sample rate and buffer");receipts.push_back(changed["last_configuration"]);
    check(c.query()["tracks"]==tracks&&c.query()["revision"].get<uint64_t>()==revision.get<uint64_t>()+1,"device change preserves Edit content and invalidates stale Plans");
    auto* result=dynamic_cast<juce::Label*>(find(w,"audio.settings.result"));check(result&&result->getText().contains(ndaw::desktop::text("已核验")),"GUI displays completion only after actual native verification");
    auto noOp=c.audioDeviceControl(request(c,changed["actual"]));check(noOp["state"]=="verified"&&noOp["unchanged"]&&c.query()["revision"]==noOp["revision"],"reapplying actual settings is an idempotent no-op outside edit history");
    auto stale=request(c,changed["actual"]);stale["base_setup_hash"]="obsolete";auto before=c.audioDevices();fails([&]{c.audioDeviceControl(stale);},"stale audio settings are rejected before mutation");
    auto bad=request(c,changed["actual"]);bad["sample_rate"]=12345;fails([&]{c.audioDeviceControl(bad);},"unsupported sample rate is not silently substituted by JUCE");bad=request(c,changed["actual"]);bad["buffer_frames"]=13;fails([&]{c.audioDeviceControl(bad);},"unsupported buffer is not silently substituted");
    bad=request(c,changed["actual"]);bad["output_channels"]={0,0};fails([&]{c.audioDeviceControl(bad);},"duplicate physical channels rejected");bad["output_channels"]={128};fails([&]{c.audioDeviceControl(bad);},"unavailable physical channel rejected");bad["output_channels"]=Json::array();fails([&]{c.audioDeviceControl(bad);},"empty output cannot be reported as successful configuration");bad=request(c,changed["actual"]);bad["output"]="missing device";fails([&]{c.audioDeviceControl(bad);},"missing actual device rejected");bad=request(c,changed["actual"]);bad["actor"]="human";fails([&]{c.audioDeviceControl(bad);},"untrusted identity field cannot alter device control permission");
    auto args=request(c,changed["actual"]);fails([&]{c.makePlan("agent:model",Json::array({operation("audio.device.apply",args)}));},"Agent Plan cannot invoke high risk local device control");
    std::string workerError;std::thread worker([&]{try{c.audioDeviceControl(args);}catch(const std::exception& e){workerError=e.what();}});worker.join();check(!workerError.empty(),"background thread cannot configure native device directly");
    check(c.audioDevices()["setup_hash"]==before["setup_hash"]&&c.audioDevices()["last_configuration"]==before["last_configuration"],"rejected controls preserve native device and last real receipt");
    auto beforePlayback=c.deviceStatus();c.seek(0);c.play();settle(350);auto afterPlayback=c.deviceStatus();std::cout<<"playback_before="<<beforePlayback.dump()<<" playback_after="<<afterPlayback.dump()<<" position="<<c.query()["position_samples"]<<std::endl;check(beforePlayback["output_maximum"]==0&&c.query()["playing"]&&afterPlayback["output_frames"].get<uint64_t>()>beforePlayback["output_frames"].get<uint64_t>()&&afterPlayback["output_maximum"].get<double>()>1e-6,"real Tracktion audio reaches CoreAudio after changed sample rate and buffer");
    auto stereo=c.outputMeters();check(stereo["available"]&&stereo["tap_point"]=="device_output_before_sdk_limiter"&&stereo["measurement"]=="sample_peak"&&stereo["channel_count"]==2,"real CoreAudio exposes the two measured output channels with truthful tap metadata");
    const auto left=stereo["channels"][0]["hold"].get<double>(),right=stereo["channels"][1]["hold"].get<double>();check(left>.0009&&std::abs(right/left-.5)<.01,"actual Tracktion stereo PCM retains the asymmetric source channel levels at the device tap");
    const auto meterRevision=c.query()["revision"],meterTracks=c.query()["tracks"];fails([&]{c.makePlan("agent:model",Json::array({operation("audio.meters.reset",Json::object())}));},"meter control is not an Edit Plan");
    fails([&]{c.outputMeterControl("audio.meters.reset",{{"actor","human"}});},"meter control cannot take untrusted identity fields");
    click(w,"view.mix");click(w,"mix.output.reset");settle(80);auto resetMeter=c.outputMeters();check(resetMeter["reset_requested"].get<uint64_t>()>0&&resetMeter["reset_applied"]==resetMeter["reset_requested"]&&!resetMeter["reset_pending"].get<bool>(),"production Mix reset waits for the actual CoreAudio callback acknowledgement");
    check(c.query()["revision"]==meterRevision&&c.query()["tracks"]==meterTracks,"output meter reset leaves Edit, revision and Undo history unchanged");
    check(!find(w,"audio.settings.apply")->isEnabled()&&!find(w,"audio.settings.refresh")->isEnabled(),"GUI disables Apply and rescan during actual playback");fails([&]{c.audioDeviceControl(request(c,changed["actual"]));},"L1 rejects reconfiguration during actual playback");c.stop();settle();check(find(w,"audio.settings.apply")->isEnabled(),"device controls return after Stop");
    auto silentReset=c.outputMeterControl("audio.meters.reset",Json::object());check(silentReset["state"]=="pending","Stop-time reset initially reports pending rather than false completion");settle(100);auto silence=c.outputMeters();check(silence["reset_applied"]==silence["reset_requested"]&&silence["channels"][0]["hold"].get<double>()<1e-7&&silence["channels"][1]["hold"].get<double>()<1e-7,"CoreAudio continues callbacks while transport stopped and clears old held peaks");
    c.undo(p["plan_id"]);check(c.query()["tracks"].empty()&&c.audioDevices()["actual"]["sample_rate"]==alternate,"Edit Undo removes the edit and leaves device configuration intact");c.redo();check(c.query()["tracks"]==tracks,"Edit Redo remains correct across device changes");
    auto mono=request(c,changed["actual"]);mono["output_channels"]={0};auto monoReceipt=configureAndWait(c,mono);check(monoReceipt["state"]=="verified"&&monoReceipt["actual"]["output_channels"]==Json::array({0}),"explicit physical channel mask is applied and read back");receipts.push_back(monoReceipt);
    auto restored=configureAndWait(c,request(c,initial["actual"]));check(restored["state"]=="verified"&&restored["actual"]==initial["actual"],"original actual CoreAudio format and channels restored");receipts.push_back(restored);click(w,"audio.settings.refresh");click(w,"audio.settings.close");for(int n=0;n<8&&find(w,"audio.settings.panel");++n)settle(50);check(!find(w,"audio.settings.panel"),"Close removes audio settings overlay");
    Json inputQualification={{"state","not_executed"},{"reason","existing microphone permission/device unavailable; no permission granted by test"}};
    if(c.deviceStatus()["input_permission"]=="authorized"&&!c.deviceStatus()["input_devices"].empty()){
        AudioDeviceTestAccess::select(w,tracks[0]["id"]);click(w,"inspector.recording");const auto inputRevision=c.query()["revision"].get<uint64_t>();click(w,"recording.enable_input");
        check(c.audioDevices()["last_configuration"]["state"]=="preparing"&&!find(w,"recording.enable_input")->isEnabled(),"production recording input handler waits for real device preparation");auto inputReceipt=ready(c);settle();
        check(inputReceipt["state"]=="verified"&&c.deviceStatus()["active_input_channels"].get<int>()>0&&AudioDeviceTestAccess::inputDefaults(c),"actual CoreAudio input maps to enabled mono Tracktion channels with monitoring off");
        check(c.query()["tracks"]==tracks&&c.query()["revision"].get<uint64_t>()==inputRevision+1,"recording inspector device setup preserves Edit and increments revision once");
        inputQualification={{"state","verified_configuration_only"},{"receipt",inputReceipt},{"devices",c.deviceStatus()["inputs"]},{"microphone_recording","not_executed"}};auto inputRestored=configureAndWait(c,request(c,initial["actual"]));check(inputRestored["state"]=="verified"&&inputRestored["actual"]==initial["actual"],"actual input device configuration restores original hardware setup");
    }
    check(Commands::mediaHash(fixture)==originalHash,"device configuration never alters source PCM");fixture.deleteFile();
    summary={{"result","passed"},{"checks",checks},{"initial",initial["actual"]},{"capabilities",capabilities},{"receipts",receipts},{"input_configuration",inputQualification},{"playback_before",beforePlayback},{"playback_after",afterPlayback},{"output_meter_qualification",{{"stereo",stereo},{"after_gui_reset",resetMeter},{"after_stop_reset",silence},{"source_hash",originalHash}}},{"scope","actual CoreAudio, Tracktion callbacks and production GUI handlers; desktop pointer interaction, physical input, device disconnect and round-trip latency are not qualified"}};}
    summary["restart"]=qualifyRestart();summary["checks"]=checks;if(argc>1){std::ofstream out(argv[1]);out<<summary.dump(2);if(!out)throw std::runtime_error("report write");}std::cout<<summary.dump(2)<<std::endl;return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
