// SPDX-License-Identifier: AGPL-3.0-only
#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace ndaw::v2 {
class ParameterTestAccess {public:
    static std::vector<std::string> history(Commands& c){return {c.history.begin(),c.history.begin()+c.historyCursor};}
    static juce::AudioPluginInstance& instance(Commands& c,const std::string& id){auto* p=dynamic_cast<te::ExternalPlugin*>(c.processor(id));if(!p||!p->getAudioPluginInstance())throw std::runtime_error("actual instance unavailable");return *p->getAudioPluginInstance();}
};
}
namespace {
class Storage final:public te::PropertyStorage {public:explicit Storage(juce::File f):PropertyStorage("NativeDAW plugin device qualification"),folder(std::move(f)){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
struct Scratch {juce::File folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-plugin-device-"+juce::Uuid().toString());~Scratch(){folder.deleteRecursively();}};
int checks=0;Json renders=Json::array(),receipts=Json::array(),playbacks=Json::array();
void check(bool ok,const char* name){if(!ok)throw std::runtime_error(name);++checks;std::cout<<"PASS "<<name<<std::endl;}
void settle(int ms=80){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json operation(const char* command,Json args){return {{"command",command},{"args",args}};}
Json run(Commands& c,Json ops){auto p=c.makePlan("human",std::move(ops));c.commit(p);settle();return p;}
Json request(Commands& c,const Json& setup){auto args=setup;args.erase("open");args.erase("running");args["base_setup_hash"]=c.audioDevices()["setup_hash"];return args;}
Json ready(Commands& c){auto r=c.audioDevices()["last_configuration"];for(int n=0;n<120&&r.is_object()&&r.value("state",std::string{})=="preparing";++n){settle(50);r=c.audioDevices()["last_configuration"];}if(r.is_object()&&r.value("state",std::string{})=="preparing")throw std::runtime_error("device preparation deadline");return r;}
Json configure(Commands& c,Json args){auto r=c.audioDeviceControl(args);return r["state"]=="preparing"?ready(c):r;}
struct Restore {Commands& c;Json original;~Restore(){try{c.stop();ready(c);auto r=configure(c,request(c,original));if(r["state"]!="verified")std::cerr<<"DEVICE RESTORE FAILED "<<r.dump()<<std::endl;}catch(const std::exception& e){std::cerr<<"DEVICE RESTORE FAILED "<<e.what()<<std::endl;}}};
void tone(const juce::File& file){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> out=file.createOutputStream();auto writer=wav.createWriterFor(out,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture writer failed");juce::AudioBuffer<float> b(2,192000);for(int i=0;i<192000;++i)for(int ch=0;ch<2;++ch)b.setSample(ch,i,.005f*std::sin(float(2*juce::MathConstants<double>::pi*1000*i/48000)));if(!writer->writeFromAudioSampleBuffer(b,0,192000))throw std::runtime_error("fixture write failed");}
Json parameter(Commands& c,const std::string& plugin,const char* name){auto q=c.query();for(const auto& t:q["tracks"])for(const auto& p:t["plugins"])if(p["id"]==plugin)for(const auto& a:p["parameters"])if(a["name"]==name)return a;throw std::runtime_error("actual enumerated parameter unavailable");}
double auAudio(Commands& c,const juce::File& folder,const std::string& track,const char* name){auto history=ParameterTestAccess::history(c);auto last=c.query()["last_parameter_capture"];auto solo=run(c,Json::array({operation("track.solo",{{"track",track},{"enabled",true}})}));auto f=folder.getChildFile("au-"+juce::Uuid().toString()+".wav");auto r=c.render(f,0,96000);check(r["frames"]==96000&&r["render_ms"].get<double>()<10000,"actual AU render meets original frame/time budget");juce::AudioFormatManager fm;fm.registerBasicFormats();std::unique_ptr<juce::AudioFormatReader> reader(fm.createReaderFor(f));if(!reader)throw std::runtime_error("actual AU render unreadable");juce::AudioBuffer<float> b(2,96000);check(reader->read(&b,0,96000,0,true,true),"actual AU render decodes");const auto rms=b.getRMSLevel(0,12000,48000);renders.push_back({{"case",name},{"rms",rms},{"receipt",r}});c.undo(solo["plan_id"]);settle();check(ParameterTestAccess::history(c)==history&&c.query()["last_parameter_capture"]==last,"render and Solo Undo cannot append false human parameter transactions");return rms;}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    Scratch scratch;Commands c(true,std::make_unique<Storage>(scratch.folder));auto initial=c.audioDevices()["actual"];Restore restore{c,initial};check(initial["type"]=="CoreAudio"&&initial["open"]&&initial["running"],"real CoreAudio manager is active");
    std::string au,vst;auto inventory=c.pluginInventory();for(const auto& p:inventory["plugins"]){if(p["name"]=="AUNBandEQ"&&p["format"]=="AudioUnit")au=p["id"];if(p["name"]=="Serum"&&p["format"]=="VST3")vst=p["id"];}check(!au.empty()&&!vst.empty(),"real independently scanned AU and VST3 are available");
    auto source=scratch.folder.getChildFile("known.wav");tone(source);auto sourceHash=Commands::mediaHash(source);
    run(c,Json::array({operation("track.create",{{"name","Actual AU audio"},{"ref","$audio"}}),operation("clip.import",{{"track","$audio"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}}),operation("plugin.external.insert",{{"track","$audio"},{"descriptor",au}}),operation("track.gain",{{"track","$audio"},{"db",-12}}),
        operation("track.create",{{"name","Actual Serum MIDI"},{"type","midi"},{"ref","$synth"}}),operation("plugin.external.insert",{{"track","$synth"},{"descriptor",vst}}),operation("track.gain",{{"track","$synth"},{"db",-42}}),operation("midi.clip.create",{{"track","$synth"},{"ref","$midi"},{"name","A4"},{"position_samples",0},{"length_samples",192000}}),operation("midi.note.add",{{"clip","$midi"},{"pitch",69},{"velocity",90},{"position_samples",0},{"length_samples",144000}})}));
    auto tracks=c.query()["tracks"];std::string audioTrack=tracks[0]["id"],auID=tracks[0]["plugins"][0]["id"],vstID=tracks[1]["plugins"][0]["id"];auto global=parameter(c,auID,"Global Gain"),master=parameter(c,vstID,"MasterVol");auto* auInstance=&ParameterTestAccess::instance(c,auID);auto* vstInstance=&ParameterTestAccess::instance(c,vstID);
    auto params=run(c,Json::array({operation("plugin.parameter",{{"plugin",auID},{"parameter",global["id"]},{"value",.75}}),operation("plugin.parameter",{{"plugin",vstID},{"parameter",master["id"]},{"value",.5}}),operation("plugin.program",{{"plugin",vstID},{"index",1}})}));
    const double expected=.005/std::sqrt(2.)*std::pow(10.,-18./20.);check(std::abs(auAudio(c,scratch.folder,audioTrack,"before device change")-expected)<3e-6,"actual AU attenuation has known numerical baseline");
    const auto clips=c.query()["tracks"];auto caps=c.audioCapabilities({{"type",initial["type"]},{"output",initial["output"]},{"input",""}});
    for(const double rate:{44100.,96000.}){
        check(std::find(caps["sample_rates"].begin(),caps["sample_rates"].end(),Json(rate))!=caps["sample_rates"].end(),"actual CoreAudio pair supports the qualification rate");
        c.pluginEditorControl("plugin.editor.open",{{"plugin",auID}});settle(150);c.pluginEditorControl("plugin.editor.open",{{"plugin",vstID}});settle(150);check(c.pluginEditorQuery().size()==2,"actual AU and VST3 editors exist before reconfiguration");
        auto args=request(c,c.audioDevices()["actual"]);args["input"]="";args["input_channels"]=Json::array();args["sample_rate"]=rate;args["buffer_frames"]=128;const auto revision=c.query()["revision"];const auto history=ParameterTestAccess::history(c);auto r=configure(c,args);receipts.push_back(r);check(r["state"]=="verified"&&r["actual"]["sample_rate"]==rate,"device with real external plugins completes actual readiness handshake");
        check(c.pluginEditorQuery().empty(),"device preparation releases native editors before rebuilding the graph");check(&ParameterTestAccess::instance(c,auID)==auInstance && &ParameterTestAccess::instance(c,vstID)==vstInstance,"device restart retains actual plugin instances and identities");
        check(auInstance->getSampleRate()==rate&&vstInstance->getSampleRate()==rate,"both native processors prepare at the actual device sample rate");settle(150);auto q=c.query();check(q["revision"].get<uint64_t>()==revision.get<uint64_t>()+1&&q["revision"]==r["revision"]&&ParameterTestAccess::history(c)==history,"device graph and deferred metadata settle as one revision without changing Edit history");
        check(q["parameter_capture"].is_null()&&q["native_plugin_states"]["failure"].is_null()&&!q["native_plugin_states"]["pending"].get<bool>(),"owned format preparation does not become an uncaptured human gesture");
        check(vstInstance->getCurrentProgram()==1,"actual Program index persists after device preparation");
        check(std::abs(parameter(c,auID,"Global Gain")["value"].get<double>()-.75)<1e-6&&std::abs(parameter(c,vstID,"MasterVol")["value"].get<double>()-.5)<1e-6,"actual AU and VST3 owned parameter values survive preparation");
        check(q["tracks"][0]["clips"]==clips[0]["clips"]&&q["tracks"][1]["clips"]==clips[1]["clips"]&&q["tracks"][0]["output"]==clips[0]["output"]&&q["tracks"][1]["output"]==clips[1]["output"]&&q["tracks"][0]["sends"]==clips[0]["sends"]&&q["tracks"][1]["sends"]==clips[1]["sends"],"real source mappings MIDI events and routing remain intact");
        const auto before=c.deviceStatus();c.seek(0);c.play();settle(400);const auto played=c.deviceStatus();check(c.query()["playing"]&&c.query()["position_samples"].get<int64_t>()>0&&played["output_frames"].get<uint64_t>()>before["output_frames"].get<uint64_t>()&&played["output_peak"].get<double>()>1e-6,"real mixed AU and VST3 audio reaches CoreAudio after reconfiguration");playbacks.push_back({{"sample_rate",rate},{"output_frames_advanced",played["output_frames"].get<uint64_t>()-before["output_frames"].get<uint64_t>()},{"status",played}});c.stop();settle();
        check(std::abs(auAudio(c,scratch.folder,audioTrack,"after device change")-expected)<3e-6,"known AU DSP remains correct after actual format change");
    }
    // A genuine SDK gesture after preparation must still become a human
    // transaction; recognizing changed AU mappings must not hide knob edits.
    auto historyBeforeGesture=ParameterTestAccess::history(c);auto* gain=auInstance->getParameters()[0];
    gain->beginChangeGesture();gain->setValueNotifyingHost(.7f);settle();gain->endChangeGesture();settle();
    auto human=c.query()["last_parameter_capture"];check(human["actor"]=="human"&&human["state"]=="committed"&&human["changes"].size()==1&&ParameterTestAccess::history(c).size()==historyBeforeGesture.size()+1,"actual AU gesture after format changes remains one captured human transaction");
    check(std::abs(parameter(c,auID,"Global Gain")["value"].get<double>()-.7)<1e-6,"actual post-preparation gesture changes native AU gain");c.undo(human["plan_id"]);settle();
    check(ParameterTestAccess::history(c)==historyBeforeGesture&&std::abs(parameter(c,auID,"Global Gain")["value"].get<double>()-.75)<1e-6,"post-preparation human Undo restores parameters and exact preceding history");
    check(std::abs(auAudio(c,scratch.folder,audioTrack,"human gesture undone")-expected)<3e-6,"post-preparation human Undo restores actual known DSP");
    c.undo(params["plan_id"]);settle();check(vstInstance->getCurrentProgram()==0&&std::abs(parameter(c,auID,"Global Gain")["value"].get<double>()-global["value"].get<double>())<1e-6,"one Undo still restores pre-change plugin parameters and Program");c.redo();settle();check(vstInstance->getCurrentProgram()==1&&std::abs(parameter(c,auID,"Global Gain")["value"].get<double>()-.75)<1e-6,"Redo survives actual device and processor preparations");
    auto saved=scratch.folder.getChildFile("device-plugins.tracktionedit");c.save(saved);c.open(saved);check(c.query()["tracks"][0]["plugins"][0]["id"]==auID&&c.query()["tracks"][1]["plugins"][0]["id"]==vstID&&ParameterTestAccess::instance(c,vstID).getCurrentProgram()==1,"saved reconfigured session restores original native plugin IDs and Program");check(std::abs(auAudio(c,scratch.folder,audioTrack,"saved reopened")-expected)<3e-6,"reopened reconfigured AU retains actual known DSP");check(Commands::mediaHash(source)==sourceHash,"format preparation never alters source PCM");
    auto restored=configure(c,request(c,initial));check(restored["state"]=="verified"&&restored["actual"]==initial,"original actual CoreAudio device setup restored");
    Json summary={{"result","passed"},{"checks",checks},{"initial",initial},{"receipts",receipts},{"renders",renders},{"playbacks",playbacks},{"source_sha256",sourceHash},{"scope","actual CoreAudio with actual AUNBandEQ AU and Serum VST3, processor preparations, real audio, original MIDI/media/routing, history and saved state; not a capacity stress test, physical audition or latency qualification"}};if(argc>1){std::ofstream out(argv[1]);out<<summary.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<summary.dump(2)<<std::endl;return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
