#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<"\n";}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* child:p.getChildren())if(auto* c=find(*child,id))return c;return nullptr;}
void settle(int ms=80){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
void click(juce::Component& p,const juce::String& id){auto* b=dynamic_cast<juce::Button*>(find(p,id));if(!b||!b->isEnabled())throw std::runtime_error("button unavailable: "+id.toStdString());b->triggerClick();settle();}
juce::ComboBox& combo(juce::Component& p,const char* id){auto* b=dynamic_cast<juce::ComboBox*>(find(p,id));if(!b||!b->isEnabled())throw std::runtime_error("chooser unavailable");return *b;}
void mode(juce::Component& p,int id){combo(p,"automation.mode").setSelectedId(id,juce::sendNotificationSync);settle();}
void field(juce::Component& p,const char* id,const char* value){auto* e=dynamic_cast<juce::TextEditor*>(find(p,id));if(!e||!e->isEnabled())throw std::runtime_error("field unavailable");e->setText(value,false);}
Json volume(ndaw::desktop::Workspace& w,const std::string& id){auto q=w.queryAutomation(id);for(const auto& l:q["lanes"])if(l["parameter"]=="volume")return l;throw std::runtime_error("lane absent");}
juce::MouseEvent mouse(juce::Component& c,juce::Point<float> p,int clicks=1){return {juce::Desktop::getInstance().getMainMouseSource(),p,juce::ModifierKeys::leftButtonModifier,1,0,0,0,0,&c,&c,juce::Time::getCurrentTime(),p,juce::Time::getCurrentTime(),clicks,false};}
Json op(const char* cmd,Json args){return {{"command",cmd},{"args",args}};}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    ndaw::desktop::Workspace w(false);w.setVisible(true);w.setSize(1440,1050);click(w,"track.create");std::string id=w.query()["tracks"][0]["id"];click(w,"inspector.automation");
    check(combo(w,"automation.mode").getNumItems()==4&&combo(w,"automation.lane").getNumItems()==2,"real volume and pan lanes and four native modes visible");
    mode(w,2);check(w.queryAutomation(id)["mode"]=="touch","GUI mode writes actual Tracktion mode");click(w,"history.undo");check(w.queryAutomation(id)["mode"]=="read","mode Undo restores Read");click(w,"history.redo");mode(w,1);
    click(w,"automation.point.add");field(w,"automation.position","0");field(w,"automation.point_value","-6");field(w,"automation.curve","1");click(w,"automation.point.set");auto first=volume(w,id)["points"][0];check(first["position_samples"]==0&&std::abs(first["value"].get<double>()+6)<.001&&first["curve"]==1,"numeric point editor stores samples dB and SDK curve");
    auto* canvas=find(w,"automation.canvas");canvas->mouseDoubleClick(mouse(*canvas,{90,90},2));settle();check(volume(w,id)["points"].size()==2,"curve double-click creates actual point");combo(w,"automation.point").setSelectedId(2,juce::sendNotificationSync);field(w,"automation.position","48000");field(w,"automation.point_value","0");field(w,"automation.curve","0");click(w,"automation.point.set");check(volume(w,id)["points"][1]["position_samples"]==48000,"second point can be placed at exact sample");
    auto snapshot=w.queryAutomation(id);field(w,"automation.point_value","broken");click(w,"automation.point.set");check(w.queryAutomation(id)==snapshot,"invalid numeric input leaves Edit and revision unchanged");field(w,"automation.point_value","99");click(w,"automation.point.set");check(w.queryAutomation(id)==snapshot,"actual range enforced at GUI command boundary");field(w,"automation.point_value","0");
    // Start moving the second point, perform another human edit, then release it.
    auto width=canvas->getWidth(),height=canvas->getHeight();auto point=juce::Point<float>{8+.1f*(width-16),8+float(1-60./66)*(height-30)};canvas->mouseDown(mouse(*canvas,point));click(w,"track.mute:"+juce::String(id));auto current=volume(w,id)["points"];canvas->mouseDrag(mouse(*canvas,{110,110}));canvas->mouseUp(mouse(*canvas,{110,110}));settle();check(volume(w,id)["points"]==current,"stale drag cannot overwrite intervening human transaction");click(w,"history.undo");
    combo(w,"automation.point").setSelectedId(2,juce::sendNotificationSync);click(w,"automation.point.delete");check(volume(w,id)["points"].size()==1,"delete button edits real curve");click(w,"history.undo");check(volume(w,id)["points"].size()==2,"delete Undo restores point");click(w,"automation.clear");check(volume(w,id)["points"].empty(),"clear button edits real curve");click(w,"history.undo");
    combo(w,"track.type").setSelectedId(5,juce::dontSendNotification);click(w,"track.create");click(w,"inspector.automation");check(!find(w,"automation.mode")->isEnabled()&&!find(w,"automation.point.add")->isEnabled(),"ordinary Folder exposes no fake automation lane");
    // Live GUI controls use the same capture API as the device/DSP tests.
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-auto-gui-"+juce::Uuid().toString());dir.createDirectory();auto session=dir.getChildFile("live.tracktionedit");std::string liveID,eqID;
    {Commands c(false);c.commit(c.makePlan("human",Json::array({op("track.create",{{"name","Live automation"},{"ref","$t"},{"type","instrument"}}),op("track.gain",{{"track","$t"},{"db",-18}}),op("automation.mode",{{"track","$t"},{"mode","touch"}})})));liveID=c.query()["tracks"][0]["id"];c.commit(c.makePlan("human",Json::array({op("plugin.insert",{{"track",liveID},{"type","4bandEq"}})})));eqID=c.query()["tracks"][0]["plugins"].back()["id"];c.save(session);}
    {ndaw::desktop::Workspace live(true);live.setVisible(true);live.setSize(1440,1050);live.openSession(session);click(live,"inspector.automation");check(dynamic_cast<juce::Slider*>(find(live,"automation.value"))->getTextFromValue(-18).contains("dB"),"instrument automation defaults to actual track volume rather than synth tuning");click(live,"transport.play");settle(180);auto capture=live.query()["automation_capture"];check(!capture.is_null()&&find(live,"automation.value")->isEnabled(),"GUI play starts genuine human capture and enables touch parameter");check(!find(live,"track.mute:"+juce::String(liveID))->isEnabled()&&!find(live,"automation.point.add")->isEnabled(),"structural edits disabled during SDK write pass");
        auto* fader=dynamic_cast<juce::Slider*>(find(live,"track.gain:"+juce::String(liveID)));fader->onDragStart();fader->setValue(-24,juce::sendNotificationSync);settle(260);fader->onDragEnd();settle(350);check(std::abs(volume(live,liveID)["value"].get<double>()+18)<.05,"Edit fader gesture genuinely returns in Touch");
        click(live,"transport.stop");auto recorded=volume(live,liveID)["points"];check(!recorded.empty()&&live.query()["last_automation_capture"]["plan_id"]==capture["plan_id"],"GUI stop commits actual fader curve receipt");click(live,"history.undo");check(volume(live,liveID)["points"].empty()&&live.query()["last_automation_capture"]["state"]=="undone","GUI one Undo restores empty curve and marks receipt undone");click(live,"history.redo");check(volume(live,liveID)["points"]==recorded,"GUI Redo restores actual recorded point identities");
        mode(live,1);click(live,"transport.play");check(!find(live,"track.gain:"+juce::String(liveID))->isEnabled(),"Read playback fader with actual curve is read-only");click(live,"transport.stop");mode(live,3);click(live,"view.mix");click(live,"transport.play");settle(180);auto* mixFader=dynamic_cast<juce::Slider*>(find(live,"track.gain:"+juce::String(liveID)));mixFader->onDragStart();mixFader->setValue(-30,juce::sendNotificationSync);settle(220);mixFader->onDragEnd();settle(300);check(std::abs(volume(live,liveID)["value"].get<double>()+30)<.05&&volume(live,liveID)["recording"],"Mix fader genuinely holds Latch");click(live,"transport.stop");click(live,"history.undo");
        click(live,"inspector.inserts");auto& choice=combo(live,"plugin.choice");choice.setSelectedId(2,juce::sendNotificationSync);settle();click(live,"transport.play");settle(180);auto* eq=dynamic_cast<juce::Slider*>(find(live,"plugin.parameter:Mid gain 1"));check(eq&&eq->isEnabled(),"enumerated native plugin parameter can record while playing");eq->onDragStart();eq->setValue(3,juce::sendNotificationSync);settle(200);eq->onDragEnd();click(live,"transport.stop");auto q=live.queryAutomation(liveID);bool actual=false;for(const auto& lane:q["lanes"])if(lane["id"]==eqID+"::Mid gain 1")actual=!lane["points"].empty();check(actual,"plugin editor gesture writes the actual instance curve");click(live,"history.undo");q=live.queryAutomation(liveID);for(const auto& lane:q["lanes"])if(lane["id"]==eqID+"::Mid gain 1")check(lane["points"].empty(),"plugin capture Undo restores original lane");
    }
    Json result={{"result","passed"},{"checks",checks},{"scope","production JUCE Edit/Mix automation editor, genuine CoreAudio gestures, no listening/endurance claim"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<result.dump(2)<<"\n";dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
