#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0,serial=0;Json renders=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<"\n";}
template<class F>void fails(F f,const char* why){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
void settle(int ms=80){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json op(const char* cmd,Json args){return {{"command",cmd},{"args",args}};}
Json run(Commands& c,Json ops){auto p=c.makePlan("human",ops);c.commit(p);settle();return p;}
Json add(const std::string& track,const std::string& param,const std::string& ref,int64_t position,double value,double curve=0){return op("automation.point.add",{{"track",track},{"parameter",param},{"ref",ref},{"position_samples",position},{"value",value},{"curve",curve}});}
Json persistentLanes(Commands& c,const std::string& track){auto lanes=c.automationQuery(track)["lanes"];for(auto& p:lanes){p.erase("value");p.erase("display");p.erase("recording");}return lanes;}
Json lane(Commands& c,const std::string& track,const std::string& parameter){auto q=c.automationQuery(track);for(auto& lane:q["lanes"])if(lane["parameter"]==parameter||lane["id"]==parameter)return lane;throw std::runtime_error("lane missing");}
void fixture(const juce::File& file){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture writer failed");juce::AudioBuffer<float> data(2,192000);for(int c=0;c<2;++c)for(int i=0;i<192000;++i)data.setSample(c,i,.1f*std::sin(2*juce::MathConstants<double>::pi*1000*i/48000));if(!writer->writeFromAudioSampleBuffer(data,0,192000))throw std::runtime_error("PCM write failed");}
juce::AudioBuffer<float> render(Commands& c,const juce::File& dir,const char* name){auto file=dir.getChildFile("auto-"+juce::String(++serial)+".wav");auto receipt=c.render(file,0,192000);check(receipt["frames"]==192000&&receipt["render_ms"].get<double>()<=10000,"actual automation render meets frame and deadline budget");renders.push_back({{"case",name},{"receipt",receipt}});juce::AudioFormatManager fm;fm.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(fm.createReaderFor(file));if(!reader||reader->numChannels!=2)throw std::runtime_error("render unreadable");juce::AudioBuffer<float> data(2,192000);if(!reader->read(&data,0,192000,0,true,true))throw std::runtime_error("render read failed");return data;}
std::string setup(Commands& c,const juce::File& source){run(c,Json::array({op("track.create",{{"name","Automation PCM"},{"ref","$track"}}),op("clip.import",{{"track","$track"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}})}));return c.query()["tracks"][0]["id"];}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-auto-"+juce::Uuid().toString());dir.createDirectory();auto source=dir.getChildFile("known.wav");fixture(source);auto hash=Commands::mediaHash(source);const double base=.1/std::sqrt(2.),six=std::pow(10.,-6./20.);
    Commands c(false);auto track=setup(c,source);auto plan=c.makePlan("agent:automation",Json::array({add(track,"volume","$a",0,-6,1),add(track,"volume","$b",48001,0),add(track,"volume","$c",191999,0)}));auto before=c.automationQuery(track);check(c.preview(plan)["changes"].size()==3&&c.automationQuery(track)==before,"automation dry-run leaves real curve unchanged");fails([&]{c.commit(plan);},"agent curve edit requires acceptance");c.commit(plan,true);settle();auto actual=render(c,dir,"sample-positioned volume Read");check(std::abs(actual.getRMSLevel(0,19200,4800)-base*six)<3e-6&&std::abs(actual.getRMSLevel(0,96000,4800)-base)<3e-6,"Read applies actual gain points to PCM");
    int first=-1;for(int i=47000;i<49000;++i){double raw=.1*std::sin(2*juce::MathConstants<double>::pi*1000*i/48000);if(std::abs(raw)>.03&&std::abs(actual.getSample(0,i)-raw*six)>1e-5){first=i;break;}}std::cout<<"step first actual change frame "<<first<<"\n";check(first>=48001&&first<=48513,"SDK step timing within fixed 512-frame budget, no early change");
    auto points=lane(c,track,"volume")["points"];check(points.size()==3&&!points[0]["id"].get<std::string>().empty(),"points have stable identities and integer positions");juce::MessageManager::getInstance()->runDispatchLoopUntil(450);c.undo(plan["plan_id"]);check(lane(c,track,"volume")["points"].empty(),"one delayed Undo removes whole curve Plan");c.redo();check(lane(c,track,"volume")["points"]==points,"Redo restores point IDs and native values");
    auto panPlan=run(c,Json::array({op("automation.clear",{{"track",track},{"parameter","volume"}}),add(track,"pan","$left",0,-1,1),add(track,"pan","$right",48000,1),add(track,"pan","$end",191999,1)}));auto panAudio=render(c,dir,"pan Read");check(std::abs(panAudio.getRMSLevel(0,19200,4800)-base*2)<3e-6&&panAudio.getRMSLevel(1,19200,4800)<3e-6&&panAudio.getRMSLevel(0,96000,4800)<3e-6&&std::abs(panAudio.getRMSLevel(1,96000,4800)-base*2)<3e-6,"actual pan curve changes channel routing with SDK Linear law");c.undo(panPlan["plan_id"]);c.redo();c.undo();
    run(c,Json::array({op("automation.clear",{{"track",track},{"parameter","volume"}}),op("plugin.insert",{{"track",track},{"type","4bandEq"}})}));auto eq=c.query()["tracks"][0]["plugins"][0];std::string eqLane;for(const auto& p:eq["parameters"])if(p["id"]=="Mid gain 1")eqLane=eq["id"].get<std::string>()+"::Mid gain 1";check(!eqLane.empty(),"EQ automation targets actual instance parameter");run(c,Json::array({op("plugin.parameter",{{"plugin",eq["id"]},{"parameter","Mid freq 1"},{"value",1000}}),add(track,eqLane,"$eq0",0,0,1),add(track,eqLane,"$eq6",48000,6),add(track,eqLane,"$eqEnd",191999,6)}));auto eqAudio=render(c,dir,"EQ gain automation");double db=20*std::log10(eqAudio.getRMSLevel(0,96000,4800)/eqAudio.getRMSLevel(0,19200,4800));std::cout<<"actual EQ delta "<<db<<" dB\n";check(db>5.5&&db<6.5,"real EQ gain automation changes audio by six dB");
    auto saved=dir.getChildFile("automation.tracktionedit");c.save(saved);{Commands reopened(false);reopened.open(saved);check(persistentLanes(reopened,track)==persistentLanes(c,track),"automation save/reopen preserves actual lanes and IDs");auto audio=render(reopened,dir,"reopened automation");check(std::abs(audio.getRMSLevel(0,96000,4800)-eqAudio.getRMSLevel(0,96000,4800))<3e-6,"reopened automation reproduces actual DSP");}
    auto point=lane(c,track,eqLane)["points"][0];auto edited=run(c,Json::array({op("automation.point.set",{{"track",track},{"parameter",eqLane},{"point",point["id"]},{"position_samples",12000},{"value",-3},{"curve",.2}})}));check(lane(c,track,eqLane)["points"][0]["id"]==point["id"]&&lane(c,track,eqLane)["points"][0]["position_samples"]==12000,"moving point preserves ID");c.undo(edited["plan_id"]);run(c,Json::array({op("automation.point.delete",{{"track",track},{"parameter",eqLane},{"point",point["id"]}})}));check(lane(c,track,eqLane)["points"].size()==2,"point delete changes actual curve");c.undo();
    auto snapshot=c.query();fails([&]{c.makePlan("human",Json::array({add(track,eqLane,"$bad",0,99)}));},"parameter range cannot be invented");fails([&]{c.makePlan("human",Json::array({add(track,"warmth","$bad",0,.5)}));},"unavailable semantic parameter rejected");fails([&]{c.makePlan("human",Json::array({op("automation.clear",{{"track",track},{"parameter",eqLane}}),op("automation.point.delete",{{"track",track},{"parameter",eqLane},{"point",point["id"]}})}));},"point removed earlier in Plan cannot be reused");check(c.query()==snapshot,"invalid Plan leaves Edit and revision unchanged");
    {Commands baseGain(false);auto id=setup(baseGain,source);run(baseGain,Json::array({op("track.gain",{{"track",id},{"db",-6}}),add(id,"volume","$one",0,-12)}));auto prior=lane(baseGain,id,"volume")["points"];render(baseGain,dir,"single-point Read before static gain Undo");auto changed=run(baseGain,Json::array({op("track.gain",{{"track",id},{"db",-3}})}));baseGain.undo(changed["plan_id"]);check(std::abs(lane(baseGain,id,"volume")["explicit_value"].get<double>()+6)<.01&&lane(baseGain,id,"volume")["points"]==prior,"static gain Undo restores stored base rather than last automated DSP value");}
    Json live=Json::array();for(const char* mode:{"read","touch","latch","write"}){Commands device(true);auto id=setup(device,source);run(device,Json::array({op("track.gain",{{"track",id},{"db",-6}}),add(id,"volume","$base0",0,-6),add(id,"volume","$baseEnd",191999,-6),op("automation.mode",{{"track",id},{"mode",mode}})}));auto initialPoints=lane(device,id,"volume")["points"];device.seek(0);device.play();settle(350);
        if(std::string(mode)=="read"){check(device.query()["automation_capture"].is_null(),"Read playback does not start write pass");fails([&]{device.automationControl("automation.gesture.begin",{{"track",id},{"parameter","volume"}});},"Read cannot write curve");fails([&]{device.makePlan("human",Json::array({op("track.gain",{{"track",id},{"db",-12}})}));},"Read fader with curve cannot masquerade as a live manual edit");device.stop();check(lane(device,id,"volume")["points"]==initialPoints,"Read leaves curve unchanged");continue;}
        auto captureID=device.query()["automation_capture"]["plan_id"];auto queryAtValue=device.query()["position_samples"].get<int64_t>();device.automationControl("automation.gesture.begin",{{"track",id},{"parameter","volume"}});device.automationControl("automation.gesture.value",{{"track",id},{"parameter","volume"},{"value",-12}});settle(400);device.automationControl("automation.gesture.end",{{"track",id},{"parameter","volume"}});auto releaseSample=device.query()["position_samples"].get<int64_t>();settle(450);auto current=lane(device,id,"volume");
        std::cout<<"mode "<<mode<<" value after release "<<current["value"]<<" recording "<<current["recording"]<<"\n";check(std::abs(current["value"].get<double>()-(std::string(mode)=="touch"?-6:-12))<.05,"Touch returns while Latch and Write hold after release");check(current["recording"].get<bool>()==(std::string(mode)!="touch"),"mode recording flag reflects real SDK state");fails([&]{device.makePlan("agent:stale",Json::array({op("track.gain",{{"track",id},{"db",0}})}));},"active write pass rejects overlapping edit Plan");device.stop();settle();auto recorded=lane(device,id,"volume")["points"];check(recorded!=initialPoints&&device.query()["automation_capture"].is_null()&&device.query()["last_automation_capture"]["plan_id"]==captureID,"Stop publishes actual recorded curve and capture receipt");auto recordedAudio=render(device,dir,mode);check(std::abs(recordedAudio.getRMSLevel(0,int(queryAtValue+4096),4800)-base*std::pow(10.,-12./20.))<3e-6,"recorded gesture actually controls rendered PCM");if(std::string(mode)!="touch")check(std::abs(recordedAudio.getRMSLevel(0,int(releaseSample+4800),4800)-base*std::pow(10.,-12./20.))<3e-6,"Latch and Write keep rendered gain after release");
        device.undo(captureID);check(lane(device,id,"volume")["points"]==initialPoints,"one Undo restores pre-pass curve");device.redo();check(lane(device,id,"volume")["points"]==recorded,"Redo restores recorded IDs and values");live.push_back({{"mode",mode},{"release_sample",releaseSample},{"current_after_release",current["value"]},{"receipt",device.query()["last_automation_capture"]},{"device",device.deviceStatus()}});
    }
    {Commands interrupted(true);auto id=setup(interrupted,source);run(interrupted,Json::array({op("track.gain",{{"track",id},{"db",-6}}),add(id,"volume","$start",0,-6),add(id,"volume","$end",191999,-6),op("automation.mode",{{"track",id},{"mode","touch"}})}));auto prior=lane(interrupted,id,"volume")["points"];interrupted.play();settle(180);auto cid=interrupted.query()["automation_capture"]["plan_id"];interrupted.automationControl("automation.gesture.begin",{{"track",id},{"parameter","volume"}});interrupted.automationControl("automation.gesture.value",{{"track",id},{"parameter","volume"},{"value",-12}});settle(200);auto stoppedAt=interrupted.query()["position_samples"].get<int64_t>();interrupted.stop();settle();check(interrupted.query()["automation_capture"].is_null()&&!lane(interrupted,id,"volume")["recording"].get<bool>(),"Stop during Touch ends gesture and commits capture");auto audio=render(interrupted,dir,"Touch interrupted by Stop");check(std::abs(audio.getRMSLevel(0,int(stoppedAt+24000),4800)-base*six)<3e-6,"interrupted Touch returns against original future curve");interrupted.undo(cid);check(lane(interrupted,id,"volume")["points"]==prior,"interrupted Touch remains one reversible transaction");}
    check(Commands::mediaHash(source)==hash,"automation never changes source PCM");Json result={{"result","passed"},{"checks",checks},{"step_requested_frame",48001},{"step_actual_frame",first},{"eq_delta_db",db},{"live",live},{"renders",renders},{"scope","actual SDK curves, renderer and CoreAudio device automation; not full RT/endurance qualification"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<result.dump(2)<<"\n";dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
