#include <nativedaw/v2/AudioAnalysis.h>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,why);}
Json op(const char* command,Json args){return {{"command",command},{"args",args}};}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-clip-tail-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto source=folder.getChildFile("real-end-pulse.wav");juce::AudioBuffer<float> data(2,24000);data.clear();for(int n=19200;n<24000;++n){data.setSample(0,n,.4f);data.setSample(1,n,-.2f);} {juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=source.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));check(writer&&writer->writeFromAudioSampleBuffer(data,0,24000),"write actual clip-end calibration pulse");}
    Commands c(false);c.commit(c.makePlan("human",Json::array({op("track.create",{{"name","Actual clip tail"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",source.getFullPathName().toStdString()},{"position_samples",0},{"ref","$c"}}),op("track.gain",{{"track","$t"},{"db",0}}),op("clip.fx.insert",{{"clip","$c"},{"type",te::DelayPlugin::xmlTypeName}})})));auto facts=c.query();const std::string clip=facts["tracks"][0]["clips"][0]["id"],delay=facts["tracks"][0]["clips"][0]["plugins"][0]["id"];c.commit(c.makePlan("human",Json::array({op("plugin.parameter",{{"plugin",delay},{"parameter","feedback"},{"value",-30}}),op("plugin.parameter",{{"plugin",delay},{"parameter","mix proportion"},{"value",1}})})));
    const auto exported=folder.getChildFile("actual-tail.wav");c.render(exported,0,38400);juce::AudioFormatManager formats;formats.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(formats.createReaderFor(exported));check(reader&&reader->lengthInSamples==38400&&reader->bitsPerSample==24,"production WAV really contains requested post-clip interval");juce::AudioBuffer<float> output(2,38400);check(reader->read(&output,0,38400,0,true,true),"decode actual exported tail PCM");double peak=0,sum=0;int64_t active=0;bool pcmMatches=true;for(int n=0;n<38400;++n){const bool pulse=n>=26400&&n<31200;for(int ch=0;ch<2;++ch){const auto value=output.getSample(ch,n);pcmMatches=pcmMatches&&std::abs(value-(pulse?(ch?-.2f:.4f):0.f))<=3e-6;if(n>=24000){peak=std::max(peak,std::abs(double(value)));sum+=double(value)*value;}}if(n>=24000&&std::abs(output.getSample(0,n))>.1f)++active;}check(pcmMatches,"all production clip Delay PCM samples match independent exact shifted source pulse");
    check(peak>.39&&active==4800&&sum>0,"native clip FX produces a real tail outside clip end when no fade bounds it");
    Scope bounded;bounded.mode=Permission::Preview;bounded.targets={clip};bounded.begin=0;bounded.end=24000;
    for(const auto& operation:Json::array({op("plugin.bypass",{{"plugin",delay},{"bypassed",true}}),op("plugin.remove",{{"plugin",delay}}),op("clip.gain",{{"clip",clip},{"db",-6}}),op("clip.fx.insert",{{"clip",clip},{"type",te::EqualiserPlugin::xmlTypeName}})})){auto plan=c.makePlan("agent:tail",Json::array({operation}));fails([&]{c.review(plan,bounded);},"finite interval cannot authorize effect changes with an unqualified tail footprint");}
    auto lock=c.makePlan("agent:tail",Json::array({op("clip.lock",{{"clip",clip},{"locked",true}})}));check(c.review(lock,bounded)["permission"]["impacts"].size()==2,"clip lock changes metadata and remains permitted in its exact clip interval");auto unrestricted=bounded;unrestricted.end=std::numeric_limits<int64_t>::max();auto plan=c.makePlan("agent:tail",Json::array({op("plugin.bypass",{{"plugin",delay},{"bypassed",true}})}));check(c.review(plan,unrestricted)["permission"]["impacts"][0]["effect_tail_unqualified"].get<bool>(),"whole-time target grant exposes real unqualified tail in review");auto before=c.query();c.commit(plan,true,unrestricted);check(c.query()["tracks"][0]["clips"][0]["plugins"][0]["bypassed"].get<bool>(),"confirmed target-bounded full-time Plan controls actual clip plugin");c.undo(plan["plan_id"]);check(c.query()["tracks"]==before["tracks"],"Undo restores tail-producing processor state");
    Json report={{"result","passed"},{"checks",checks},{"post_clip_peak",peak},{"post_clip_active_frames",active},{"clip_end_samples",24000},{"tail_pulse_start_samples",26400},{"tail_pulse_end_samples",31200},{"policy","effect tail is not bounded by clip position alone; restricted targets retained, whole-time authorization needed until footprint qualification"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<"RESULT "<<report.dump()<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
