#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0,serial=0;Json renders=Json::array();
void check(bool v,const char* n){if(!v)throw std::runtime_error(n);++checks;std::cout<<"PASS "<<n<<std::endl;}
template<class F>void fails(F f,const char* n){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,n);}
Json op(const char* cmd,Json a){return {{"command",cmd},{"args",a}};}
Json run(Commands& c,Json ops){return c.commit(c.makePlan("human",ops));}
Json clips(Commands& c){return c.query()["tracks"][0]["clips"];}
juce::File fixture(const juce::File& dir,double sr,bool dc=false){auto file=dir.getChildFile("source-"+juce::String(sr)+".wav");juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(sr).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture writer unavailable");juce::AudioBuffer<float> pcm(2,int(sr*4));for(int n=0;n<pcm.getNumSamples();++n){pcm.setSample(0,n,dc?.1f:float(.1*std::sin(2*juce::MathConstants<double>::pi*1000*n/sr)));pcm.setSample(1,n,dc?.08f:float(.08*std::sin(2*juce::MathConstants<double>::pi*431*n/sr)));}if(!writer->writeFromAudioSampleBuffer(pcm,0,pcm.getNumSamples()))throw std::runtime_error("fixture write failed");writer.reset();return file;}
juce::AudioBuffer<float> render(Commands& c,const juce::File& dir,const char* name,int64_t frames=240000){auto file=dir.getChildFile("render-"+juce::String(++serial)+".wav");auto receipt=c.render(file,0,frames);check(receipt["render_ms"].get<double>()<=10000&&receipt["frames"]==frames,"clip render meets fixed 10 second and exact length budget");renders.push_back({{"case",name},{"receipt",receipt}});juce::AudioFormatManager f;f.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(f.createReaderFor(file));if(!reader)throw std::runtime_error("render read failed");juce::AudioBuffer<float> pcm(2,int(frames));if(!reader->read(&pcm,0,int(frames),0,true,true))throw std::runtime_error("PCM read failed");return pcm;}
double difference(const juce::AudioBuffer<float>& a,int ai,const juce::AudioBuffer<float>& b,int bi,int length,double scale=1){double e=0;for(int c=0;c<2;++c)for(int i=0;i<length;++i)e=std::max(e,std::abs(double(a.getSample(c,ai+i))-b.getSample(c,bi+i)*scale));return e;}
void restore(Commands& c,const Json& receipt,const Json& before,const Json& after){juce::MessageManager::getInstance()->runDispatchLoopUntil(400);c.undo(receipt["plan_id"]);check(clips(c)==before,"one delayed Undo restores clip IDs source mapping and parameters");c.redo();check(clips(c)==after,"Redo restores identical clip state and stable IDs");c.undo(receipt["plan_id"]);}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-clips-"+juce::Uuid().toString());dir.createDirectory();auto file=fixture(dir,48000);auto hash=Commands::mediaHash(file);Commands c(false);
    run(c,Json::array({op("track.create",{{"name","Audio"},{"ref","$a"}}),op("clip.import",{{"track","$a"},{"path",file.getFullPathName().toStdString()},{"position_samples",24000},{"ref","$c"}})}));const auto original=clips(c);std::string id=original[0]["id"],track=c.query()["tracks"][0]["id"];auto pcm=render(c,dir,"original");
    check(original[0]["source_sample_rate"]==48000&&original[0]["source_frames"]==192000&&original[0]["source_offset_samples"]==0,"query distinguishes source PCM frames from timeline samples");
    auto plan=c.makePlan("agent:clip-test",Json::array({op("clip.trim",{{"clip",id},{"start_samples",48000},{"end_samples",168000}}),op("clip.move",{{"clip",id},{"position_samples",72000}}),op("clip.gain",{{"clip",id},{"db",-6}}),op("clip.fade",{{"clip",id},{"in_samples",4800},{"out_samples",4800},{"in_curve","linear"},{"out_curve","s_curve"}})}));
    auto initial=c.query();auto preview=c.preview(plan);check(c.query()==initial&&preview["clip_changes"].size()==4&&preview["clip_changes"][1]["after"]["source_offset_samples"]==24000,"compound preview reports mapped source offset without mutating Edit");fails([&]{c.commit(plan);},"Agent clip edit requires preview acceptance");auto result=c.commit(plan,true);auto edited=clips(c);auto shifted=render(c,dir,"trim move gain fade");
    check(edited[0]["start_samples"]==72000&&edited[0]["length_samples"]==120000&&edited[0]["source_offset_samples"]==24000,"trim preserves source sync and move preserves source offset");
    check(shifted.getMagnitude(0,0,72000)<=2e-6&&difference(shifted,80000,pcm,56000,100000,std::pow(10.,-6./20))<=2e-6,"real PCM is silent before moved start and maps exact source with -6 dB clip gain");
    check(c.commit(plan,true)["replayed"]&&clips(c)==edited,"network retry does not repeat clip edit");restore(c,result,original,edited);auto undone=render(c,dir,"undo composite");check(difference(undone,0,pcm,0,240000)<=2e-6,"Undo restores original actual PCM");
    result=run(c,Json::array({op("clip.split",{{"clip",id},{"position_samples",120001},{"ref","$right"}}),op("clip.gain",{{"clip","$right"},{"db",-6}})}));auto split=clips(c);check(split.size()==2&&split[0]["length_samples"]==96001&&split[1]["start_samples"]==120001&&split[1]["source_offset_samples"]==96001&&split[1]["parent_clip"]==id,"sample-grid split creates stable source lineage and local reference");
    auto splitPCM=render(c,dir,"split gain");check(difference(splitPCM,24128,pcm,24128,95745)<=2e-6&&difference(splitPCM,120129,pcm,120129,95000,std::pow(10.,-6./20))<=2e-6,"split real audio retains phase on both sides outside declared 128 frame edge window");restore(c,result,original,split);
    result=run(c,Json::array({op("clip.split",{{"clip",id},{"position_samples",24001},{"ref","$one"}})}));check(clips(c)[0]["length_samples"]==1&&clips(c)[1]["source_offset_samples"]==1,"native clip copy/setters support one-sample split without SDK editor helper exclusion");c.undo(result["plan_id"]);
    result=run(c,Json::array({op("clip.copy",{{"clip",id},{"track",track},{"position_samples",240000},{"ref","$copy"}}),op("clip.trim",{{"clip","$copy"},{"start_samples",264000},{"end_samples",384000}})}));auto copied=clips(c);check(copied.size()==2&&copied[1]["source_offset_samples"]==24000&&copied[1]["parent_clip"]==id&&copied[0]==original[0],"copy trim retains original and reports parent lineage");restore(c,result,original,copied);
    result=run(c,Json::array({op("clip.delete",{{"clip",id}})}));auto emptyExport=dir.getChildFile("empty.wav");fails([&]{c.render(emptyExport,0,240000);},"empty native graph refuses export without a success receipt");check(clips(c).empty()&&!emptyExport.existsAsFile()&&Commands::mediaHash(file)==hash,"delete removes last clip, preserves source and cannot report fictitious export");restore(c,result,original,Json::array());
    result=run(c,Json::array({op("clip.lock",{{"clip",id},{"locked",true}})}));auto locked=clips(c);fails([&]{c.makePlan("human",Json::array({op("clip.move",{{"clip",id},{"position_samples",0}})}));},"locked clip rejects human or Agent edit");restore(c,result,original,locked);
    auto before=c.query();fails([&]{c.makePlan("human",Json::array({op("clip.trim",{{"clip",id},{"start_samples",0},{"end_samples",216000}})}));},"trim rejects source-before-zero");fails([&]{c.makePlan("human",Json::array({op("clip.trim",{{"clip",id},{"start_samples",24000},{"end_samples",216001}})}));},"trim rejects source-end overflow");fails([&]{c.makePlan("human",Json::array({op("clip.fade",{{"clip",id},{"in_samples",192000},{"out_samples",1},{"in_curve","linear"},{"out_curve","linear"}})}));},"fade sum cannot silently rescale requested lengths");fails([&]{c.makePlan("human",Json::array({op("clip.gain",{{"clip",id},{"db",25}})}));},"gain outside real SDK range rejected");fails([&]{c.makePlan("human",Json::array({op("clip.gain",{{"clip",id},{"db",std::numeric_limits<double>::quiet_NaN()}})}));},"non-finite gain rejected");fails([&]{c.makePlan("human",Json::array({op("clip.split",{{"clip",id},{"position_samples",24000},{"ref","$bad"}})}));},"split at clip edge rejected");fails([&]{c.makePlan("human",Json::array({op("clip.delete",{{"clip",id}}),op("clip.gain",{{"clip",id},{"db",0}})}));},"same-Plan deleted target rejected atomically");fails([&]{c.makePlan("human",Json::array({op("clip.copy",{{"clip",id},{"track","missing"},{"position_samples",0},{"ref","$bad"}})}));},"missing copy destination rejected");fails([&]{c.makePlan("human",Json::array({op("clip.trim",{{"clip",id},{"start_samples",1},{"end_samples",std::numeric_limits<int64_t>::max()}})}));},"extreme integer rejected before source offset arithmetic");fails([&]{c.makePlan("human",Json::array({op("clip.lock",{{"clip",id},{"locked",true}}),op("clip.move",{{"clip",id},{"position_samples",0}})}));},"same-Plan newly locked clip cannot be edited");check(c.query()==before,"invalid clip plans leave history revision and Edit unchanged");
    fails([&]{c.makePlan("agent:clip-test",Json::array({op("clip.gain",{{"clip",id},{"db",0},{"media_hash","stale-analysis-hash"}})}));},"planner must not silently replace supplied stale analysis media hash");
    fails([&]{c.makePlan("agent:clip-test",Json::array({op("clip.import",{{"track",track},{"path",file.getFullPathName().toStdString()},{"position_samples",0},{"media_hash","stale-import-hash"}})}));},"planner rejects supplied stale import media hash");
    auto bound=c.makePlan("agent:clip-test",Json::array({op("clip.gain",{{"clip",id},{"db",0},{"media_hash",hash}})}));check(bound["operations"][0]["args"]["media_hash"]==hash,"explicit current evidence hash remains bound to the Plan");
    auto stale=c.makePlan("agent:clip-test",Json::array({op("clip.move",{{"clip",id},{"position_samples",0}})}));result=run(c,Json::array({op("track.mute",{{"track",track},{"enabled",true}})}));fails([&]{c.commit(stale,true);},"stale Agent clip plan cannot overwrite later human edit");c.undo(result["plan_id"]);
    result=run(c,Json::array({op("clip.trim",{{"clip",id},{"start_samples",48000},{"end_samples",168000}}),op("clip.split",{{"clip",id},{"position_samples",96000},{"ref","$new"}}),op("clip.fade",{{"clip","$new"},{"in_samples",2400},{"out_samples",4800},{"in_curve","convex"},{"out_curve","concave"}})}));auto savedClips=clips(c);auto save=dir.getChildFile("edited.tracktionedit");c.save(save);Commands opened(false);opened.open(save);check(clips(opened)==savedClips,"save reopen retains source offsets fades lineage and stable IDs");auto beforeSave=render(c,dir,"before save"),afterSave=render(opened,dir,"reopened");check(difference(beforeSave,0,afterSave,0,240000)<=2e-6,"reopened clip renders numerically identical PCM");check(Commands::mediaHash(file)==hash,"all edits and Undo preserve original audio hash");
    auto dc=fixture(dir,96000,true);Commands d(false);run(d,Json::array({op("track.create",{{"name","96 kHz DC"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",dc.getFullPathName().toStdString()},{"position_samples",0}})}));auto did=clips(d)[0]["id"].get<std::string>();check(clips(d)[0]["source_sample_rate"]==96000&&clips(d)[0]["source_frames"]==384000&&clips(d)[0]["length_samples"]==192000,"96 kHz PCM length maps to 48 kHz session sample grid");
    for(const std::string curve:{"linear","convex","concave","s_curve"}){run(d,Json::array({op("clip.fade",{{"clip",did},{"in_samples",48000},{"out_samples",48000},{"in_curve",curve},{"out_curve",curve}})}));auto audio=render(d,dir,curve.c_str(),192000);double error=0;for(int n:{12000,24000,36000}){const double a=n/48000.,theta=a*juce::MathConstants<double>::halfPi;double gain=curve=="linear"?a:curve=="convex"?std::sin(theta):curve=="concave"?1-std::cos(theta):(1-a)*(1-std::cos(theta))+a*std::sin(theta);error=std::max(error,std::abs(double(audio.getSample(0,n))-.1*gain));error=std::max(error,std::abs(double(audio.getSample(0,192000-n))-.1*gain));}std::cout<<"fade "<<curve<<" error="<<error<<std::endl;check(error<=2e-4,"real fade PCM matches declared curve at quarter half and three-quarter positions");}
    auto hashPlan=d.makePlan("agent:clip-test",Json::array({op("clip.gain",{{"clip",did},{"db",-3}})}));{juce::FileOutputStream out(dc);out.setPosition(dc.getSize());out.writeByte(0);}fails([&]{d.commit(hashPlan,true);},"source media changed after preview blocks clip commit");
    Json summary={{"result","passed"},{"checks",checks},{"renders",renders},{"budgets",{{"pcm_max_error",2e-6},{"fade_error",2e-4},{"split_edge_window_samples",128},{"render_deadline_ms",10000}}},{"scope","actual Tracktion waveform clips/native DSP; non-looped unstretched audio only, crossfades/slip/stretch and hardware listening remain pending"}};if(argc>1){std::ofstream out(argv[1]);out<<summary.dump(2);if(!out)throw std::runtime_error("evidence write failed");}std::cout<<summary.dump(2)<<std::endl;dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
