#include <nativedaw/v2/AudioAnalysis.h>
#include <nativedaw/v2/McpSession.h>
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;
namespace {
int checks=0;Json evidence=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,why);}
void pump(int ms=10){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json op(const char* command,Json args){return {{"command",command},{"args",args}};}
void commit(Commands& c,Json ops){c.commit(c.makePlan("human",ops));}
void near(double a,double b,const char* why){if(std::abs(a-b)>3e-6)throw std::runtime_error(std::string(why)+" actual="+std::to_string(a)+" expected="+std::to_string(b));check(true,why);}
Json wait(Commands& c){const auto until=juce::Time::getMillisecondCounterHiRes()+12000;while(c.analysisStatus()["busy"].get<bool>()){if(juce::Time::getMillisecondCounterHiRes()>until)throw std::runtime_error("Clip FX exceeds fixed twelve-second budget");pump();}return c.analysisStatus();}
Json request(Commands& c,const std::string& clip,const std::string& key){return {{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]},{"clip",clip},{"start_samples",28800},{"end_samples",124800},{"request_key",key},{"detector_profile",{{"silence_threshold_dbfs",-60},{"minimum_silence_ms",100},{"transient_minimum_dbfs",-36},{"transient_rise_db",12},{"transient_refractory_ms",50}}}};}
Json measure(Commands& c,const std::string& clip,const std::string& key){c.analysisControl("clip",request(c,clip,key));auto result=wait(c);if(result["state"]!="completed")throw std::runtime_error(result.dump());auto r=result["receipt"];check(r["current"].get<bool>()&&r["frames"]==96000&&r["binding"]["tap_point"]=="clip_post_fx"&&r["binding"]["object_id"]==clip,"real current float32 Clip FX receipt binds exact nonzero session range and actual clip");const auto& scope=r["binding"]["tap_configuration"];check(scope["clip_gain_pan_included"].get<bool>()&&scope["clip_fades_included"].get<bool>()&&!scope["master_included"].get<bool>()&&!scope["track_processing_included"].get<bool>()&&!scope["other_clips_included"].get<bool>()&&!scope["upstream_routes_and_inputs_included"].get<bool>(),"tap declares the actual isolated clip graph and exclusions");evidence.push_back(r);return r;}
void wave(const juce::File& path,const juce::AudioBuffer<float>& data,double rate){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=path.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(rate).withNumChannels(2).withBitsPerSample(32));check(writer&&writer->writeFromAudioSampleBuffer(data,0,data.getNumSamples()),"write self-owned real float PCM file");}
Json rpc(McpSession& s,const char* method,Json params){static int serial=0;const int id=++serial;std::vector<Json> output;std::thread worker([&]{output=s.receive(Json{{"jsonrpc","2.0"},{"id",id},{"method",method},{"params",params}}.dump());});worker.join();const auto until=juce::Time::getMillisecondCounterHiRes()+5000;while(output.empty()){if(juce::Time::getMillisecondCounterHiRes()>until)throw std::runtime_error("MCP exceeds fixed five-second budget");pump();output=s.ready();}for(const auto& item:output)if(item.value("id",Json(nullptr))==id)return item;throw std::runtime_error("MCP response ID mismatch");}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-clip-fx-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();const auto source=folder.getChildFile("owned-48k-pulses.wav");juce::AudioBuffer<float> pcm(2,120000);pcm.clear();for(int n=24000;n<28800;++n){pcm.setSample(0,n,.8f);pcm.setSample(1,n,-.4f);}wave(source,pcm,48000);const auto hash=Commands::mediaHash(source);
    Commands c(false);commit(c,Json::array({op("track.create",{{"name","Clip FX vocal"},{"ref","$v"}}),op("clip.import",{{"track","$v"},{"path",source.getFullPathName().toStdString()},{"position_samples",24000},{"ref","$clip"}}),op("track.gain",{{"track","$v"},{"db",0}})}));auto q=c.query();const std::string track=q["tracks"][0]["id"],clip=q["tracks"][0]["clips"][0]["id"];
    commit(c,Json::array({op("clip.trim",{{"clip",clip},{"start_samples",28800},{"end_samples",124800}}),op("clip.gain",{{"clip",clip},{"db",6}}),op("clip.fx.insert",{{"clip",clip},{"type",te::DelayPlugin::xmlTypeName}})}));q=c.query();auto fx=q["tracks"][0]["clips"][0]["plugins"];check(fx.size()==1&&q["tracks"][0]["plugins"].empty()&&fx[0]["owner_clip"]==clip&&!fx[0]["automation_workflow_qualified"].get<bool>(),"actual native Delay belongs to clip instead of track and exposes real parameter IDs");const std::string delay=fx[0]["id"];
    commit(c,Json::array({op("plugin.parameter",{{"plugin",delay},{"parameter","feedback"},{"value",te::DelayPlugin::getMinDelayFeedbackDb()}}),op("plugin.parameter",{{"plugin",delay},{"parameter","mix proportion"},{"value",1}}),op("plugin.delay_time",{{"plugin",delay},{"ms",150}})}));
    auto before=c.query();auto wet=measure(c,clip,"wet-known");const double gain=juce::Decibels::decibelsToGain(6.f);near(wet["peak"],double(.8f)*gain,"actual wet 150ms clip Delay preserves independently predicted pulse peak");near(wet["rms"],std::sqrt((std::pow(double(.8f)*gain,2)+std::pow(double(.4f)*gain,2))*4800/(2*96000)),"wet pulse RMS matches independent gain and exact frame count");check(wet["events"].size()>0&&wet["events"][0]["kind"]=="silence","processed silence is measured from wet clip PCM");Json fullScale=nullptr;for(const auto& e:wet["events"])if(e["kind"]=="full_scale_exceedance")fullScale=e;check(fullScale.is_object()&&fullScale["start_samples"]==55200&&fullScale["end_samples"]==60000&&wet["over_full_scale_frames"]==4800,"actual wet delay moves full-scale interval by exactly 7200 samples after source offset mapping");Json silences=Json::array();for(const auto& e:wet["events"])if(e["kind"]=="silence")silences.push_back({e["start_samples"],e["end_samples"]});check(silences==Json::array({Json::array({28800,55200}),Json::array({60000,124800})}),"all measured wet silence intervals exactly match independent PCM boundaries");check(c.query()["tracks"]==before["tracks"]&&c.query()["revision"]==before["revision"],"offline clip tap leaves active routing, native plugin state and revision unchanged");
    const auto exportedFile=folder.getChildFile("formal-wet.wav");auto exported=c.render(exportedFile,28800,124800);auto reference=analysis::measure(exportedFile,28800);check(reference["file_bits"]==24&&!reference["file_float"].get<bool>(),"formal export produces actual integer24 WAV");check(reference["peak"].get<double>()<wet["peak"].get<double>(),"formal integer export really clips this over-full-scale test; not claimed lossless float comparison");evidence.push_back({{"case","overfullscale_integer_export"},{"render",exported},{"measured",reference}});
    commit(c,Json::array({op("clip.gain",{{"clip",clip},{"db",-6}})}));auto quiet=measure(c,clip,"quiet-native-export");const auto quietFile=folder.getChildFile("formal-unclipped.wav");c.render(quietFile,28800,124800);auto quietReference=analysis::measure(quietFile,28800);near(quiet["peak"],quietReference["peak"],"unclipped native clip tap peak agrees with production WAV");near(quiet["rms"],quietReference["rms"],"unclipped native clip tap RMS agrees with production WAV");commit(c,Json::array({op("clip.fade",{{"clip",clip},{"in_samples",60000},{"out_samples",0},{"in_curve","linear"},{"out_curve","linear"}})}));auto faded=measure(c,clip,"native-fade");check(faded["peak"].get<double>()<quiet["peak"].get<double>()*.6&&faded["peak"].get<double>()>quiet["peak"].get<double>()*.5,"actual post-plugin clip fade attenuates delayed pulse at its shifted position");auto fadeFile=folder.getChildFile("formal-fade.wav");c.render(fadeFile,28800,124800);auto fadeReference=analysis::measure(fadeFile,28800);near(faded["peak"],fadeReference["peak"],"native clip fade peak agrees with actual WAV");near(faded["rms"],fadeReference["rms"],"native clip fade RMS agrees with actual WAV");c.undo();c.undo();
    commit(c,Json::array({op("plugin.insert",{{"track",track},{"type",te::DelayPlugin::xmlTypeName}}),op("track.gain",{{"track",track},{"db",-18}}),op("track.mute",{{"track",track},{"enabled",true}}),op("clip.import",{{"track",track},{"path",source.getFullPathName().toStdString()},{"position_samples",28800}}),op("track.create",{{"name","Unrelated direct output"},{"ref","$other"}}),op("clip.import",{{"track","$other"},{"path",source.getFullPathName().toStdString()},{"position_samples",28800}}),op("track.gain",{{"track","$other"},{"db",6}}),op("track.create",{{"name","Upstream actual instrument"},{"type","instrument"},{"ref","$synth"}}),op("midi.clip.create",{{"track","$synth"},{"ref","$notes"},{"name","Actual synth input"},{"position_samples",0},{"length_samples",144000}}),op("midi.note.add",{{"clip","$notes"},{"pitch",69},{"velocity",90},{"position_samples",0},{"length_samples",120000}}),op("track.output",{{"track","$synth"},{"target",track}})}));pump(300);before=c.query();auto isolated=measure(c,clip,"isolated-wet");near(isolated["peak"],wet["peak"],"track insert, mute, fader, overlapping clip and upstream synth do not enter selected clip measurement");near(isolated["rms"],wet["rms"],"isolated real graph RMS excludes unrelated outputs and inputs");if(c.query()["tracks"]!=before["tracks"])std::cerr<<"DIFF "<<Json::diff(before["tracks"],c.query()["tracks"]).dump()<<std::endl;check(c.query()["tracks"]==before["tracks"],"isolating render never severs production routes or removes production clips");
    commit(c,Json::array({op("plugin.bypass",{{"plugin",delay},{"bypassed",true}})}));check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"clip bypass invalidates previous processed evidence");auto dry=measure(c,clip,"dry-bypass");fullScale=nullptr;for(const auto& e:dry["events"])if(e["kind"]=="full_scale_exceedance")fullScale=e;check(fullScale["start_samples"]==48000&&fullScale["end_samples"]==52800,"native bypass restores exact original pulse position");c.undo();check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"Undo never silently revives a processed artifact");auto restored=measure(c,clip,"undone-bypass");near(restored["rms"],wet["rms"],"Undo restores actual wet Delay rendering");
    auto plan=c.makePlan("agent:clip",Json::array({op("plugin.parameter",{{"plugin",delay},{"parameter","mix proportion"},{"value",.5}})}));Scope scope;scope.mode=Permission::Preview;scope.targets={delay};scope.commands={"plugin.parameter"};scope.begin=28800;scope.end=124800;fails([&]{c.review(plan,scope);},"finite clip interval cannot authorize unqualified processing tails");scope.begin=0;scope.end=std::numeric_limits<int64_t>::max();check(c.review(plan,scope)["permission"]["impacts"][0]["effect_tail_unqualified"].get<bool>(),"actual plugin ID grant retains its target restriction and declares unqualified effect tail");auto tooSmall=scope;tooSmall.end=124799;fails([&]{c.review(plan,tooSmall);},"plugin edit cannot escape granted clip time boundary");auto wrong=scope;wrong.targets={before["tracks"][1]["id"]};fails([&]{c.review(plan,wrong);},"unrelated track grant cannot authorize clip processor edit");c.commit(plan,true,scope);check(c.commit(plan,true,scope)["replayed"].get<bool>(),"network retry does not duplicate actual clip edit");c.undo(plan["plan_id"]);
    auto stale=c.makePlan("agent:clip",Json::array({op("plugin.bypass",{{"plugin",delay},{"bypassed",true}})}));c.parameterControl("parameter.gesture.value",{{"plugin",delay},{"parameter","mix proportion"},{"value",.4}});fails([&]{c.commit(stale,true);},"human clip parameter edit advances revision and rejects stale agent plan");c.undo();
    commit(c,Json::array({op("clip.lock",{{"clip",clip},{"locked",true}})}));fails([&]{c.commit(c.makePlan("human",Json::array({op("plugin.parameter",{{"plugin",delay},{"parameter","mix proportion"},{"value",.2}})})));},"locked clip rejects generic plugin Plan");fails([&]{c.parameterControl("parameter.gesture.value",{{"plugin",delay},{"parameter","mix proportion"},{"value",.2}});},"locked clip also rejects human parameter bypass");fails([&]{c.commit(c.makePlan("human",Json::array({op("clip.fx.insert",{{"clip",clip},{"type",te::EqualiserPlugin::xmlTypeName}})})));},"locked clip rejects additional effects");c.undo();
    commit(c,Json::array({op("clip.fx.insert",{{"clip",clip},{"type",te::EqualiserPlugin::xmlTypeName}}),op("clip.fx.insert",{{"clip",clip},{"type",te::DelayPlugin::xmlTypeName}}),op("clip.fx.insert",{{"clip",clip},{"type",te::EqualiserPlugin::xmlTypeName}})}));auto ordered=c.query()["tracks"][0]["clips"][0]["plugins"];auto removeLast=c.makePlan("human",Json::array({op("plugin.remove",{{"plugin",ordered[3]["id"]}}),op("clip.gain",{{"clip",clip},{"db",-6}})}));auto orderedPreview=c.preview(removeLast);check(orderedPreview["clip_changes"][0]["after"]["fx_types"]==Json::array({te::DelayPlugin::xmlTypeName,te::EqualiserPlugin::xmlTypeName,te::DelayPlugin::xmlTypeName}),"ordered preview removes the exact repeated-type plugin ID instead of the first matching type");c.commit(removeLast);check(c.query()["tracks"][0]["clips"][0]["plugins"][1]["id"]==ordered[1]["id"]&&c.query()["tracks"][0]["clips"][0]["plugins"].size()==3,"ordered removal commits the exact previewed native chain");c.undo();c.undo();
    auto snapshot=c.query();Json tooMany=Json::array();for(int i=0;i<5;++i)tooMany.push_back(op("clip.fx.insert",{{"clip",clip},{"type",te::EqualiserPlugin::xmlTypeName}}));fails([&]{c.commit(c.makePlan("human",tooMany));},"multi-operation Plan preflights native five-slot clip limit");check(c.query()["tracks"]==snapshot["tracks"]&&c.query()["revision"]==snapshot["revision"],"resource rejection creates no partial native plugins or history");fails([&]{c.makePlan("human",Json::array({op("plugin.remove",{{"plugin",delay}}),op("plugin.bypass",{{"plugin",delay},{"bypassed",true}})}));},"removed clip plugin cannot be addressed later in same Plan");fails([&]{c.makePlan("human",Json::array({op("clip.delete",{{"clip",clip}}),op("plugin.remove",{{"plugin",delay}})}));},"deleted clip cannot be addressed through its plugin ID");fails([&]{c.makePlan("human",Json::array({op("track.delete",{{"track",track},{"connections","disconnect"}}),op("plugin.remove",{{"plugin",delay}})}));},"deleted owner track cannot be addressed through descendant clip plugin");
    commit(c,Json::array({op("clip.copy",{{"clip",clip},{"track",track},{"position_samples",144000},{"ref","$copy"}})}));auto copy=c.query()["tracks"][0]["clips"].back();check(copy["plugins"].size()==1&&copy["plugins"][0]["id"]!=delay&&copy["plugins"][0]["owner_clip"]==copy["id"],"native clip copy gives copied processor distinct stable identity and owner");c.undo();
    commit(c,Json::array({op("plugin.remove",{{"plugin",delay}})}));check(c.query()["tracks"][0]["clips"][0]["plugins"].empty(),"generic remove deletes actual clip processor");c.undo();check(c.query()["tracks"][0]["clips"][0]["plugins"][0]["id"]==delay,"Undo removal restores original native processor ID and state");
    auto invalid=request(c,clip,"invalid");invalid["start_samples"]=28799;fails([&]{c.analysisControl("clip",invalid);},"clip analysis range cannot silently include audio outside selected clip");invalid=request(c,"missing","invalid");fails([&]{c.analysisControl("clip",invalid);},"missing clip cannot produce successful analysis");fails([&]{c.makePlan("human",Json::array({op("plugin.parameter",{{"plugin",delay},{"parameter","warmth"},{"value",1}})}));},"invented clip parameter rejected against actual native enumeration");
    auto rawArgs=Json{{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]},{"clip",clip},{"source_start_frame",4800},{"source_end_frame",100800},{"request_key","raw-before-edit"}};c.analysisControl("source",rawArgs);check(wait(c)["state"]=="completed","raw source analysis actually reads original PCM");commit(c,Json::array({op("plugin.bypass",{{"plugin",delay},{"bypassed",true}})}));check(c.analysisStatus()["receipt"]["current"].get<bool>(),"clip processor edit does not invalidate raw source evidence");c.undo();
    CommandQueue queue(c);Scope read;read.mode=Permission::ReadOnly;auto client=queue.connect("agent:clip",read);McpSession session(client,Commands::registry());rpc(session,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","Clip FX integration"},{"version","1"}}}});session.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());auto response=rpc(session,"tools/call",{{"name","analyze_clip"},{"arguments",request(c,clip,"mcp-clip")}});check(!response["result"]["isError"].get<bool>(),"registry-generated read-only MCP submits real Clip FX job");check(wait(c)["state"]=="completed","MCP clip job reaches actual terminal completion");auto remote=rpc(session,"tools/call",{{"name","query_analysis"},{"arguments",Json::object()}})["result"]["structuredContent"]["result"]["receipt"];near(remote["peak"],wet["peak"],"MCP returns independently predicted actual Clip FX PCM");auto paged=rpc(session,"tools/call",{{"name","query_objects"},{"arguments",{{"collection","clip_plugins"},{"target",clip},{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]}}}});check(!paged["result"]["isError"].get<bool>()&&paged["result"]["structuredContent"]["result"]["items"][0]["id"]==delay,"paged MCP clip plugin collection exposes actual stable processor ID");
    auto retry=request(c,clip,"retry-clip");auto job=c.analysisControl("clip",retry,"agent:clip");check(c.analysisControl("clip",retry,"agent:clip")["request"]["artifact_id"]==job["request"]["artifact_id"],"same analysis key shares actual clip job");auto changed=retry;changed["end_samples"]=124799;fails([&]{c.analysisControl("clip",changed,"agent:clip");},"same request key cannot change clip range");c.analysisControl("cancel",{{"artifact_id",job["request"]["artifact_id"]}},"agent:clip");check(wait(c)["state"]=="cancelled","cancellation waits for actual clip render worker terminal state");
    const auto saved=folder.getChildFile("real-clip-fx.tracktionedit");const auto tracks=c.query()["tracks"];c.save(saved);c.open(saved);check(c.query()["tracks"]==tracks&&c.analysisStatus()["state"]=="idle","close/open restores clip processor states and IDs without reviving old evidence");check(Commands::mediaHash(source)==hash,"all edits, renders, MCP and save/open preserve original media hash");
    // A second source tests native file/session rate conversion with a formal render of the same range.
    std::set<std::string> retired;for(const auto& t:c.query()["tracks"]){retired.insert(t["id"]);for(const auto& p:t["plugins"])retired.insert(p["id"]);for(const auto& cl:t["clips"]){retired.insert(cl["id"]);for(const auto& p:cl["plugins"])retired.insert(p["id"]);}}
    c.commit(c.makePlan("human",Json::array({op("track.delete",{{"track",c.query()["tracks"][2]["id"]},{"connections","disconnect"}}),op("track.delete",{{"track",c.query()["tracks"][1]["id"]},{"connections","disconnect"}}),op("track.delete",{{"track",track},{"connections","disconnect"}})})));juce::AudioBuffer<float> tone(2,110250);for(int n=0;n<tone.getNumSamples();++n){tone.setSample(0,n,float(.15*std::sin(2*juce::MathConstants<double>::pi*1000*n/44100)));tone.setSample(1,n,tone.getSample(0,n));}const auto rateSource=folder.getChildFile("owned-44k1.wav");wave(rateSource,tone,44100);commit(c,Json::array({op("track.create",{{"name","Rate conversion"},{"ref","$r"}}),op("clip.import",{{"track","$r"},{"path",rateSource.getFullPathName().toStdString()},{"position_samples",24000},{"ref","$c"}}),op("track.gain",{{"track","$r"},{"db",0}}),op("clip.trim",{{"clip","$c"},{"start_samples",28800},{"end_samples",124800}}),op("clip.fx.insert",{{"clip","$c"},{"type",te::EqualiserPlugin::xmlTypeName}})}));q=c.query();const std::string rateClip=q["tracks"][0]["clips"][0]["id"],eq=q["tracks"][0]["clips"][0]["plugins"][0]["id"];check(!retired.contains(eq)&&!retired.contains(rateClip)&&!retired.contains(q["tracks"][0]["id"]),"reopened Edit reserves native ID high-water mark before deleting tracks; new clip/plugin IDs cannot collide with retired Undo/cache objects");commit(c,Json::array({op("plugin.parameter",{{"plugin",eq},{"parameter","Mid freq 1"},{"value",1000}}),op("plugin.parameter",{{"plugin",eq},{"parameter","Mid gain 1"},{"value",6}})}));auto rateFX=measure(c,rateClip,"rate-eq");check(rateFX["sample_rate"]==48000&&rateFX["peak"].get<double>()>.27&&c.query()["tracks"][0]["clips"][0]["source_sample_rate"]==44100,"native Clip EQ really processes a resampled 44.1k source in 48k session");auto rateFile=folder.getChildFile("formal-eq-rate.wav");c.render(rateFile,28800,124800);auto rateReference=analysis::measure(rateFile,28800);near(rateFX["peak"],rateReference["peak"],"resampled Clip EQ peak matches independent production WAV");near(rateFX["rms"],rateReference["rms"],"resampled Clip EQ RMS matches independent production WAV");
    for(const auto& type:{te::CompressorPlugin::xmlTypeName,te::ReverbPlugin::xmlTypeName}){commit(c,Json::array({op("clip.fx.insert",{{"clip",rateClip},{"type",type}})}));auto plugin=c.query()["tracks"][0]["clips"][0]["plugins"].back();check(!plugin["parameters"].empty()&&plugin["owner_clip"]==rateClip,"actual clip effect exposes native instance and enumerated parameters");auto measured=measure(c,rateClip,std::string("qualified-")+type);auto renderedFile=folder.getChildFile(juce::String(type)+"-actual.wav");c.render(renderedFile,28800,124800);auto rendered=analysis::measure(renderedFile,28800);near(measured["peak"],rendered["peak"],"native clip processor peak agrees with production WAV");near(measured["rms"],rendered["rms"],"native clip processor RMS agrees with production WAV");c.undo();}
    const auto elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<120000,"Clip FX backend qualification stays within fixed 120 second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"evidence",evidence},{"scope","actual Tracktion clip plugins and isolated renders, read-only MCP; live desktop separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<"RESULT "<<checks<<" checks / "<<elapsed<<" ms"<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<std::endl;folder.deleteRecursively();return 1;}}
