#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;using namespace ndaw::desktop;
namespace {
int checks=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
void pump(int ms=30){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* child:p.getChildren())if(auto* result=find(*child,id))return result;return nullptr;}
void click(Workspace& w,const juce::String& id){auto* b=dynamic_cast<juce::Button*>(find(w,id));if(!b||!b->isEnabled())throw std::runtime_error("native button unavailable: "+id.toStdString());auto callback=b->onClick;bool delivered=false;b->onClick=[&]{delivered=true;callback();};b->triggerClick();const auto until=juce::Time::getMillisecondCounterHiRes()+1000;while(!delivered&&juce::Time::getMillisecondCounterHiRes()<until)pump(1);b->onClick=callback;check(delivered,"actual native callback delivered");pump();}
juce::TextEditor& field(Workspace& w,const char* id){auto* e=dynamic_cast<juce::TextEditor*>(find(w,id));if(!e)throw std::runtime_error(std::string("native field unavailable: ")+id);return *e;}
juce::ComboBox& combo(Workspace& w,const char* id){auto* c=dynamic_cast<juce::ComboBox*>(find(w,id));if(!c)throw std::runtime_error(std::string("native chooser unavailable: ")+id);return *c;}
juce::Slider& slider(Workspace& w,const char* id){auto* s=dynamic_cast<juce::Slider*>(find(w,id));if(!s)throw std::runtime_error(std::string("native slider unavailable: ")+id);return *s;}
void value(Workspace& w,const char* id,const char* text){auto& e=field(w,id);static_cast<juce::Component*>(&e)->focusGained(juce::Component::focusChangedDirectly);e.setText(text,true);}
Json wait(Workspace& w){const auto until=juce::Time::getMillisecondCounterHiRes()+12000;while(w.queryAnalysis().value("busy",false)){if(juce::Time::getMillisecondCounterHiRes()>until)throw std::runtime_error("native clip analysis exceeds twelve seconds");pump(10);}pump(300);auto s=w.queryAnalysis();if(s["state"]!="completed")throw std::runtime_error(s.dump());return s["receipt"];}
class Storage final:public te::PropertyStorage{public:explicit Storage(juce::File folder):PropertyStorage("Forma Clip FX GUI"),folder(folder){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-clip-fx-ui-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();const auto source=folder.getChildFile("actual-clip-pulse.wav");juce::AudioBuffer<float> data(2,120000);data.clear();for(int n=24000;n<28800;++n){data.setSample(0,n,.8f);data.setSample(1,n,-.4f);} {juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=source.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));if(!writer||!writer->writeFromAudioSampleBuffer(data,0,data.getNumSamples()))throw std::runtime_error("native fixture write failed");}const auto hash=Commands::mediaHash(source);
    Workspace w(false,std::make_unique<Storage>(folder.getChildFile("prefs")));w.setVisible(true);w.prepareImport(source);pump();click(w,"plan.accept");const std::string clip=w.query()["tracks"][0]["clips"][0]["id"];click(w,"clip.select:"+juce::String(clip));value(w,"clip.gain.db","6");click(w,"clip.gain");click(w,"clip.fx.open");combo(w,"plugin.type").setSelectedId(4,juce::sendNotificationSync);click(w,"clip.fx.insert");auto before=w.query();const std::string delay=before["tracks"][0]["clips"][0]["plugins"][0]["id"];check(before["tracks"][0]["plugins"].empty()&&before["tracks"][0]["clips"][0]["clip_fx_count"]==1,"GUI inserts real Delay only into selected clip through L1");check(!combo(w,"plugin.type").isItemEnabled(5),"clip inspector cannot offer unqualified instrument insert");slider(w,"plugin.parameter:feedback").setValue(-30,juce::sendNotificationSync);pump();slider(w,"plugin.parameter:mix proportion").setValue(1,juce::sendNotificationSync);pump();check(w.query()["tracks"][0]["clips"][0]["plugins"][0]["parameters"][1]["value"]==1,"actual native parameter gesture changes clip Delay mix");before=w.query();
    w.showAnalysis();pump();combo(w,"analysis.tap").setSelectedId(6,juce::sendNotificationSync);pump();check(find(w,"analysis.clip.run")&&find(w,"analysis.source_clip")&&!find(w,"analysis.track")&&!find(w,"analysis.delivery.run")&&field(w,"analysis.start_samples").getText()=="0"&&field(w,"analysis.end_samples").getText()=="120000","native Clip FX tap selects actual clip and session range without delivery/source-frame controls");click(w,"analysis.events.enabled");click(w,"analysis.clip.run");auto wet=wait(w);check(wet["binding"]["tap_point"]=="clip_post_fx"&&wet["binding"]["object_id"]==clip&&wet["peak"].get<double>()>1.59,"native Clip FX analysis produces real over-full-scale PCM receipt");check(field(w,"analysis.summary").getText().contains("单个原生片段效果链")&&field(w,"analysis.summary").getText().contains("排除其他片段")&&w.query()["tracks"]==before["tracks"]&&w.query()["revision"]==before["revision"],"native summary labels selected clip evidence and analysis keeps Edit/history unchanged");int event=-1;for(const auto& e:wet["events"])if(e["kind"]=="full_scale_exceedance"){event=e["id"];check(e["start_samples"]==31200&&e["end_samples"]==36000,"GUI analysis full-scale interval includes actual 150ms clip Delay");}check(event>=0,"wet clip has a real event to locate");click(w,"analysis.locate:"+juce::String(event));check(w.query()["position_samples"]==31200&&!find(w,"analysis.panel"),"actual clip event callback seeks native Transport and returns to Edit");
    click(w,"plugin.bypass");check(w.query()["tracks"][0]["clips"][0]["plugins"][0]["bypassed"].get<bool>()&&!w.queryAnalysis()["receipt"]["current"].get<bool>(),"human GUI clip bypass changes real processor and invalidates evidence");click(w,"history.undo");check(!w.query()["tracks"][0]["clips"][0]["plugins"][0]["bypassed"].get<bool>(),"GUI Undo restores native clip bypass state");click(w,"clip.lock");check(!find(w,"clip.fx.insert")->isEnabled()&&!find(w,"plugin.bypass")->isEnabled()&&!slider(w,"plugin.parameter:mix proportion").isEnabled(),"native inspector disables actual clip edits and parameter controls when locked");click(w,"clip.lock");click(w,"plugin.remove");check(w.query()["tracks"][0]["clips"][0]["plugins"].empty(),"GUI remove deletes actual clip plugin");click(w,"history.undo");check(w.query()["tracks"][0]["clips"][0]["plugins"][0]["id"]==delay,"GUI Undo removal restores native stable processor ID");
    click(w,"inspector.inserts");check(find(w,"plugin.insert")&&!find(w,"clip.fx.insert"),"track insert tab returns to separate original track effect chain");click(w,"plugin.insert");check(w.query()["tracks"][0]["plugins"].size()==1&&w.query()["tracks"][0]["clips"][0]["plugins"].size()==1,"track inspector still inserts a real independent track processor");check(Commands::mediaHash(source)==hash,"native Clip FX workflow preserves original PCM");const auto elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"native Clip FX workflow retains fixed sixty-second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"wet",wet},{"scope","actual JUCE native callbacks and Tracktion; live desktop separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<"RESULT "<<checks<<" checks / "<<elapsed<<" ms"<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<std::endl;folder.deleteRecursively();return 1;}}
