#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
using ndaw::desktop::text;
namespace {
int checks=0;void check(bool b,const char* s){if(!b)throw std::runtime_error(s);++checks;std::cout<<"PASS "<<s<<std::endl;}
void settle(int ms=80){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* c:p.getChildren())if(auto* f=find(*c,id))return f;return nullptr;}
void click(juce::Component& p,const juce::String& id){auto* b=dynamic_cast<juce::Button*>(find(p,id));if(!b||!b->isEnabled())throw std::runtime_error("button unavailable: "+id.toStdString());b->triggerClick();settle();}
void field(juce::Component& p,const char* id,const char* value){auto* f=dynamic_cast<juce::TextEditor*>(find(p,id));if(!f||!f->isEnabled())throw std::runtime_error("field unavailable");static_cast<juce::Component*>(f)->focusGained(juce::Component::focusChangedDirectly);f->setText(value,true);}
Json op(const char* cmd,Json a){return {{"command",cmd},{"args",a}};}
Json clips(ndaw::desktop::Workspace& w){return w.query()["tracks"][0]["clips"];}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-clip-ui-"+juce::Uuid().toString());dir.createDirectory();auto file=dir.getChildFile("actual.wav");{
        juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> s=file.createOutputStream();auto writer=wav.createWriterFor(s,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("writer failed");juce::AudioBuffer<float> pcm(2,192000);for(int i=0;i<192000;++i)for(int c=0;c<2;++c)pcm.setSample(c,i,float(.1*std::sin(2*juce::MathConstants<double>::pi*1000*i/48000.)));if(!writer->writeFromAudioSampleBuffer(pcm,0,192000))throw std::runtime_error("write failed");
    }
    auto hash=Commands::mediaHash(file);ndaw::desktop::Workspace w(false);w.setVisible(true);w.setSize(1440,1000);w.prepareImport(file);click(w,text("plan.accept"));auto original=clips(w);std::string id=original[0]["id"],track=w.query()["tracks"][0]["id"];click(w,text("clip.select:"+id));check(find(w,"clip.trim")&&find(w,"clip.gain"),"native clip header selection opens real edit dock");
    field(w,"clip.start","24000");field(w,"clip.end","168000");click(w,"clip.trim");auto trimmed=clips(w);check(trimmed[0]["start_samples"]==24000&&trimmed[0]["source_offset_samples"]==24000&&trimmed[0]["length_samples"]==144000,"GUI trim commits source-preserving native Edit mapping");
    Commands c(false);c.commit(c.makePlan("human",Json::array({op("track.create",{{"name","actual"},{"ref","$a"}}),op("clip.import",{{"track","$a"},{"path",file.getFullPathName().toStdString()},{"position_samples",0},{"ref","$c"}}),op("track.gain",{{"track","$a"},{"db",-12}})})));auto cid=c.query()["tracks"][0]["clips"][0]["id"];auto plan=c.makePlan("agent:gui-equivalence",Json::array({op("clip.trim",{{"clip",cid},{"start_samples",24000},{"end_samples",168000}})}));c.commit(plan,true);auto agent=c.query()["tracks"][0]["clips"][0];auto human=trimmed[0];human.erase("id");agent.erase("id");check(human==agent,"GUI and accepted Agent Plan produce same clip facts apart from instance IDs");
    click(w,"history.undo");check(clips(w)==original,"GUI Undo restores original clip and offset");click(w,"history.redo");check(clips(w)==trimmed,"GUI Redo retains trimmed stable ID");
    field(w,"clip.position","48000");settle(55);check(dynamic_cast<juce::TextEditor*>(find(w,"clip.position"))->getText()=="48000","focused typed position survives background facts refresh before commit");click(w,"clip.move");check(clips(w)[0]["start_samples"]==48000&&clips(w)[0]["source_offset_samples"]==24000,"GUI exact position entry moves clip without changing source offset");field(w,"clip.gain.db","-6");click(w,"clip.gain");check(clips(w)[0]["gain_db"]==-6,"GUI Clip Gain changes real clip level");
    field(w,"clip.fade.in","4800");field(w,"clip.fade.out","9600");auto* curves=dynamic_cast<juce::ComboBox*>(find(w,"clip.fade.in_curve"));curves->setSelectedId(2,juce::sendNotificationSync);click(w,"clip.fade");check(clips(w)[0]["fade_in_samples"]==4800&&clips(w)[0]["fade_out_samples"]==9600&&clips(w)[0]["fade_in_curve"]=="convex","GUI fade values and curve reach actual native DSP properties");
    auto* area=dynamic_cast<ndaw::desktop::EditArea*>(find(w,"edit.timeline"));check(area!=nullptr,"actual timeline is addressable for gesture regression");auto source=juce::Desktop::getInstance().getMainMouseSource();auto now=juce::Time::getCurrentTime();
    auto down=[&](int x,int y){juce::MouseEvent e(source,juce::Point<float>(float(x),float(y)),juce::ModifierKeys::leftButtonModifier,1,0,0,0,0,area,area,now,{float(x),float(y)},now,1,false);area->mouseDown(e);};
    auto drag=[&](int from,int to,int y){down(from,y);juce::MouseEvent e(source,juce::Point<float>(float(to),float(y)),juce::ModifierKeys::leftButtonModifier,1,0,0,0,0,area,area,now,{float(from),float(y)},now,1,true);area->mouseDrag(e);area->mouseUp(e);settle();};
    auto beforeDrag=clips(w);auto rect=area->clipRect(beforeDrag[0],0);drag(rect.getCentreX(),rect.getCentreX()+30,100);auto moved=clips(w);check(moved[0]["start_samples"].get<int64_t>()>beforeDrag[0]["start_samples"].get<int64_t>()&&moved[0]["source_offset_samples"]==beforeDrag[0]["source_offset_samples"],"timeline drag issues one real source-preserving move Plan");click(w,"history.undo");check(clips(w)==beforeDrag,"single Undo reverses entire drag");
    rect=area->clipRect(beforeDrag[0],0);drag(rect.getX()+2,rect.getX()+16,100);auto edge=clips(w);check(edge[0]["source_offset_samples"].get<int64_t>()>beforeDrag[0]["source_offset_samples"].get<int64_t>()&&edge[0]["start_samples"].get<int64_t>()>beforeDrag[0]["start_samples"].get<int64_t>(),"timeline edge drag trims source and session together");click(w,"history.undo");
    rect=area->clipRect(clips(w)[0],0);down(rect.getCentreX(),100);click(w,"history.undo");auto concurrent=w.query();juce::MouseEvent conflict(source,juce::Point<float>(float(rect.getCentreX()+30),100),juce::ModifierKeys::leftButtonModifier,1,0,0,0,0,area,area,now,{float(rect.getCentreX()),100},now,1,true);area->mouseDrag(conflict);area->mouseUp(conflict);settle();check(w.query()==concurrent,"stale clip drag cannot overwrite interleaved human Undo");click(w,"history.redo");check(clips(w)==beforeDrag,"concurrent rejection preserves subsequent Redo");
    field(w,"clip.position","12345");click(w,"history.undo");concurrent=w.query();click(w,"clip.move");check(w.query()==concurrent,"typed clip edit checks original revision after interleaved human Undo");click(w,"history.redo");check(clips(w)==beforeDrag,"stale typed edit does not consume redo history");
    auto bounds=area->clipRect(clips(w)[0],0);down(bounds.getCentreX(),100);settle();click(w,"clip.split");auto split=clips(w);check(split.size()==2&&split[0]["id"]==id&&split[1]["parent_clip"]==id,"GUI playhead split inserts real second clip with source lineage");click(w,"history.undo");check(clips(w)==beforeDrag,"GUI split Undo restores original whole clip");
    click(w,"clip.lock");check(clips(w)[0]["locked"]&&!find(w,"clip.move")->isEnabled()&&!find(w,"clip.delete")->isEnabled(),"lock disables destructive and positional UI edits");click(w,"clip.lock");check(!clips(w)[0]["locked"]&&find(w,"clip.move")->isEnabled(),"unlock restores actual edit affordances");click(w,"clip.copy");check(clips(w).size()==2&&clips(w)[1]["parent_clip"]==id,"GUI copy creates an independent non-destructive clip");click(w,"history.undo");click(w,"clip.delete");check(clips(w).empty()&&!find(w,"clip.trim"),"GUI delete removes actual clip and closes stale dock");click(w,"history.undo");check(clips(w)==beforeDrag,"GUI deleted clip Undo restores state");click(w,text("clip.select:"+id));
    auto beforeBad=w.query();field(w,"clip.start","1.5");click(w,"clip.trim");check(w.query()==beforeBad,"invalid exact position cannot modify native Edit");field(w,"clip.start","48000");field(w,"clip.end","192000");click(w,"clip.trim");check(Commands::mediaHash(file)==hash,"GUI edits preserve original media hash");
    Json result={{"result","passed"},{"checks",checks},{"scope","production JUCE clip controls and gestures, actual Edit changes; GUI/accepted structured Agent equivalence, not LLM or external MCP"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);}std::cout<<result.dump(2)<<std::endl;dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
