#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;using namespace ndaw::desktop;
namespace {
int checks=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
void pump(int ms=30){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& parent,const juce::String& id){if(!parent.isVisible())return nullptr;if(parent.getComponentID()==id)return &parent;for(auto* child:parent.getChildren())if(auto* result=find(*child,id))return result;return nullptr;}
void click(juce::Component& parent,const char* id){auto* button=dynamic_cast<juce::Button*>(find(parent,id));if(!button||!button->isEnabled())throw std::runtime_error(std::string("unavailable delivery button: ")+id);auto before=button->onClick;bool delivered=false;button->onClick=[&]{delivered=true;before();};button->triggerClick();const auto deadline=juce::Time::getMillisecondCounterHiRes()+1000;while(!delivered&&juce::Time::getMillisecondCounterHiRes()<deadline)pump(5);button->onClick=before;check(delivered,"actual asynchronous native button callback delivered");}
juce::TextEditor& editor(Workspace& w,const char* id){auto* result=dynamic_cast<juce::TextEditor*>(find(w,id));if(!result)throw std::runtime_error(std::string("missing delivery editor: ")+id);return *result;}
Json wait(Workspace& w){const auto deadline=juce::Time::getMillisecondCounterHiRes()+12000;while(w.queryAnalysis()["busy"].get<bool>()){if(juce::Time::getMillisecondCounterHiRes()>deadline)throw std::runtime_error("GUI delivery job exceeded preset twelve seconds");pump(20);}pump(300);return w.queryAnalysis();}
class Storage final:public te::PropertyStorage{public:explicit Storage(juce::File folder):PropertyStorage("Forma delivery UI"),folder(folder){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-delivery-ui-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();const auto source=folder.getChildFile("quiet-ending.wav");juce::AudioBuffer<float> data(2,192000);for(int n=0;n<192000;++n)for(int ch=0;ch<2;++ch)data.setSample(ch,n,n>=168000?0:float(.1*std::sin(2*juce::MathConstants<double>::pi*1000*n/48000)));juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=source.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));if(!writer||!writer->writeFromAudioSampleBuffer(data,0,192000))throw std::runtime_error("GUI delivery PCM write failed");writer.reset();const auto hash=Commands::mediaHash(source);
    Workspace w(false,std::make_unique<Storage>(folder.getChildFile("prefs")));w.setVisible(true);w.prepareImport(source);pump();click(w,"plan.accept");pump();const std::string track=w.query()["tracks"][0]["id"];auto* gain=dynamic_cast<juce::Slider*>(find(w,"track.gain:"+juce::String{track}));check(gain!=nullptr,"actual native source-track gain is available");gain->setValue(6,juce::sendNotificationSync);pump();const auto before=w.query();
    w.menuItemSelected(43,2);pump();editor(w,"analysis.start_samples").setText("24000");editor(w,"analysis.end_samples").setText("192000");check(editor(w,"delivery.target_lufs").getText()=="-14"&&editor(w,"delivery.true_peak_ceiling").getText()=="-1","native delivery controls expose the editable example criteria");click(w,"analysis.delivery.run");
    check(w.queryAnalysis()["busy"].get<bool>()&&!editor(w,"delivery.target_lufs").isEnabled()&&!find(w,"analysis.delivery.run")->isEnabled(),"native controls remain disabled until the real pending measurement terminates");auto passed=wait(w);check(passed["state"]=="completed"&&passed["receipt"]["delivery"]["status"]=="passed","native delivery action receives a genuine passing selected Master receipt");auto& summary=editor(w,"analysis.summary");check(summary.getText().contains("交付条件：通过")&&summary.getText().contains("整体响度：通过")&&summary.getText().contains("True Peak：通过")&&summary.getText().contains("超过满刻度：通过")&&summary.getText().contains("末尾电平 / 截断风险：通过"),"GUI displays all four actual criterion results");check(summary.getText().contains("RMS")&&summary.getText().contains("dBFS")&&summary.getText().contains("不能证明混响尾音完整")&&summary.getText().contains("不是平台认证"),"GUI states actual units and the tail and certification limits");
    editor(w,"delivery.true_peak_ceiling").setText("-15");pump(300);check(summary.getText().contains("TP ≤ -1.00 dBTP"),"editing a field does not relabel criteria bound to an existing result");click(w,"analysis.delivery.run");auto failed=wait(w);check(failed["state"]=="completed"&&failed["receipt"]["delivery"]["status"]=="failed"&&summary.getText().contains("交付条件：未通过")&&summary.getText().contains("True Peak：未通过"),"GUI distinguishes completed measurement from failed delivery conditions");
    const auto artifact=failed["receipt"]["artifact_id"];editor(w,"delivery.true_peak_ceiling").setText("-100");click(w,"analysis.delivery.run");pump(400);check(!w.queryAnalysis()["busy"].get<bool>()&&w.queryAnalysis()["receipt"]["artifact_id"]==artifact&&summary.getText().contains("操作未完成")&&summary.getText().contains("outside supported finite range"),"invalid threshold creates no job and remains visible after timer refresh");
    editor(w,"delivery.true_peak_ceiling").setText("-1");click(w,"analysis.delivery.run");check(!summary.getText().contains("操作未完成"),"a valid new submission clears the previous local error");click(w,"analysis.cancel");check(wait(w)["state"]=="cancelled","native delivery cancellation yields an actual cancelled receipt");click(w,"analysis.close");
    const auto after=w.query();check(after["revision"]==before["revision"]&&after["tracks"]==before["tracks"]&&after["can_undo"]==before["can_undo"]&&after["can_redo"]==before["can_redo"]&&Commands::mediaHash(source)==hash,"delivery controls reports and cancellation preserve Edit revision facts Undo availability and original media");
    click(w,"history.undo");check(std::abs(w.query()["tracks"][0]["gain_db"].get<double>()+12)<.001,"one native Undo restores the imported -12dB human gain and not a delivery analysis");const double elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"native delivery qualification meets preset sixty-second total budget");const Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"passed",passed},{"failed",failed},{"scope","actual JUCE callbacks and Tracktion render, not desktop acceptance"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("GUI delivery report write failed");}std::cout<<report.dump(2)<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
