#include <nativedaw/v2/AudioAnalysis.h>
#include <nativedaw/v2/DeliveryCheck.h>
#include <nativedaw/v2/McpSession.h>
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;
namespace {
int checks=0;Json evidence=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
void pump(int ms=10){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
void write(const juce::File& file,const juce::AudioBuffer<float>& audio){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(audio.getNumChannels()).withBitsPerSample(32));if(!writer||!writer->writeFromAudioSampleBuffer(audio,0,audio.getNumSamples()))throw std::runtime_error("delivery PCM write failed");}
void sine(juce::AudioBuffer<float>& audio,bool quietEnd){for(int n=0;n<audio.getNumSamples();++n)for(int ch=0;ch<audio.getNumChannels();++ch)audio.setSample(ch,n,quietEnd&&n>=168000?0:float(.1*std::sin(2*juce::MathConstants<double>::pi*1000*n/48000)));}
Json op(const char* id,Json args){return {{"command",id},{"args",args}};}
Json request(Commands& c,const char* key){return {{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]},{"start_samples",24000},{"end_samples",192000},{"request_key",key}};}
Json wait(Commands& c){const auto deadline=juce::Time::getMillisecondCounterHiRes()+12000;while(c.analysisStatus()["busy"].get<bool>()){if(juce::Time::getMillisecondCounterHiRes()>deadline)throw std::runtime_error("native delivery render exceeded preset twelve seconds");pump();}return c.analysisStatus();}
Json rpc(McpSession& session,const char* method,Json params=Json::object()){
    static int key=0;std::vector<Json> out;const int id=++key;std::thread requestThread([&]{out=session.receive(Json{{"jsonrpc","2.0"},{"id",id},{"method",method},{"params",params}}.dump());});requestThread.join();
    const auto deadline=juce::Time::getMillisecondCounterHiRes()+5000;while(out.empty()){if(juce::Time::getMillisecondCounterHiRes()>deadline)throw std::runtime_error("MCP delivery reply exceeded preset five seconds");pump();std::thread ready([&]{out=session.ready();});ready.join();}return out.at(0);
}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-delivery-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();
    const auto defaults=delivery::normaliseProfile(Json::object());check(defaults["target_lufs"]==-14&&defaults["true_peak_ceiling_dbtp"]==-1&&defaults["lufs_tolerance"]==1,"profile defaults match the explicit example and not a platform guarantee");
    fails([&]{delivery::normaliseProfile({{"upload",true}});},"unknown delivery fields cannot introduce uploading");fails([&]{delivery::normaliseProfile({{"expect_silent_ending","yes"}});},"ending policy requires an actual boolean");fails([&]{delivery::normaliseProfile({{"true_peak_ceiling_dbtp",-21}});},"out-of-range true peak threshold is rejected");fails([&]{delivery::normaliseProfile({{"lufs_tolerance",-1}});},"negative loudness tolerance is rejected");fails([&]{delivery::normaliseProfile({{"target_lufs",std::numeric_limits<double>::infinity()}});},"nonfinite profile threshold is rejected");
    auto profile=delivery::normaliseProfile({{"target_lufs",-20}});juce::AudioBuffer<float> audio(2,192000);sine(audio,true);const auto source=folder.getChildFile("quiet-ending.wav");write(source,audio);const auto hash=Commands::mediaHash(source);auto measured=analysis::measure(source,24013);auto report=delivery::evaluate(measured,profile);
    check(report["status"]=="passed"&&report["checks"].size()==4,"actual calibrated PCM with quiet ending passes all four explicit conditions");
    check(std::abs(measured["true_peak_dbtp"].get<double>()+20)<.02&&std::abs(measured["lufs_i"].get<double>()+20)<1,"known quiet-ending PCM remains within preset -20dBTP +/-0.02 and -20LUFS +/-1 budgets");
    check(measured["ending_window"]["frames"]==4800&&measured["ending_window"]["start_samples"]==211213&&measured["ending_window"]["end_samples"]==216013&&measured["ending_window"]["peak"]==0,"last 100ms window uses real PCM and exact nonzero session origin");
    check(std::abs(measured["rms_dbfs"].get<double>()-20*std::log10(measured["rms"].get<double>()))<1e-12,"display RMS dBFS is the actual linear PCM RMS conversion");
    check(!report["tail_truncation_certified"].get<bool>()&&!report["export_file_certified"].get<bool>()&&!report["platform_certified"].get<bool>(),"passing conditions do not certify tails exports or a streaming platform");evidence.push_back({{"measurement",measured},{"delivery",report}});
    juce::AudioBuffer<float> louder(audio);louder.applyGain(2);const auto louderFile=folder.getChildFile("louder.wav");write(louderFile,louder);auto strict=delivery::evaluate(analysis::measure(louderFile,0),{{"target_lufs",-14},{"true_peak_ceiling_dbtp",-15}});check(strict["status"]=="failed"&&strict["checks"][1]["status"]=="failed"&&strict["checks"][0]["status"]=="passed","strict peak ceiling fails independently of passing loudness");
    check(delivery::evaluate(measured,defaults)["checks"][0]["status"]=="failed","real loudness outside the target is a failed condition");
    sine(audio,false);const auto active=folder.getChildFile("active-ending.wav");write(active,audio);auto activeMeasurement=analysis::measure(active,0);auto activeReport=delivery::evaluate(activeMeasurement,profile);check(activeReport["status"]=="needs_review"&&activeReport["checks"][3]["status"]=="review","actual nonquiet end requests human review instead of inventing a truncated tail");
    const double tailRms=activeMeasurement["ending_window"]["rms"],tailPeak=activeMeasurement["ending_window"]["peak"];check(std::abs(tailPeak-.1)<1e-7&&std::abs(tailRms-.1/std::sqrt(2.))<1e-8,"active last-window peak and RMS match independently known sine samples");
    check(delivery::evaluate(activeMeasurement,{{"target_lufs",-20},{"expect_silent_ending",false}})["status"]=="passed","explicit user policy can omit ending silence without claiming tails complete");evidence.push_back({{"measurement",activeMeasurement},{"delivery",activeReport}});
    audio.clear();const auto silent=folder.getChildFile("silence.wav");write(silent,audio);auto silentReport=delivery::evaluate(analysis::measure(silent,0),defaults);check(silentReport["status"]=="indeterminate"&&silentReport["checks"][0]["status"]=="indeterminate"&&silentReport["checks"][1]["status"]=="passed","silent audio has undefined LUFS and cannot pass the overall check");
    audio.setSize(2,2400);sine(audio,false);const auto shortFile=folder.getChildFile("short.wav");write(shortFile,audio);auto shortReport=delivery::evaluate(analysis::measure(shortFile,0),profile);check(shortReport["status"]=="indeterminate"&&shortReport["checks"][3]["status"]=="indeterminate","50ms PCM does not fabricate a complete 100ms ending or integrated loudness");
    audio.setSample(0,500,std::numeric_limits<float>::quiet_NaN());const auto invalid=folder.getChildFile("nonfinite.wav");write(invalid,audio);fails([&]{analysis::measure(invalid,0);},"actual nonfinite float PCM never produces a successful delivery measurement");
    auto unverified=measured;unverified["audio_verified"]=false;fails([&]{delivery::evaluate(unverified,profile);},"rule evaluator rejects unverified input measurements");
    Commands c(false);c.commit(c.makePlan("human",Json::array({op("track.create",{{"name","Delivery Source"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}}),op("track.gain",{{"track","$t"},{"db",6}})})));const auto before=c.query();const std::string track=before["tracks"][0]["id"];
    auto args=request(c,"native-delivery");const auto submitted=c.analysisControl("delivery",args);check(submitted["busy"].get<bool>()&&!submitted["request"].contains("delivery"),"delivery submission returns a genuine pending job without a fake result");
    const auto retry=c.analysisControl("delivery",args);check(retry["request"]["artifact_id"]==submitted["request"]["artifact_id"],"identical live delivery retry shares its actual render");auto mismatch=args;mismatch["profile"]={{"target_lufs",-15}};fails([&]{c.analysisControl("delivery",mismatch);},"retry cannot reuse a key with different delivery thresholds");fails([&]{c.analysisControl("master",args);},"retry cannot reuse a delivery key for a different analysis purpose");
    auto native=wait(c);check(native["state"]=="completed"&&native["receipt"]["current"].get<bool>()&&native["receipt"]["delivery"]["status"]=="passed","Tracktion gain and selected native Master render pass the explicit example conditions");
    const auto& artifact=native["receipt"];check(artifact["frames"]==168000&&artifact["binding"]["purpose"]=="delivery"&&artifact["media"][0]["sha256"]==hash&&artifact["binding"]["processing_chain_hash"].get<std::string>().size()==64,"actual delivery receipt binds exact render length purpose chain and source hash");
    const auto profileText=artifact["delivery"]["profile"].dump();check(artifact["delivery"]["profile_sha256"]==juce::SHA256(profileText.data(),profileText.size()).toHexString().toStdString()&&artifact["binding"]["delivery_profile"]==artifact["delivery"]["profile"],"normalised criteria and profile hash are immutable parts of the measured receipt");
    check(c.analysisControl("delivery",args)["receipt"]["artifact_id"]==artifact["artifact_id"],"completed delivery retry returns the same receipt without rerendering");fails([&]{c.analysisControl("delivery",mismatch);},"completed retry rejects altered thresholds");
    const auto after=c.query();check(after["revision"]==before["revision"]&&after["tracks"]==before["tracks"]&&after["can_undo"]==before["can_undo"]&&after["can_redo"]==before["can_redo"]&&after["position_samples"]==before["position_samples"],"delivery measurement cannot change Edit revision facts Undo availability or transport cursor");evidence.push_back(native);
    CommandQueue queue(c);Scope scope;scope.mode=Permission::ReadOnly;auto client=queue.connect("agent:delivery",scope);McpSession session(client,Commands::registry());rpc(session,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","delivery-tests"},{"version","1"}}}});session.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());bool found=false;Json pageArgs=Json::object();do{const auto page=rpc(session,"tools/list",pageArgs)["result"];for(const auto& tool:page["tools"])if(tool["name"]=="analyze_delivery")found=tool["annotations"]["readOnlyHint"].get<bool>()&&tool["inputSchema"]["properties"]["profile"]["additionalProperties"]==false;pageArgs=page.contains("nextCursor")?Json{{"cursor",page["nextCursor"]}}:Json::object();}while(!pageArgs.empty());check(found,"MCP read-only delivery tool and strict profile schema come from the L1 registry");
    auto rejected=rpc(session,"tools/call",{{"name","analyze_delivery"},{"arguments",Json{{"session_token",c.sessionToken()},{"base_revision",c.query()["revision"]},{"start_samples",0},{"end_samples",192000},{"request_key","unknown-path"},{"path","/tmp/untrusted.wav"}}}});check(rejected["result"]["isError"].get<bool>(),"MCP delivery cannot request arbitrary file output");
    auto mcpArgs=request(c,"mcp-delivery");mcpArgs["profile"]={{"true_peak_ceiling_dbtp",-15}};const auto accepted=rpc(session,"tools/call",{{"name","analyze_delivery"},{"arguments",mcpArgs}});check(!accepted["result"]["isError"].get<bool>(),"read-only MCP client can request the actual local delivery job");wait(c);const auto external=rpc(session,"tools/call",{{"name","query_analysis"},{"arguments",Json::object()}})["result"]["structuredContent"]["result"];check(external["state"]=="completed"&&external["receipt"]["delivery"]["status"]=="failed"&&external["receipt"]["delivery"]["checks"][1]["status"]=="failed","MCP completed measurement accurately returns failed peak criteria and actual evidence");evidence.push_back(external);
    c.commit(c.makePlan("human",Json::array({op("clip.gain",{{"clip",before["tracks"][0]["clips"][0]["id"]},{"db",18}})})));check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"new human clip gain invalidates the prior delivery receipt");auto overArgs=request(c,"over-delivery");c.analysisControl("delivery",overArgs);auto overs=wait(c);check(overs["state"]=="completed"&&overs["receipt"]["delivery"]["status"]=="failed"&&overs["receipt"]["delivery"]["checks"][2]["status"]=="failed"&&overs["receipt"]["over_full_scale_frames"].get<int64_t>()>0,"native float overs fail clipping-risk condition without claiming the analysis itself failed");evidence.push_back(overs);
    check(Commands::mediaHash(source)==hash,"all delivery jobs and MCP queries preserve the original PCM");const double elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"delivery qualification meets preset sixty-second total budget");const Json summary={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"evidence",evidence},{"scope","actual PCM/native rendering and MCP protocol; not a desktop model demonstration or platform certification"}};if(argc>1){std::ofstream out(argv[1]);out<<summary.dump(2);if(!out)throw std::runtime_error("delivery report write failed");}std::cout<<summary.dump(2)<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
