#include <nativedaw/v2/ExportVerification.h>
#include <nativedaw/v2/McpSession.h>
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;
namespace {
int checks=0;Json runs=Json::array();double now(){return juce::Time::getMillisecondCounterHiRes();}
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,why);}
void pump(int ms=5){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json op(const char* cmd,Json args){return {{"command",cmd},{"args",args}};}
Json commit(Commands& c,Json ops){return c.commit(c.makePlan("human",ops));}
Json request(Commands& c,const juce::File& file,int64_t postroll,const std::string& key){auto args=c.exportRequest(true);args["postroll_samples"]=postroll;args["destination"]=file.getFullPathName().toStdString();args["request_key"]=key;return args;}
struct Heartbeat final:juce::Timer {
    std::vector<double> gaps;double last=now();
    Heartbeat(){startTimer(10);}~Heartbeat(){stopTimer();}
    void timerCallback()override{const auto at=now();gaps.push_back(at-last);last=at;}
    Json finish(){stopTimer();gaps.push_back(now()-last);auto sorted=gaps;std::sort(sorted.begin(),sorted.end());return {{"count",sorted.size()},{"max_ms",sorted.back()},{"p95_ms",sorted[size_t(std::ceil(sorted.size()*.95))-1]}};}
};
Json wait(Commands& c){Heartbeat heartbeat;const auto began=now();while(c.analysisStatus()["busy"].get<bool>()){if(now()-began>12000)throw std::runtime_error("verified export exceeded unchanged twelve-second job budget");pump();}auto state=c.analysisStatus();state["test_heartbeat"]=heartbeat.finish();check(state["test_heartbeat"]["max_ms"].get<double>()<=250&&state["test_heartbeat"]["p95_ms"].get<double>()<=50,"actual export message heartbeat meets unchanged 250/50 ms budgets");runs.push_back(state);return state;}
void parked(Commands& c,const Json& started){c.analysisControl("pause",{{"artifact_id",started["request"]["artifact_id"]},{"paused",true}});const auto until=now()+5000;while(!c.analysisStatus()["pause"]["worker_parked"].get<bool>()&&now()<until)pump();check(c.analysisStatus()["pause"]["worker_parked"].get<bool>(),"export pause acknowledges a real worker checkpoint");}
Json rpc(McpSession& m,const char* method,Json params){static int id=0;const int key=++id;std::vector<Json> output;std::thread t([&]{output=m.receive(Json{{"jsonrpc","2.0"},{"id",key},{"method",method},{"params",params}}.dump());});t.join();const auto until=now()+5000;while(output.empty()&&now()<until){pump();output=m.ready();}for(auto& r:output)if(r.value("id",Json(nullptr))==key)return r;throw std::runtime_error("export MCP timeout");}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto began=now();const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-export-tests-"+juce::Uuid().toString());folder.createDirectory();try{
    auto source=folder.getChildFile("actual-end-pulse.wav");juce::AudioBuffer<float> original(2,24000);original.clear();for(int n=19200;n<24000;++n){original.setSample(0,n,.4f);original.setSample(1,n,-.2f);} {juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=source.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));check(writer&&writer->writeFromAudioSampleBuffer(original,0,24000),"actual original stereo calibration PCM written");}
    const auto originalHash=Commands::mediaHash(source);Commands c(false);commit(c,Json::array({op("track.create",{{"name","Tail and quantisation"},{"ref","$t"}}),op("track.gain",{{"track","$t"},{"db",0}}),op("clip.import",{{"track","$t"},{"path",source.getFullPathName().toStdString()},{"position_samples",0},{"ref","$c"}}),op("clip.gain",{{"clip","$c"},{"db",12}}),op("clip.fx.insert",{{"clip","$c"},{"type",te::DelayPlugin::xmlTypeName}}),op("session.range.set",{{"start_samples",13},{"end_samples",23999}})}));auto facts=c.query();const auto track=facts["tracks"][0]["id"],delay=facts["tracks"][0]["clips"][0]["plugins"][0]["id"];commit(c,Json::array({op("plugin.parameter",{{"plugin",delay},{"parameter","feedback"},{"value",-30}}),op("plugin.parameter",{{"plugin",delay},{"parameter","mix proportion"},{"value",1}})}));c.seek(17);const auto before=c.query();
    auto shortPath=folder.getChildFile("truncated.wav");auto shortArgs=request(c,shortPath,0,"short");const auto start=now();auto started=c.analysisControl("export",shortArgs);check(!shortPath.exists()&&started["busy"].get<bool>(),"accepted job cannot report a published file before real completion");auto shortState=wait(c);check(shortState["state"]=="completed"&&shortState["receipt"]["file_verification"]["status"]=="verified_published"&&shortPath.existsAsFile(),"actual staged PCM24 verified before atomic publication");check(now()-start<12000&&shortState["runtime"]["preparation_ms"]["total"].get<double>()<1000,"real new export retains fixed job and graph preparation budgets");auto& shortResult=shortState["receipt"];check(shortResult["frames"]==23986&&shortResult["peak"]==0&&shortResult["continuation"]["status"]=="needs_review"&&shortResult["continuation"]["over_full_scale_frames"]==4800,"silent file end does not hide the real omitted delayed pulse");check(!shortResult["continuation"]["tail_truncation_certified"].get<bool>()&&shortResult["continuation"]["start_samples"]==23999&&shortResult["continuation"]["end_samples"]==119999,"actual continuation has explicit outside-file frame domain and no fake full-tail certification");check(c.analysisControl("export",shortArgs)["receipt"]["artifact_id"]==shortResult["artifact_id"],"identical live receipt retry does not create a second file");auto changed=shortArgs;changed["postroll_samples"]=1;fails([&]{c.analysisControl("export",changed);},"same export key cannot change output intent");
    auto path=folder.getChildFile("with-postroll.wav");auto args=request(c,path,24000,"postroll");c.analysisControl("export",args);auto complete=wait(c);check(complete["state"]=="completed"&&complete["receipt"]["current"].get<bool>(),"half-second postroll produces actual current file receipt");auto& result=complete["receipt"];check(result["frames"]==47986&&result["file_bits"]==24&&!result["file_float"].get<bool>()&&result["channels"]==2&&result["sample_rate"]==48000,"actual decoded export matches exact unaligned range plus postroll and declared PCM format");check(result["float_reference"]["peak"].get<double>()>1.59&&result["float_reference"]["over_full_scale_frames"]==4800&&result["peak"].get<double>()<1&&result["delivery"]["float_encoding_risk"]["status"]=="failed"&&result["delivery"]["status"]=="failed","real integer saturation cannot masquerade as safe floating Master evidence");check(result["continuation"]["status"]=="quiet_observed_window"&&result["continuation"]["peak"]==0&&!result["delivery"]["tail_truncation_certified"].get<bool>(),"postroll includes known Delay tail but finite quiet window remains bounded evidence");
    juce::AudioFormatManager formats;formats.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(formats.createReaderFor(path));check(reader&&reader->lengthInSamples==47986&&reader->bitsPerSample==24&&!reader->usesFloatingPointData,"independent reader validates published WAV header");juce::AudioBuffer<float> encoded(2,47986);check(reader->read(&encoded,0,47986,0,true,true),"independent decoder reads published PCM");bool samples=true;double squares=0,peak=0;for(int n=0;n<47986;++n)for(int ch=0;ch<2;++ch){const auto at=n+13;const float expected=at>=26400&&at<31200?std::clamp((ch?-.2f:.4f)*juce::Decibels::decibelsToGain(12.f),-1.f,1.f):0.f;const double actual=encoded.getSample(ch,n);samples&=std::abs(actual-expected)<=3e-6;squares+=actual*actual;peak=std::max(peak,std::abs(actual));}check(samples,"every exported sample agrees with independent delay/gain/saturation prediction within original tolerance");check(std::abs(result["rms"].get<double>()-std::sqrt(squares/(47986*2)))<1e-12&&result["peak"]==peak,"published file RMS/Peak match independent decoded signal");check(Commands::mediaHash(path)==result["file_verification"]["sha256"].get<std::string>(),"actual final WAV bytes match verified hash");
    check(c.query()["tracks"]==before["tracks"]&&c.query()["revision"]==before["revision"]&&c.query()["position_samples"]==before["position_samples"],"export does not alter real project/history/cursor");
    CommandQueue queue(c);Scope readonly;McpSession m(queue.connect("agent:export-observer",readonly),Commands::registry());rpc(m,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","export-tests"},{"version","1"}}}});m.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());auto remote=rpc(m,"tools/call",{{"name","query_analysis"},{"arguments",Json::object()}});check(remote["result"]["structuredContent"]["result"]["receipt"]["file_verification"]==result["file_verification"],"real read-only MCP sees same final published file verification");check(rpc(m,"tools/call",{{"name","export.verified"},{"arguments",args}}).contains("error"),"MCP cannot invoke local file-write control");fails([&]{c.analysisControl("export",request(c,folder.getChildFile("unauthorized.wav"),0,"unauthorized"),"agent:untrusted");},"foreign actor cannot acquire arbitrary external write grant");
    // Mutation of the actual output with preserved size/mtime invalidates deep location.
    juce::MemoryBlock bytes;path.loadFileAsData(bytes);const auto mtime=path.getLastModificationTime();auto altered=bytes;static_cast<unsigned char*>(altered.getData())[altered.getSize()-1]^=0x01;path.replaceWithData(altered.getData(),altered.getSize());path.setLastModificationTime(mtime);fails([&]{c.analysisControl("locate_loudness",{{"artifact_id",result["artifact_id"]},{"point_index",0},{"series","momentary"}});},"deep location rejects same-size same-time output byte mutation");check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"changed published output is permanently stale for current location");path.replaceWithData(bytes.getData(),bytes.getSize());path.setLastModificationTime(mtime);
    auto collision=folder.getChildFile("collision.wav");auto collisionJob=c.analysisControl("export",request(c,collision,0,"collision"));parked(c,collisionJob);collision.replaceWithText("owned collision sentinel");const auto sentinel=Commands::mediaHash(collision);c.analysisControl("pause",{{"artifact_id",collisionJob["request"]["artifact_id"]},{"paused",false}});auto collided=wait(c);check(collided["state"]=="failed"&&Commands::mediaHash(collision)==sentinel&&!collided["receipt"].contains("file_verification"),"actual final-name race rejects atomically and preserves existing original bytes");
    auto cancelPath=folder.getChildFile("cancelled.wav");auto pending=c.analysisControl("export",request(c,cancelPath,0,"cancel"));parked(c,pending);fails([&]{c.render(folder.getChildFile("parallel.wav"),0,48000);},"ordinary export cannot start a second render while the shared job is active");c.analysisControl("cancel",{{"artifact_id",pending["request"]["artifact_id"]}});auto cancelled=wait(c);check(cancelled["state"]=="cancelled"&&!cancelPath.exists(),"pause then cancel never publishes output or success");
    auto stale=folder.getChildFile("human-newer.wav");pending=c.analysisControl("export",request(c,stale,0,"human-newer"));parked(c,pending);commit(c,Json::array({op("track.rename",{{"track",track},{"name","Newer human track"}})}));c.analysisControl("pause",{{"artifact_id",pending["request"]["artifact_id"]},{"paused",false}});auto conflict=wait(c);check(conflict["state"]=="failed"&&!stale.exists()&&c.query()["tracks"][0]["name"]=="Newer human track","new human revision prevents stale export publication without losing human work");
    auto tooLong=request(c,folder.getChildFile("too-long.wav"),1440001,"too-long");fails([&]{c.analysisControl("export",tooLong);},"explicit postroll budget rejects rather than silently reducing duration");fails([&]{analysis::stageVerifiedWav(source,folder.getChildFile("invalid-format.wav"),0,24000,{},Json::object());},"real wrong-length render cannot be encoded as a successful verified export");check(!folder.getChildFile("invalid-format.wav").exists(),"format rejection creates no output");
    // Actual PCM whose file interval passes every original criterion, but has
    // known later signal: the additional evidence must prevent overall pass.
    auto policyRender=folder.getChildFile("policy-float.wav");juce::AudioBuffer<float> policyPcm(2,144000);policyPcm.clear();
    for(int n=0;n<36000;++n)for(int ch=0;ch<2;++ch)policyPcm.setSample(ch,n,float(.1*std::sin(2*juce::MathConstants<double>::pi*1000*n/48000)));
    for(int n=50000;n<54800;++n)for(int ch=0;ch<2;++ch)policyPcm.setSample(ch,n,.2f);
    {juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=policyRender.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));check(writer&&writer->writeFromAudioSampleBuffer(policyPcm,0,144000),"write actual passing interval with active outside-file continuation");}
    auto policyReference=analysis::measure(policyRender,0,{}, {0,48000},nullptr,analysis::FeatureDomain::SessionSamples);
    auto policy=analysis::stageVerifiedWav(policyRender,folder.getChildFile("policy-pcm24.wav"),0,48000,{},{{"target_lufs",policyReference["lufs_i"]}});
    bool originalCriteria=true;for(size_t n=0;n<4;++n)originalCriteria&=policy["delivery"]["checks"][n]["status"]=="passed";
    check(originalCriteria&&policy["delivery"]["checks"].size()==6&&policy["delivery"]["checks"][5]["status"]=="review"&&policy["delivery"]["status"]=="needs_review","actual outside-file signal prevents overall pass even when all original file criteria pass");
    check(folder.findChildFiles(juce::File::findDirectories,false,".forma-export-*").isEmpty(),"owned staging directories are reclaimed after success and failures");check(Commands::mediaHash(source)==originalHash,"all export and fault workflows preserve original media hash");check(now()-began<120000,"full verified export qualification retains preset 120 seconds");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",now()-began},{"runs",runs},{"scope","real Tracktion snapshot, PCM24 and actual filesystem/MCP; production desktop separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("export report write failed");}std::cout<<"RESULT "<<checks<<" checks "<<now()-began<<" ms"<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
