#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;using namespace ndaw::desktop;
namespace ndaw::v2 {class McpTestAccess {public:static Commands& commands(Workspace& w){return w.commands;}};}
namespace {
int checks=0;double now(){return juce::Time::getMillisecondCounterHiRes();}void pump(int ms=5){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
juce::Component* find(juce::Component& c,const char* id){if(!c.isVisible())return nullptr;if(c.getComponentID()==id)return &c;for(auto* child:c.getChildren())if(auto* found=find(*child,id))return found;return nullptr;}
void click(juce::Component& c,const char* id){auto* button=dynamic_cast<juce::Button*>(find(c,id));if(!button||!button->isEnabled())throw std::runtime_error(std::string("unavailable native button: ")+id);button->triggerClick();pump(20);}
Json op(const char* cmd,Json args){return {{"command",cmd},{"args",args}};}
Json wait(Commands& c,ExportPanel& p){const auto until=now()+12000;while(c.analysisStatus()["busy"].get<bool>()&&now()<until){pump();p.update(c.analysisStatus());}auto state=c.analysisStatus();p.update(state);check(!state["busy"].get<bool>(),"real native export terminal receipt within twelve seconds");return state;}
class Storage final:public te::PropertyStorage {public:Storage(juce::File folder):PropertyStorage("Forma verified export GUI"),folder(folder){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto began=now();auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-export-ui-"+juce::Uuid().toString());folder.createDirectory();try{
    auto source=folder.getChildFile("real-source.wav");juce::AudioBuffer<float> signal(2,48000);signal.clear();for(int n=0;n<48000;++n){signal.setSample(0,n,float(.1*std::sin(2*juce::MathConstants<double>::pi*1000*n/48000)));signal.setSample(1,n,-signal.getSample(0,n));}{juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=source.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));check(writer&&writer->writeFromAudioSampleBuffer(signal,0,48000),"real production PCM fixture written");}
    const auto hash=Commands::mediaHash(source);Workspace w(false,std::make_unique<Storage>(folder.getChildFile("prefs")));w.setVisible(true);w.prepareImport(source);pump();click(w,"plan.accept");const auto before=w.query();w.showVerifiedExport();pump();check(find(w,"export.panel")&&find(w,"export.verified.begin"),"actual Workspace opens native verified-export panel");click(w,"export.close");check(!find(w,"export.panel"),"actual Workspace closes export panel through native callback");auto& c=McpTestAccess::commands(w);auto target=folder.getChildFile("actual-published.wav");bool closed=false;
    // Test-only local chooser grant selects owned paths; rendering/commands/UI are production.
    ExportPanel p([&](const auto& method,const auto& args){return c.analysisControl(method,args);},[&](Json args){args["destination"]=target.getFullPathName().toStdString();try{p.update(c.analysisControl("export",args));}catch(const std::exception& e){p.showError(e.what());}},[&]{closed=true;});p.setSize(1100,700);p.setVisible(true);p.bind(c.exportRequest(false),c.analysisStatus());auto* post=dynamic_cast<juce::TextEditor*>(find(p,"export.postroll_seconds"));auto* summary=dynamic_cast<juce::TextEditor*>(find(p,"export.summary"));check(post&&summary&&!dynamic_cast<juce::Button*>(find(p,"export.cancel"))->isEnabled(),"actual native range/postroll/result controls exist without fake live job");
    post->setText("31",false);click(p,"export.verified.begin");check(!target.exists()&&summary->getText().contains("0–30"),"native invalid postroll rejects with visible error before any output");post->setText("0.5",false);click(p,"export.verified.begin");check(c.analysisStatus()["busy"].get<bool>()&&!target.exists()&&!summary->getText().contains("已生成并校验"),"native submission shows pending until actual file exists and validates");click(p,"export.pause");const auto until=now()+5000;while(!c.analysisStatus()["pause"]["worker_parked"].get<bool>()&&now()<until)pump();p.update(c.analysisStatus());check(summary->getText().contains("工作线程已停驻")&&dynamic_cast<juce::Button*>(find(p,"export.pause"))->getButtonText()==text("继续导出"),"native pause shows genuine checkpoint acknowledgement");click(p,"export.pause");auto state=wait(c,p);check(state["state"]=="completed"&&target.existsAsFile()&&state["receipt"]["frames"]==72000,"native resume generates exact range plus chosen postroll in real WAV");check(summary->getText().contains(target.getFullPathName())&&summary->getText().contains("PCM24")&&summary->getText().contains("SHA256")&&summary->getText().contains("LUFS-I")&&summary->getText().contains("True Peak")&&summary->getText().contains("不能证明全部尾音"),"native result exposes real file format/hash/measurements and finite continuation boundary");check(!dynamic_cast<juce::Button*>(find(p,"export.pause"))->isEnabled()&&!dynamic_cast<juce::Button*>(find(p,"export.cancel"))->isEnabled(),"native controls disable after actual completed receipt");check(w.query()["revision"]==before["revision"]&&w.query()["tracks"]==before["tracks"],"native verified export uses same engine without editing project facts");
    target=folder.getChildFile("cancelled.wav");p.bind(c.exportRequest(false),c.analysisStatus());click(p,"export.verified.begin");click(p,"export.pause");click(p,"export.cancel");auto cancelled=wait(c,p);check(cancelled["state"]=="cancelled"&&!target.exists()&&!summary->getText().contains("已生成并校验"),"native cancelled workflow has no output or invented completion");click(p,"export.close");check(closed,"native close callback executed");check(Commands::mediaHash(source)==hash,"native export never alters original media bytes");check(now()-began<60000,"native verified export qualification retains sixty-second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",now()-began},{"receipt",state},{"scope","actual Workspace/ExportPanel/Commands and real PCM; test-only owned chooser path, production system picker and desktop separately qualified"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("native export report write failed");}std::cout<<"RESULT "<<checks<<" checks "<<now()-began<<" ms"<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
