#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<"\n";}
template<class F>void fails(F f,const char* why){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
Json op(const char* cmd,Json args){return {{"command",cmd},{"args",args}};}
Json find(Commands& c,const std::string& id){auto facts=c.query();for(auto& t:facts["tracks"])if(t["id"]==id)return t;throw std::runtime_error("missing queried ID");}
void settle(){juce::MessageManager::getInstance()->runDispatchLoopUntil(80);}
void signal(const juce::File& file,int channel,float amplitude,double frequency){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture write failed");juce::AudioBuffer<float> data(2,96000);data.clear();for(int i=0;i<96000;++i)data.setSample(channel,i,amplitude*std::sin(2*juce::MathConstants<double>::pi*frequency*i/48000));if(!writer->writeFromAudioSampleBuffer(data,0,96000))throw std::runtime_error("fixture PCM failed");}
std::array<double,2> rms(const juce::File& file){juce::AudioFormatManager fm;fm.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(fm.createReaderFor(file));if(!reader||reader->lengthInSamples!=96000||reader->numChannels!=2)throw std::runtime_error("actual render format mismatch");juce::AudioBuffer<float> data(2,48000);if(!reader->read(&data,0,48000,2048,true,true))throw std::runtime_error("render read failed");return {data.getRMSLevel(0,0,48000),data.getRMSLevel(1,0,48000)};}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-groups-"+juce::Uuid().toString());dir.createDirectory();auto left=dir.getChildFile("left.wav"),right=dir.getChildFile("right.wav");signal(left,0,.2f,1000);signal(right,1,.1f,2000);auto hash=Commands::mediaHash(left);
    Commands c(false);c.commit(c.makePlan("human",Json::array({op("track.create",{{"name","Left"},{"ref","$left"}}),op("clip.import",{{"track","$left"},{"path",left.getFullPathName().toStdString()},{"position_samples",0}}),op("track.create",{{"name","Right"},{"ref","$right"}}),op("clip.import",{{"track","$right"},{"path",right.getFullPathName().toStdString()},{"position_samples",0}})})));
    const std::string l=c.query()["tracks"][0]["id"],r=c.query()["tracks"][1]["id"];auto original=find(c,l);Json renders=Json::array();int serial=0;const double a=.2/std::sqrt(2.),b=.1/std::sqrt(2.),six=std::pow(10.,-6./20.);
    auto measure=[&](const char* name,double el,double er){settle();auto dest=dir.getChildFile("out-"+juce::String(++serial)+".wav");auto receipt=c.render(dest,0,96000);auto actual=rms(dest);std::cout<<name<<" RMS "<<actual[0]<<","<<actual[1]<<" expected "<<el<<","<<er<<"\n";check(std::abs(actual[0]-el)<3e-6&&std::abs(actual[1]-er)<3e-6,name);renders.push_back({{"case",name},{"rms",actual},{"receipt",receipt}});};
    auto run=[&](Json operations){auto p=c.makePlan("human",operations);c.commit(p);settle();return p;};
    measure("ungrouped known PCM",a,b);
    auto folderPlan=c.makePlan("agent:qualification",Json::array({op("track.create",{{"name","Vocal folder"},{"type","folder"},{"ref","$folder"}}),op("track.parent",{{"track",l},{"parent","$folder"}})}));auto before=c.query();check(c.preview(folderPlan)["changes"].size()==2&&c.query()==before,"hierarchy preview is read-only");fails([&]{c.commit(folderPlan);},"agent grouping needs acceptance");c.commit(folderPlan,true);settle();std::string folder;{auto q=c.query();for(auto& t:q["tracks"])if(t["type"]=="folder")folder=t["id"];}
    check(!folder.empty()&&find(c,l)["parent"]==folder&&find(c,l)["depth"]==1,"real Folder contains stable-ID member");check(find(c,folder)["gain_db"].is_null()&&!find(c,folder)["capabilities"]["audio_routing"].get<bool>(),"Folder has no pretend fader or audio route");measure("organisational Folder leaves PCM unchanged",a,b);
    check(find(c,l)["output"]==original["output"]&&find(c,l)["gain_db"]==original["gain_db"]&&find(c,l)["clips"]==original["clips"],"group preserves output own fader and original clip ID");
    juce::MessageManager::getInstance()->runDispatchLoopUntil(450);c.undo(folderPlan["plan_id"]);check(c.query()["tracks"].size()==2&&find(c,l)["parent"]=="root","one delayed Undo removes Folder and restores membership");c.redo();settle();check(find(c,l)["parent"]==folder,"Redo restores Folder and member IDs");
    run(Json::array({op("track.collapsed",{{"track",folder},{"enabled",true}})}));check(find(c,l)["edit_hidden"]&&find(c,folder)["collapsed"],"collapse fact hides descendants only in Edit");c.undo();check(!find(c,l)["edit_hidden"].get<bool>(),"collapse Undo restores visibility");
    auto vcaPlan=run(Json::array({op("track.create",{{"name","Vocal VCA"},{"type","vca"},{"ref","$vca"}}),op("track.parent",{{"track",folder},{"parent","$vca"}}),op("track.gain",{{"track","$vca"},{"db",-6}})}));std::string vca;{auto q=c.query();for(auto& t:q["tracks"])if(t["type"]=="vca")vca=t["id"];}
    check(find(c,l)["depth"]==2&&find(c,vca).contains("vca"),"actual SDK VCA controls nested descendant");measure("VCA minus6 attenuates descendant without changing unrelated track",a*six,b);check(find(c,l)["gain_db"]==original["gain_db"]&&find(c,l)["output"]==original["output"],"VCA leaves member own parameter and routing unchanged");
    c.undo(vcaPlan["plan_id"]);measure("VCA compound Undo restores gain and group",a,b);c.redo();measure("VCA compound Redo restores actual DSP",a*six,b);
    run(Json::array({op("track.mute",{{"track",vca},{"enabled",true}})}));measure("VCA group Mute silences descendants",0,b);c.undo();
    run(Json::array({op("track.solo",{{"track",vca},{"enabled",true}})}));measure("VCA group Solo excludes unrelated track",a*six,0);run(Json::array({op("track.solo_safe",{{"track",r},{"enabled",true}})}));measure("unrelated Solo Safe remains audible",a*six,b);c.undo();c.undo();
    run(Json::array({op("track.create",{{"name","Outer VCA"},{"type","vca"},{"ref","$outer"}}),op("track.parent",{{"track",vca},{"parent","$outer"}}),op("track.gain",{{"track","$outer"},{"db",-6}})}));std::string outer;{auto q=c.query();for(auto& t:q["tracks"])if(t["name"]=="Outer VCA")outer=t["id"];}
    // SDK law: p(dB)=exp((dB-6)/20); VCA offsets p(member), not dB.
    const double nestedDb=20*std::log(2*std::exp(-12./20.)-std::exp(-6./20.))+6;
    measure("nested VCA follows declared SDK fader law",a*std::pow(10.,nestedDb/20.),b);check(find(c,l)["depth"]==3,"nested parent depth comes from Edit");
    auto saved=dir.getChildFile("group.tracktionedit");c.save(saved);{Commands reopened(false);reopened.open(saved);check(reopened.query()["tracks"]==c.query()["tracks"],"group VCA flags IDs and member order survive reopen");auto wav=dir.getChildFile("restored.wav");reopened.render(wav,0,96000);auto actual=rms(wav);check(std::abs(actual[0]-a*std::pow(10.,nestedDb/20.))<3e-6&&std::abs(actual[1]-b)<3e-6,"reopened VCA audio agrees numerically");}
    run(Json::array({op("track.parent",{{"track",l},{"parent","root"}})}));measure("detaching restores member signal and preserves output",a,b);c.undo();settle();check(find(c,l)["parent"]==folder,"detach Undo restores exact parent");
    auto good=c.query();auto reject=[&](Json bad,const char* why){fails([&]{c.makePlan("human",Json::array({op("track.rename",{{"track",l},{"name","must not happen"}}),bad}));},why);check(c.query()==good,"rejected Plan has no partial Edit writes");};
    reject(op("track.rename",{{"track",l},{"name",std::string(65,'x')}}),"SDK name truncation is rejected before write");reject(op("track.rename",{{"track",l},{"name",std::string("x\0y",3)}}),"embedded NUL name rejected");reject(op("track.parent",{{"track",outer},{"parent",folder}}),"ancestor cycle is rejected");reject(op("track.parent",{{"track",folder},{"parent",folder}}),"self parent is rejected");reject(op("track.parent",{{"track",l},{"parent",r}}),"audio track cannot be a group parent");reject(op("track.parent",{{"track","missing"},{"parent",folder}}),"missing member rejected");reject(op("track.gain",{{"track",folder},{"db",-6}}),"Folder fake gain rejected");reject(op("track.output",{{"track",vca},{"target",r}}),"VCA fake audio route rejected");reject(op("clip.import",{{"track",folder},{"path",left.getFullPathName().toStdString()},{"position_samples",0}}),"Folder audio clip rejected");reject(op("plugin.insert",{{"track",vca},{"type","reverb"}}),"VCA audio effect insertion rejected");
    auto stale=c.makePlan("agent:old",Json::array({op("track.parent",{{"track",l},{"parent","root"}})}));run(Json::array({op("track.rename",{{"track",folder},{"name","Renamed folder"}})}));fails([&]{c.commit(stale,true);},"human group edit invalidates agent plan");check(c.commit(vcaPlan)["replayed"],"retried VCA Plan is idempotent");check(Commands::mediaHash(left)==hash,"source PCM hash preserved");
    {Commands s(false);s.commit(s.makePlan("human",Json::array({op("track.create",{{"name","Send source"},{"ref","$source"}}),op("clip.import",{{"track","$source"},{"path",left.getFullPathName().toStdString()},{"position_samples",0}}),op("track.create",{{"name","Return"},{"type","aux"},{"ref","$aux"}}),op("track.create",{{"name","Send VCA"},{"type","vca"},{"ref","$vca"}}),op("track.parent",{{"track","$source"},{"parent","$vca"}}),op("track.gain",{{"track","$source"},{"db",-6}}),op("track.gain",{{"track","$vca"},{"db",-6}}),op("track.output",{{"track","$source"},{"target","none"}}),op("send.create",{{"track","$source"},{"target","$aux"},{"db",0},{"position","pre"}})})));settle();
        auto q=s.query();std::string sourceID;for(auto& t:q["tracks"])if(t["name"]=="Send source")sourceID=t["id"];auto sendID=find(s,sourceID)["sends"][0]["id"];
        auto preFile=dir.getChildFile("vca-pre.wav");auto pre=s.render(preFile,0,96000);auto preRms=rms(preFile);check(std::abs(preRms[0]-a)<3e-6&&preRms[1]<3e-6,"Pre send stays before member and VCA fader");
        s.commit(s.makePlan("human",Json::array({op("send.position",{{"send",sendID},{"position","post"}})})));settle();auto postFile=dir.getChildFile("vca-post.wav");auto post=s.render(postFile,0,96000);auto postRms=rms(postFile);check(std::abs(postRms[0]-a*std::pow(10.,nestedDb/20.))<3e-6&&postRms[1]<3e-6,"Post send follows actual member and VCA gain");
        s.undo();settle();auto undoFile=dir.getChildFile("vca-pre-undo.wav");s.render(undoFile,0,96000);check(std::abs(rms(undoFile)[0]-a)<3e-6,"send position Undo restores VCA-independent Pre signal");
        renders.push_back({{"case","VCA pre/post"},{"pre_rms",preRms},{"post_rms",postRms},{"pre",pre},{"post",post}});
    }
    Json summary={{"result","passed"},{"checks",checks},{"nested_vca_effective_db",nestedDb},{"renders",renders},{"scope","real Tracktion Folder/VCA and renderer; no model or hardware claim"}};if(argc>1){std::ofstream out(argv[1]);out<<summary.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<summary.dump(2)<<"\n";dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
