#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<"\n";}
juce::Component* visible(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* child:p.getChildren())if(auto* r=visible(*child,id))return r;return nullptr;}
void settle(){juce::MessageManager::getInstance()->runDispatchLoopUntil(80);}
void click(juce::Component& p,const juce::String& id){auto* b=dynamic_cast<juce::Button*>(visible(p,id));if(!b||!b->isEnabled())throw std::runtime_error("missing enabled button: "+id.toStdString());b->triggerClick();settle();}
juce::ComboBox& combo(juce::Component& p,const juce::String& id){auto* b=dynamic_cast<juce::ComboBox*>(visible(p,id));if(!b||!b->isEnabled())throw std::runtime_error("missing enabled chooser: "+id.toStdString());return *b;}
void choose(juce::Component& p,const juce::String& id,const juce::String& name){auto& c=combo(p,id);for(int i=0;i<c.getNumItems();++i)if(c.getItemText(i)==name){c.setSelectedId(c.getItemId(i),juce::sendNotificationSync);settle();return;}throw std::runtime_error("choice absent: "+name.toStdString());}
Json track(ndaw::desktop::Workspace& w,const std::string& id){auto q=w.query();for(const auto& t:q["tracks"])if(t["id"]==id)return t;throw std::runtime_error("track absent");}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    ndaw::desktop::Workspace w(false);w.setVisible(true);w.setSize(1120,700);auto& types=combo(w,"track.type");check(types.getNumItems()==6,"GUI exposes all six implemented SDK track roles");
    click(w,"track.create");std::string audio=w.query()["tracks"][0]["id"];auto original=track(w,audio);
    types.setSelectedId(5,juce::dontSendNotification);click(w,"track.create");std::string folder=w.query()["tracks"].back()["id"];check(track(w,folder)["type"]=="folder"&&visible(w,"group.parent"),"new Folder selects working grouping inspector");
    check(!visible(w,"track.gain:"+juce::String(folder)),"Folder has no fake gain control");choose(w,"group.candidate",juce::String(original["name"].get<std::string>()));click(w,"group.add");check(track(w,audio)["parent"]==folder&&w.query()["revision"]==3,"member add writes one real parent transaction");check(track(w,audio)["output"]==original["output"]&&track(w,audio)["gain_db"]==original["gain_db"],"GUI membership preserves member output and own gain");
    click(w,"track.fold:"+juce::String(folder));check(track(w,audio)["edit_hidden"]&&!visible(w,"track.select:"+juce::String(audio)),"Edit fold hides actual descendants");click(w,"view.mix");check(visible(w,"track.select:"+juce::String(audio))!=nullptr,"Mix retains members when Edit Folder collapsed");click(w,"history.undo");click(w,"view.edit");check(visible(w,"track.select:"+juce::String(audio))!=nullptr,"fold Undo restores Edit member");
    types.setSelectedId(6,juce::dontSendNotification);click(w,"track.create");std::string vca=w.query()["tracks"].back()["id"];choose(w,"group.candidate",juce::String(track(w,folder)["name"].get<std::string>()));click(w,"group.add");check(track(w,folder)["parent"]==vca&&track(w,audio)["depth"]==2,"GUI creates native hierarchical VCA membership");
    auto* gain=dynamic_cast<juce::Slider*>(visible(w,"track.gain:"+juce::String(vca)));check(gain&&gain->isEnabled(),"VCA exposes actual SDK gain control");gain->setValue(-6,juce::sendNotificationSync);settle();check(std::abs(track(w,vca)["gain_db"].get<double>()+6)<.01&&track(w,audio)["gain_db"]==original["gain_db"],"VCA gesture changes only real VCA parameter");click(w,"history.undo");check(std::abs(track(w,vca)["gain_db"].get<double>())<.01,"VCA gain Undo restores parameter");click(w,"history.redo");
    click(w,"track.select:"+juce::String(audio));check(dynamic_cast<juce::TextEditor*>(visible(w,"group.name"))->getText().toStdString()==original["name"].get<std::string>(),"inspector name follows target even after focus changes");choose(w,"group.parent",ndaw::desktop::text("Root · 顶层"));check(track(w,audio)["parent"]=="root","parent chooser detaches actual track");click(w,"history.undo");check(track(w,audio)["parent"]==folder,"parent chooser Undo restores membership");
    click(w,"track.select:"+juce::String(vca));auto& parents=combo(w,"group.parent");check(parents.getNumItems()==1,"GUI excludes self and descendant group parents");click(w,"group.remove");check(track(w,folder)["parent"]=="root"&&track(w,audio)["parent"]==folder,"member remove moves group with children intact");click(w,"history.undo");
    auto* name=dynamic_cast<juce::TextEditor*>(visible(w,"group.name"));name->setText("Vocal VCA",false);juce::MessageManager::getInstance()->runDispatchLoopUntil(450);check(name->getText()=="Vocal VCA","timer preserves unsaved same-target name before rename");click(w,"track.rename");check(track(w,vca)["name"]=="Vocal VCA","GUI rename writes actual SDK name");click(w,"history.undo");check(track(w,vca)["name"]!="Vocal VCA","rename Undo restores name");
    click(w,"inspector.routing");auto* output=visible(w,"routing.output");auto* add=visible(w,"send.create");check(output&&!output->isEnabled()&&add&&!add->isEnabled(),"VCA does not expose false audio routing");click(w,"inspector.inserts");auto* insert=visible(w,"plugin.insert");check(insert&&!insert->isEnabled(),"VCA cannot pretend to host audio inserts");
    click(w,"track.select:"+juce::String(audio));click(w,"inspector.routing");auto& destinations=combo(w,"routing.output");check(destinations.getNumItems()==2,"audio output chooser excludes organisational groups");
    w.setSize(1600,1000);click(w,"inspector.group");check(visible(w,"group.parent")&&visible(w,"view.mix"),"group inspector works at both supported test sizes");
    Json result={{"result","passed"},{"checks",checks},{"scope","production JUCE GUI controls and real Edit, devices closed; audio VCA qualified separately"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<result.dump(2)<<"\n";return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
