#include "Workspace.h"
#include "LegacyFixture.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;void check(bool b,const char* s){if(!b)throw std::runtime_error(s);++checks;std::cout<<"PASS "<<s<<std::endl;}
void settle(){juce::MessageManager::getInstance()->runDispatchLoopUntil(80);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* c:p.getChildren())if(auto* found=find(*c,id))return found;return nullptr;}
void click(juce::Component& p,const char* id){auto* b=dynamic_cast<juce::Button*>(find(p,id));if(!b||!b->isEnabled())throw std::runtime_error("button unavailable");b->triggerClick();settle();}
Json normalise(Json tracks){std::map<std::string,std::string> names;for(const auto& t:tracks)names[t["id"]]=t["name"];for(auto& t:tracks){t.erase("id");if(names.contains(t["output"]["target"]))t["output"]["target"]=names.at(t["output"]["target"]);for(auto& c:t["clips"])c.erase("id");}return tracks;}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-legacy-ui-"+juce::Uuid().toString());dir.createDirectory();auto audio=legacyFixture::audio(dir);auto hash=Commands::mediaHash(audio);auto initial=legacyFixture::session(audio);initial["tracks"][0]["pan"]=.35;auto file=legacyFixture::write(dir,initial);
    ndaw::desktop::Workspace w(false);w.setVisible(true);w.setSize(1440,1000);auto original=w.query();w.prepareLegacyImport(file);auto* report=dynamic_cast<juce::TextEditor*>(find(w,"legacy.report"));check(report&&report->isReadOnly()&&report->getText().contains(juce::String::fromUTF8("待确认"))&&find(w,"plan.accept"),"native legacy preview shows readable report and acceptance control");check(w.query()==original,"GUI preview never creates tracks before acceptance");click(w,"plan.reject");check(w.query()==original&&!find(w,"legacy.report"),"GUI reject leaves actual Edit unchanged");
    w.openSession(file);check(find(w,"plan.accept")&&w.query()==original,"opening .ndaw uses import preview rather than replacing Edit");click(w,"plan.accept");auto after=w.query()["tracks"];check(after.size()==2&&w.queryLegacyReports().size()==1&&after[0]["clips"][0]["length_samples"]==48000,"GUI acceptance commits real imported native tracks and clips");check(find(w,"legacy.report")&&!find(w,"plan.accept"),"committed report remains viewable without a misleading second accept");click(w,"plan.reject");check(!find(w,"legacy.report")&&w.query()["tracks"]==after,"closing committed report restores Inspector without modifying Edit");
    Commands c(false);auto p=legacyFixture::plan(c,file,"agent:gui-equivalence");c.commit(p,true);check(normalise(after)==normalise(c.query()["tracks"]),"GUI and accepted structured Agent import produce same actual Edit facts");
    check(std::abs(after[0]["base_gain_db"].get<double>()+6)<1e-5&&std::abs(after[0]["base_pan"].get<double>()-.35)<1e-7,"GUI import uses real negative gain and non-centre panner");
    for(int cycle=0;cycle<3;++cycle){
        juce::MessageManager::getInstance()->runDispatchLoopUntil(380);click(w,"history.undo");check(w.query()["tracks"].empty()&&w.queryLegacyReports().empty(),"GUI one Undo removes whole legacy import");click(w,"history.redo");settle();auto redone=w.query();if(redone["tracks"]!=after)std::cerr<<"REDO DIFF "<<Json::diff(after,redone["tracks"]).dump(2)<<std::endl;check(redone["tracks"]==after&&w.queryLegacyReports().size()==1,"repeated delayed GUI Redo restores identical IDs gain pan routing and preservation report");
    }
    auto saved=dir.getChildFile("reopened.tracktionedit");c.save(saved);w.openSession(saved);w.menuItemSelected(12,0);settle();check(w.queryLegacyReports()==c.legacyReports()&&find(w,"legacy.report"),"saved import report can be reopened from File menu");
    auto before=w.query();w.prepareLegacyImport(file);auto changed=legacyFixture::session(audio);changed["name"]="changed since preview";legacyFixture::write(dir,changed);click(w,"plan.accept");check(w.query()==before,"stale native import preview cannot overwrite current Edit");click(w,"plan.reject");
    changed=legacyFixture::session(audio);changed["sources"][0]["path"]="media/missing.wav";file=legacyFixture::write(dir,changed);w.prepareImport(file);report=dynamic_cast<juce::TextEditor*>(find(w,"legacy.report"));check(report&&report->getText().contains("missing")&&w.query()==before,"drag/import path exposes unavailable source before any commit");click(w,"plan.accept");check(w.query()["tracks"].size()==4&&!w.query()["tracks"][2]["clips"][0]["legacy_media_available"].get<bool>(),"GUI merges missing-media clip while preserving existing tracks");click(w,"history.undo");check(w.query()["tracks"]==before["tracks"],"merge Undo preserves previously opened tracks");
    check(Commands::mediaHash(audio)==hash,"native GUI import never alters original audio");Json result={{"result","passed"},{"checks",checks},{"scope","production JUCE preview/accept/reject/report/Undo/Redo/open and same L1 structured Agent; not an LLM invocation"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);}std::cout<<result.dump(2)<<std::endl;dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
