#include "LegacyFixture.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;Json renders=Json::array();
void check(bool b,const char* s){if(!b)throw std::runtime_error(s);++checks;std::cout<<"PASS "<<s<<std::endl;}
template<class F>void fails(F f,const char* s){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,s);}
Json tracks(Commands& c){return c.query()["tracks"];}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-legacy-"+juce::Uuid().toString());dir.createDirectory();auto media=legacyFixture::audio(dir);auto originalHash=Commands::mediaHash(media);
    for(int version=1;version<=7;++version){Commands c(false);auto j=legacyFixture::session(media,version);auto file=legacyFixture::write(dir,j);auto before=c.query();auto p=legacyFixture::plan(c,file,"agent:legacy-test");auto preview=c.preview(p)["legacy_imports"][0];
        check(c.query()==before&&preview["legacy_schema"]==version&&preview["dependencies"][0]["status"]=="verified","schema preview validates checksum/source without writing Edit");fails([&]{c.commit(p);},"Agent legacy import requires acceptance");auto receipt=c.commit(p,true);auto after=tracks(c);auto reports=c.legacyReports();
        check(after.size()==2&&after[0]["clips"].size()==1&&std::abs(after[0]["gain_db"].get<double>()+6)<1e-5&&after[0]["clips"][0]["source_offset_samples"]==12000&&after[0]["clips"][0]["start_samples"]==24000&&after[0]["clips"][0]["length_samples"]==48000,"schemas 1–7 create real clip mapping and fader");
        check(after[0]["output"]["target"]==after[1]["id"]&&after[1]["output"]["target"]=="master"&&!after[0]["input"]["armed"].get<bool>(),"imported output uses isolated Aux; recording stays disarmed");
        check(c.commit(p,true)["replayed"]&&tracks(c)==after,"retry cannot duplicate imported tracks");juce::MessageManager::getInstance()->runDispatchLoopUntil(380);c.undo(receipt["plan_id"]);check(tracks(c).empty()&&c.legacyReports().empty(),"one delayed Undo removes entire import and preservation metadata");c.redo();check(tracks(c)==after&&c.legacyReports()==reports,"Redo retains actual IDs faders routing and report");
        if(version==7){auto wav=dir.getChildFile("render.wav");auto r=c.render(wav,0,96000);renders.push_back(r);juce::AudioFormatManager f;f.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(f.createReaderFor(wav));juce::AudioBuffer<float> pcm(2,96000);reader->read(&pcm,0,96000,0,true,true);double error=0;for(int n=30000;n<65000;++n){error=std::max(error,std::abs(pcm.getSample(0,n)-.1*std::pow(10.,-12./20)));error=std::max(error,std::abs(pcm.getSample(1,n)-.05*std::pow(10.,-12./20)));}
            check(error<=2e-6&&pcm.getMagnitude(0,0,24000)<=2e-6&&r["frames"]==96000&&r["render_ms"].get<double>()<=10000,"real PCM passes gain/source/routing 2e-6 and exact length/10s budgets");auto saved=dir.getChildFile("saved.tracktionedit");c.save(saved);c.open(saved);check(tracks(c)==after&&c.legacyReports()==reports,"native save/reopen preserves actual Edit and legacy report");auto xml=juce::XmlDocument::parse(saved);auto metadata=juce::ValueTree::fromXml(*xml).getChildWithName("NATIVEDAW").getChildWithName("LEGACYIMPORT");check(Json::parse(metadata["original_envelope"].toString().toStdString())["session"]==j,"all original fields including untrusted text retained as data");}
    }
    {Commands c(false);auto m=legacyFixture::audio(dir,44100);auto j=legacyFixture::session(m,7,44100);auto f=legacyFixture::write(dir,j);c.commit(legacyFixture::plan(c,f));auto clip=tracks(c)[0]["clips"][0];check(clip["start_samples"]==24000&&clip["length_samples"]==48000&&clip["source_offset_samples"]==12000&&clip["source_sample_rate"]==44100,"44.1 kHz source offsets remain seconds on 48 kHz timeline");auto r=c.render(dir.getChildFile("src.wav"),0,96000);check(r["frames"]==96000&&r["true_peak_dbtp"].get<double>()<-25,"native SRC renders actual imported range");renders.push_back(r);}
    {Commands c(false);auto j=legacyFixture::session(media);auto alt=j["tracks"][0]["playlists"][0];alt["id"]="alternate";alt["clips"][0]["id"]="alternate-clip";alt["role"]="alternate";j["tracks"][0]["playlists"].push_back(alt);j["custom_state"]={{"selection",123},{"notes","data only"}};auto f=legacyFixture::write(dir,j);c.commit(legacyFixture::plan(c,f));auto r=c.legacyReports()[0];check(tracks(c)[0]["clips"].size()==1&&std::any_of(r["unmapped"].begin(),r["unmapped"].end(),[](const auto& row){return row["field"]=="/tracks/0/playlists/1/clips/0/id";}),"inactive Playlist is explicitly reported and preserved, not played");check(std::any_of(r["unmapped"].begin(),r["unmapped"].end(),[](const auto& row){return row["field"]=="/custom_state/selection";}),"unknown fields are listed individually");}
    {Commands c(false);auto j=legacyFixture::session(media);j["sources"][0]["path"]="media/missing.wav";auto f=legacyFixture::write(dir,j);c.commit(legacyFixture::plan(c,f));auto q=tracks(c)[0]["clips"][0];check(q["length_samples"]==48000&&!q["legacy_media_available"].get<bool>()&&c.legacyReports()[0]["dependencies"][0]["status"]=="missing","missing media retains real clip ID length and original reference");auto saved=dir.getChildFile("missing.tracktionedit");c.save(saved);c.open(saved);check(tracks(c)[0]["clips"][0]==q,"missing-media native clip survives reopen");}
    {Commands c(false);auto j=legacyFixture::session(media);j["sources"][0]["sha256"]=std::string(64,'a');auto f=legacyFixture::write(dir,j);c.commit(legacyFixture::plan(c,f));check(!tracks(c)[0]["clips"][0]["legacy_media_available"].get<bool>()&&c.legacyReports()[0]["dependencies"][0]["status"]=="hash_mismatch","changed source never plays as expected media");}
    {Commands c(false);auto j=legacyFixture::session(media);auto state=dir.getChildFile("state.bin");state.replaceWithText("opaque real bytes");j["tracks"][0]["processors"]=Json::array({{{"id","plugin"},{"kind","plugin"},{"description","not executable"},{"parameters",Json::array({{{"id","parameter"},{"value",.5}}})},{"state",{{"path","state.bin"},{"sha256",Commands::mediaHash(state)},{"bytes",state.getSize()}}}}});auto f=legacyFixture::write(dir,j);auto p=legacyFixture::plan(c,f);check(c.preview(p)["legacy_imports"][0]["muted_for_incomplete_mapping"]==1,"preview explains automatic mute for unrestored plugin");c.commit(p);check(tracks(c)[0]["mute"]&&tracks(c)[0]["legacy_chain_unavailable"]&&tracks(c)[0]["plugins"].empty(),"missing plugin is never presented as instantiated success");auto saved=dir.getChildFile("plugin.tracktionedit");c.save(saved);auto xml=juce::XmlDocument::parse(saved);auto meta=juce::ValueTree::fromXml(*xml).getChildWithName("NATIVEDAW").getChildWithName("LEGACYIMPORT");auto blob=Json::parse(meta["plugin_state_base64"].toString().toStdString());juce::MemoryOutputStream bytes;juce::Base64::convertFromBase64(bytes,juce::String(blob["plugin"].get<std::string>()));check(bytes.toUTF8()=="opaque real bytes","verified opaque plugin bytes persist without loading plugin");}
    {Commands c(false);auto j=legacyFixture::session(media);auto file=legacyFixture::write(dir,j);auto p=legacyFixture::plan(c,file);auto before=c.query();j["name"]="changed";legacyFixture::write(dir,j);fails([&]{c.commit(p);},"changed document rejects stale Plan");check(c.query()==before,"failed legacy preflight leaves Edit and revision unchanged");p=legacyFixture::plan(c,file);media.appendText("altered");fails([&]{c.commit(p);},"media changes between preview and commit reject atomically");media=legacyFixture::audio(dir);check(Commands::mediaHash(media)==originalHash,"test restores original fixture content");}
    {Commands c(false);auto j=legacyFixture::session(media);auto f=legacyFixture::write(dir,j);auto document=Json::parse(f.loadFileAsString().toStdString());document["session"]["name"]="bad checksum";f.replaceWithText(juce::String(document.dump()));fails([&]{legacyFixture::plan(c,f);},"corrupt checksum rejected");j["tracks"][0]["playlists"][0]["clips"][0]["id"]="vocal";f=legacyFixture::write(dir,j);fails([&]{legacyFixture::plan(c,f);},"duplicate stable ID rejected");j=legacyFixture::session(media);j["sources"][0]["path"]="../source.wav";f=legacyFixture::write(dir,j);fails([&]{legacyFixture::plan(c,f);},"dependency path traversal rejected");j=legacyFixture::session(media);j["tracks"][0]["playlists"][0]["clips"][0]["length"]=999999999;f=legacyFixture::write(dir,j);fails([&]{legacyFixture::plan(c,f);},"invalid source mapping rejected before creation");check(tracks(c).empty(),"invalid imports never create partial tracks");}
    {Commands c(false);auto j=legacyFixture::session(media);auto aux=j["tracks"][0];aux["id"]="aux";aux["name"]="Vocal Aux";aux["kind"]="aux";aux["input_bus_id"]="aux-bus";aux["playlists"]=Json::array();aux["active_playlist_id"]=nullptr;aux["target_playlist_id"]=nullptr;aux["record_armed"]=false;aux["monitor_mode"]="off";aux["input_channels"]=Json::array();aux["output"]["id"]="aux-output";aux["gain_db"]=-6;
        auto master=aux;master["id"]="master";master["name"]="Legacy Master";master["kind"]="master";master["input_bus_id"]="main";master["output"]=nullptr;master["gain_db"]=-3;
        j["tracks"][0]["output"]["target_bus_id"]="aux-bus";j["tracks"][0]["sends"]=Json::array({{{"id","send"},{"target_bus_id","aux-bus"},{"gain_db",-6},{"pan",0},{"muted",false},{"pre_fader",true}}});j["tracks"].push_back(aux);j["tracks"].push_back(master);j["buses"][0]["owner_track_id"]="master";j["buses"].push_back({{"id","aux-bus"},{"name","Vocal"},{"channels",2},{"role","aux"},{"owner_track_id","aux"}});
        auto file=legacyFixture::write(dir,j);auto p=legacyFixture::plan(c,file);auto pre=c.preview(p)["legacy_imports"][0];check(std::none_of(pre["unmapped"].begin(),pre["unmapped"].end(),[](const auto& row){return row["field"].template get<std::string>().starts_with("/tracks/0/sends/0/");}),"mapped neutral Send fields are not misreported as missing");auto receipt=c.commit(p);auto after=tracks(c);check(after.size()==3&&after[0]["output"]["target"]==after[1]["id"]&&after[1]["output"]["target"]==after[2]["id"]&&after[2]["output"]["target"]=="master","old Aux/Main ownership becomes actual isolated native routing");check(after[0]["sends"].size()==1&&after[0]["sends"][0]["position"]=="pre","old pre-fader send becomes real native Send instance");
        auto r=c.render(dir.getChildFile("routes.wav"),0,96000);renders.push_back(r);double expected=.1*std::pow(10.,-6./20)* (std::pow(10.,-6./20)+std::pow(10.,-6./20))*std::pow(10.,-6./20)*std::pow(10.,-3./20);check(std::abs(r["peak"].get<double>()-expected)<=2e-6,"actual Aux plus pre-send plus imported Master PCM matches fixed gain budget");c.undo(receipt["plan_id"]);check(tracks(c).empty(),"route-rich import Undo removes all native destinations");c.redo();check(tracks(c)==after,"route-rich Redo restores flags faders and Sends");auto saved=dir.getChildFile("routes.tracktionedit");c.save(saved);c.open(saved);check(tracks(c)==after,"route-rich import survives native save/reopen");
        j["tracks"][1]["output"]["target_bus_id"]="aux-bus";file=legacyFixture::write(dir,j);auto before=tracks(c);fails([&]{legacyFixture::plan(c,file);},"legacy route cycle rejected in preflight");check(tracks(c)==before,"route-cycle failure preserves current native Edit");}
    check(Commands::mediaHash(media)==originalHash,"all production imports preserve original media hash");Json result={{"result","passed"},{"checks",checks},{"renders",renders},{"scope","schemas 1–7 production importer, native Edit/Undo/save/PCM; preserved unsupported fields are not implemented workflows"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);}std::cout<<result.dump(2)<<std::endl;dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
