#include "LoudnessFixture.h"
#include <nativedaw/v2/LoudnessCurve.h>
#include <nativedaw/v2/McpSession.h>
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;namespace fx=loudness_fixture;
namespace {
int checks=0;double maxJob=0;Json evidence=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
void pump(int ms=10){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json op(const char* name,Json args){return {{"command",name},{"args",args}};}
void commit(Commands& c,Json ops){c.commit(c.makePlan("human",ops));}
Json wait(Commands& c){const auto began=juce::Time::getMillisecondCounterHiRes();while(c.analysisStatus()["busy"].get<bool>()){if(juce::Time::getMillisecondCounterHiRes()-began>12000)throw std::runtime_error("curve job exceeds fixed12 seconds");pump();}maxJob=std::max(maxJob,juce::Time::getMillisecondCounterHiRes()-began);auto state=c.analysisStatus();if(state["state"]!="completed")throw std::runtime_error(state.dump());return state["receipt"];}
Json args(Commands& c,const char* key){return {{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]},{"start_samples",13},{"end_samples",384077},{"request_key",key}};}
Json rpc(McpSession& session,const char* method,Json params){static int serial=0;const int id=++serial;std::vector<Json> out;std::thread t([&]{out=session.receive(Json{{"jsonrpc","2.0"},{"id",id},{"method",method},{"params",params}}.dump());});t.join();const auto began=juce::Time::getMillisecondCounterHiRes();while(out.empty()){if(juce::Time::getMillisecondCounterHiRes()-began>5000)throw std::runtime_error("curve MCP exceeds5 seconds");pump();std::thread p([&]{out=session.ready();});p.join();}return out[0];}
void numerical(const juce::File& folder){
    for(int rate:{44100,48000,96000}){
        const auto pcm=fx::pcm(rate);const auto file=folder.getChildFile(juce::String(rate)+".wav");fx::write(file,pcm,rate);const int begin=13,end=pcm.getNumSamples()-9;const int64_t origin=34567;auto r=analysis::measure(file,origin,{}, {begin,end},nullptr,analysis::FeatureDomain::SessionSamples);const auto& curve=r["loudness_curve"];
        check(fx::matches(curve["points"],fx::reference(pcm,rate,begin,end)),"all M/S points agree with independently chunked pinned libebur128 within1e-6 LU at44.1/48/96k");
        check(curve["points"].size()==77&&curve["point_count"]==77&&curve["trailing_frames"]==(end-begin)%((rate+5)/10),"complete hop grid and partial tail accounting retain every point");
        bool positions=true;for(size_t i=0;i<curve["points"].size();++i){auto p=analysis::loudnessPoint(curve,int64_t(i),"momentary");const auto frame=curve["points"][i][0].get<int64_t>();positions&=p["start_samples"].get<int64_t>()==origin+std::llround((frame-4*((rate+5)/10))*48000./rate)&&p["end_samples"].get<int64_t>()==origin+std::llround(frame*48000./rate)&&p["location_samples"].get<int64_t>()==origin+std::llround((frame-1)*48000./rate);}
        check(positions,"every full window converts exact actual rate and nonzero engineering origin, locating inside exclusive end");
        auto raw=analysis::measure(file,0,{}, {begin,end});const auto first=analysis::loudnessPoint(raw["loudness_curve"],0,"momentary");check(first["source_start_frame"]==begin&&first["source_end_frame"]==begin+4*((rate+5)/10)&&!first.contains("start_samples"),"raw curves retain native file frames without engineering coordinates");
        check(analysis::loudnessPoint(curve,0,"short_term")["status"]=="insufficient_window"&&analysis::loudnessPoint(curve,26,"short_term")["status"]=="measured","short term appears only at a full actual3 second window");
        fails([&]{analysis::loudnessPoint(curve,-1,"momentary");},"negative curve ID rejected");fails([&]{analysis::loudnessPoint(curve,77,"momentary");},"out of range curve ID rejected");fails([&]{analysis::loudnessPoint(curve,0,"imagined");},"nonexistent series rejected");
        evidence.push_back({{"rate",rate},{"curve_points",curve["point_count"]},{"curve_bytes",curve.dump().size()}});
    }
    juce::AudioBuffer<float> zero(1,48000*4);zero.clear();const auto silent=folder.getChildFile("silence.wav");fx::write(silent,zero,48000);auto r=analysis::measure(silent,0);check(analysis::loudnessPoint(r["loudness_curve"],0,"momentary")["status"]=="negative_infinity"&&analysis::loudnessPoint(r["loudness_curve"],26,"short_term")["status"]=="negative_infinity","full silent windows report negative infinity separately from missing measurements");r=analysis::measure(silent,0,{}, {0,19199});check(r["loudness_curve"]["points"].empty()&&r["lufs_m_max"].is_null(),"under400ms never fabricates a loudness curve");
    juce::AudioBuffer<float> longPcm(2,8000*300);longPcm.clear();for(int n=0;n<longPcm.getNumSamples();++n)if(n%16000<800)for(int ch=0;ch<2;++ch)longPcm.setSample(ch,n,float(1.1*std::sin(2*juce::MathConstants<double>::pi*1000*n/8000.)));
    const auto longFile=folder.getChildFile("300seconds.wav");fx::write(longFile,longPcm,8000);r=analysis::measure(longFile,123,{}, {},Json::object(),analysis::FeatureDomain::SessionSamples);check(r["loudness_curve"]["points"].size()==2997&&r["loudness_curve"].dump().size()<=192*1024&&r.dump().size()<=252*1024&&r["events"].size()==128&&r["events_omitted"].get<int>()>0,"full300 second grid and dense event families fit unchanged byte budgets without losing curve points");check(fx::matches(r["loudness_curve"]["points"],fx::reference(longPcm,8000,0,longPcm.getNumSamples())),"all2997 long range points have independent library agreement");evidence.push_back({{"long_curve_points",2997},{"curve_bytes",r["loudness_curve"].dump().size()},{"receipt_bytes",r.dump().size()}});
    analysis::Control stop;stop.cancelled=[] {return true;};fails([&]{analysis::measure(longFile,0,stop);},"loudness decode obeys actual cancellation");
}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-loudness-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();numerical(folder);const auto pcm=fx::pcm(48000);const auto file=folder.getChildFile("actual-levels.wav");fx::write(file,pcm,48000);const auto hash=Commands::mediaHash(file);Commands c(false);commit(c,Json::array({op("track.create",{{"name","Level changes"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",file.getFullPathName().toStdString()},{"position_samples",0}}),op("track.gain",{{"track","$t"},{"db",-6}})}));auto facts=c.query();const std::string track=facts["tracks"][0]["id"],clip=facts["tracks"][0]["clips"][0]["id"];
    c.analysisControl("master",args(c,"master"));auto master=wait(c);check(master["current"].get<bool>()&&fx::matches(master["loudness_curve"]["points"],fx::reference(pcm,48000,13,384077,juce::Decibels::decibelsToGain(-6.f))),"actual Master graph series agrees with known PCM and actual fader");check(c.query()["tracks"]==facts["tracks"]&&c.query()["revision"]==facts["revision"],"curves do not create Edit mutations or Undo entries");
    auto locate=[&](const Json& r,int index,const char* series){return c.analysisControl("locate_loudness",{{"artifact_id",r["artifact_id"]},{"point_index",index},{"series",series}});};auto found=locate(master,30,"short_term");check(c.query()["position_samples"]==13+34*4800-1&&found["point"]["start_samples"]==13+4*4800,"local L1 short term location uses actual3 second window and last inside frame");fails([&]{locate(master,0,"short_term");},"incomplete window cannot seek");fails([&]{c.analysisControl("locate_loudness",{{"artifact_id",master["artifact_id"]},{"point_index",0},{"series","momentary"}},"agent:untrusted");},"external clients cannot bypass local transport control");
    auto request=args(c,"pre");request["track"]=track;request["tap_point"]="track_pre_inserts";c.analysisControl("track",request);auto pre=wait(c);check(fx::matches(pre["loudness_curve"]["points"],fx::reference(pcm,48000,13,384077)),"actual pre-insert series excludes fader processing");
    CommandQueue queue(c);Scope read;read.mode=Permission::ReadOnly;McpSession session(queue.connect("agent:curve",read),Commands::registry());rpc(session,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","loudness-tests"},{"version","1"}}}});session.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());auto reply=rpc(session,"tools/call",{{"name","analyze_delivery"},{"arguments",args(c,"mcp-delivery")}});check(!reply["result"]["isError"].get<bool>(),"readonly real MCP delivery accepts curve analysis");auto delivery=wait(c);const auto measured=rpc(session,"tools/call",{{"name","query_analysis"},{"arguments",Json::object()}})["result"]["structuredContent"]["result"]["receipt"];check(measured["loudness_curve"]==delivery["loudness_curve"]&&measured.contains("delivery"),"actual protocol query returns the same curve and delivery criteria as L1");
    commit(c,Json::array({op("track.gain",{{"track",track},{"db",-12}})}));fails([&]{locate(delivery,30,"short_term");},"human mix edit rejects stale curve location");c.undo();check(!c.analysisStatus()["receipt"]["current"].get<bool>()&&std::abs(c.query()["tracks"][0]["gain_db"].get<double>()+6)<1e-5,"Undo restores human fader without reviving obsolete curves");
    auto raw=args(c,"raw");raw.erase("start_samples");raw.erase("end_samples");raw["clip"]=clip;raw["source_start_frame"]=13;raw["source_end_frame"]=384077;c.analysisControl("source",raw);auto source=wait(c);commit(c,Json::array({op("clip.move",{{"clip",clip},{"position_samples",96000}})}));auto location=c.analysisControl("locate_loudness",{{"artifact_id",source["artifact_id"]},{"point_index",30},{"series","short_term"},{"clip_id",clip},{"base_revision",c.query()["revision"]}});check(c.query()["position_samples"]==96000+13+34*4800-1&&location["point"]["source_location_frame"]==13+34*4800-1,"raw window evidence survives move and maps its actual native point to current clip");
    const auto saved=folder.getChildFile("curve.tracktionedit");c.save(saved);c.open(saved);check(c.analysisStatus()["state"]=="idle"&&c.analysisStatus()["receipt"].is_null()&&Commands::mediaHash(file)==hash,"save reopen preserves source and never revives old curve success");const auto elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<120000,"curve backend retains fixed120 second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"max_job_ms",maxJob},{"numerical",evidence},{"master",master},{"pre",pre},{"delivery",delivery},{"scope","actual offline PCM and graph/MCP; production desktop separately qualified"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("curve evidence write failed");}std::cout<<"checks "<<checks<<" elapsed_ms "<<elapsed<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
