#include "Workspace.h"
#include "LoudnessFixture.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;using namespace ndaw::desktop;namespace fx=loudness_fixture;
namespace {
int checks=0;double maxJob=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
void pump(int ms=30){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* child:p.getChildren())if(auto* found=find(*child,id))return found;return nullptr;}
void click(Workspace& w,const juce::String& id){auto* b=dynamic_cast<juce::Button*>(find(w,id));if(!b||!b->isEnabled())throw std::runtime_error("native curve button unavailable: "+id.toStdString());const auto callback=b->onClick;bool delivered=false;b->onClick=[&]{delivered=true;callback();};b->triggerClick();const auto deadline=juce::Time::getMillisecondCounterHiRes()+1000;while(!delivered&&juce::Time::getMillisecondCounterHiRes()<deadline)pump(1);b->onClick=callback;check(delivered,"actual asynchronous native callback delivered");pump();}
juce::TextEditor& field(Workspace& w,const char* id){auto* f=dynamic_cast<juce::TextEditor*>(find(w,id));if(!f)throw std::runtime_error(id);return *f;}
juce::ComboBox& combo(Workspace& w,const char* id){auto* f=dynamic_cast<juce::ComboBox*>(find(w,id));if(!f)throw std::runtime_error(id);return *f;}
juce::Slider& slider(Workspace& w,const juce::String& id){auto* f=dynamic_cast<juce::Slider*>(find(w,id));if(!f)throw std::runtime_error(id.toStdString());return *f;}
Json wait(Workspace& w){const auto began=juce::Time::getMillisecondCounterHiRes();while(w.queryAnalysis().value("busy",false)){if(juce::Time::getMillisecondCounterHiRes()-began>12000)throw std::runtime_error("native curve job exceeds12 seconds");pump(10);}maxJob=std::max(maxJob,juce::Time::getMillisecondCounterHiRes()-began);pump(300);const auto state=w.queryAnalysis();if(state["state"]!="completed")throw std::runtime_error(state.dump());return state["receipt"];}
class Storage final:public te::PropertyStorage{public:explicit Storage(juce::File f):PropertyStorage("Forma curve UI"),folder(f){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-lufs-ui-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();const auto pcm=fx::pcm(48000);const auto source=folder.getChildFile("levels.wav");fx::write(source,pcm,48000);const auto hash=Commands::mediaHash(source);Workspace w(false,std::make_unique<Storage>(folder.getChildFile("prefs")));w.setSize(1280,900);w.setVisible(true);w.prepareImport(source);pump();click(w,"plan.accept");const std::string track=w.query()["tracks"][0]["id"],clip=w.query()["tracks"][0]["clips"][0]["id"];const auto facts=w.query();w.showAnalysis();field(w,"analysis.start_samples").setText("13");field(w,"analysis.end_samples").setText("384077");click(w,"analysis.master.run");const auto master=wait(w);
    check(master["current"].get<bool>()&&fx::matches(master["loudness_curve"]["points"],fx::reference(pcm,48000,13,384077,juce::Decibels::decibelsToGain(-12.f))),"GUI curve is actual rendered Master rather than decorative values");check(find(w,"analysis.loudness_curve")&&field(w,"analysis.summary").getText().contains("连续响度：77 点"),"native scrollable curve and actual grid count are visible");check(w.query()["tracks"]==facts["tracks"]&&w.query()["revision"]==facts["revision"],"native graph inspection adds no Edit or history writes");
    combo(w,"analysis.loudness.series").setSelectedId(2,juce::sendNotificationSync);check(!find(w,"analysis.loudness.locate")->isEnabled()&&dynamic_cast<juce::Label*>(find(w,"analysis.loudness.readout"))->getText().contains("窗口不足"),"short term warmup displays insufficient and disables seek");click(w,"analysis.loudness.max_s");check(find(w,"analysis.loudness.locate")->isEnabled()&&slider(w,"analysis.loudness.point").getValue()>=26,"max S selects a real complete3 second window");click(w,"analysis.loudness.max_m");const auto selected=int64_t(slider(w,"analysis.loudness.point").getValue());const auto expected=analysis::loudnessPoint(master["loudness_curve"],selected,"momentary");double maxM=-INFINITY;for(const auto& row:master["loudness_curve"]["points"])if(row[1].is_number())maxM=std::max(maxM,row[1].get<double>());check(expected["lufs"]==maxM&&combo(w,"analysis.loudness.series").getSelectedId()==1,"max M selects measured highest value with correct series");check(std::abs(master["loudness_curve"]["points"][35][1].get<double>()-master["loudness_curve"]["points"][10][1].get<double>()-20)<.01,"known20dB level change appears in genuine native loudness series");click(w,"analysis.loudness.locate");check(w.query()["position_samples"]==expected["location_samples"]&&!find(w,"analysis.panel"),"native curve action locates actual window end inside analysed range");
    slider(w,"track.gain:"+juce::String(track)).setValue(-18,juce::sendNotificationSync);pump();w.showAnalysis();click(w,"analysis.loudness.max_m");check(!find(w,"analysis.loudness.locate")->isEnabled()&&field(w,"analysis.summary").getText().contains("历史快照"),"human gain disables stale curve location while evidence remains inspectable");click(w,"analysis.close");click(w,"history.undo");check(std::abs(w.query()["tracks"][0]["gain_db"].get<double>()+12)<1e-5&&!w.queryAnalysis()["receipt"]["current"].get<bool>(),"GUI Undo restores human fader and old curve remains stale");
    w.showAnalysis();field(w,"analysis.start_samples").setText("13");field(w,"analysis.end_samples").setText("384077");click(w,"analysis.master.run");const auto fresh=wait(w);check(fresh["artifact_id"]!=master["artifact_id"]&&fresh["loudness_curve"]==master["loudness_curve"]&&fresh["current"].get<bool>(),"remeasurement restores exact current curve with a new receipt");
    combo(w,"analysis.tap").setSelectedId(2,juce::sendNotificationSync);field(w,"analysis.start_samples").setText("13");field(w,"analysis.end_samples").setText("384077");click(w,"analysis.source.run");const auto raw=wait(w);click(w,"analysis.loudness.max_m");const int64_t rawIndex=slider(w,"analysis.loudness.point").getValue();const auto rawPoint=analysis::loudnessPoint(raw["loudness_curve"],rawIndex,"momentary");check(dynamic_cast<juce::Label*>(find(w,"analysis.loudness.readout"))->getText().contains("源帧"),"raw source curve displays native frame window rather than session position");click(w,"analysis.loudness.locate");check(w.query()["position_samples"]==rawPoint["source_location_frame"],"source GUI curve location uses current actual clip mapping");
    click(w,"clip.select:"+juce::String(clip));auto& position=field(w,"clip.position");static_cast<juce::Component*>(&position)->focusGained(juce::Component::focusChangedDirectly);position.setText("96000",true);click(w,"clip.move");w.showAnalysis();click(w,"analysis.loudness.max_m");click(w,"analysis.loudness.locate");check(w.query()["position_samples"]==rawPoint["source_location_frame"].get<int64_t>()+96000&&w.queryAnalysis()["receipt"]["artifact_id"]==raw["artifact_id"],"human move preserves raw evidence and GUI locates current mapped curve point");
    w.showAnalysis();w.setSize(1120,700);auto* graph=find(w,"analysis.loudness_curve");check(graph&&find(w,"analysis.loudness.locate")->getRight()<=graph->getWidth()&&find(w,"analysis.loudness.readout")->getRight()<find(w,"analysis.loudness.locate")->getX(),"minimum native window has scrollable graph without control overlap");check(Commands::mediaHash(source)==hash,"native curve viewing, editing and Undo preserve original media");const auto elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"native curve workflow retains fixed60 second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"max_job_ms",maxJob},{"master",master},{"raw",raw},{"scope","actual native callbacks and graph; production desktop demonstration separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("native curve report write failed");}std::cout<<"checks "<<checks<<" elapsed_ms "<<elapsed<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
