#include "Workspace.h"
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;
namespace ndaw::v2 {class RecordingTestAccess {public:static te::HostedAudioDeviceInterface& host(ndaw::desktop::Workspace& w,const juce::File& dir){w.recordDirectory=dir;auto& dm=w.commands.engine.getDeviceManager();auto& h=dm.getHostedAudioDeviceInterface();te::HostedAudioDeviceInterface::Parameters p;p.sampleRate=48000;p.blockSize=256;p.inputChannels=0;p.outputChannels=2;h.initialise(p);dm.rescanMidiDeviceList();return h;}static Json device(ndaw::desktop::Workspace& w){return w.commands.deviceStatus();}static void key(ndaw::desktop::Workspace& w,bool on){if(on)w.recording.keyState.noteOn(1,69,100.f/127);else w.recording.keyState.noteOff(1,69,0);}};}
namespace {
int checks=0;void check(bool b,const char* s){if(!b)throw std::runtime_error(s);++checks;std::cout<<"PASS "<<s<<std::endl;}void settle(int ms=90){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* c:p.getChildren())if(auto* f=find(*c,id))return f;return nullptr;}
void click(juce::Component& p,const char* id){auto* b=dynamic_cast<juce::Button*>(find(p,id));if(!b||!b->isEnabled())throw std::runtime_error(std::string("button unavailable: ")+id);b->triggerClick();settle();}
juce::ComboBox& combo(juce::Component& p,const char* id){auto* c=dynamic_cast<juce::ComboBox*>(find(p,id));if(!c||!c->isEnabled())throw std::runtime_error(std::string("combo unavailable: ")+id);return *c;}
struct Feed{explicit Feed(te::HostedAudioDeviceInterface& h):thread([this,&h]{juce::AudioBuffer<float> b(2,256);juce::MidiBuffer m;while(!done){b.clear();m.clear();h.processBlock(b,m);juce::Thread::sleep(3);}}){}~Feed(){done=true;thread.join();}std::atomic<bool> done{false};std::thread thread;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
 auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-midi-gui-"+juce::Uuid().toString());dir.createDirectory();ndaw::desktop::Workspace w(false);w.setVisible(true);w.setSize(1440,1080);combo(w,"track.type").setSelectedId(3,juce::dontSendNotification);click(w,"track.create");click(w,"inspector.recording");check(!find(w,"track.arm")->isEnabled()&&!find(w,"transport.record")->isEnabled(),"instrument recording UI refuses absent MIDI input");auto& h=RecordingTestAccess::host(w,dir);Feed feed(h);settle(180);
 auto& inputs=combo(w,"recording.input");check(inputs.getNumItems()>=2,"GUI enumerates actual native MIDI inputs");int hosted=0;for(int n=0;n<inputs.getNumItems();++n)if(inputs.getItemText(n)=="MIDI Input")hosted=inputs.getItemId(n);check(hosted>0,"hosted test input is visible by real SDK name");inputs.setSelectedId(hosted,juce::sendNotificationSync);settle();check(w.query()["tracks"][0]["input"]["available"]&&w.query()["tracks"][0]["input"]["kind"]=="midi","GUI choice assigns actual MIDI destination");click(w,"track.arm");combo(w,"recording.monitor").setSelectedId(2,juce::sendNotificationSync);settle();auto* keys=dynamic_cast<juce::MidiKeyboardComponent*>(find(w,"recording.midi_keyboard"));check(keys&&keys->isEnabled()&&find(w,"transport.record")->isEnabled(),"native screen keyboard and Record enabled by real arm and monitor state");RecordingTestAccess::key(w,true);settle(130);check(RecordingTestAccess::device(w)["output_maximum"].get<double>()>1e-4,"production keyboard-state callback plays audible FourOsc PCM");RecordingTestAccess::key(w,false);settle();check(w.query()["tracks"][0]["clips"][0]["notes"].empty(),"live playing outside Record creates no fake timeline note");
 click(w,"transport.record");RecordingTestAccess::key(w,true);settle(240);check(w.query()["recording"].get<bool>()&&find(w,"recording.midi_keyboard")->isEnabled(),"keyboard remains playable during native MIDI recording");check(!find(w,"recording.input")->isEnabled()&&!find(w,"recording.enable_input")->isEnabled(),"device and assignment controls disabled during capture");auto* detail=dynamic_cast<juce::Label*>(find(w,"recording.detail"));check(detail&&detail->getText().contains("MIDI 事件")&&!detail->getText().contains("写入文件"),"MIDI task status truthfully describes event capture");RecordingTestAccess::key(w,false);settle(90);click(w,"transport.stop");auto q=w.query(),receipt=q["last_recording"];check(receipt["state"]=="committed"&&receipt["files"].empty()&&receipt["clips"].size()==1,"GUI Stop receives actual MIDI capture receipt");check(q["tracks"][0]["clips"].size()==2&&q["tracks"][0]["clips"][1]["notes"][0]["pitch"]==69,"new editable A4 recording preserves original empty clip");click(w,"history.undo");check(w.query()["tracks"][0]["clips"].size()==1&&w.query()["last_recording"]["state"]=="undone","GUI Undo removes entire native MIDI recording");click(w,"history.redo");check(w.query()["tracks"][0]["clips"]==q["tracks"][0]["clips"],"GUI Redo restores exact MIDI IDs and events");
 click(w,"transport.record");settle(100);click(w,"transport.stop");check(w.query()["last_recording"]["state"]=="no_events"&&detail->getText().contains("未收到 MIDI"),"empty MIDI capture displays no-events result rather than success");
 // Native output selection uses the same routing command and Undo, without GUI Edit writes.
 click(w,"inspector.routing");auto& output=combo(w,"routing.output");int port=0;for(int n=0;n<output.getNumItems();++n)if(output.getItemText(n).contains("MIDI Output"))port=output.getItemId(n);check(port>0,"Routing exposes enumerated enabled native MIDI output");output.setSelectedId(port,juce::sendNotificationSync);settle();check(w.query()["tracks"][0]["output"]["target"]==RecordingTestAccess::device(w)["midi_outputs"][0]["id"],"GUI output selection routes track to actual native MIDI port");click(w,"history.undo");check(w.query()["tracks"][0]["output"]["target"]=="master","output Undo restores audio Master route");click(w,"inspector.recording");combo(w,"recording.midi_direction").setSelectedId(1,juce::sendNotificationSync);settle();auto& hardware=combo(w,"recording.hardware");int hd=0;for(int n=0;n<hardware.getNumItems();++n)if(hardware.getItemText(n).startsWith("MIDI Input"))hd=hardware.getItemId(n);hardware.setSelectedId(hd,juce::sendNotificationSync);settle();click(w,"recording.enable_input");settle(240);check(!w.query()["tracks"][0]["input"]["available"].get<bool>()&&!find(w,"transport.record")->isEnabled(),"native GUI device disable prevents false recording availability");click(w,"recording.enable_input");settle(240);check(w.query()["tracks"][0]["input"]["available"]&&find(w,"recording.midi_keyboard")->isEnabled(),"device re-enable restores real native assignment and keyboard");
 w.setSize(1120,740);settle();check(find(w,"recording.midi_keyboard")->getWidth()>250,"MIDI keyboard retains usable width in smaller native window with scrolling inspector");
 Json result={{"result","passed"},{"checks",checks},{"receipt",receipt},{"scope","production JUCE keyboard-state callback, recording, MIDI routing and device controls using explicit hosted MIDI test interface; physical hardware pending"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);}std::cout<<result.dump(2)<<std::endl;return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
