#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0,number=0;Json renders=Json::array();
void check(bool b,const char* s){if(!b)throw std::runtime_error(s);++checks;std::cout<<"PASS "<<s<<std::endl;}
template<class F>void fails(F f,const char* s){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,s);}
Json op(const char* c,Json a){return {{"command",c},{"args",a}};}
Json commit(Commands& c,Json ops){return c.commit(c.makePlan("human",ops));}
Json notes(Commands& c){return c.query()["tracks"][0]["clips"][0]["notes"];}
Json note(Commands& c,const std::string& key){for(const auto& n:notes(c))if(n["id"]==key)return n;throw std::runtime_error("note missing in query");}
Json add(const std::string& clip,int pitch,int64_t onset,int64_t length,const std::string& ref=""){Json a={{"clip",clip},{"pitch",pitch},{"velocity",92},{"position_samples",onset},{"length_samples",length}};if(!ref.empty())a["ref"]=ref;return op("midi.note.add",a);}
Json selection(const std::string& clip,Json ids){return {{"clip",clip},{"selection","notes"},{"note_ids",ids}};}
Json quant(Json a,double grid=1,double strength=1){a["grid_beats"]=grid;a["strength"]=strength;return op("midi.notes.quantize",a);}
Json transpose(Json a,int interval){a["semitones"]=interval;return op("midi.notes.transpose",a);}
juce::AudioBuffer<float> render(Commands& c,const juce::File& dir,const char* name){auto f=dir.getChildFile("transform-"+juce::String(++number)+".wav");auto r=c.render(f,0,144000);check(r["render_ms"].get<double>()<=10000&&r["frames"]==144000,"actual transform render time and frame budget");renders.push_back({{"case",name},{"receipt",r}});juce::AudioFormatManager fm;fm.registerBasicFormats();auto rd=std::unique_ptr<juce::AudioFormatReader>(fm.createReaderFor(f));if(!rd||rd->numChannels!=2)throw std::runtime_error("render unreadable");juce::AudioBuffer<float> pcm(2,144000);if(!rd->read(&pcm,0,144000,0,true,true))throw std::runtime_error("render read failed");return pcm;}
int onset(const juce::AudioBuffer<float>& a){for(int i=0;i<a.getNumSamples();++i)if(std::abs(a.getSample(0,i))>3e-6)return i;return -1;}
double frequency(const juce::AudioBuffer<float>& a,int first){constexpr int n=32768;juce::dsp::FFT fft(15);std::vector<float> x(2*n,0);for(int i=0;i<n;++i)x[i]=a.getSample(0,first+i)*float(.5-.5*std::cos(2*juce::MathConstants<double>::pi*i/(n-1)));fft.performFrequencyOnlyForwardTransform(x.data());int peak=1;for(int i=2;i<n/2;++i)if(x[i]>x[peak])peak=i;auto l=std::log(std::max(1e-20f,x[peak-1])),m=std::log(std::max(1e-20f,x[peak])),r=std::log(std::max(1e-20f,x[peak+1]));return (peak+.5*(l-r)/(l-2*m+r))*48000/n;}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
 auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-transform-"+juce::Uuid().toString());dir.createDirectory();Commands c(false);
 commit(c,Json::array({op("track.create",{{"name","Transform FourOsc"},{"type","instrument"},{"ref","$t"}}),op("track.gain",{{"track","$t"},{"db",-12}}),op("midi.clip.create",{{"track","$t"},{"name","Expressive MIDI"},{"ref","$c"},{"position_samples",0},{"length_samples",384000}}),add("$c",69,30000,48000),add("$c",72,135000,6000),add("$c",60,150000,6000)}));
 auto base=c.query();const std::string clip=base["tracks"][0]["clips"][0]["id"],track=base["tracks"][0]["id"],a4=notes(c)[0]["id"],second=notes(c)[1]["id"],third=notes(c)[2]["id"];
 auto initial=render(c,dir,"expressive onset");check(onset(initial)>=30000&&onset(initial)<=30256&&std::abs(frequency(initial,34096)-440)<=2,"baseline actual off-grid A4 onset and frequency");
 auto q=c.makePlan("agent:transform-test",Json::array({quant(selection(clip,Json::array({a4})))}));auto preview=c.preview(q);
 check(c.query()==base&&preview["midi_changes"][0]["notes"][0]["before"]["position_samples"]==30000&&preview["midi_changes"][0]["notes"][0]["after"]["position_samples"]==24000,"readonly quantise preview lists actual before after samples");fails([&]{c.commit(q);},"agent quantise requires acceptance");auto receipt=c.commit(q,true);
 check(note(c,a4)["position_samples"]==24000&&note(c,a4)["length_beats"]==2&&note(c,a4)["velocity"]==92&&note(c,second)==base["tracks"][0]["clips"][0]["notes"][1],"selected quantise preserves duration velocity ID and other notes");
 auto aligned=render(c,dir,"quantised A4");check(onset(aligned)>=24000&&onset(aligned)<=24256&&aligned.getMagnitude(0,0,24000)<=3e-6,"quantise changes real schedule without early sound");
 auto trans=c.makePlan("human",Json::array({transpose(selection(clip,Json::array({a4})),12)}));auto td=c.preview(trans)["midi_changes"][0]["notes"][0];check(td["before"]["pitch"]==69&&td["after"]["pitch"]==81&&td["after"]["position_samples"]==24000,"transpose preview lists real pitches and unchanged onset");auto tr=c.commit(trans);
 auto high=render(c,dir,"transposed A5");double hz=frequency(high,28096);check(std::abs(hz-880)<=2&&onset(high)>=24000&&onset(high)<=24256,"transpose produces actual A5 PCM at unchanged schedule");
 c.undo(tr["plan_id"]);check(note(c,a4)["pitch"]==69,"transpose Undo restores real note");c.undo(receipt["plan_id"]);check(c.query()["tracks"]==base["tracks"],"quantise Undo restores all original MIDI and instrument state");auto retry=c.commit(q,true);check(retry["replayed"]==true&&retry["state"]=="undone"&&c.query()["tracks"]==base["tracks"],"idempotent retry after Undo never re-applies quantisation");c.redo();check(note(c,a4)["position_samples"]==24000,"quantise Redo restores same stable note");c.redo();check(note(c,a4)["pitch"]==81,"transpose Redo restores pitch");c.undo();c.undo();
 auto partial=commit(c,Json::array({quant(selection(clip,Json::array({a4})),1,.5),transpose(selection(clip,Json::array({a4})),7)}));check(note(c,a4)["position_samples"]==27000&&note(c,a4)["pitch"]==76,"partial strength quantise and transpose use ordered compound Plan");c.undo(partial["plan_id"]);check(c.query()["tracks"]==base["tracks"],"one Undo restores compound transform");
 auto tie=commit(c,Json::array({quant(selection(clip,Json::array({a4})),.5)}));check(note(c,a4)["position_samples"]==36000,"exact half-grid tie rounds forward");c.undo(tie["plan_id"]);
 auto scoped=Json{{"clip",clip},{"selection","range"},{"range_start_samples",135000},{"range_end_samples",150000}};auto rp=commit(c,Json::array({transpose(scoped,-12)}));check(note(c,second)["pitch"]==60&&note(c,third)["pitch"]==60&&note(c,a4)["pitch"]==69,"range includes left onset excludes right onset and untouched notes");c.undo(rp["plan_id"]);
 auto all=Json{{"clip",clip},{"selection","all"}};auto ap=commit(c,Json::array({quant(all)}));check(note(c,a4)["position_samples"]==24000&&note(c,second)["position_samples"]==144000&&note(c,third)["position_samples"]==144000,"all selection moves actual onsets without deduplicating different notes");c.undo(ap["plan_id"]);
 auto step=c.makePlan("human",Json::array({op("tempo.set",{{"position_samples",96000},{"bpm",60}}),quant(all)}));auto sd=c.preview(step)["midi_changes"][0];check(sd["notes"].size()==3&&c.query()["tracks"]==base["tracks"],"tempo plus transform preview remains readonly");auto sr=c.commit(step);check(note(c,second)["position_samples"]==192000&&note(c,third)["position_samples"]==192000&&note(c,a4)["position_samples"]==24000,"quantise after same-Plan tempo point uses step map sample positions");c.undo(sr["plan_id"]);check(c.query()["tracks"]==base["tracks"]&&c.query()["music"]["tempos"]==base["music"]["tempos"],"compound tempo transform Undo restores map and notes");
 auto mr=commit(c,Json::array({op("meter.set",{{"position_samples",0},{"numerator",3},{"denominator",8}}),quant(all)}));check(note(c,a4)["position_samples"]==12000&&note(c,second)["position_samples"]==72000,"quantise uses actual 3/8 meter beat units rather than fixed quarter notes");c.undo(mr["plan_id"]);
 auto stale=c.makePlan("agent:transform-test",Json::array({transpose(all,-2)}));auto mute=commit(c,Json::array({op("track.mute",{{"track",track},{"enabled",true}})}));auto human=c.query();fails([&]{c.commit(stale,true);},"stale transform cannot overwrite interleaved human mute");check(c.query()==human,"stale transform leaves human state and revision intact");fails([&]{c.undo(q["plan_id"]);},"selective old agent Undo cannot erase later human transaction");c.undo(mute["plan_id"]);
 auto immutable=c.query();auto bad=[&](Json ops,const char* s){fails([&]{c.makePlan("human",ops);},s);check(c.query()==immutable,"failed transform leaves authoritative Edit unchanged");};
 bad(Json::array({quant(selection(clip,Json::array({"absent"})))}),"missing selected note rejected");bad(Json::array({quant(selection(clip,Json::array()))}),"empty explicit selection rejected");bad(Json::array({quant(selection(clip,Json::array({a4,a4})))}),"duplicate note IDs rejected");bad(Json::array({quant(selection(clip,Json::array({42})))}),"non-string note ID rejected");bad(Json::array({quant(all,0)}),"zero grid rejected");bad(Json::array({quant(all,1./256)}),"grid below declared resolution rejected");bad(Json::array({quant(all,1,1.01)}),"strength above one rejected");bad(Json::array({transpose(all,128)}),"semitone interval beyond declared range rejected");auto huge=transpose(all,1);huge["args"]["semitones"]=uint64_t(4294967296);bad(Json::array({huge}),"large integer cannot wrap into allowed semitone interval");huge["args"]["semitones"]=std::numeric_limits<uint64_t>::max();bad(Json::array({huge}),"unsigned integer cannot wrap command representation");
 auto invalid=all;invalid["selection"]="inferred";bad(Json::array({quant(invalid)}),"unknown selection rejected");invalid=all;invalid["note_ids"]=Json::array({a4});bad(Json::array({quant(invalid)}),"unrelated explicit IDs cannot hide behind all scope");invalid=scoped;invalid["range_end_samples"]=135000;bad(Json::array({quant(invalid)}),"empty range rejected");invalid=scoped;invalid["range_start_samples"]=200000;bad(Json::array({quant(invalid)}),"reversed range rejected");invalid=scoped;invalid["range_start_samples"]=0;invalid["range_end_samples"]=1000;bad(Json::array({quant(invalid)}),"empty onset range rejected");invalid=scoped;invalid["range_start_samples"]=1.5;bad(Json::array({quant(invalid)}),"fractional sample range rejected");invalid=all;invalid["clip"]="missing";bad(Json::array({quant(invalid)}),"absent clip rejected");
 bad(Json::array({op("midi.note.delete",{{"clip",clip},{"note",a4}}),quant(selection(clip,Json::array({a4})))}),"note removed earlier in same Plan rejects later transformation");
 auto edge=commit(c,Json::array({add(clip,120,350000,34000)}));auto edgeState=c.query();fails([&]{c.makePlan("human",Json::array({transpose(all,12)}));},"one pitch overflow rejects entire selection");fails([&]{c.makePlan("human",Json::array({quant(all)}));},"one boundary crossing rejects entire selection");check(c.query()==edgeState,"overflow preflight does not partially modify other selected notes");c.undo(edge["plan_id"]);
 auto ref=c.makePlan("human",Json::array({add(clip,65,123000,6000,"$new"),transpose(selection(clip,Json::array({"$new"})),2),quant(selection(clip,Json::array({"$new"})))}));check(c.preview(ref)["midi_changes"][1]["notes"][0]["after"]["pitch"]==67,"preview simulates locally created transformed note");auto rr=c.commit(ref);const std::string newID=rr["objects"][0]["id"];check(note(c,newID)["pitch"]==67&&note(c,newID)["position_samples"]==120000,"execution resolves local note reference through ordered transformations");c.undo(rr["plan_id"]);
 auto plainFile=dir.getChildFile("unprocessed.tracktionedit");c.save(plainFile);
 auto altered=[&](const char* name,bool loop){auto xml=juce::XmlDocument::parse(plainFile);if(!xml)throw std::runtime_error("fixture parse failed");auto* t=xml->getChildByName("TRACK");auto* m=t?t->getChildByName("MIDICLIP"):nullptr;if(!m)throw std::runtime_error("fixture MIDI absent");if(loop)m->setAttribute("loopLengthBeats",2.);else{auto* q=m->getChildByName("QUANTISATION");if(!q)throw std::runtime_error("fixture quantisation absent");q->setAttribute("type","1 beat");}auto f=dir.getChildFile(name);if(!xml->writeTo(f))throw std::runtime_error("fixture write failed");Commands special(false);special.open(f);auto old=special.query();check(old["tracks"][0]["clips"][0]["bulk_transform_available"]==false,"query explains unsupported playback-transformed clip");fails([&]{special.makePlan("human",Json::array({quant(all)}));},"loop or existing playback quantiser rejected without misleading raw-position preview");check(special.query()==old,"rejected playback-transformed clip remains unchanged");};altered("looped.tracktionedit",true);altered("playback-quantised.tracktionedit",false);
 auto final=commit(c,Json::array({quant(selection(clip,Json::array({a4}))),transpose(selection(clip,Json::array({a4})),12)}));auto file=dir.getChildFile("transformed.tracktionedit");c.save(file);Commands reopened(false);reopened.open(file);check(reopened.query()["tracks"]==c.query()["tracks"],"save reopen preserves transformed notes stable IDs instrument and routing");auto restored=render(reopened,dir,"reopened A5");check(onset(restored)>=24000&&onset(restored)<=24256&&std::abs(frequency(restored,28096)-880)<=2,"reopened transformed instrument sounds at actual new onset and pitch");c.undo(final["plan_id"]);
 Commands offset(false);commit(offset,Json::array({op("track.create",{{"name","Offset instrument"},{"type","instrument"},{"ref","$t"}}),op("midi.clip.create",{{"track","$t"},{"name","Offset"},{"ref","$c"},{"position_samples",12000},{"length_samples",192000}}),add("$c",69,42000,24000,"$n"),quant(selection("$c",Json::array({"$n"})))}));
 check(notes(offset)[0]["position_samples"]==48000&&notes(offset)[0]["source_beat"]==1.5&&notes(offset)[0]["length_beats"]==1,"offset clip quantises on absolute session grid and retains source duration");
 const std::string oc=offset.query()["tracks"][0]["clips"][0]["id"];Json many=Json::array();for(int i=0;i<90;++i){many.push_back(add(oc,48+i%24,14000+i*1000,250));if(many.size()==50){commit(offset,many);many=Json::array();}}if(!many.empty())commit(offset,many);auto manyBefore=offset.query()["tracks"];
 auto mq=offset.makePlan("human",Json::array({quant({{"clip",oc},{"selection","all"}},.25)}));check(offset.preview(mq)["midi_changes"][0]["notes"].size()==91,"one bulk command covers more notes than the Plan operation limit without dropping notes");auto mqr=offset.commit(mq);check(notes(offset).size()==91,"bulk execution retains every actual note");offset.undo(mqr["plan_id"]);check(offset.query()["tracks"]==manyBefore,"bulk Undo restores all notes and IDs together");
 Json report{{"result","passed"},{"checks",checks},{"a5_frequency_hz",hz},{"renders",renders},{"scope","production L1, native MIDI, FourOsc PCM, preview, revision, Undo and reopen; no hardware MIDI or model claim"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);out.close();if(!out)throw std::runtime_error("report write failed");}std::cout<<report.dump(2)<<std::endl;dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
