#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
#include <thread>
#include <mutex>
using namespace ndaw::v2;
namespace ndaw::v2 {class RecordingTestAccess {public:static te::HostedAudioDeviceInterface& host(Commands& c){auto& dm=c.engine.getDeviceManager();auto& h=dm.getHostedAudioDeviceInterface();te::HostedAudioDeviceInterface::Parameters p;p.sampleRate=48000;p.blockSize=256;p.inputChannels=1;p.outputChannels=2;h.initialise(p);dm.setAllWaveInputsToNumChannels(1);for(auto* i:dm.getWaveInputDevices()){i->setEnabled(true);i->setMonitorMode(te::InputDevice::MonitorMode::off);i->setOutputFormat("WAV file");i->setBitDepth(24);}dm.rescanMidiDeviceList();return h;}static void recordingEnabled(Commands& c,const std::string& id,bool enabled){c.engine.getDeviceManager().findMidiInputDeviceForID(juce::String(id))->recordingEnabled=enabled;}};}
namespace {
int checks=0;void check(bool b,const char* s){if(!b)throw std::runtime_error(s);++checks;std::cout<<"PASS "<<s<<std::endl;}
void settle(int ms=90){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
template<class F>void fails(F f,const char* s){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,s);}
Json op(const char* c,Json a){return {{"command",c},{"args",a}};}Json run(Commands& c,Json ops){return c.commit(c.makePlan("human",ops));}
struct Feed {
    explicit Feed(te::HostedAudioDeviceInterface& h):thread([this,&h]{juce::AudioBuffer<float> b(2,256);juce::MidiBuffer midi;int64_t pos=0;while(!done){for(int i=0;i<256;++i)b.setSample(0,i,float(.08*std::sin(2*juce::MathConstants<double>::pi*1000*(pos+i)/48000.)));b.clear(1,0,256);midi.clear();auto start=anchor.load();if(start>=0){auto add=[&](int64_t offset,juce::MidiMessage m){auto at=start+offset;if(at>=pos&&at<pos+256)midi.addEvent(m,int(at-pos));};add(4800,juce::MidiMessage::noteOn(1,69,(juce::uint8)100));add(14400,juce::MidiMessage::noteOff(1,69));add(16800,juce::MidiMessage::controllerEvent(1,1,64));add(19200,juce::MidiMessage::pitchWheel(1,9000));add(21600,juce::MidiMessage::noteOn(1,72,(juce::uint8)90));add(31200,juce::MidiMessage::noteOff(1,72));}h.processBlock(b,midi);if(!midi.isEmpty()){std::lock_guard lock(mutex);for(auto e:midi)out.push_back(e.getMessage());}pos+=256;frame=pos;juce::Thread::sleep(2);}}){}
    ~Feed(){done=true;thread.join();}void schedule(){anchor=frame.load()+2048;}int noteOns(){std::lock_guard lock(mutex);int n=0;for(auto& m:out)n+=m.isNoteOn();return n;}std::atomic<bool> done{false};std::atomic<int64_t> frame{0},anchor{-1};std::mutex mutex;std::vector<juce::MidiMessage> out;std::thread thread;
};
void normaliseFloatingFacts(const Json& expected,Json& actual){if(expected.is_number_float()&&actual.is_number_float()){check(std::abs(expected.get<double>()-actual.get<double>())<1e-10,"reopened derived floating fact within 1e-10; integer samples remain exact");actual=expected;}else if(expected.is_object()&&actual.is_object()){for(auto it=expected.begin();it!=expected.end();++it)if(actual.contains(it.key()))normaliseFloatingFacts(it.value(),actual[it.key()]);}else if(expected.is_array()&&actual.is_array()&&expected.size()==actual.size()){for(size_t n=0;n<expected.size();++n)normaliseFloatingFacts(expected[n],actual[n]);}}
Json captured(const Json& track){for(const auto& c:track["clips"])if(c["notes"].size()==2)return c;throw std::runtime_error("captured two-note clip absent");}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
 auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-midi-record-"+juce::Uuid().toString());dir.createDirectory();Commands c(false);auto& h=RecordingTestAccess::host(c);Feed feed(h);settle();auto ds=c.deviceStatus();check(ds["midi_inputs"].size()>=1&&ds["midi_outputs"].size()>=1&&ds["midi_inputs"][0]["kind"]=="hosted_test","SDK hosted MIDI endpoints truthfully labelled as test-only devices");std::string input=ds["midi_inputs"][0]["id"],output=ds["midi_outputs"][0]["id"],wave=ds["inputs"][0]["id"];
 auto create=run(c,Json::array({op("track.create",{{"name","Keys"},{"type","instrument"},{"ref","$i"}}),op("track.gain",{{"track","$i"},{"db",-12}}),op("midi.clip.create",{{"track","$i"},{"ref","$old"},{"name","Original"},{"position_samples",0},{"length_samples",96000}}),op("midi.note.add",{{"clip","$old"},{"pitch",55},{"velocity",80},{"position_samples",0},{"length_samples",12000}}),op("track.create",{{"name","MIDI Out"},{"type","midi"},{"ref","$m"}}),op("track.input",{{"track","$i"},{"device",input}}),op("track.arm",{{"track","$i"},{"enabled",true}}),op("track.input",{{"track","$m"},{"device",input}}),op("track.arm",{{"track","$m"},{"enabled",true}}),op("track.output",{{"track","$m"},{"target",output}})}));settle();auto q=c.query();std::string ins=q["tracks"][0]["id"],midi=q["tracks"][1]["id"],original=q["tracks"][0]["clips"][0]["id"];auto old=q["tracks"][0]["clips"][0];check(q["tracks"][0]["input"]["kind"]=="midi"&&q["tracks"][0]["input"]["armed"]&&q["tracks"][1]["output"]["target"]==output,"one Plan assigns MIDI input, arm and native MIDI output");
 auto snapshot=q;fails([&]{c.makePlan("human",Json::array({op("track.input",{{"track",ins},{"device",wave}})}));},"wave input rejected on instrument");fails([&]{c.configureMidiDevice("input","invented",true);},"invented MIDI port rejected");check(c.query()==snapshot,"failed MIDI requests do not change state");
 auto mon=run(c,Json::array({op("track.monitor",{{"track",ins},{"mode","auto"}}),op("track.monitor",{{"track",midi},{"mode","auto"}})}));settle();c.midiKeyboard(ins,69,100,true);settle(140);check(c.deviceStatus()["output_peak"].get<double>()>1e-4,"live keyboard events pass through actual FourOsc and audio graph");check(feed.noteOns()>0,"native MIDI output produces actual note-on events in hosted test callback");c.midiKeyboard(ins,69,100,false);settle(140);c.undo(mon["plan_id"]);settle();check(!c.query()["tracks"][0]["input"]["monitoring"].get<bool>(),"monitor Undo restores actual MIDI live path");fails([&]{c.midiKeyboard(ins,69,100,true);},"Off monitoring refuses unrecorded screen key");c.redo();settle();
 c.seek(0);RecordingTestAccess::recordingEnabled(c,input,false);auto disabled=c.query();fails([&]{c.record(dir);},"disabled native MIDI recording rejected before starting transaction");check(c.query()==disabled,"failed MIDI start leaves capture, history and original clips unchanged");RecordingTestAccess::recordingEnabled(c,input,true);auto start=c.record(dir);check(c.query()["recording"].get<bool>()&&start["targets"].size()==2&&c.query()["tracks"][0]["input"]["recording_file"]=="","native MIDI capture starts without inventing WAV file");feed.schedule();settle(600);fails([&]{c.configureMidiDevice("input",input,false);},"cannot disable MIDI input during capture");c.stop();q=c.query();auto receipt=q["last_recording"];check(receipt["state"]=="committed"&&receipt["files"].empty()&&receipt["clips"].size()==2,"Stop validates two native MIDI clips without false disk-file receipt");check(q["tracks"][0]["clips"].size()==2&&q["tracks"][0]["clips"][0]==old,"non-destructive native MIDI recording preserves overlapping original clip");auto recorded=captured(q["tracks"][0]);auto parallel=captured(q["tracks"][1]);check(recorded["notes"][0]["pitch"]==69&&recorded["notes"][0]["velocity"]==100&&recorded["notes"][1]["pitch"]==72&&recorded["notes"][1]["velocity"]==90,"captured real event pitches and velocities remain exact");check(std::abs(recorded["notes"][0]["length_samples"].get<int64_t>()-9600)<=256,"recorded MIDI duration meets predeclared one-block 256-sample budget");check(std::abs(recorded["notes"][0]["position_samples"].get<int64_t>()-parallel["notes"][0]["position_samples"].get<int64_t>())<=256,"shared-input multi-track MIDI onset alignment within 256 frames");check(recorded["controller_events"].size()==2&&recorded["controller_events"][0]["type"]==1&&recorded["controller_events"][0]["raw_value"]==8192&&recorded["controller_events"][1]["type"]==0x1005&&recorded["controller_events"][1]["raw_value"]==9000,"native CC and pitch bend captured with explicit SDK raw units");for(const auto& n:recorded["notes"])check(n["id"]!=""&&n["id"]!="0","captured note stable ID allocated by L1");
 auto tracks=q["tracks"];c.undo(receipt["plan_id"]);check(c.query()["tracks"][0]["clips"]==Json::array({old})&&c.query()["tracks"][1]["clips"].empty(),"one Undo removes both MIDI captures and preserves original");c.redo();check(c.query()["tracks"]==tracks,"Redo restores captured events, note IDs and native routing identically");
 auto saved=dir.getChildFile("midi.tracktionedit");c.save(saved);{Commands re(false);re.open(saved);auto reopenedClips=re.query()["tracks"][0]["clips"];auto expectedClips=tracks[0]["clips"];normaliseFloatingFacts(expectedClips,reopenedClips);check(reopenedClips==expectedClips,"save/reopen preserves MIDI notes and controllers");check(!re.query()["tracks"][0]["input"]["available"].get<bool>()&&re.query()["tracks"][0]["input"]["device"]==input,"missing MIDI device retains original stable reference");auto rendered=re.render(dir.getChildFile("recorded.wav"),0,96000);check(rendered["audio_verified"]&&rendered["peak"].get<double>()>1e-4&&rendered["frames"]==96000&&rendered["render_ms"].get<double>()<10000,"captured instrument MIDI renders actual 48 kHz PCM within fixed 10-second budget");}
 // No new scheduled events: report no_events and leave the previous Undo transaction intact.
 feed.anchor=-1;c.seek(0);auto history=Json::array({c.query()["can_undo"],c.query()["can_redo"]});c.record(dir);settle(180);c.stop();check(c.query()["last_recording"]["state"]=="no_events"&&c.query()["last_recording"]["clips"].empty(),"empty MIDI recording explicitly returns no_events");check(Json::array({c.query()["can_undo"],c.query()["can_redo"]})==history&&c.query()["tracks"]==tracks,"empty capture creates no fake clip or history transaction");
 c.undo(receipt["plan_id"]);check(c.query()["tracks"][0]["clips"]==Json::array({old}),"empty capture leaves previous transaction as the real Undo target");c.redo();
 auto stale=c.makePlan("human",Json::array({op("track.gain",{{"track",ins},{"db",-9}})}));c.configureMidiDevice("input",input,false);fails([&]{c.commit(stale);},"device configuration invalidates pre-existing Plan");settle(230);check(c.deviceStatus()["midi_configuration"]["state"]=="applied"&&!c.query()["tracks"][0]["input"]["available"].get<bool>(),"asynchronous native input disable has actual completion receipt");fails([&]{c.record(dir);},"missing armed MIDI device blocks capture");c.configureMidiDevice("input",input,true);settle(230);check(c.deviceStatus()["midi_configuration"]["state"]=="applied"&&c.query()["tracks"][0]["input"]["available"].get<bool>(),"native input enable rebuild restores actual target");
 auto audio=run(c,Json::array({op("track.create",{{"name","Audio"},{"type","audio"},{"ref","$a"}}),op("track.input",{{"track","$a"},{"device",wave}}),op("track.arm",{{"track","$a"},{"enabled",true}})}));settle();auto aq=c.query()["tracks"][2];fails([&]{c.makePlan("human",Json::array({op("track.output",{{"track",aq["id"]},{"target",output}})}));},"audio track cannot silently become MIDI output");c.seek(0);c.record(dir);feed.schedule();settle(600);c.stop();auto mixed=c.query()["last_recording"];check(mixed["state"]=="committed"&&mixed["files"].size()==1&&mixed["clips"].size()==3,"native mixed audio and two MIDI tracks captured in one transaction");c.undo(mixed["plan_id"]);check(c.query()["tracks"][2]["clips"].empty()&&c.query()["tracks"][0]["clips"].size()==2,"mixed recording Undo removes all newly captured media together");
 Json result={{"result","passed"},{"checks",checks},{"receipt",receipt},{"mixed_receipt",mixed},{"scope","actual Tracktion MIDI capture/graph/output and disk writer with explicit hosted test inputs; physical keyboard and external synth pending"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);}std::cout<<result.dump(2)<<std::endl;return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
