#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
constexpr int frames=144000;int checks=0,serial=0;Json renders=Json::array(),live=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<"\n";}
template<class F>void fails(F f,const char* why){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
void settle(int ms=80){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json op(const char* cmd,Json a){return {{"command",cmd},{"args",a}};}
Json run(Commands& c,Json ops){auto plan=c.makePlan("human",ops);c.commit(plan);return plan;}
Json pan(const std::string& id,double v){return op("track.pan",{{"track",id},{"value",v}});}
Json law(const std::string& id,const char* v){return op("track.pan_law",{{"track",id},{"law",v}});}
Json point(const std::string& id,const char* ref,int64_t pos,double v){return op("automation.point.add",{{"track",id},{"parameter","pan"},{"ref",ref},{"position_samples",pos},{"value",v},{"curve",0}});}
Json lane(Commands& c,const std::string& id){auto q=c.automationQuery(id);for(const auto& l:q["lanes"])if(l["parameter"]=="pan")return l;throw std::runtime_error("pan lane absent");}
void fixture(const juce::File& file,int channels){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(channels).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture writer failed");juce::AudioBuffer<float> b(channels,frames);for(int ch=0;ch<channels;++ch)for(int i=0;i<frames;++i)b.setSample(ch,i,.1f*std::sin(2*juce::MathConstants<double>::pi*(ch?880:440)*i/48000));if(!writer->writeFromAudioSampleBuffer(b,0,frames))throw std::runtime_error("fixture write failed");}
std::string setup(Commands& c,const juce::File& file){run(c,Json::array({op("track.create",{{"name","Pan source"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",file.getFullPathName().toStdString()},{"position_samples",0}})}));return c.query()["tracks"][0]["id"];}
juce::AudioBuffer<float> render(Commands& c,const juce::File& dir,const std::string& name){auto out=dir.getChildFile("pan-"+juce::String(++serial)+".wav");auto r=c.render(out,0,frames);check(r["frames"]==frames&&r["channels"]==2&&r["pcm_bits"]==24&&r["render_ms"].get<double>()<10000,"real stereo WAV satisfies fixed format/frame/deadline budget");renders.push_back({{"case",name},{"receipt",r}});juce::AudioFormatManager fm;fm.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(fm.createReaderFor(out));if(!reader)throw std::runtime_error("render unreadable");juce::AudioBuffer<float> b(2,frames);if(!reader->read(&b,0,frames,0,true,true))throw std::runtime_error("render read failed");return b;}
void amplitude(const juce::AudioBuffer<float>& b,double l,double r,const char* why,int start=24000,int count=24000){const double base=.1/std::sqrt(2.);auto a=b.getRMSLevel(0,start,count),z=b.getRMSLevel(1,start,count);std::cout<<"RMS "<<a<<" "<<z<<" expected "<<base*l<<" "<<base*r<<"\n";check(std::abs(a-base*l)<3e-6&&std::abs(z-base*r)<3e-6,why);}
double difference(const juce::AudioBuffer<float>& a,const juce::AudioBuffer<float>& b){double d=0;for(int ch=0;ch<2;++ch)for(int i=24000;i<frames;++i)d=std::max(d,double(std::abs(a.getSample(ch,i)-b.getSample(ch,i))));return d;}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    const auto started=juce::Time::getMillisecondCounterHiRes();auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-pan-"+juce::Uuid().toString());dir.createDirectory();auto mono=dir.getChildFile("mono.wav"),stereo=dir.getChildFile("stereo.wav");fixture(mono,1);fixture(stereo,2);const auto mh=Commands::mediaHash(mono),sh=Commands::mediaHash(stereo);
    Commands c(false);const auto id=setup(c,stereo);const auto initial=c.query()["tracks"];auto p=c.makePlan("agent:pan",Json::array({law(id,"center_3db"),pan(id,-1)}));auto preview=c.preview(p);
    check(preview["pan_changes"].size()==2&&preview["pan_changes"][0]["before"]["law"]=="linear"&&preview["pan_changes"][1]["before"]["law"]=="center_3db"&&c.query()["tracks"]==initial,"ordered preview reports law and pan without editing");
    fails([&]{c.commit(p);},"Agent pan requires preview acceptance");c.commit(p,true);amplitude(render(c,dir,"agent accepted left 3dB"),1,0,"hard left 3 dB law retains only original left channel");settle(450);c.undo(p["plan_id"]);check(c.query()["tracks"]==initial,"compound pan and law Undo restores base values and actual law");auto original=render(c,dir,"linear centre Undo");amplitude(original,1,1,"linear centre preserves distinct stereo channels");c.redo();amplitude(render(c,dir,"compound Redo"),1,0,"Redo restores native audio path");c.undo();
    auto snap=c.makePlan("human",Json::array({pan(id,.004)}));check(c.preview(snap)["pan_changes"][0]["requested_value"]==.004&&c.preview(snap)["pan_changes"][0]["after"]["value"]==0,"preview discloses actual native centre snap");c.commit(snap);check(c.query()["tracks"][0]["base_pan"]==0,"native snapped base is truthful");
    for(auto v:{-1.01,1.01,std::numeric_limits<double>::infinity(),std::numeric_limits<double>::quiet_NaN()})fails([&]{c.makePlan("human",Json::array({pan(id,v)}));},"invalid pan cannot change project");fails([&]{c.makePlan("human",Json::array({law(id,"equal_power_invented")}));},"invented Pan Law rejected");fails([&]{c.makePlan("human",Json::array({pan("missing",0)}));},"missing pan target rejected");fails([&]{c.makePlan("human",Json::array({op("track.delete",{{"track",id},{"connections","reject"}}),pan(id,1)}));},"pan of target deleted earlier rejects whole Plan");
    for(const char* type:{"folder","vca"})fails([&]{c.makePlan("human",Json::array({op("track.create",{{"ref","$group"},{"name","Group"},{"type",type}}),pan("$group",.5)}));},"Folder and VCA expose no fake panner");
    auto stale=c.makePlan("agent:stale",Json::array({pan(id,.5)}));run(c,Json::array({pan(id,-.5)}));fails([&]{c.commit(stale,true);},"human pan invalidates older Agent Plan");
    Scope scope;scope.mode=Permission::ScopedLowRisk;scope.targets={id};scope.commands={"track.pan"};auto automatic=c.makePlan("agent:scope",Json::array({pan(id,.5)}));check(!c.review(automatic,scope)["permission"]["automatic_allowed"].get<bool>(),"new pan does not silently expand automatic permission");scope.end=48000;fails([&]{c.review(automatic,scope);},"whole-track pan cannot fit partial time permission");
    run(c,Json::array({law(id,"linear"),pan(id,1)}));amplitude(render(c,dir,"linear right endpoint"),0,2,"linear right endpoint has SDK +6.02dB gain without channel exchange");
    for(auto [name,ratio]:std::initializer_list<std::pair<const char*,double>>{{"center_2.5db",2.5/3},{"center_3db",1},{"center_4.5db",1.5},{"center_6db",2}}){run(c,Json::array({law(id,name),pan(id,0)}));const double a=std::pow(std::sqrt(.5),ratio);amplitude(render(c,dir,name),a,a,"native non-linear centre law matches known PCM gain");}
    run(c,Json::array({law(id,"default"),pan(id,0)}));check(c.query()["tracks"][0]["pan_law_setting"]=="default"&&c.query()["tracks"][0]["pan_law_effective"]=="linear","default choice distinguished from current effective law");amplitude(render(c,dir,"default"),1,1,"actual default law measured");
    {Commands m(false);auto mid=setup(m,mono);run(m,Json::array({law(mid,"center_3db"),pan(mid,0)}));amplitude(render(m,dir,"mono 3dB centre"),std::sqrt(.5),std::sqrt(.5),"mono source reaches both output channels with measured centre law");run(m,Json::array({pan(mid,1)}));amplitude(render(m,dir,"mono right"),0,1,"mono hard right reaches only right output");}
    run(c,Json::array({law(id,"linear"),point(id,"$left",0,-1),point(id,"$leftEnd",48000,-1),point(id,"$rightStart",48001,1),point(id,"$rightEnd",frames-1,1)}));auto automated=render(c,dir,"Read pan step");amplitude(automated,2,0,"Read curve genuinely pans early audio left",24000,4800);amplitude(automated,0,2,"Read curve genuinely pans later audio right",72000,24000);
    auto saved=dir.getChildFile("pan.tracktionedit");c.save(saved);{Commands reopened(false);reopened.open(saved);auto expected=c.query()["tracks"],actual=reopened.query()["tracks"];for(auto& t:expected)t.erase("pan");for(auto& t:actual)t.erase("pan");check(actual==expected,"pan base law curve stable IDs restore independently of live observation");check(difference(automated,render(reopened,dir,"reopened Read pan"))<3e-6,"saved pan automation restores actual PCM");}
    {Commands mix(false);auto plan=mix.makePlan("agent:mix",Json::array({
        op("track.create",{{"name","Audio"},{"ref","$voice"}}),op("clip.import",{{"track","$voice"},{"path",stereo.getFullPathName().toStdString()},{"position_samples",0}}),
        op("plugin.insert",{{"track","$voice"},{"type","4bandEq"}}),op("plugin.insert",{{"track","$voice"},{"type","compressor"}}),law("$voice","center_3db"),pan("$voice",.25),
        op("track.gain",{{"track","$voice"},{"db",-12}}),point("$voice","$p0",0,.25),point("$voice","$p1",frames-1,.25),
        op("track.create",{{"name","Reverb"},{"ref","$aux"},{"type","aux"}}),op("plugin.insert",{{"track","$aux"},{"type","reverb"},{"wet_only",true}}),op("send.create",{{"track","$voice"},{"target","$aux"},{"db",-18},{"position","post"}}),
        op("track.create",{{"name","Synth"},{"ref","$synth"},{"type","instrument"}}),law("$synth","center_3db"),pan("$synth",1),op("track.gain",{{"track","$synth"},{"db",-18}}),
        op("midi.clip.create",{{"track","$synth"},{"ref","$notes"},{"name","Editable notes"},{"position_samples",0},{"length_samples",frames}}),op("midi.note.add",{{"clip","$notes"},{"pitch",69},{"velocity",90},{"position_samples",48000},{"length_samples",48000}})}));
        check(mix.preview(plan)["pan_changes"].size()==4&&mix.query()["tracks"].empty(),"compound audio FX Aux MIDI and pan plan remains a dry-run");mix.commit(plan,true);auto tracks=mix.query()["tracks"];const std::string voice=tracks[0]["id"],synth=tracks[2]["id"],eq=tracks[0]["plugins"][0]["id"],compressor=tracks[0]["plugins"][1]["id"];
        check(tracks.size()==3&&tracks[0]["sends"].size()==1&&tracks[0]["output"]["kind"]=="device"&&tracks[2]["clips"][0]["notes"].size()==1,"real combined routing preserves voice output and editable MIDI");
        run(mix,Json::array({op("plugin.parameter",{{"plugin",eq},{"parameter","Mid freq 1"},{"value",440}}),op("plugin.parameter",{{"plugin",eq},{"parameter","Mid gain 1"},{"value",3}}),op("plugin.parameter",{{"plugin",compressor},{"parameter","threshold"},{"value",.05}}),op("plugin.parameter",{{"plugin",compressor},{"parameter","ratio"},{"value",.25}})}));
        auto mixed=render(mix,dir,"EQ compressor Reverb Aux MIDI and pan");check(mixed.getRMSLevel(0,48000,48000)>1e-5&&mixed.getRMSLevel(1,48000,48000)>1e-5&&mixed.getMagnitude(0,frames)<1,"combined native chain outputs finite unclipped genuine PCM");
        run(mix,Json::array({op("track.mute",{{"track",synth},{"enabled",true}})}));auto audioOnly=render(mix,dir,"combined audio only");check(difference(audioOnly,mixed)>1e-3,"real MIDI instrument contributes measured audio to combined mix");
        const auto output=mix.query()["tracks"][0]["output"];auto savedMix=dir.getChildFile("combined.tracktionedit");mix.save(savedMix);Commands reopened(false);reopened.open(savedMix);check(reopened.query()["tracks"]==mix.query()["tracks"],"mixed pan processors routes automation and MIDI state restore");check(reopened.query()["tracks"][0]["output"]==output&&difference(audioOnly,render(reopened,dir,"combined audio save reopen"))<3e-6,"audio-only reopened combined chain restores PCM without claiming synth bit identity");
        auto change=run(mix,Json::array({op("automation.clear",{{"track",voice},{"parameter","pan"}}),pan(voice,-1)}));check(difference(audioOnly,render(mix,dir,"combined hard left with Aux tail"))>1e-3,"pan changes real combined effect and Aux audio");
        // The combined effect/return path changes numerical gain; compare Undo
        // with its measured baseline instead of pretending it is dry PCM.
        mix.undo(change["plan_id"]);check(difference(audioOnly,render(mix,dir,"combined pan Undo"))<3e-6,"combined pan and curve Undo restores measured effect path");
    }
    for(const char* mode:{"read","touch","latch","write"}){Commands d(true);auto t=setup(d,stereo);run(d,Json::array({pan(t,0),point(t,"$start",0,0),point(t,"$end",frames-1,0),op("automation.mode",{{"track",t},{"mode",mode}})}));auto prior=lane(d,t)["points"];d.seek(0);d.play();settle(220);check(d.query()["playing"].get<bool>()&&d.deviceStatus()["available"].get<bool>(),"live pan uses running native device transport");
        if(std::string(mode)=="read"){fails([&]{d.makePlan("human",Json::array({pan(t,-1)}));},"playing Read curve owns panner");fails([&]{d.makePlan("human",Json::array({law(t,"center_3db")}));},"playing Pan Law change rejected");d.stop();check(lane(d,t)["points"]==prior,"Read playback leaves curve unchanged");continue;}
        const auto capture=d.query()["automation_capture"]["plan_id"];d.automationControl("automation.gesture.begin",{{"track",t},{"parameter","pan"}});d.automationControl("automation.gesture.value",{{"track",t},{"parameter","pan"},{"value",-1}});settle(100);const int at=d.query()["position_samples"];settle(230);d.automationControl("automation.gesture.end",{{"track",t},{"parameter","pan"}});const int release=d.query()["position_samples"];settle(330);auto current=lane(d,t);bool touch=std::string(mode)=="touch";check(std::abs(current["value"].get<double>()-(touch?0:-1))<.01,"Touch returns; Latch and Write genuinely hold pan");d.stop();settle();auto recorded=lane(d,t)["points"];check(recorded!=prior&&d.query()["last_automation_capture"]["plan_id"]==capture,"real pan write pass commits one receipt");auto actual=render(d,dir,mode);amplitude(actual,2,0,"live written pan controls actual rendered stereo",at+2048,2400);if(touch)amplitude(actual,1,1,"Touch returns audio to original future curve",release+24000,4800);else amplitude(actual,2,0,"Latch and Write keep panned audio after release",release+12000,4800);d.undo(capture);check(lane(d,t)["points"]==prior,"one Undo restores original live pan curve");amplitude(render(d,dir,std::string(mode)+" Undo"),1,1,"live pass Undo restores centre PCM");d.redo();check(lane(d,t)["points"]==recorded,"live pass Redo retains point identities");live.push_back({{"mode",mode},{"value_sample",at},{"release_sample",release},{"receipt",d.query()["last_automation_capture"]},{"device",d.deviceStatus()}});
    }
    check(Commands::mediaHash(mono)==mh&&Commands::mediaHash(stereo)==sh,"original mono and stereo media hashes unchanged");auto elapsed=juce::Time::getMillisecondCounterHiRes()-started;check(elapsed<120000,"fixed pan qualification completes within 120 seconds");Json result={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"renders",renders},{"live",live},{"scope","real Tracktion pan PCM, native device automation and L1 transactions; no listening, MIDI hardware or endurance claim"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<result.dump(2)<<"\n";dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
