#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<"\n";}
void settle(int ms=80){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* ch:p.getChildren())if(auto* f=find(*ch,id))return f;return nullptr;}
void click(juce::Component& p,const juce::String& id){auto* b=dynamic_cast<juce::Button*>(find(p,id));if(!b||!b->isEnabled())throw std::runtime_error("button unavailable "+id.toStdString());b->triggerClick();settle();}
juce::Slider& slider(juce::Component& p,const juce::String& id){auto* b=dynamic_cast<juce::Slider*>(find(p,id));if(!b)throw std::runtime_error("pan slider unavailable");return *b;}
Json op(const char* cmd,Json a){return {{"command",cmd},{"args",a}};}
Json panLane(ndaw::desktop::Workspace& w,const std::string& id){auto q=w.queryAutomation(id);for(const auto& l:q["lanes"])if(l["parameter"]=="pan")return l;throw std::runtime_error("pan lane absent");}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    ndaw::desktop::Workspace w(false);w.setVisible(true);w.setSize(1440,1050);click(w,"track.create");std::string id=w.query()["tracks"][0]["id"];const auto control="track.pan:"+juce::String(id);auto revision=w.query()["revision"].get<uint64_t>();auto& edit=slider(w,control);check(edit.isEnabled()&&edit.getTextFromValue(0)=="C"&&edit.getTextFromValue(-.5)=="L 50"&&edit.getValueFromText("R 50")==.5,"Edit exposes real centre and L/R numeric panner");edit.setValue(-.5,juce::sendNotificationSync);settle();check(w.query()["tracks"][0]["base_pan"]==-.5&&w.query()["revision"]==revision+1,"Edit panner writes one L1 transaction");click(w,"view.mix");check(slider(w,control).getValue()==-.5,"Mix reflects same Edit panner");auto* law=dynamic_cast<juce::ComboBox*>(find(w,"track.pan_law:"+juce::String(id)));check(law&&law->getNumItems()==6&&law->isEnabled(),"Mix exposes actual native Pan Law choices");law->setSelectedId(4,juce::sendNotificationSync);settle();check(w.query()["tracks"][0]["pan_law_setting"]=="center_3db","Mix Pan Law commits real SDK setting");click(w,"history.undo");check(w.query()["tracks"][0]["pan_law_setting"]=="linear","GUI law Undo restores original law");click(w,"history.undo");check(std::abs(slider(w,control).getValue())<1e-10&&w.query()["tracks"][0]["base_pan"]==0,"one prior GUI Undo restores actual pan base");click(w,"history.redo");click(w,"view.edit");check(slider(w,control).getValue()==-.5,"Edit reflects Mix history Redo");
    auto* types=dynamic_cast<juce::ComboBox*>(find(w,"track.type"));for(int type:{5,6}){types->setSelectedId(type,juce::dontSendNotification);click(w,"track.create");auto group=w.query()["tracks"].back();check(!group["capabilities"]["pan"].get<bool>()&&find(w,"track.pan:"+juce::String(group["id"].get<std::string>()))==nullptr,"Folder and VCA have no fake GUI panner");}
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-pan-gui-"+juce::Uuid().toString());dir.createDirectory();
    for(const char* mode:{"touch","latch","write"}){auto saved=dir.getChildFile(juce::String(mode)+".tracktionedit");std::string track;
        {Commands c(false);c.commit(c.makePlan("human",Json::array({op("track.create",{{"name","Pan gesture"},{"ref","$t"}}),op("automation.mode",{{"track","$t"},{"mode",mode}}),op("automation.point.add",{{"track","$t"},{"parameter","pan"},{"ref","$a"},{"position_samples",0},{"value",0},{"curve",0}}),op("automation.point.add",{{"track","$t"},{"parameter","pan"},{"ref","$b"},{"position_samples",144000},{"value",0},{"curve",0}})})));track=c.query()["tracks"][0]["id"];c.save(saved);}
        ndaw::desktop::Workspace live(true);live.setVisible(true);live.setSize(1440,1050);live.openSession(saved);if(std::string(mode)!="touch")click(live,"view.mix");auto prior=panLane(live,track)["points"];click(live,"transport.play");settle(180);auto capture=live.query()["automation_capture"];check(!capture.is_null(),"GUI starts real automation capture");auto& p=slider(live,"track.pan:"+juce::String(track));check(p.isEnabled(),"native live panner enabled in supported write mode");p.onDragStart();p.setValue(.75,juce::sendNotificationSync);settle(230);p.onDragEnd();settle(330);check(std::abs(panLane(live,track)["value"].get<double>()-(std::string(mode)=="touch"?0:.75))<.01,"GUI pan gesture obeys Touch return or Latch/Write hold");click(live,"transport.stop");auto recorded=panLane(live,track)["points"];check(recorded!=prior&&live.query()["last_automation_capture"]["plan_id"]==capture["plan_id"],"GUI pan Stop publishes real curve receipt");click(live,"history.undo");check(panLane(live,track)["points"]==prior,"one GUI Undo reverses entire pan write pass");click(live,"history.redo");check(panLane(live,track)["points"]==recorded,"GUI Redo preserves recorded curve IDs");
    }
    Json result={{"result","passed"},{"checks",checks},{"scope","production Edit/Mix L1 pan controls and genuine native device automation; PCM tested separately"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<result.dump(2)<<"\n";dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
