#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;
namespace ndaw::v2 {
// Tests alone obtain SDK objects to exercise actual bypass entry points.
class ParameterTestAccess {public:static te::AutomatableParameter& get(Commands& c,const std::string& plugin,const std::string& parameter){
    for(auto* p:te::getAllPlugins(*c.edit,true))if(p->itemID.toString().toStdString()==plugin)if(auto a=p->getAutomatableParameterByID(juce::String(parameter)))return *a;
    throw std::runtime_error("test parameter missing");
}};
}
namespace {
int checks=0,serial=0;Json renders=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
void settle(int ms=70){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json op(const char* cmd,Json args){return {{"command",cmd},{"args",args}};}
Json run(Commands& c,Json ops,const char* actor="human"){auto p=c.makePlan(actor,ops);c.commit(p,std::string(actor)!="human");settle();return p;}
Json parameter(Commands& c,const std::string& plugin,const char* id){auto q=c.query();for(const auto& t:q["tracks"])for(const auto& p:t["plugins"])if(p["id"]==plugin)for(const auto& a:p["parameters"])if(a["id"]==id)return a;throw std::runtime_error("query parameter absent");}
void fixture(const juce::File& file){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture writer failed");juce::AudioBuffer<float> data(2,96000);for(int c=0;c<2;++c)for(int i=0;i<96000;++i)data.setSample(c,i,.1f*std::sin(2*juce::MathConstants<double>::pi*1000*i/48000));check(writer->writeFromAudioSampleBuffer(data,0,96000),"known PCM written to a real file");}
double audio(Commands& c,const juce::File& dir){auto file=dir.getChildFile("render-"+juce::String(++serial)+".wav");auto r=c.render(file,0,96000);check(r["frames"]==96000&&r["render_ms"].get<double>()<10000,"real renderer meets fixed frame and time budgets");renders.push_back(r);juce::AudioFormatManager fm;fm.registerBasicFormats();std::unique_ptr<juce::AudioFormatReader> reader(fm.createReaderFor(file));if(!reader)throw std::runtime_error("render unreadable");juce::AudioBuffer<float> data(2,96000);reader->read(&data,0,96000,0,true,true);return data.getRMSLevel(0,24000,24000);}
std::pair<std::string,std::string> setup(Commands& c,const juce::File& source){run(c,Json::array({op("track.create",{{"name","Native parameter PCM"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}}),op("plugin.insert",{{"track","$t"},{"type",te::EqualiserPlugin::xmlTypeName}})}));auto t=c.query()["tracks"][0];auto plugin=t["plugins"][0]["id"].get<std::string>();run(c,Json::array({op("plugin.parameter",{{"plugin",plugin},{"parameter","Mid freq 1"},{"value",1000}})}));return {t["id"],plugin};}
Json lane(Commands& c,const std::string& track,const std::string& parameter){auto q=c.automationQuery(track);for(const auto& p:q["lanes"])if(p["parameter"]==parameter)return p;throw std::runtime_error("lane absent");}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-parameter-"+juce::Uuid().toString());dir.createDirectory();auto source=dir.getChildFile("known.wav");fixture(source);auto hash=Commands::mediaHash(source);
    Commands c(false);auto [track,plugin]=setup(c,source);auto& gain=ParameterTestAccess::get(c,plugin,"Mid gain 1");auto& freq=ParameterTestAccess::get(c,plugin,"Mid freq 1");
    check(c.query()["last_parameter_capture"].is_null(),"owned Plans do not create duplicate human captures");double baseline=audio(c,dir);auto oldPlan=c.makePlan("agent:stale",Json::array({op("track.gain",{{"track",track},{"db",-3}})}));auto rev=c.query()["revision"];
    gain.parameterChangeGestureBegin();check(c.query()["parameter_capture"]["actor"]=="human"&&c.query()["revision"]>rev,"actual SDK gesture starts human boundary and invalidates plans immediately");
    fails([&]{c.commit(oldPlan,true);},"old Agent Plan cannot interleave with a native gesture");fails([&]{c.undo();},"Undo cannot split a native gesture");fails([&]{c.save(dir.getChildFile("busy.tracktionedit"));},"save cannot publish a half-finished gesture");
    gain.setParameter(3,juce::sendNotification);settle(450);gain.setParameter(6,juce::sendNotification);check(parameter(c,plugin,"Mid gain 1")["value"]==6,"actual SDK writes reach explicit value immediately");
    gain.parameterChangeGestureEnd();auto receipt=c.query()["last_parameter_capture"];check(receipt["state"]=="committed"&&receipt["source"]=="sdk-parameter"&&receipt["changes"].size()==1,"long gesture remains one named human capture");check(receipt["changes"][0]["before"]==0&&receipt["changes"][0]["value"]==6&&receipt["changes"][0]["plugin"]==plugin,"capture preserves actual object IDs and before after values");
    fails([&]{c.commit(oldPlan,true);},"completed human edit rejects a stale Agent version");double boosted=audio(c,dir);double delta=20*std::log10(boosted/baseline);check(std::abs(delta-6)<.01,"captured EQ gesture changes real PCM by six dB");
    c.undo(receipt["plan_id"]);check(parameter(c,plugin,"Mid gain 1")["value"]==0&&c.query()["last_parameter_capture"]["state"]=="undone","one Undo restores real explicit base and receipt");check(std::abs(audio(c,dir)-baseline)<3e-6,"Undo restores real DSP rather than only the display");c.redo();check(parameter(c,plugin,"Mid gain 1")["value"]==6&&c.query()["last_parameter_capture"]["state"]=="committed","Redo restores DSP base and same capture identity");
    auto agent=run(c,Json::array({op("track.gain",{{"track",track},{"db",-3}})}),"agent:accepted");freq.midiControllerMoved(freq.valueRange.convertTo0to1(1200));auto controller=c.query()["last_parameter_capture"];check(std::abs(parameter(c,plugin,"Mid freq 1")["value"].get<float>()-1200)<.002&&controller["plan_id"]!=receipt["plan_id"],"actual SDK controller movement creates a separate human transaction");fails([&]{c.undo(agent["plan_id"]);},"selective Agent Undo protects subsequent human controller edit");c.undo(controller["plan_id"]);check(parameter(c,plugin,"Mid freq 1")["value"]==1000,"controller transaction Undo restores its original value");c.undo(agent["plan_id"]);check(std::abs(c.query()["tracks"][0]["gain_db"].get<double>())<.001,"Agent Undo works after newer human transaction is explicitly undone");c.redo();c.redo();
    auto snapshot=c.query()["tracks"];auto sameRev=c.query()["revision"];gain.setParameter(6,juce::sendNotification);check(c.query()["revision"]==sameRev&&c.query()["tracks"]==snapshot,"spurious unchanged SDK notification has no fake edit");gain.setParameter(std::numeric_limits<float>::quiet_NaN(),juce::sendNotification);check(c.query()["parameter_failure"]["state"]=="failed"&&c.query()["tracks"]==snapshot,"invalid native value fails without changing Edit");gain.setParameter(99,juce::sendNotification);check(parameter(c,plugin,"Mid gain 1")["value"]==6,"out of range SDK value cannot be silently accepted");
    std::thread worker([&]{gain.parameterChangeGestureBegin();gain.setParameter(-6,juce::sendNotification);gain.parameterChangeGestureEnd();});worker.join();check(c.query()["tracks"]==snapshot&&c.query()["revision"]==sameRev,"off-thread SDK requests are rejected before Edit mutation");
    gain.parameterChangeGestureBegin();freq.parameterChangeGestureBegin();gain.setParameter(2,juce::sendNotification);freq.setParameter(800,juce::sendNotification);gain.parameterChangeGestureEnd();check(!c.query()["parameter_capture"].is_null(),"overlapping native gestures retain shared transaction until all end");freq.parameterChangeGestureEnd();auto shared=c.query()["last_parameter_capture"];check(shared["changes"].size()==2,"one human transaction captures both actual parameters");c.undo(shared["plan_id"]);check(parameter(c,plugin,"Mid gain 1")["value"]==6&&std::abs(parameter(c,plugin,"Mid freq 1")["value"].get<float>()-1200)<.002,"multi parameter Undo restores both bases together");
    gain.parameterChangeGestureBegin();gain.parameterChangeGestureEnd();check(c.query()["last_parameter_capture"]["state"]=="no_changes"&&c.query()["can_redo"],"empty gesture creates no fake transaction and retains Redo");c.redo();check(parameter(c,plugin,"Mid gain 1")["value"]==2,"Redo remains executable after empty gesture");
    gain.parameterChangeGestureBegin();gain.setParameter(4,juce::sendNotification);c.stop();auto stopped=c.query()["last_parameter_capture"];check(stopped["state"]=="committed"&&stopped["interrupted"]&&c.query()["parameter_capture"].is_null(),"Stop closes unfinished native gesture with an explicit receipt");c.undo(stopped["plan_id"]);check(parameter(c,plugin,"Mid gain 1")["value"]==2,"interrupted gesture Undo remains one real transaction");c.redo();
    auto saved=dir.getChildFile("native.tracktionedit");c.save(saved);c.undo();check(parameter(c,plugin,"Mid gain 1")["value"]==2,"Save adds no untracked transaction above native history");c.redo();{Commands reopened(false);reopened.open(saved);check(parameter(reopened,plugin,"Mid gain 1")["value"]==4,"save reopen retains captured native parameter base");auto& p=ParameterTestAccess::get(reopened,plugin,"Mid gain 1");p.setParameter(5,juce::sendNotification);reopened.undo();check(parameter(reopened,plugin,"Mid gain 1")["value"]==4,"interception reattaches to newly opened Edit");}
    auto fader=lane(c,track,"volume");auto& volume=ParameterTestAccess::get(c,fader["owner"],"volume");double priorDb=c.query()["tracks"][0]["gain_db"];
    volume.midiControllerMoved(te::decibelsToVolumeFaderPosition(-9));auto faderReceipt=c.query()["last_parameter_capture"];
    check(std::abs(c.query()["tracks"][0]["gain_db"].get<double>()+9)<.002,"native controller fader value uses actual SDK nonlinear scale");
    c.undo(faderReceipt["plan_id"]);check(std::abs(c.query()["tracks"][0]["gain_db"].get<double>()-priorDb)<.002,"native fader Undo restores original audible gain");
    for(const char* mode:{"touch","latch"}){Commands live(true);auto [id,fx]=setup(live,source);run(live,Json::array({op("automation.mode",{{"track",id},{"mode",mode}})}));std::string param=std::string(mode)=="latch"?"volume":"Mid gain 1";auto facts=lane(live,id,param);auto before=facts["points"];auto& p=ParameterTestAccess::get(live,facts["owner"],param);float writeValue=param=="volume"?te::decibelsToVolumeFaderPosition(-12):6;live.play();settle(150);auto capture=live.query()["automation_capture"]["plan_id"];p.parameterChangeGestureBegin();p.setParameter(writeValue,juce::sendNotification);check(std::abs(lane(live,id,param)["explicit_value"].get<double>()-(param=="volume"?-12:6))<.002,"native automation value converts enumerated units correctly");settle(220);p.parameterChangeGestureEnd();settle(250);live.stop();check(live.query()["last_parameter_capture"].is_null()&&live.query()["last_automation_capture"]["plan_id"]==capture,"native write gestures join existing automation pass without duplicate history");check(lane(live,id,param)["points"]!=before,"native gestures produce actual automation points");live.undo(capture);check(lane(live,id,param)["points"]==before,"native automation gestures undo with the whole pass");live.redo();
        run(live,Json::array({op("automation.mode",{{"track",id},{"mode","read"}})}));auto revision=live.query()["revision"];live.seek(0);live.play();settle(250);check(live.query()["revision"]==revision&&live.query()["parameter_capture"].is_null(),"automatic Read stream does not masquerade as human edits");p.parameterChangeGestureBegin();p.setParameter(param=="volume"?te::decibelsToVolumeFaderPosition(-6):3,juce::sendNotification);check(live.query()["parameter_failure"]["state"]=="failed"&&live.query()["revision"]==revision,"Read playing curve blocks bypass user writes");live.stop();
    }
    fails([&]{c.parameterControl("parameter.gesture.value",{{"plugin",plugin},{"parameter","warmth"},{"value",1}});},"GUI boundary cannot invent plugin parameter IDs");check(Commands::mediaHash(source)==hash,"native parameter editing preserves source media hash");
    Json result={{"result","passed"},{"checks",checks},{"eq_delta_db",delta},{"receipt",receipt},{"renders",renders},{"scope","actual SDK parameter and controller methods, real PCM, Undo/Redo and CoreAudio automation; external plugin windows and physical controllers unexecuted"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);}std::cout<<result.dump(2)<<std::endl;dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
