#include "ProcessedEventsFixture.h"
#include <nativedaw/v2/SourceFeatures.h>
#include <nativedaw/v2/McpSession.h>
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;namespace fx=processed_fixture;
namespace {
int checks=0;Json evidence=Json::array();double maxJob=0,maxRpc=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void rejects(F f,const char* why){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,why);}
void pump(int ms=10){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json op(const char* command,Json args){return {{"command",command},{"args",args}};}
void commit(Commands& c,Json ops){c.commit(c.makePlan("human",ops));}
Json request(Commands& c,const char* key){return {{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]},{"start_samples",29013},{"end_samples",124013},{"request_key",key},{"detector_profile",Json::object()}};}
Json wait(Commands& c){const auto began=juce::Time::getMillisecondCounterHiRes();while(c.analysisStatus().value("busy",false)){if(juce::Time::getMillisecondCounterHiRes()-began>12000)throw std::runtime_error("processed event job exceeds fixed 12 seconds");pump();}maxJob=std::max(maxJob,juce::Time::getMillisecondCounterHiRes()-began);return c.analysisStatus();}
Json measure(Commands& c,const std::string& track,const char* tap,const char* key){auto args=request(c,key);args["track"]=track;args["tap_point"]=tap;c.analysisControl("track",args);auto status=wait(c);if(status["state"]!="completed")throw std::runtime_error(status.dump());auto receipt=status["receipt"];check(receipt["current"].get<bool>()&&receipt["frames"]==95000&&receipt["binding"]["tap_point"]==tap&&receipt["processed_event_detection_enabled"].get<bool>(),"actual native tap has current exact-range processed event receipt");evidence.push_back(receipt);return receipt;}
void expect(const Json& receipt,const juce::AudioBuffer<float>& pcm,float gain,int delay){
    check(fx::intervals(receipt,"silence")==fx::silence(pcm,48000,29013,124013,29013,24000,gain,delay),"all rendered silence boundaries equal independent gain/position/delay PCM prediction");
    check(fx::intervals(receipt,"transient_candidate")==fx::onsets(48000,29013,29013,24000,delay),"rendered transient onset and complete-window end map to exact session samples");
    check(receipt["processed_features"]["profile_sha256"]==receipt["binding"]["detector_profile_sha256"]&&!receipt.contains("source_features")&&!receipt["processed_features"]["qualifies_performance_quality"].get<bool>()&&!receipt["processed_features"]["qualifies_breath_detection"].get<bool>(),"conditions hash binds actual evidence with no original-source or quality claim");
}
Json rpc(McpSession& session,const char* method,Json params){static int id=0;const int key=++id;const auto began=juce::Time::getMillisecondCounterHiRes();std::vector<Json> output;std::thread worker([&]{output=session.receive(Json{{"jsonrpc","2.0"},{"id",key},{"method",method},{"params",params}}.dump());});worker.join();while(output.empty()){if(juce::Time::getMillisecondCounterHiRes()-began>5000)throw std::runtime_error("MCP reply exceeds fixed 5 seconds");pump();output=session.ready();}maxRpc=std::max(maxRpc,juce::Time::getMillisecondCounterHiRes()-began);for(const auto& item:output)if(item.value("id",Json(nullptr))==key)return item;throw std::runtime_error("MCP ID mismatch");}
void numerical(const juce::File& folder){for(int rate:{44100,48000,96000}){
    const auto pcm=fx::pcm(rate);const auto file=folder.getChildFile("events-"+juce::String(rate)+".wav");fx::write(file,pcm,rate);const int64_t begin=rate/10+13,end=rate*21/10+13,origin=34567;auto r=analysis::measure(file,origin,{}, {begin,end},Json::object(),analysis::FeatureDomain::SessionSamples);
    check(r["event_counts"]["silence"]==3&&r["event_counts"]["transient_candidate"]==2&&r["event_count"]==5,"real native-rate PCM produces exact measured/estimated family counts");
    check(fx::intervals(r,"silence")==fx::silence(pcm,rate,begin,end,origin),"all nonzero-range silence boundaries convert from actual rate to session samples");check(fx::intervals(r,"transient_candidate")==fx::onsets(rate,begin,origin),"known transient onset and window end convert independently at 44.1/48/96 kHz");
    bool proper=true;for(const auto& e:r["events"])proper&=!e.contains("source_start_frame")&&!e.contains("source_end_frame")&&e["start_samples"].get<int64_t>()==origin+std::llround(e["render_start_frame"].get<int64_t>()*48000./rate)&&e["estimated"].get<bool>()==(e["kind"]=="transient_candidate");check(proper,"processed frame references identify rendered PCM and label candidate estimates");evidence.push_back(r);
    rejects([&]{analysis::measure(file,9007199254740991LL,{}, {begin,end},Json::object(),analysis::FeatureDomain::SessionSamples);},"session origin overflow rejects imprecise positions");
    analysis::Control stop;stop.cancelled=[] {return true;};rejects([&]{analysis::measure(file,origin,stop, {begin,end},Json::object(),analysis::FeatureDomain::SessionSamples);},"actual decoded event measurement observes cancellation");
}
    juce::AudioBuffer<float> dense(2,48000*20);dense.clear();for(int n=1200;n<dense.getNumSamples();n+=9600)dense.setSample(0,n,1.25f);const auto file=folder.getChildFile("dense.wav");fx::write(file,dense,48000);auto r=analysis::measure(file,123,{}, {},Json::object(),analysis::FeatureDomain::SessionSamples);
    check(r["event_counts"]["full_scale_exceedance"]==100&&r["event_counts"]["silence"]==100&&r["event_counts"]["transient_candidate"]==100&&r["event_count"]==300&&r["events"].size()==128&&r["events_omitted"]==172,"merged fullscale/silence/transient output stays bounded with exact total and omission counts");bool sorted=true;for(size_t i=0;i<r["events"].size();++i)sorted&=r["events"][i]["id"]==i&&(i==0||r["events"][i-1]["start_samples"]<=r["events"][i]["start_samples"]);check(sorted,"bounded retained events are sorted with usable stable receipt-local IDs");evidence.push_back(r);
}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-processed-events-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();numerical(folder);const auto pcm=fx::pcm(48000);const auto source=folder.getChildFile("actual-chain.wav");fx::write(source,pcm,48000);const auto hash=Commands::mediaHash(source);Commands c(false);
    commit(c,Json::array({op("track.create",{{"name","Actual vocal pulses"},{"ref","$v"}}),op("clip.import",{{"track","$v"},{"path",source.getFullPathName().toStdString()},{"position_samples",24000}}),op("track.gain",{{"track","$v"},{"db",-18}})}));auto facts=c.query();const std::string track=facts["tracks"][0]["id"],clip=facts["tracks"][0]["clips"][0]["id"];commit(c,Json::array({op("clip.gain",{{"clip",clip},{"db",12}})}));const auto initial=c.query();const float clipGain=juce::Decibels::decibelsToGain(12.f),fader=juce::Decibels::decibelsToGain(-18.f);
    auto pre=measure(c,track,"track_pre_inserts","pre");expect(pre,pcm,clipGain,0);check(pre["event_counts"]["silence"]==4,"Clip Gain elevates the low pulse above silence threshold in actual pre-insert PCM");auto bus=measure(c,track,"bus","bus");expect(bus,pcm,clipGain*fader,0);check(bus["event_counts"]["silence"]==3,"actual fader drops the same pulse back below silence threshold at Bus output");check(c.query()["revision"]==initial["revision"]&&c.query()["tracks"]==initial["tracks"],"actual analysis creates no Edit/history transaction");
    commit(c,Json::array({op("plugin.insert",{{"track",track},{"type",te::DelayPlugin::xmlTypeName}})}));const std::string delay=c.query()["tracks"][0]["plugins"][0]["id"];commit(c,Json::array({op("plugin.parameter",{{"plugin",delay},{"parameter","feedback"},{"value",-30}}),op("plugin.parameter",{{"plugin",delay},{"parameter","mix proportion"},{"value",1}})}));
    auto post=measure(c,track,"track_post_inserts","wet-delay");expect(post,pcm,clipGain,7200);auto unchangedPre=measure(c,track,"track_pre_inserts","dry-before-delay");expect(unchangedPre,pcm,clipGain,0);check(fx::intervals(pre,"transient_candidate")==fx::intervals(unchangedPre,"transient_candidate")&&fx::intervals(post,"transient_candidate")!=fx::intervals(pre,"transient_candidate"),"wet Delay shifts real post-insert candidates while pre-insert evidence remains dry");
    auto raw=request(c,"raw");raw.erase("detector_profile");raw.erase("start_samples");raw.erase("end_samples");raw["clip"]=clip;raw["source_start_frame"]=5013;raw["source_end_frame"]=100013;c.analysisControl("source",raw);auto rawReceipt=wait(c)["receipt"];check(rawReceipt["event_counts"]["silence"]==3&&fx::intervals(rawReceipt,"transient_candidate","source_start_frame","source_end_frame")[0][0]==12000&&!rawReceipt.contains("processed_features"),"raw source events retain unprocessed native frames independently of gain/fader/Delay");
    auto retry=request(c,"retry");retry["track"]=track;retry["tap_point"]="bus";auto pending=c.analysisControl("track",retry,"agent:events");auto normalized=retry;normalized["detector_profile"]=analysis::sourceProfile(Json::object());check(c.analysisControl("track",normalized,"agent:events")["request"]["artifact_id"]==pending["request"]["artifact_id"],"empty and explicit normalized default profiles share one idempotent real job");auto changed=retry;changed["detector_profile"]={{"silence_threshold_dbfs",-50}};rejects([&]{c.analysisControl("track",changed,"agent:events");},"same-key retry cannot change measured event conditions");c.analysisControl("cancel",{{"artifact_id",pending["request"]["artifact_id"]}},"agent:events");check(wait(c)["state"]=="cancelled","processed events cancel with actual terminal receipt");
    auto invalid=request(c,"invalid");invalid["track"]=track;invalid["tap_point"]="bus";for(auto bad:std::initializer_list<Json>{nullptr,{{"unknown",1}},{{"minimum_silence_ms",0}},{{"transient_rise_db",NAN}}}){invalid["detector_profile"]=bad;rejects([&]{c.analysisControl("track",invalid);},"invalid detector conditions cannot replace evidence or create success");}
    auto disabled=request(c,"disabled");disabled.erase("detector_profile");c.analysisControl("master",disabled);auto noDetection=wait(c)["receipt"];check(!noDetection["processed_event_detection_enabled"].get<bool>()&&noDetection["event_counts"]["silence"].is_null()&&noDetection["event_counts"]["transient_candidate"].is_null()&&!noDetection.contains("processed_features"),"omitted conditions mean unanalysed events rather than fabricated absence");evidence.push_back(noDetection);
    CommandQueue queue(c);Scope read;read.mode=Permission::ReadOnly;McpSession session(queue.connect("agent:events",read),Commands::registry());rpc(session,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","processed-events-tests"},{"version","1"}}}});session.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());bool registered=false;Json pageArgs=Json::object();while(true){const auto page=rpc(session,"tools/list",pageArgs)["result"];for(const auto& tool:page["tools"])if(tool["name"]=="analyze_delivery")registered=tool["inputSchema"]["properties"].contains("detector_profile");if(!page.contains("nextCursor"))break;pageArgs["cursor"]=page["nextCursor"];}check(registered,"MCP tool schema is generated from actual detector command registration");
    auto response=rpc(session,"tools/call",{{"name","analyze_delivery"},{"arguments",request(c,"mcp-delivery")}});check(!response["result"]["isError"].get<bool>(),"read-only actual MCP enables processed event delivery evidence");check(wait(c)["state"]=="completed","real MCP delivery worker completes with actual PCM");auto receipt=rpc(session,"tools/call",{{"name","query_analysis"},{"arguments",Json::object()}})["result"]["structuredContent"]["result"]["receipt"];expect(receipt,pcm,clipGain*fader,7200);check(receipt.contains("delivery")&&receipt["delivery"]["checks"].size()==4&&receipt["over_full_scale_frames"]==0&&receipt["event_count"].get<int>()>0,"delivery rule does not misclassify silence/transient events as clipping risk");evidence.push_back(receipt);
    Json onset;for(const auto& e:receipt["events"])if(e["kind"]=="transient_candidate"){onset=e;break;}c.analysisControl("locate",{{"artifact_id",receipt["artifact_id"]},{"event_id",onset["id"]}});check(c.query()["position_samples"]==43200,"processed candidate locates actual Transport at delayed material onset");commit(c,Json::array({op("track.gain",{{"track",track},{"db",-6}})}));check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"interleaved human gain invalidates processing evidence");rejects([&]{c.analysisControl("locate",{{"artifact_id",receipt["artifact_id"]},{"event_id",onset["id"]}});},"stale processed onset cannot silently seek after human change");c.undo();check(!c.analysisStatus()["receipt"]["current"].get<bool>()&&std::abs(c.query()["tracks"][0]["gain_db"].get<double>()+18)<1e-5,"Undo restores human value while old processed evidence stays stale at new revision");
    const auto saved=folder.getChildFile("events.tracktionedit");c.save(saved);c.open(saved);check(c.analysisStatus()["state"]=="idle"&&c.query()["tracks"][0]["plugins"].size()==1&&Commands::mediaHash(source)==hash,"save/reopen retains real chain without reviving receipts or changing original media");const double elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<120000,"processed event backend qualification retains fixed 120-second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"max_job_ms",maxJob},{"max_mcp_reply_ms",maxRpc},{"evidence",evidence},{"scope","actual PCM, Tracktion native graph and MCP; production desktop/model qualification separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<report.dump(2)<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<std::endl;folder.deleteRecursively();return 1;}}
