#include "Workspace.h"
#include "ProcessedEventsFixture.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;using namespace ndaw::desktop;namespace fx=processed_fixture;
namespace {
int checks=0;double maxJob=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
void pump(int ms=30){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* child:p.getChildren())if(auto* found=find(*child,id))return found;return nullptr;}
void click(Workspace& w,const juce::String& id){auto* b=dynamic_cast<juce::Button*>(find(w,id));if(!b||!b->isEnabled())throw std::runtime_error("native button unavailable: "+id.toStdString());auto callback=b->onClick;bool delivered=false;b->onClick=[&]{delivered=true;callback();};b->triggerClick();const auto deadline=juce::Time::getMillisecondCounterHiRes()+1000;while(!delivered&&juce::Time::getMillisecondCounterHiRes()<deadline)pump(1);b->onClick=callback;check(delivered,"actual native asynchronous callback delivered");pump();}
juce::TextEditor& field(Workspace& w,const char* id){auto* f=dynamic_cast<juce::TextEditor*>(find(w,id));if(!f)throw std::runtime_error(std::string("native field unavailable: ")+id);return *f;}
void value(Workspace& w,const char* id,const char* text){auto& f=field(w,id);static_cast<juce::Component*>(&f)->focusGained(juce::Component::focusChangedDirectly);f.setText(text,true);}
juce::ComboBox& combo(Workspace& w,const char* id){auto* c=dynamic_cast<juce::ComboBox*>(find(w,id));if(!c)throw std::runtime_error(std::string("native chooser unavailable: ")+id);return *c;}
Json wait(Workspace& w){const auto began=juce::Time::getMillisecondCounterHiRes();while(w.queryAnalysis().value("busy",false)){if(juce::Time::getMillisecondCounterHiRes()-began>12000)throw std::runtime_error("native event job exceeds fixed 12 seconds");pump(10);}maxJob=std::max(maxJob,juce::Time::getMillisecondCounterHiRes()-began);pump(300);return w.queryAnalysis();}
void range(Workspace& w){field(w,"analysis.start_samples").setText("29013");field(w,"analysis.end_samples").setText("124013");}
class Storage final:public te::PropertyStorage{public:explicit Storage(juce::File f):PropertyStorage("Forma processed events UI"),folder(f){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-event-ui-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();const auto source=folder.getChildFile("actual-pulses.wav");const auto pcm=fx::pcm(48000);fx::write(source,pcm,48000);const auto hash=Commands::mediaHash(source);Workspace w(false,std::make_unique<Storage>(folder.getChildFile("prefs")));w.setSize(1120,700);w.setVisible(true);w.prepareImport(source);pump();click(w,"plan.accept");const std::string track=w.query()["tracks"][0]["id"],clip=w.query()["tracks"][0]["clips"][0]["id"];click(w,"clip.select:"+juce::String(clip));value(w,"clip.position","24000");click(w,"clip.move");value(w,"clip.gain.db","12");click(w,"clip.gain");auto* fader=dynamic_cast<juce::Slider*>(find(w,"track.gain:"+juce::String(track)));check(fader,"actual native fader available");fader->setValue(-18,juce::sendNotificationSync);pump();const auto initial=w.query();
    w.showAnalysis();combo(w,"analysis.tap").setSelectedId(3,juce::sendNotificationSync);pump();auto* enabled=dynamic_cast<juce::ToggleButton*>(find(w,"analysis.events.enabled"));check(enabled&&!enabled->getToggleState()&&!find(w,"analysis.events.silence_ms")&&!find(w,"source.silence_ms"),"optional processed detector starts off without misleading source controls");click(w,"analysis.events.enabled");check(enabled->getToggleState()&&find(w,"analysis.events.silence_ms")&&!find(w,"analysis.delivery.run"),"native detector toggle exposes five actual conditions for selected track tap");
    range(w);click(w,"analysis.track.run");auto state=wait(w);if(state["state"]!="completed")throw std::runtime_error(state.dump());auto pre=state["receipt"];check(pre["current"].get<bool>()&&pre["event_counts"]["silence"]==4&&pre["event_counts"]["transient_candidate"]==2&&fx::intervals(pre,"silence")==fx::silence(pcm,48000,29013,124013,29013,24000,juce::Decibels::decibelsToGain(12.f)),"native GUI produces exact independently predicted processed event boundaries");check(field(w,"analysis.summary").getText().contains("处理后事件")&&field(w,"analysis.summary").getText().contains("工程采样位置")&&field(w,"analysis.summary").getText().contains("条件 SHA256")&&field(w,"analysis.summary").getText().contains("不是呼吸识别"),"native summary states real processing domain conditions and estimate limits");check(w.query()["revision"]==initial["revision"]&&w.query()["tracks"]==initial["tracks"],"native detector does not edit active tracks or history");Json onset;for(const auto& e:pre["events"])if(e["kind"]=="transient_candidate"){onset=e;break;}auto* locate=find(w,"analysis.locate:"+juce::String(onset["id"].get<int>()));check(locate&&dynamic_cast<juce::Button*>(locate)->getButtonText().contains("瞬态候选 / 估计"),"native event row labels measured silence and estimated transients individually");click(w,"analysis.locate:"+juce::String(onset["id"].get<int>()));check(w.query()["position_samples"]==36000&&!find(w,"analysis.panel"),"real event callback locates Transport at actual material onset");
    value(w,"clip.position","30000");click(w,"clip.move");w.showAnalysis();pump();check(!w.queryAnalysis()["receipt"]["current"].get<bool>()&&!find(w,"analysis.locate:"+juce::String(onset["id"].get<int>()))->isEnabled(),"interleaved human clip move disables obsolete processed event location");check(find(w,"analysis.events.silence_ms")&&field(w,"analysis.events.silence_ms").getText().getDoubleValue()==100,"opening stored processed receipt restores actual detector conditions");click(w,"analysis.close");click(w,"history.undo");check(w.query()["tracks"][0]["clips"][0]["start_samples"]==24000&&!w.queryAnalysis()["receipt"]["current"].get<bool>(),"human Undo restores clip but cannot revive a stale analysis version");w.showAnalysis();range(w);click(w,"analysis.track.run");state=wait(w);check(state["state"]=="completed"&&state["receipt"]["current"].get<bool>()&&state["receipt"]["artifact_id"]!=pre["artifact_id"]&&fx::intervals(state["receipt"],"transient_candidate")==fx::intervals(pre,"transient_candidate"),"native remeasurement produces a new current receipt at restored material location");const auto current=state["receipt"];
    field(w,"analysis.events.silence_ms").setText("0");click(w,"analysis.track.run");pump(300);check(!w.queryAnalysis()["busy"].get<bool>()&&w.queryAnalysis()["receipt"]["artifact_id"]==current["artifact_id"]&&field(w,"analysis.summary").getText().contains("操作未完成"),"invalid native condition fails visibly and preserves measured artifact");field(w,"analysis.events.silence_ms").setText("100");click(w,"analysis.events.enabled");click(w,"analysis.track.run");state=wait(w);check(state["state"]=="completed"&&!state["receipt"]["processed_event_detection_enabled"].get<bool>()&&state["receipt"]["event_counts"]["silence"].is_null()&&field(w,"analysis.summary").getText().contains("本次未检测"),"disabled GUI detector returns explicit unanalysed state instead of fake zero events");
    click(w,"analysis.track.run");click(w,"analysis.cancel");check(wait(w)["state"]=="cancelled","native cancellation waits for actual terminal receipt");combo(w,"analysis.tap").setSelectedId(2,juce::sendNotificationSync);check(find(w,"source.silence_ms")&&!find(w,"analysis.events.enabled")&&field(w,"analysis.end_samples").getText()=="144000","source mode retains native file-frame contract and original controls");combo(w,"analysis.tap").setSelectedId(1,juce::sendNotificationSync);click(w,"analysis.events.enabled");const auto eventsBounds=find(w,"analysis.events.silence_ms")->getBounds(),deliveryBounds=find(w,"delivery.target_lufs")->getBounds(),summaryBounds=find(w,"analysis.summary")->getBounds(),toggleBounds=find(w,"analysis.events.enabled")->getBounds();check(!eventsBounds.intersects(deliveryBounds)&&!eventsBounds.intersects(summaryBounds)&&toggleBounds.getRight()<=1120&&find(w,"analysis.delivery.run"),"Master delivery and detector controls fit minimum window without overlapping");check(Commands::mediaHash(source)==hash,"all native event workflows preserve original PCM");const double elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"native event workflow retains fixed sixty-second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"max_job_ms",maxJob},{"pre",pre},{"remeasured",current},{"scope","actual native JUCE callbacks and Tracktion graph; desktop/model demonstration separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<report.dump(2)<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<std::endl;folder.deleteRecursively();return 1;}}
