#include "Workspace.h"
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;
namespace ndaw::v2 {
class RecordingTestAccess {
public:
    static te::HostedAudioDeviceInterface& host(ndaw::desktop::Workspace& w,const juce::File& directory){w.recordDirectory=directory;auto& dm=w.commands.engine.getDeviceManager();auto& h=dm.getHostedAudioDeviceInterface();te::HostedAudioDeviceInterface::Parameters p;p.sampleRate=48000;p.blockSize=256;p.inputChannels=2;h.initialise(p);dm.setAllWaveInputsToNumChannels(1);for(auto* i:dm.getWaveInputDevices()){i->setEnabled(true);i->setMonitorMode(te::InputDevice::MonitorMode::off);i->setOutputFormat("WAV file");i->setBitDepth(24);i->setRecordTriggerDb(-60);}return h;}
};
}
namespace {
int checks=0;void check(bool b,const char* s){if(!b)throw std::runtime_error(s);++checks;std::cout<<"PASS "<<s<<std::endl;}
void settle(int ms=90){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* c:p.getChildren())if(auto* f=find(*c,id))return f;return nullptr;}
void click(juce::Component& p,const char* id){auto* b=dynamic_cast<juce::Button*>(find(p,id));if(!b||!b->isEnabled())throw std::runtime_error(std::string("button unavailable: ")+id);b->triggerClick();settle();}
juce::ComboBox& combo(juce::Component& p,const char* id){auto* c=dynamic_cast<juce::ComboBox*>(find(p,id));if(!c||!c->isEnabled())throw std::runtime_error(std::string("combo unavailable: ")+id);return *c;}
struct Feed{explicit Feed(te::HostedAudioDeviceInterface& h):thread([this,&h]{juce::AudioBuffer<float> b(2,256);juce::MidiBuffer m;int n=0;while(!stop){for(int i=0;i<256;++i)for(int c=0;c<2;++c)b.setSample(c,i,float(.1*std::sin(2*juce::MathConstants<double>::pi*1000*(n+i)/48000.)));h.processBlock(b,m);n+=256;juce::Thread::sleep(2);}}){}~Feed(){stop=true;thread.join();}std::atomic<bool> stop{false};std::thread thread;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-record-gui-"+juce::Uuid().toString());dir.createDirectory();ndaw::desktop::Workspace w(false);w.setVisible(true);w.setSize(1440,1000);click(w,"track.create");click(w,"inspector.recording");check(!find(w,"track.arm")->isEnabled()&&!find(w,"transport.record")->isEnabled(),"record UI refuses missing physical input and destination");auto& h=RecordingTestAccess::host(w,dir);Feed feed(h);settle();
    check(combo(w,"recording.input").getNumItems()==3,"native input selector enumerates actual engine channels");combo(w,"recording.input").setSelectedId(2,juce::sendNotificationSync);settle();check(w.query()["tracks"][0]["input"]["available"]&&find(w,"track.arm")->isEnabled(),"GUI input choice configures actual SDK destination");click(w,"track.arm");combo(w,"recording.monitor").setSelectedId(2,juce::sendNotificationSync);settle();check(w.query()["tracks"][0]["input"]["armed"]&&w.query()["tracks"][0]["input"]["monitoring"],"GUI arm and Auto monitor use real Tracktion input");
    click(w,"track.create");combo(w,"recording.input").setSelectedId(3,juce::sendNotificationSync);settle();click(w,"track.arm");check(find(w,"transport.record")->isEnabled(),"two armed tracks and explicit writable directory enable Record");click(w,"transport.record");settle(450);auto q=w.query();check(q["recording"].get<bool>()&&q["recording_capture"]["targets"].size()==2,"GUI Record starts both real native inputs");check(!find(w,"recording.input")->isEnabled()&&!find(w,"track.arm")->isEnabled(),"I/O and arming controls disabled during record transaction");check(!find(w,"transport.record")->isEnabled()&&!find(w,"history.undo")->isEnabled(),"repeated Record and Undo disabled while recording");auto* details=dynamic_cast<juce::Label*>(find(w,"recording.detail"));check(details&&details->getText().contains("正在录音"),"task status identifies real recording before completion");click(w,"transport.stop");q=w.query();auto receipt=q["last_recording"];check(receipt["state"]=="committed"&&receipt["files"].size()==2,"GUI Stop exposes validated multi-track file receipt");check(q["tracks"][0]["clips"].size()==1&&q["tracks"][1]["clips"].size()==1,"actual captured wave clips return to native Edit timeline");click(w,"history.undo");check(w.query()["tracks"][0]["clips"].empty()&&w.query()["last_recording"]["state"]=="undone","GUI one Undo removes both clips and updates receipt");for(const auto& f:receipt["files"])check(juce::File(juce::String(f["path"].get<std::string>())).existsAsFile(),"GUI Undo preserves recorded source file");click(w,"history.redo");check(w.query()["tracks"][0]["clips"]==q["tracks"][0]["clips"],"GUI Redo restores identical stable captured clips");
    combo(w,"track.type").setSelectedId(5,juce::dontSendNotification);click(w,"track.create");click(w,"inspector.recording");check(!find(w,"track.arm")->isEnabled()&&!find(w,"recording.input")->isEnabled(),"Folder does not expose fake audio-input capability");
    Json result={{"result","passed"},{"checks",checks},{"receipt",receipt},{"scope","production native JUCE recording controls with actual SDK graph and writer, hosted test signal; microphone permission and hardware checked separately"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);}std::cout<<result.dump(2)<<std::endl;return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
