#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
Json op(const char* cmd,Json a){return {{"command",cmd},{"args",a}};}
Json run(Commands& c,Json ops){auto p=c.makePlan("human",ops);c.commit(p);juce::MessageManager::getInstance()->runDispatchLoopUntil(50);return p;}
void fixture(const juce::File& file){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture writer failed");juce::AudioBuffer<float> data(2,48000);for(int c=0;c<2;++c)for(int i=0;i<48000;++i)data.setSample(c,i,.1f*std::sin(2*juce::MathConstants<double>::pi*1000*i/48000));check(writer->writeFromAudioSampleBuffer(data,0,48000),"known PCM fixture written");}
double audio(Commands& c,const juce::File& file){auto r=c.render(file,0,48000);check(r["frames"]==48000&&r["render_ms"].get<double>()<10000,"scoped edit renderer meets fixed real audio budget");return r["rms"].get<double>();}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-scope-"+juce::Uuid().toString());dir.createDirectory();auto source=dir.getChildFile("known.wav");fixture(source);auto hash=Commands::mediaHash(source);Commands c(false);
    run(c,Json::array({op("track.create",{{"name","Vocal"},{"ref","$a"}}),op("clip.import",{{"track","$a"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}}),op("track.create",{{"name","Other"},{"ref","$b"}})}));auto tracks=c.query()["tracks"];std::string first=tracks[0]["id"],second=tracks[1]["id"],clip=tracks[0]["clips"][0]["id"];
    Scope readOnly;readOnly.mode=Permission::ReadOnly;auto p=c.makePlan("agent:scope",Json::array({op("track.gain",{{"track",first},{"db",-6}})}));auto before=c.query();fails([&]{c.commit(p,true,readOnly);},"acceptance cannot override read only");check(c.query()==before,"permission rejection leaves real Edit and revision unchanged");fails([&]{c.commit(p);},"preview mode still needs explicit acceptance");
    Scope scope;scope.mode=Permission::ScopedLowRisk;scope.targets={first};scope.commands=Scope::defaultCommands();check(c.review(p,scope)["permission"]["automatic_allowed"],"explicit track scope authorises low risk attenuation");double baseline=audio(c,dir.getChildFile("before.wav"));auto result=c.commit(p,false,scope);check(result["state"]=="committed"&&std::abs(c.query()["tracks"][0]["gain_db"].get<double>()+6)<.002,"allowed automatic plan writes actual SDK gain");check(std::abs(audio(c,dir.getChildFile("after.wav"))/baseline-std::pow(10.,-6./20.))<3e-6,"scoped attenuation changes real PCM as declared");c.undo(p["plan_id"]);check(std::abs(audio(c,dir.getChildFile("undo.wav"))-baseline)<3e-6,"scoped plan Undo restores original PCM");c.redo();check(c.commit(p,false,scope)["replayed"],"scoped network retry is idempotent");fails([&]{c.commit(p,true,readOnly);},"read only cannot report a commit replay as authorised");
    auto loud=c.makePlan("agent:scope",Json::array({op("track.gain",{{"track",first},{"db",0}})}));check(!c.review(loud,scope)["permission"]["automatic_allowed"].get<bool>(),"raising audible gain requires a preview even in automatic mode");fails([&]{c.commit(loud,false,scope);},"unsafe automatic gain is rejected before writing");c.commit(loud,true,scope);c.undo(loud["plan_id"]);
    auto fade=c.makePlan("agent:scope",Json::array({op("clip.fade",{{"clip",clip},{"in_samples",4800},{"out_samples",0},{"in_curve","linear"},{"out_curve","linear"}})}));c.commit(fade,false,scope);
    auto shape=c.makePlan("agent:scope",Json::array({op("clip.fade",{{"clip",clip},{"in_samples",4800},{"out_samples",0},{"in_curve","convex"},{"out_curve","linear"}})}));
    check(!c.review(shape,scope)["permission"]["automatic_allowed"].get<bool>(),"active fade curve change cannot automatically raise waveform level");c.undo(fade["plan_id"]);
    Scope soloScope=scope;soloScope.commands={"track.solo"};auto solo=c.makePlan("agent:scope",Json::array({op("track.solo",{{"track",first},{"enabled",true}})}));fails([&]{c.commit(solo,true,soloScope);},"bounded Solo cannot implicitly alter audibility of ungranted tracks");
    auto outside=c.makePlan("agent:scope",Json::array({op("track.rename",{{"track",second},{"name","Not allowed"}})}));before=c.query();fails([&]{c.commit(outside,true,scope);},"accepted plan cannot escape granted object set");check(c.query()==before,"outside scope does not partly commit");auto commands=scope;commands.commands={"track.rename"};fails([&]{c.commit(c.makePlan("agent:scope",Json::array({op("track.gain",{{"track",first},{"db",-9}})})),true,commands);},"explicit command allowlist is enforced at L1");
    auto range=scope;range.begin=0;range.end=48000;fails([&]{c.commit(c.makePlan("agent:scope",Json::array({op("track.gain",{{"track",first},{"db",-9}})})),true,range);},"partial time grant cannot authorise whole track gain");
    auto clipGain=c.makePlan("agent:scope",Json::array({op("clip.gain",{{"clip",clip},{"db",-3}})}));check(c.review(clipGain,range)["permission"]["impacts"].size()==2,"clip footprint covers both original and resulting range");c.commit(clipGain,false,range);check(c.query()["tracks"][0]["clips"][0]["gain_db"]==-3,"bounded clip gain writes actual object");c.undo(clipGain["plan_id"]);
    auto move=c.makePlan("agent:scope",Json::array({op("clip.move",{{"clip",clip},{"position_samples",24000}})}));fails([&]{c.commit(move,true,range);},"move destination cannot escape the time grant");range.end=96000;c.commit(move,false,range);check(c.query()["tracks"][0]["clips"][0]["start_samples"]==24000,"within scope move succeeds");c.undo(move["plan_id"]);range.begin=24000;fails([&]{c.commit(c.makePlan("agent:scope",Json::array({op("clip.trim",{{"clip",clip},{"start_samples",24000},{"end_samples",48000}})})),true,range);},"trim cannot delete an ungranted original range");range.begin=0;
    Scope copy=scope;copy.targets={clip};copy.commands={"clip.copy"};auto copyPlan=c.makePlan("agent:scope",Json::array({op("clip.copy",{{"clip",clip},{"track",second},{"position_samples",0},{"ref","$copy"}})}));fails([&]{c.commit(copyPlan,true,copy);},"copy requires separate destination track grant");copy.targets.insert(second);copy.end=48000;auto lateCopy=c.makePlan("agent:scope",Json::array({op("clip.copy",{{"clip",clip},{"track",second},{"position_samples",24000},{"ref","$copy"}})}));fails([&]{c.commit(lateCopy,true,copy);},"new copied object cannot escape time scope");c.commit(copyPlan,true,copy);check(c.query()["tracks"][1]["clips"].size()==1,"explicit source and destination copy grant succeeds");c.undo(copyPlan["plan_id"]);
    auto split=scope;split.targets={clip};split.commands={"clip.split","clip.gain"};auto splitPlan=c.makePlan("agent:scope",Json::array({op("clip.split",{{"clip",clip},{"position_samples",24000},{"ref","$right"}}),op("clip.gain",{{"clip","$right"},{"db",-3}})}));c.commit(splitPlan,true,split);check(c.query()["tracks"][0]["clips"].size()==2&&c.query()["tracks"][0]["clips"][1]["gain_db"]==-3,"derived split object inherits explicit source grant inside one plan");c.undo(splitPlan["plan_id"]);
    run(c,Json::array({op("track.create",{{"name","MIDI"},{"type","midi"},{"ref","$m"}}),op("midi.clip.create",{{"track","$m"},{"name","Notes"},{"ref","$c"},{"position_samples",0},{"length_samples",192000}}),op("midi.note.add",{{"clip","$c"},{"pitch",60},{"velocity",90},{"position_samples",24000},{"length_samples",12000},{"ref","$n"}})}));auto midi=c.query()["tracks"][2];std::string mc=midi["clips"][0]["id"],note=midi["clips"][0]["notes"][0]["id"];Scope music=scope;music.targets={midi["id"]};music.begin=24000;music.end=48000;
    auto transpose=c.makePlan("agent:scope",Json::array({op("midi.notes.transpose",{{"clip",mc},{"selection","all"},{"semitones",12}})}));c.commit(transpose,false,music);check(c.query()["tracks"][2]["clips"][0]["notes"][0]["pitch"]==72,"MIDI scope follows actual affected note times, not whole clip duration");c.undo(transpose["plan_id"]);auto duration=c.makePlan("agent:scope",Json::array({op("midi.note.set",{{"clip",mc},{"note",note},{"pitch",60},{"velocity",90},{"position_samples",24000},{"length_samples",48000}})}));fails([&]{c.commit(duration,true,music);},"MIDI note duration cannot extend beyond granted end");
    Scope invalid=scope;invalid.targets.clear();fails([&]{invalid.validate();},"empty automatic targets are not wildcard permission");invalid=scope;invalid.commands.clear();fails([&]{invalid.validate();},"empty automatic command allowlist is rejected");invalid=scope;invalid.begin=50;invalid.end=50;fails([&]{invalid.validate();},"invalid time grant rejected");invalid=scope;invalid.targets={"$future"};fails([&]{invalid.validate();},"unresolved symbols cannot be permission targets");
    auto create=c.makePlan("agent:scope",Json::array({op("track.create",{{"name","Aux"},{"type","aux"},{"ref","$aux"}})}));scope.commands.insert("track.create");fails([&]{c.commit(create,true,scope);},"bounded grants cannot silently expand to newly created tracks");
    check(Commands::mediaHash(source)==hash,"scope workflow never changes original PCM");Json summary={{"result","passed"},{"checks",checks},{"scope","actual Tracktion objects, integer ranges, command grants, audio and transaction validation; not a full MCP or physical GUI test"}};if(argc>1){std::ofstream out(argv[1]);out<<summary.dump(2);}std::cout<<summary.dump(2)<<std::endl;dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
