#include <nativedaw/v2/EngineCommands.h>
#include "RecoveryStore.h"
#include <chrono>
#include <fstream>
#include <iostream>

using namespace ndaw::v2;
namespace {
using Clock=std::chrono::steady_clock;
class Storage final:public te::PropertyStorage {
public:explicit Storage(juce::File f):PropertyStorage("Forma snapshot tests"),folder(std::move(f)){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}
private:juce::File folder;
};
struct Scratch {juce::File folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-snapshots-"+juce::Uuid().toString());~Scratch(){folder.deleteRecursively();}};
int checks=0;Json metrics=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F task,const char* why){bool rejected=false;try{task();}catch(const std::exception&){rejected=true;}check(rejected,why);}
void pump(int ms=20){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json wait(Commands& c){auto began=Clock::now();while(c.recoveryStatus().value("busy",false)){if(Clock::now()-began>std::chrono::seconds(5))throw std::runtime_error("snapshot I/O exceeded predeclared 5 second fixture budget");pump();}auto status=c.recoveryStatus();metrics.push_back({{"job",status["state"]},{"ms",std::chrono::duration<double,std::milli>(Clock::now()-began).count()}});return status;}
void start(Commands& c){c.recoveryControl("session.recovery.start",Json::object());check(wait(c)["state"]=="idle","owned recovery directory and preferences load successfully");}
Json op(const char* command,Json args){return {{"command",command},{"args",args}};}
Json run(Commands& c,Json ops){auto p=c.makePlan("human",ops);c.commit(p);pump();return p;}
Json capture(Commands& c){c.recoveryControl("session.recovery.capture",Json::object());auto s=wait(c);check(s["state"]=="saved","snapshot has an actual durable save receipt");check(s["receipt"]["snapshot"]["snapshot_capture_ms"].get<double>()<1000,"64-track message-thread capture stays below 1 second");metrics.push_back({{"snapshot",s["receipt"]["snapshot"]}});return s["receipt"]["snapshot"];}
Json restore(Commands& c,const Json& snapshot){return c.recoveryControl("session.recovery.restore",{{"id",snapshot["id"]},{"sha256",snapshot["sha256"]},{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]}});}
void fixture(const juce::File& file){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("PCM fixture writer unavailable");juce::AudioBuffer<float> pcm(2,144000);for(int c=0;c<2;++c)for(int n=0;n<144000;++n)pcm.setSample(c,n,(c==0?.05f:.025f)*std::sin(2*juce::MathConstants<double>::pi*1000*n/48000));if(!writer->writeFromAudioSampleBuffer(pcm,0,144000))throw std::runtime_error("PCM fixture write failed");}
std::string render(Commands& c,const juce::File& directory){auto path=directory.getChildFile(juce::Uuid().toString()+".wav");auto result=c.render(path,0,144000);check(result["frames"]==144000&&result["channels"]==2&&result["render_ms"].get<double>()<10000,"real renderer preserves three-second stereo format within budget");juce::AudioFormatManager formats;formats.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(formats.createReaderFor(path));if(!reader)throw std::runtime_error("render cannot be decoded");juce::AudioBuffer<float> pcm(2,144000);if(!reader->read(&pcm,0,144000,0,true,true))throw std::runtime_error("render decode failed");juce::SHA256 hash;std::string data;for(int c=0;c<2;++c)data.append(reinterpret_cast<const char*>(pcm.getReadPointer(c)),144000*sizeof(float));metrics.push_back(result);return juce::SHA256(data.data(),data.size()).toHexString().toStdString();}
void mainFlow(const juce::File& folder){
    auto prefs=folder.getChildFile("prefs"),source=folder.getChildFile("source.wav");fixture(source);auto sourceHash=Commands::mediaHash(source);
    Commands c(false,std::make_unique<Storage>(prefs));start(c);
    auto ops=Json::array({op("track.create",{{"name","Voice"},{"ref","$voice"}}),op("clip.import",{{"track","$voice"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}}),op("plugin.insert",{{"track","$voice"},{"type","4bandEq"}}),op("track.create",{{"name","Aux"},{"type","aux"},{"ref","$aux"}}),op("send.create",{{"track","$voice"},{"target","$aux"},{"db",-18},{"position","post"}}),op("track.create",{{"name","MIDI"},{"type","midi"},{"ref","$midi"}}),op("midi.clip.create",{{"track","$midi"},{"ref","$clip"},{"name","Notes"},{"position_samples",0},{"length_samples",96000}}),op("midi.note.add",{{"clip","$clip"},{"pitch",60},{"velocity",100},{"position_samples",0},{"length_samples",24000}}),op("automation.point.add",{{"track","$voice"},{"parameter","volume"},{"ref","$auto"},{"position_samples",0},{"value",-6},{"curve",0}})});
    run(c,ops);ops=Json::array();for(int i=3;i<64;++i)ops.push_back(op("track.create",{{"name","Track "+std::to_string(i)},{"ref","$t"+std::to_string(i)}}));run(c,ops);const std::string voice=c.query()["tracks"][0]["id"];
    check(c.query()["tracks"].size()==64,"fixed benchmark contains 64 actual tracks, MIDI, automation, EQ and Aux");
    auto savedFile=folder.getChildFile("original.tracktionedit");c.save(savedFile);auto originalHash=Commands::mediaHash(savedFile);auto before=c.query();auto pcm=render(c,folder);auto snapshot=capture(c);
    check(c.query()["tracks"]==before["tracks"]&&c.query()["revision"]==before["revision"]&&c.query()["can_undo"]==before["can_undo"],"capturing does not change facts, revision or Undo");
    run(c,Json::array({op("track.rename",{{"track",voice},{"name","New human edit"}})}));auto token=c.sessionToken();restore(c,snapshot);auto restored=wait(c);
    check(restored["state"]=="restored"&&restored["receipt"].contains("previous_session_backup"),"restore verifies target and backs up current session before switching");
    check(c.sessionToken()!=token&&!c.query()["can_undo"].get<bool>()&&!restored["receipt"]["audio_verified"].get<bool>(),"restore creates a new session without pretending Undo or audio qualification survived");
    check(c.query()["tracks"]==before["tracks"],"actual audio/MIDI/automation/routing/EQ object state survives recovery");
    check(render(c,folder)==pcm,"decoded PCM is bit-identical after verified snapshot recovery");
    auto backup=restored["receipt"]["previous_session_backup"];restore(c,backup);check(wait(c)["state"]=="restored"&&c.query()["tracks"][0]["name"]=="New human edit","previous session remains recoverable rather than overwritten");
    check(Commands::mediaHash(source)==sourceHash&&Commands::mediaHash(savedFile)==originalHash,"original audio and saved user project hashes remain unchanged");
    restore(c,snapshot);run(c,Json::array({op("track.rename",{{"track",voice},{"name","While reading"}})}));check(wait(c)["state"]=="failed"&&c.query()["tracks"][0]["name"]=="While reading","interleaved human edit rejects stale recovery and retains newer facts");
    restore(c,snapshot);c.recoveryControl("session.recovery.cancel",Json::object());check(wait(c)["state"]=="cancelled"&&c.query()["tracks"][0]["name"]=="While reading","cancellation prevents the asynchronous session switch");
    auto args=Json{{"id",snapshot["id"]},{"sha256",snapshot["sha256"]},{"session_token",c.sessionToken()},{"base_revision",0}};fails([&]{c.recoveryControl("session.recovery.restore",args);},"stale preview revision is rejected before filesystem work");
    args["base_revision"]=c.querySummary()["revision"];args["accepted"]=true;fails([&]{c.recoveryControl("session.recovery.restore",args);},"injected authority is rejected");
    c.recoveryControl("session.recovery.configure",{{"enabled",false},{"interval_seconds",10}});check(wait(c)["state"]=="idle","local preferences persist with a real write receipt");
    Commands second(false,std::make_unique<Storage>(prefs));start(second);check(!second.recoveryStatus()["enabled"].get<bool>()&&second.recoveryStatus()["interval_seconds"]==10,"new app instance reads persisted interval and disabled state");
    auto recoveryDir=prefs.getChildFile("Recovery");auto payload=recoveryDir.getChildFile(snapshot["id"].get<std::string>()+".tracktionedit");auto contents=payload.loadFileAsString();payload.replaceWithText("<EDIT/>");restore(c,snapshot);check(wait(c)["state"]=="failed"&&c.query()["tracks"][0]["name"]=="While reading","corrupt or truncated payload cannot replace the current Edit");payload.replaceWithText(contents);
    recoveryDir.getChildFile("orphan.tracktionedit").replaceWithText("<EDIT/>");auto catalog=recovery::list(recoveryDir);check(catalog["entries"].size()>=3&&std::none_of(catalog["entries"].begin(),catalog["entries"].end(),[](const auto& row){return row["id"]=="orphan";}),"payload without committed manifest is not offered as a successful snapshot");
    auto manifest=recoveryDir.getChildFile(snapshot["id"].get<std::string>()+".json");auto metaText=manifest.loadFileAsString();manifest.replaceWithText("{}");check(recovery::list(recoveryDir)["entries"].size()==catalog["entries"].size(),"damaged manifests remain visible in the catalog instead of being silently deleted");fails([&]{recovery::read(recoveryDir,snapshot["id"],snapshot["sha256"]);},"invalid schema fails closed");manifest.replaceWithText(metaText);
    fails([&]{recovery::read(recoveryDir,"../source",snapshot["sha256"]);},"snapshot IDs cannot escape the managed directory");fails([&]{recovery::read(recoveryDir,snapshot["id"],std::string(64,'0'));},"changed checksum requires a new preview");
    auto bad=prefs.getChildFile("Recovery-blocked");bad.replaceWithText("file, not directory");fails([&]{recovery::write(bad,{juce::ValueTree(te::IDs::EDIT),snapshot});},"real OS filesystem failure is reported");check(recovery::read(recoveryDir,snapshot["id"],snapshot["sha256"]).state.isValid(),"filesystem failure does not damage an earlier committed snapshot");
    fails([&]{c.makePlan("agent:test",Json::array({op("session.recovery.restore",args)}));},"external editing Plans cannot invoke local recovery controls");
    // Verify relative references using a real saved Edit file, not an engine double.
    auto document=juce::ValueTree::fromXml(*juce::XmlDocument::parse(savedFile));int converted=0;
    std::function<void(juce::ValueTree)> relative=[&](juce::ValueTree node){if(node.getProperty(te::IDs::source).toString()==source.getFullPathName()){node.setProperty(te::IDs::source,"source.wav",nullptr);++converted;}for(auto child:node)relative(child);};relative(document);
    check(converted==1,"relative-media fixture retains one actual WaveAudioClip reference");auto relativeFile=folder.getChildFile("relative.tracktionedit");relativeFile.replaceWithText(document.toXmlString());c.open(relativeFile);auto relativeSnapshot=capture(c);restore(c,relativeSnapshot);check(wait(c)["state"]=="restored"&&render(c,folder)==pcm,"relative source resolves to original media after recovery to an independent session");
    auto keyed=c.makePlan("agent:automated-test",Json::array({op("track.rename",{{"track",voice},{"name","Keyed edit"}})}));keyed["request_key"]="snapshot-request";keyed["request_fingerprint"]=std::string(64,'1');keyed["request_scope_hash"]=std::string(64,'2');c.commit(keyed,true);check(c.requestRecovery("snapshot-request")["trusted_current_run"],"keyed test transaction has a real live L1 execution receipt");auto audited=capture(c);restore(c,audited);check(wait(c)["state"]=="restored"&&c.requestRecovery("snapshot-request")["state"]=="recovery_requires_review"&&c.requestRecovery("snapshot-request")["receipt"].is_null(),"restored AI request marker stays historical and does not invent current success");
    const auto oldRestoreReceipt=c.recoveryStatus()["receipt"];check(c.recoveryStatus()["receipt_current_session"],"restore receipt belongs to the actual recovered session");
    c.open(savedFile);auto switched=c.recoveryStatus();check(switched["state"]=="idle"&&!switched["receipt_current_session"].get<bool>()&&switched["receipt"]==oldRestoreReceipt,"opening another Edit preserves the genuine old receipt without claiming the new session was restored");
    auto switchedSnapshot=capture(c);check(c.recoveryStatus()["receipt_current_session"],"new snapshot receipt is bound to the current session");c.open(savedFile);switched=c.recoveryStatus();check(switched["state"]=="idle"&&!switched["receipt_current_session"].get<bool>()&&switched["receipt"]["snapshot"]==switchedSnapshot,"reopening a saved file does not pretend its new session has an acknowledged recovery snapshot");
    auto blockedPrefs=folder.getChildFile("blocked-prefs");blockedPrefs.createDirectory();blockedPrefs.getChildFile("Recovery").replaceWithText("occupied by a regular file");Commands blocked(false,std::make_unique<Storage>(blockedPrefs));blocked.recoveryControl("session.recovery.start",Json::object());check(wait(blocked)["state"]=="failed","catalog startup exposes an actual OS directory failure");run(blocked,Json::array({op("track.create",{{"name","Keep editing"},{"ref","$keep"}})}));blocked.recoveryControl("session.recovery.capture",Json::object());check(wait(blocked)["state"]=="failed"&&blocked.query()["tracks"].size()==1,"write failure is visible and ordinary DAW edits remain usable");
}
void automatic(const juce::File& folder){Commands c(false,std::make_unique<Storage>(folder));start(c);c.recoveryControl("session.recovery.configure",{{"enabled",true},{"interval_seconds",10}});wait(c);run(c,Json::array({op("track.create",{{"name","Auto saved"},{"ref","$auto"}})}));auto end=Clock::now()+std::chrono::seconds(15);while(c.recoveryStatus()["state"]!="saved"){if(Clock::now()>end)throw std::runtime_error("automatic snapshot did not arrive at 10 second interval");pump();}check(c.recoveryStatus()["catalog"]["entries"].size()==1,"production timer saves a changed stopped session automatically");}
int crashWorker(const juce::File& folder){Commands c(false,std::make_unique<Storage>(folder.getChildFile("crash-prefs")));start(c);run(c,Json::array({op("track.create",{{"name","Survived SIGKILL"},{"ref","$crash"}})}));auto snapshot=capture(c);if(!folder.getChildFile("crash-ready.json").replaceWithText(snapshot.dump()))return 3;for(;;)pump();}
void crash(const juce::File& folder){juce::ChildProcess child;struct Cleanup{juce::ChildProcess& c;~Cleanup(){if(c.isRunning()){c.kill();c.waitForProcessToFinish(3000);}}} cleanup{child};check(child.start(juce::StringArray{juce::File::getSpecialLocation(juce::File::currentExecutableFile).getFullPathName(),"--crash-worker",folder.getFullPathName()}),"owned crash-test child starts actual production Commands");auto end=Clock::now()+std::chrono::seconds(10);auto ready=folder.getChildFile("crash-ready.json");while(!ready.existsAsFile()){if(!child.isRunning()||Clock::now()>end)throw std::runtime_error("crash worker failed before durable save");pump();}auto snapshot=Json::parse(ready.loadFileAsString().toStdString());check(child.isRunning()&&child.kill()&&child.waitForProcessToFinish(3000),"acknowledged snapshot survives real abrupt child process termination");Commands c(false,std::make_unique<Storage>(folder.getChildFile("crash-prefs")));start(c);restore(c,snapshot);check(wait(c)["state"]=="restored"&&c.query()["tracks"][0]["name"]=="Survived SIGKILL","fresh instance restores unsaved project facts from durable snapshot");}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{if(argc==3&&std::string(argv[1])=="--crash-worker")return crashWorker(juce::File(argv[2]));Scratch scratch;scratch.folder.createDirectory();mainFlow(scratch.folder);automatic(scratch.folder.getChildFile("automatic"));crash(scratch.folder);Json summary{{"result","passed"},{"test","M1-RECOVERY-01"},{"checks",checks},{"metrics",metrics},{"scope","production detached snapshots, real filesystem, actual renderer and abrupt process exit; no active-recording, WAL, persistent Undo or desktop audition claim"}};if(argc>1){std::ofstream report(argv[1]);report<<summary.dump(2);if(!report)throw std::runtime_error("report write failed");}std::cout<<summary.dump(2)<<std::endl;return 0;}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
