#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;using namespace ndaw::desktop;
namespace {
int checks=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
void pump(int ms=30){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& parent,const juce::String& id){if(!parent.isVisible())return nullptr;if(parent.getComponentID()==id)return &parent;for(auto* child:parent.getChildren())if(auto* result=find(*child,id))return result;return nullptr;}
void click(juce::Component& parent,const juce::String& id){auto* button=dynamic_cast<juce::Button*>(find(parent,id));if(!button||!button->isEnabled())throw std::runtime_error("unavailable source button: "+id.toStdString());auto callback=button->onClick;bool delivered=false;button->onClick=[&]{delivered=true;callback();};button->triggerClick();const auto deadline=juce::Time::getMillisecondCounterHiRes()+1000;while(!delivered&&juce::Time::getMillisecondCounterHiRes()<deadline)pump(1);button->onClick=callback;check(delivered,"actual native asynchronous button callback delivered");}
juce::TextEditor& editor(Workspace& w,const char* id){auto* value=dynamic_cast<juce::TextEditor*>(find(w,id));if(!value)throw std::runtime_error(std::string("source editor missing: ")+id);return *value;}
void field(Workspace& w,const char* id,const char* value){auto& input=editor(w,id);static_cast<juce::Component*>(&input)->focusGained(juce::Component::focusChangedDirectly);input.setText(value,true);}
juce::ComboBox& combo(Workspace& w,const char* id){auto* value=dynamic_cast<juce::ComboBox*>(find(w,id));if(!value)throw std::runtime_error(std::string("source chooser missing: ")+id);return *value;}
Json wait(Workspace& w){const auto deadline=juce::Time::getMillisecondCounterHiRes()+12000;while(w.queryAnalysis().value("busy",false)){if(juce::Time::getMillisecondCounterHiRes()>deadline)throw std::runtime_error("native source job exceeds twelve seconds");pump(10);}pump(300);return w.queryAnalysis();}
class Storage final:public te::PropertyStorage{public:explicit Storage(juce::File dir):PropertyStorage("Forma source GUI"),dir(dir){}juce::File getAppPrefsFolder()override{dir.createDirectory();return dir;}private:juce::File dir;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-source-gui-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();const int rate=44100;const auto source=folder.getChildFile("native-impulses.wav");juce::AudioBuffer<float> data(2,rate*30);data.clear();for(const int frame:{rate/4,rate*5/4}){data.setSample(0,frame,.5f);data.setSample(1,frame,-.5f);}juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=source.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(rate).withNumChannels(2).withBitsPerSample(32));if(!writer||!writer->writeFromAudioSampleBuffer(data,0,data.getNumSamples()))throw std::runtime_error("source GUI PCM write failed");writer.reset();const auto hash=Commands::mediaHash(source);
    Workspace w(false,std::make_unique<Storage>(folder.getChildFile("prefs")));w.setVisible(true);w.prepareImport(source);pump();click(w,"plan.accept");pump();const std::string clip=w.query()["tracks"][0]["clips"][0]["id"];click(w,"clip.select:"+juce::String(clip));pump();const auto before=w.query();w.menuItemSelected(43,2);pump();combo(w,"analysis.tap").setSelectedId(2,juce::sendNotificationSync);pump();
    check(combo(w,"analysis.source_clip").getNumItems()==1&&editor(w,"analysis.end_samples").getText()==juce::String(rate*30)&&find(w,"analysis.source.run")&&!find(w,"analysis.delivery.run"),"native raw tap selects actual clip and exposes native source frames without Master delivery controls");
    editor(w,"analysis.start_samples").setText(juce::String(rate/10));editor(w,"analysis.end_samples").setText(juce::String(rate*2));click(w,"analysis.source.run");auto complete=wait(w);auto artifact=complete["receipt"];check(complete["state"]=="completed"&&artifact["binding"]["media_sha256"]==hash&&artifact["event_counts"]["silence"]==3&&artifact["event_counts"]["transient_candidate"]==2,"native source button receives genuine PCM and detected native-frame events");
    check(editor(w,"analysis.summary").getText().contains("44100 Hz")&&editor(w,"analysis.summary").getText().contains("未经过 Clip FX")&&editor(w,"analysis.summary").getText().contains("不是呼吸识别"),"native summary states source rate processing tap and detector limitations");
    check(w.query()["revision"]==before["revision"]&&w.query()["tracks"]==before["tracks"],"native source analysis creates no edit history or mix changes");int first=-1,second=-1;for(const auto& e:artifact["events"])if(e["kind"]=="transient_candidate"){if(first<0)first=e["id"];else second=e["id"];}
    click(w,"analysis.locate:"+juce::String(first));check(w.query()["position_samples"]==12000&&!find(w,"analysis.panel"),"actual source event button seeks 44.1k candidate to exact 48k session position");
    field(w,"clip.position","96000");pump();click(w,"clip.move");pump();check(w.query()["tracks"][0]["clips"][0]["start_samples"]==96000,"focused native position field survives refresh and commits the requested real move");w.showAnalysis();pump(300);check(w.queryAnalysis()["receipt"]["artifact_id"]==artifact["artifact_id"]&&w.queryAnalysis()["receipt"]["current"].get<bool>(),"native human move preserves valid immutable source receipt");click(w,"analysis.locate:"+juce::String(first));check(w.query()["position_samples"]==108000,"native location updates after real clip move");
    field(w,"clip.start","100800");field(w,"clip.end","216000");pump();click(w,"clip.trim");pump();w.showAnalysis();pump();click(w,"analysis.locate:"+juce::String(first));check(w.query()["position_samples"]==108000,"native trimmed-source offset keeps the same original material location");click(w,"clip.split");pump();w.showAnalysis();pump(300);auto views=w.queryAnalysis()["receipt"]["mapping_set"]["clips"];check(views.size()==2&&combo(w,"analysis.mapping_clip").getNumItems()==2,"native source panel discovers actual new split clip IDs");int right=0;for(size_t i=0;i<views.size();++i)if(views[i]["clip_id"]!=clip)right=int(i)+1;
    check(!find(w,"analysis.locate:"+juce::String(second))->isEnabled(),"source onset cropped from selected original half cannot be located");combo(w,"analysis.mapping_clip").setSelectedId(right,juce::sendNotificationSync);pump();click(w,"analysis.locate:"+juce::String(second));check(w.query()["position_samples"]==156000,"choosing actual right half locates second source candidate without reanalysis");
    click(w,"history.undo");pump();w.showAnalysis();pump();check(combo(w,"analysis.mapping_clip").getNumItems()==1&&w.queryAnalysis()["receipt"]["current"].get<bool>(),"native Undo restores unsplit clip views and retains source evidence");click(w,"analysis.close");click(w,"history.redo");pump();w.showAnalysis();pump();check(combo(w,"analysis.mapping_clip").getNumItems()==2,"native Redo restores real split views");
    const auto unchanged=w.query();editor(w,"source.silence_ms").setText("0");click(w,"analysis.source.run");pump(300);check(!w.queryAnalysis()["busy"].get<bool>()&&w.queryAnalysis()["receipt"]["artifact_id"]==artifact["artifact_id"]&&editor(w,"analysis.summary").getText().contains("操作未完成"),"invalid native detector field fails visibly without inventing or replacing an artifact");
    editor(w,"source.silence_ms").setText("100");editor(w,"analysis.start_samples").setText("0");editor(w,"analysis.end_samples").setText(juce::String(rate*30));click(w,"analysis.source.run");click(w,"analysis.cancel");check(wait(w)["state"]=="cancelled","native raw source cancellation produces actual terminal cancellation");click(w,"analysis.close");check(w.query()["revision"]==unchanged["revision"]&&w.query()["tracks"]==unchanged["tracks"]&&Commands::mediaHash(source)==hash,"native profile errors cancellation and source locate preserve original PCM Edit and history");
    w.showAnalysis();combo(w,"analysis.tap").setSelectedId(1,juce::sendNotificationSync);pump();check(find(w,"analysis.master.run")&&find(w,"analysis.delivery.run")&&!find(w,"source.silence_ms"),"native panel returns to the existing functioning Master workflow");const double elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"native source qualification meets fixed sixty-second total budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"artifact",artifact},{"scope","actual native JUCE callbacks, PCM decode and Edit commands; desktop demonstration is separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("source GUI report write failed");}std::cout<<report.dump(2)<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
