#include <nativedaw/v2/AudioAnalysis.h>
#include <nativedaw/v2/SourceFeatures.h>
#include <nativedaw/v2/SourceMapping.h>
#include <nativedaw/v2/McpGateway.h>
#include <nativedaw/v2/McpSession.h>
#include <thread>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;Json evidence=Json::array();
void check(bool ok,const char* name){if(!ok)throw std::runtime_error(name);++checks;std::cout<<"PASS "<<name<<std::endl;}
template<class F>void rejects(F f,const char* name){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,name);}
Json op(const char* command,Json args){return {{"command",command},{"args",args}};}
void pump(int ms=10){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json wait(Commands& c){const auto deadline=juce::Time::getMillisecondCounterHiRes()+12000;while(c.analysisStatus().value("busy",false)&&juce::Time::getMillisecondCounterHiRes()<deadline)pump();auto s=c.analysisStatus();check(!s.value("busy",false),"source fixture completes within fixed twelve-second budget");return s;}
juce::File impulseFile(const juce::File& dir,int rate){auto f=dir.getChildFile("native-"+juce::String(rate)+".wav");juce::AudioBuffer<float> pcm(2,rate*3);pcm.clear();for(int frame:{rate/4,rate*5/4}){pcm.setSample(0,frame,.5f);pcm.setSample(1,frame,-.5f);}juce::WavAudioFormat format;std::unique_ptr<juce::OutputStream> stream=f.createOutputStream();auto writer=format.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(rate).withNumChannels(2).withBitsPerSample(32));if(!writer||!writer->writeFromAudioSampleBuffer(pcm,0,pcm.getNumSamples()))throw std::runtime_error("impulse PCM creation failed");return f;}
Json args(Commands& c,const std::string& clip,int rate,const char* key){return {{"session_token",c.sessionToken()},{"base_revision",c.query()["revision"]},{"clip",clip},{"source_start_frame",rate/10},{"source_end_frame",rate*2},{"request_key",key}};}
Json rpc(McpSession& s,const char* method,Json params){static int id=1;const auto key=id++;std::vector<Json> replies;std::thread receive([&]{replies=s.receive(Json{{"jsonrpc","2.0"},{"id",key},{"method",method},{"params",params}}.dump());});receive.join();const auto deadline=juce::Time::getMillisecondCounterHiRes()+5000;while(replies.empty()&&juce::Time::getMillisecondCounterHiRes()<deadline){pump(1);std::thread ready([&]{replies=s.ready();});ready.join();}if(replies.size()!=1)throw std::runtime_error("MCP reply deadline");return replies.front();}
void numerical(const juce::File& dir,int rate){const auto file=impulseFile(dir,rate);const auto hash=Commands::mediaHash(file);const int64_t begin=rate/10,end=rate*2;const auto measured=analysis::measure(file,0,{}, {begin,end},Json::object());
    check(measured["frames"]==end-begin&&measured["read_range"]["begin_frame"]==begin&&measured["peak_file_frame"]==rate/4,"nonzero source frame range is read exactly at native rate");
    check(std::abs(measured["peak"].get<double>()-.5)<1e-12&&std::abs(measured["rms"].get<double>()-.5*std::sqrt(2./double(end-begin)))<1e-12&&std::abs(measured["correlation"].get<double>()+1)<1e-12,"decoded impulse Peak RMS and opposite-channel correlation meet independent 1e-12 numeric budget");
    const auto& f=measured["source_features"];check(f["event_counts"]["silence"]==3&&f["event_counts"]["transient_candidate"]==2&&!f["qualifies_performance_quality"].get<bool>()&&!f["qualifies_breath_detection"].get<bool>(),"actual PCM produces three exact silence ranges and two explicitly estimated energy candidates");
    std::vector<Json> quiet,onsets;for(const auto& event:f["events"])(event["kind"]=="silence"?quiet:onsets).push_back(event);
    check(quiet[0]["source_start_frame"]==begin&&quiet[0]["source_end_frame"]==rate/4&&quiet[1]["source_start_frame"]==rate/4+1&&quiet[1]["source_end_frame"]==rate*5/4&&quiet[2]["source_start_frame"]==rate*5/4+1&&quiet[2]["source_end_frame"]==end,"all contiguous silence boundaries exactly match independent native PCM frame prediction");
    check(onsets[0]["source_start_frame"]==rate/4&&onsets[1]["source_start_frame"]==rate*5/4&&onsets[0]["estimated"].get<bool>(),"candidate first-above-threshold frames match known impulses without a performance-quality claim");
    check(Commands::mediaHash(file)==hash,"raw measurements never modify original media");rejects([&]{analysis::measure(file,0,{}, {begin,rate*4},Json::object());},"range beyond source PCM is rejected");
}
void boundedFeatures(){
    analysis::SourceFeatures dense(48000,0,Json::object());const int64_t end=48000*20;for(int64_t n=0;n<end;++n){const double v=n%9600==1200?.5:0;dense.frame(n,v,v*v);}const auto report=dense.finish(end);
    check(report["event_counts"]["silence"]==100&&report["event_counts"]["transient_candidate"]==100&&report["events"].size()==128&&report["events_omitted"]==72,"dense PCM retains bounded candidate families while all counts and omissions remain exact");
    analysis::SourceFeatures refractory(48000,0,{{"transient_refractory_ms",1000}});for(int64_t n=0;n<96000;++n){const double v=n==12000||n==24000||n==72000?.5:0;refractory.frame(n,v,v*v);}check(refractory.finish(96000)["event_counts"]["transient_candidate"]==2,"configured refractory suppresses nearby candidates using actual energy bins");
    Json map={{"available",true},{"clip_id","test"},{"track_id","owner"},{"source_sample_rate",44100},{"speed_ratio",2},{"source_offset_seconds",.1},{"start_samples",96000},{"end_samples",144000}};
    Json onset={{"kind","transient_candidate"},{"id",0},{"source_start_frame",11025},{"source_end_frame",11245}};check(analysis::projectSourceEvent(onset,map)["start_samples"]==99600,"inverse linear-speed mapping uses native source rate offset and session rate");map["available"]=false;check(analysis::projectSourceEvent(onset,map).is_null(),"unsupported mapping cannot invent a session location");map["available"]=true;onset["source_start_frame"]=0;check(analysis::projectSourceEvent(onset,map).is_null(),"cropped transient onset is unavailable rather than moved to a clip edge");
    map["speed_ratio"]=1.;map["source_offset_seconds"]=.24999999999999992;map["start_samples"]=108000;map["end_samples"]=216000;Json quiet={{"kind","silence"},{"id",0},{"source_start_frame",4410},{"source_end_frame",11025}};check(analysis::projectSourceEvent(quiet,map).is_null(),"actual SDK split-offset rounding cannot invent a one-sample silence location at the transient boundary");onset["source_start_frame"]=11025;check(analysis::projectSourceEvent(onset,map)["start_samples"]==108000,"split-boundary transient remains visible at exact material onset");
}
void lifecycle(const juce::File& dir){
    auto file=dir.getChildFile("long-source.wav");juce::AudioBuffer<float> pcm(2,48000*60);pcm.clear();pcm.setSample(0,12000,.5f);juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));if(!writer||!writer->writeFromAudioSampleBuffer(pcm,0,pcm.getNumSamples()))throw std::runtime_error("lifecycle PCM creation failed");writer.reset();
    Commands c(false);c.commit(c.makePlan("human",Json::array({op("track.create",{{"name","Source cancellation"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",file.getFullPathName().toStdString()},{"position_samples",0}})})));const auto before=c.query();const std::string clip=before["tracks"][0]["clips"][0]["id"];auto request=args(c,clip,48000,"source-cancel");request["source_start_frame"]=0;request["source_end_frame"]=pcm.getNumSamples();auto pending=c.analysisControl("source",request);
    check(pending["busy"].get<bool>()&&!pending["progress_available"].get<bool>()&&pending["progress"].is_null(),"pending raw-source job explicitly exposes no fabricated progress estimate");
    rejects([&]{c.analysisControl("master",{{"session_token",c.sessionToken()},{"base_revision",before["revision"]},{"start_samples",0},{"end_samples",48000},{"request_key","parallel-master"}});},"Master and source requests share the production single-worker budget");
    const auto cancelledAt=juce::Time::getMillisecondCounterHiRes();c.analysisControl("cancel",{{"artifact_id",pending["request"]["artifact_id"]}});auto cancelled=wait(c);check(cancelled["state"]=="cancelled"&&juce::Time::getMillisecondCounterHiRes()-cancelledAt<2000,"source hashing/measurement cancellation has a real terminal receipt within fixed two seconds");
    check(c.query()["revision"]==before["revision"]&&c.query()["tracks"]==before["tracks"],"single-worker rejection and cancellation preserve native Edit facts and revision");
    auto invalid=request;invalid["request_key"]="missing-object";invalid["clip"]="does-not-exist";rejects([&]{c.analysisControl("source",invalid);},"missing audio clip is rejected without false analysis success");invalid=request;invalid["request_key"]="bad-range";invalid["source_end_frame"]=pcm.getNumSamples()+1;rejects([&]{c.analysisControl("source",invalid);},"native source range beyond actual media rejects before launching a job");
}
void integration(const juce::File& dir){
    const int rate=44100;auto source=impulseFile(dir,rate);auto hash=Commands::mediaHash(source);Commands c(false);c.commit(c.makePlan("human",Json::array({op("track.create",{{"name","Source impulses"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",source.getFullPathName().toStdString()},{"position_samples",48000}})})));
    auto initial=c.query();const std::string track=initial["tracks"][0]["id"],clip=initial["tracks"][0]["clips"][0]["id"];auto request=args(c,clip,rate,"source-native");auto pending=c.analysisControl("source",request);check(pending["busy"].get<bool>()&&!pending["request"].contains("media_sha256"),"source job starts pending and cannot invent a measured hash or result");check(c.analysisControl("source",request)["request"]["artifact_id"]==pending["request"]["artifact_id"],"identical source retry shares actual worker");auto altered=request;altered["profile"]={{"silence_threshold_dbfs",-50}};rejects([&]{c.analysisControl("source",altered);},"same key cannot change source detector conditions");
    auto complete=wait(c);auto artifact=complete["receipt"];check(complete["state"]=="completed"&&artifact["current"].get<bool>()&&artifact["binding"]["tap_point"]=="source_clip"&&artifact["binding"]["media_sha256"]==hash&&!artifact.contains("render_sha256")&&!artifact["binding"].contains("start_samples"),"real original PCM provenance distinguishes native frames and raw media from Master rendering");
    check(c.query()["revision"]==initial["revision"]&&c.query()["tracks"]==initial["tracks"]&&c.query()["position_samples"]==initial["position_samples"],"analysis creates no edit transaction and changes no track or transport");
    Json onset;for(const auto& e:artifact["events"])if(e["kind"]=="transient_candidate"&&e["source_start_frame"]==rate/4)onset=e;check(onset.is_object(),"native source receipt contains the actual first transient candidate");
    auto locate=[&](const std::string& id,int64_t event){return c.analysisControl("locate",{{"artifact_id",artifact["artifact_id"]},{"event_id",event},{"clip_id",id},{"base_revision",c.query()["revision"]}});};locate(clip,onset["id"]);check(c.query()["position_samples"]==60000,"44.1 kHz source frame maps to actual 48 kHz Transport at the independent expected position");
    c.commit(c.makePlan("human",Json::array({op("clip.move",{{"clip",clip},{"position_samples",96000}})})));auto moved=c.analysisStatus()["receipt"];check(moved["current"].get<bool>()&&moved["events"]==artifact["events"]&&moved["artifact_id"]==artifact["artifact_id"]&&moved["mapping_revision"]==c.query()["revision"],"move preserves immutable source evidence and returns a new current mapping revision");
    rejects([&]{c.analysisControl("locate",{{"artifact_id",artifact["artifact_id"]},{"event_id",onset["id"]},{"clip_id",clip},{"base_revision",initial["revision"]}});},"stale mapping version cannot seek to an obsolete preview");locate(clip,onset["id"]);check(c.query()["position_samples"]==108000,"moved source candidate locates at updated native clip position");
    c.commit(c.makePlan("human",Json::array({op("clip.trim",{{"clip",clip},{"start_samples",100800},{"end_samples",216000}})})));locate(clip,onset["id"]);check(c.query()["position_samples"]==108000&&c.analysisStatus()["receipt"]["events"]==artifact["events"],"non-destructive trim updates offset while leaving source events and absolute material position intact");
    c.commit(c.makePlan("human",Json::array({op("clip.split",{{"clip",clip},{"position_samples",144000},{"ref","$right"}})})));auto split=c.query();std::string right;for(const auto& q:split["tracks"][0]["clips"])if(q["id"]!=clip)right=q["id"];
    Json second;for(const auto& e:artifact["events"])if(e["kind"]=="transient_candidate"&&e["source_start_frame"]==rate*5/4)second=e;rejects([&]{locate(clip,second["id"]);},"event outside original half after split is not spuriously located");locate(right,second["id"]);check(c.query()["position_samples"]==156000&&c.analysisStatus()["receipt"]["mapping_set"]["total"]==2,"same source artifact follows split to actual right clip ID and correct native location");
    c.undo();check(c.analysisStatus()["receipt"]["mapping_set"]["total"]==1&&c.analysisStatus()["receipt"]["current"].get<bool>(),"Undo changes clip views while preserving valid original-source evidence");c.redo();check(c.analysisStatus()["receipt"]["mapping_set"]["total"]==2,"Redo restores source views with no duplicate measurements");
    c.commit(c.makePlan("human",Json::array({op("track.gain",{{"track",track},{"db",6}}),op("clip.gain",{{"clip",clip},{"db",18}})})));auto mix=c.analysisStatus()["receipt"];check(mix["current"].get<bool>()&&mix["events"]==artifact["events"]&&mix["peak"]==.5,"track and Clip gain do not invalidate or falsely alter a raw-source tap measurement");
    evidence.push_back(mix);
    CommandQueue queue(c);Scope ro;ro.mode=Permission::ReadOnly;auto client=queue.connect("agent:source-tests",ro);McpSession session(client,Commands::registry());rpc(session,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","source-tests"},{"version","1"}}}});session.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());
    const auto page=rpc(session,"tools/call",{{"name","query_objects"},{"arguments",{{"collection","clips"},{"target",track},{"session_token",c.sessionToken()},{"base_revision",c.query()["revision"]}}}})["result"]["structuredContent"]["result"];check(page["items"][0]["source_sample_rate"]==rate&&page["items"][0]["source_frames"]==rate*3&&page["items"][0]["source_mapping_available"].get<bool>(),"registered MCP clip page supplies actual native rate frame count and mapping availability for planning");
    auto mcpArgs=args(c,right,rate,"source-mcp");auto forbidden=mcpArgs;forbidden["path"]="/tmp/unknown.wav";check(rpc(session,"tools/call",{{"name","analyze_source_clip"},{"arguments",forbidden}})["result"]["isError"].get<bool>(),"MCP source analysis cannot take an arbitrary media path");
    auto accepted=rpc(session,"tools/call",{{"name","analyze_source_clip"},{"arguments",mcpArgs}});check(!accepted["result"]["isError"].get<bool>(),"read-only MCP tool executes actual source worker via the registered command queue");wait(c);auto remote=rpc(session,"tools/call",{{"name","query_analysis"},{"arguments",Json::object()}})["result"]["structuredContent"]["result"];check(remote["receipt"]["binding"]["media_sha256"]==hash&&remote["receipt"]["mapping_set"]["total"]==2&&remote["receipt"]["current"].get<bool>(),"MCP returns actual source identity evidence and current split clip mappings");
    artifact=remote["receipt"];auto saved=dir.getChildFile("source.tracktionedit");c.save(saved);c.open(saved);check(c.analysisStatus()["state"]=="idle"&&!c.query()["can_undo"].get<bool>(),"save/reopen retains native clips but does not promote saved analysis or Undo to a live success");
    auto afterOpen=c.query();const std::string reopened=afterOpen["tracks"][0]["clips"][0]["id"];c.analysisControl("source",args(c,reopened,rate,"source-reopened"));artifact=wait(c)["receipt"];
    juce::MemoryBlock bytes;check(source.loadFileAsData(bytes),"fault injection preserves a complete copy of owned PCM");const auto timestamp=source.getLastModificationTime();auto changed=bytes;static_cast<char*>(changed.getData())[changed.getSize()-1]^=1;check(source.replaceWithData(changed.getData(),changed.getSize())&&source.setLastModificationTime(timestamp),"inject same-size same-mtime PCM mutation");
    rejects([&]{c.analysisControl("locate",{{"artifact_id",artifact["artifact_id"]},{"event_id",0},{"clip_id",reopened},{"base_revision",c.query()["revision"]}});},"deep SHA256 verification rejects a same-size same-mtime source mutation before seek");check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"source integrity failure permanently invalidates the artifact");source.replaceWithData(bytes.getData(),bytes.getSize());source.setLastModificationTime(timestamp);check(Commands::mediaHash(source)==hash,"all edits and fault recovery leave original source bytes unchanged");
}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-source-"+juce::Uuid().toString());dir.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();for(int rate:{44100,48000,96000})numerical(dir,rate);
    check(analysis::sourceProfile(Json::object()).dump()==analysis::sourceProfile({{"minimum_silence_ms",100},{"silence_threshold_dbfs",-60}}).dump(),"equivalent detector defaults canonicalise identically");rejects([&]{analysis::sourceProfile({{"upload",true}});},"unknown detector fields cannot request upload");rejects([&]{analysis::sourceProfile({{"minimum_silence_ms",0}});},"unsupported detector conditions are rejected");
    boundedFeatures();lifecycle(dir);integration(dir);const double elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<90000,"source qualification meets fixed ninety-second total budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"evidence",evidence},{"scope","real detached PCM, native Edit commands, source-frame mappings and production MCP protocol; not a subjective listening or desktop model demonstration"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("source test report write failed");}std::cout<<report.dump(2)<<std::endl;dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;dir.deleteRecursively();return 1;}}
