#include "Workspace.h"
#include "SpectrumFixture.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;using namespace ndaw::desktop;namespace fx=spectrum_fixture;
namespace {
int checks=0;double maxJob=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
void pump(int ms=30){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* child:p.getChildren())if(auto* found=find(*child,id))return found;return nullptr;}
void click(Workspace& w,const juce::String& id){auto* b=dynamic_cast<juce::Button*>(find(w,id));if(!b||!b->isEnabled())throw std::runtime_error("native spectrum button unavailable: "+id.toStdString());const auto callback=b->onClick;bool delivered=false;b->onClick=[&]{delivered=true;callback();};b->triggerClick();const auto deadline=juce::Time::getMillisecondCounterHiRes()+1000;while(!delivered&&juce::Time::getMillisecondCounterHiRes()<deadline)pump(1);b->onClick=callback;check(delivered,"actual asynchronous native callback delivered");pump();}
juce::TextEditor& field(Workspace& w,const char* id){auto* p=dynamic_cast<juce::TextEditor*>(find(w,id));if(!p)throw std::runtime_error(id);return *p;}
juce::ComboBox& combo(Workspace& w,const char* id){auto* p=dynamic_cast<juce::ComboBox*>(find(w,id));if(!p)throw std::runtime_error(id);return *p;}
juce::Slider& slider(Workspace& w,const juce::String& id){auto* p=dynamic_cast<juce::Slider*>(find(w,id));if(!p)throw std::runtime_error(id.toStdString());return *p;}
juce::String label(Workspace& w,const char* id){auto* p=dynamic_cast<juce::Label*>(find(w,id));if(!p)throw std::runtime_error(id);return p->getText();}
Json wait(Workspace& w){const auto began=juce::Time::getMillisecondCounterHiRes();while(w.queryAnalysis().value("busy",false)){if(juce::Time::getMillisecondCounterHiRes()-began>12000)throw std::runtime_error("native spectrum exceeds12 second job budget");pump(10);}maxJob=std::max(maxJob,juce::Time::getMillisecondCounterHiRes()-began);pump(300);const auto state=w.queryAnalysis();if(state["state"]!="completed")throw std::runtime_error(state.dump());return state["receipt"];}
class Storage final:public te::PropertyStorage{public:explicit Storage(juce::File f):PropertyStorage("Forma spectrum UI"),folder(f){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-spectrum-ui-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();const auto data=fx::pcm();const auto file=folder.getChildFile("bands.wav");loudness_fixture::write(file,data,48000);const auto hash=Commands::mediaHash(file);Workspace w(false,std::make_unique<Storage>(folder.getChildFile("prefs")));w.setSize(1280,1100);w.setVisible(true);w.prepareImport(file);pump();click(w,"plan.accept");const auto facts=w.query();const std::string track=facts["tracks"][0]["id"];w.showAnalysis();field(w,"analysis.start_samples").setText("23");field(w,"analysis.end_samples").setText("48060");click(w,"analysis.master.run");const auto master=wait(w);
    check(fx::matches(master["spectrum"],data,23,48060,juce::Decibels::decibelsToGain(-12.f)),"native panel spectrum is real rendered Master with known fader");check(find(w,"analysis.spectrum")&&field(w,"analysis.summary").getText().contains("2049频点"),"native scroll panel exposes actual spectrum and bin count");click(w,"analysis.spectrum.maximum");check(slider(w,"analysis.spectrum.bin").getValue()==master["spectrum"]["dominant_bin"].get<int>()&&label(w,"analysis.spectrum.readout").contains("实际完整窗"),"maximum selects actual measured bin and window provenance");
    slider(w,"analysis.spectrum.bin").setValue(128,juce::sendNotificationSync);check(label(w,"analysis.spectrum.readout").contains("1500.000 Hz"),"explicit FFT bin frequency derives from real sample rate");combo(w,"analysis.spectrum.band").setSelectedId(3,juce::sendNotificationSync);const auto band=master["spectrum"]["bands"][2];check(label(w,"analysis.spectrum.band_readout").contains(juce::String(100*band["fraction"].get<double>(),3)+"%")&&label(w,"analysis.spectrum.band_readout").contains("Ch 2"),"band display uses actual power fraction and individual channel measurements");check(w.query()["tracks"]==facts["tracks"]&&w.query()["revision"]==facts["revision"],"inspection creates no Edit or Undo writes");
    click(w,"analysis.close");slider(w,"track.gain:"+juce::String(track)).setValue(-18,juce::sendNotificationSync);pump();w.showAnalysis();check(!w.queryAnalysis()["receipt"]["current"].get<bool>()&&field(w,"analysis.summary").getText().contains("历史快照")&&find(w,"analysis.spectrum.maximum")->isEnabled(),"human edit leaves historical spectrum inspectable without current-evidence claim");click(w,"analysis.close");click(w,"history.undo");w.showAnalysis();check(!w.queryAnalysis()["receipt"]["current"].get<bool>()&&std::abs(w.query()["tracks"][0]["gain_db"].get<double>()+12)<1e-5,"native Undo restores real fader while old spectrum remains stale");field(w,"analysis.start_samples").setText("23");field(w,"analysis.end_samples").setText("48060");click(w,"analysis.master.run");const auto restored=wait(w);check(restored["current"].get<bool>()&&restored["artifact_id"]!=master["artifact_id"]&&restored["spectrum"]==master["spectrum"],"remeasurement returns exact current spectrum with new artifact");
    combo(w,"analysis.tap").setSelectedId(2,juce::sendNotificationSync);field(w,"analysis.start_samples").setText("0");field(w,"analysis.end_samples").setText("4095");click(w,"analysis.source.run");const auto shortResult=wait(w);check(shortResult["spectrum"]["status"]=="insufficient_window"&&!find(w,"analysis.spectrum.maximum")->isEnabled()&&label(w,"analysis.spectrum.readout").contains("未补零"),"short raw PCM presents unavailable spectrum and disables invented maximum");w.setSize(1120,700);const auto* view=find(w,"analysis.spectrum");check(view&&find(w,"analysis.spectrum.maximum")->getRight()<=view->getWidth()&&find(w,"analysis.spectrum.band_readout")->getRight()<=view->getWidth(),"minimum window keeps actual spectrum controls within scrollable content");check(Commands::mediaHash(file)==hash,"all native analysis and Undo preserve original media");const auto elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"native spectrum workflow stays inside fixed60 second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"max_job_ms",maxJob},{"master",master},{"restored",restored},{"short",shortResult},{"scope","actual asynchronous native controls; production desktop separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("native spectrum report write failed");}folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
