#include "SpectrumFixture.h"
#include <nativedaw/v2/Spectrum.h>
#include <nativedaw/v2/SourceFeatures.h>
#include <nativedaw/v2/McpSession.h>
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;namespace fx=spectrum_fixture;
namespace {
int checks=0;double maxJob=0;Json examples=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
void pump(){juce::MessageManager::getInstance()->runDispatchLoopUntil(10);}
void edit(Commands& c,const char* command,Json args){c.commit(c.makePlan("human",Json::array({{{"command",command},{"args",args}}})));}
Json args(Commands& c,const char* key){return {{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]},{"start_samples",23},{"end_samples",48060},{"request_key",key}};}
Json wait(Commands& c){const auto began=juce::Time::getMillisecondCounterHiRes();while(c.analysisStatus()["busy"].get<bool>()){if(juce::Time::getMillisecondCounterHiRes()-began>12000)throw std::runtime_error("spectrum job exceeds12 seconds");pump();}maxJob=std::max(maxJob,juce::Time::getMillisecondCounterHiRes()-began);const auto state=c.analysisStatus();if(state["state"]!="completed")throw std::runtime_error(state.dump());return state["receipt"];}
Json rpc(McpSession& session,const char* method,Json params){static int serial=0;std::vector<Json> out;std::thread t([&]{out=session.receive(Json{{"jsonrpc","2.0"},{"id",++serial},{"method",method},{"params",params}}.dump());});t.join();const auto began=juce::Time::getMillisecondCounterHiRes();while(out.empty()){if(juce::Time::getMillisecondCounterHiRes()-began>5000)throw std::runtime_error("spectrum MCP exceeds5 seconds");pump();std::thread p([&]{out=session.ready();});p.join();}return out[0];}
void numerical(const juce::File& folder){
    for(int rate:{8000,44100,48000,96000,192000})for(int channels:{1,2}){
        const auto data=fx::pcm(12605,channels);const auto file=folder.getChildFile(juce::String(rate)+"-"+juce::String(channels)+".wav");loudness_fixture::write(file,data,rate);const auto measured=analysis::measure(file,34567,{}, {23,12588},nullptr,analysis::FeatureDomain::SessionSamples);const auto& s=measured["spectrum"];
        check(s["status"]=="measured"&&s["bin_power"].size()==2049&&s["window_count"]==fx::ends(12565).size()&&s["final_end_aligned_window"].get<bool>(),"full actual grid and distinct end-aligned window retained at8/44.1/48/96/192k mono/stereo");
        check(fx::matches(s,data,23,12588),"independent double DFT bins and time-domain Parseval agree within fixed tolerances");
        check(s["decoded_start_frame"]==23&&s["decoded_end_frame"]==12588&&s["session_start_samples"]==34567&&s["bin_width_hz"]==rate/4096.,"nonzero decode range and engineering origin remain explicit");
        int covered=0;double total=0;bool bands=true;for(const auto& band:s["bands"]){bands&=band["first_bin"]==covered;covered=band["end_bin"];double predicted=0;for(int k=band["first_bin"];k<covered;++k)predicted+=s["bin_power"][k].get<double>();bands&=fx::close(band["power"],predicted)&&band["upper_hz"].get<double>()<=rate/2.;double channelMean=0;for(const auto& power:band["channel_power"])channelMean+=power.get<double>()/channels;bands&=fx::close(channelMean,band["power"]);total+=band["power"].get<double>();}check(bands&&covered==2049&&fx::close(total,s["total_power"]),"band centres partition every DC/Nyquist bin exactly once and retain channel powers");examples.push_back({{"rate",rate},{"channels",channels},{"spectrum",s}});
    }
    const auto rate=48000;juce::AudioBuffer<float> tones(2,8192);for(int n=0;n<8192;++n){const float v=.2f*std::sin(2*juce::MathConstants<double>::pi*128*n/4096);tones.setSample(0,n,v);tones.setSample(1,n,-v);}const auto file=folder.getChildFile("anti.wav");loudness_fixture::write(file,tones,rate);const auto anti=analysis::measure(file,0)["spectrum"];check(fx::close(anti["total_power"],.02)&&fx::close(anti["bin_power"][128],.04/3)&&anti["dominant_bin"]==128,"opposite polarity stereo remains real power with calibrated Hann central bin");
    const auto shortFile=folder.getChildFile("short.wav");juce::AudioBuffer<float> silent(1,4095);silent.clear();loudness_fixture::write(shortFile,silent,rate);const auto shortResult=analysis::measure(shortFile,0)["spectrum"];check(shortResult["status"]=="insufficient_window"&&shortResult["bin_power"].empty()&&shortResult["total_power"].is_null(),"short range has no padded or invented spectral power");
    silent.setSize(1,4096);silent.clear();const auto zeroFile=folder.getChildFile("zero.wav");loudness_fixture::write(zeroFile,silent,rate);const auto zero=analysis::measure(zeroFile,0)["spectrum"];check(zero["status"]=="measured"&&zero["window_count"]==1&&zero["total_power"]==0&&zero["rms_dbfs"].is_null()&&zero["dominant_bin"].is_null(),"actual full-window silence is distinct from unavailable spectrum");for(const auto& b:zero["bands"])check(b["fraction"].is_null(),"silence does not manufacture frequency percentages");
    juce::AudioBuffer<float> dc(1,4096);for(int n=0;n<4096;++n)dc.setSample(0,n,.25f);const auto dcFile=folder.getChildFile("dc.wav");loudness_fixture::write(dcFile,dc,rate);const auto d=analysis::measure(dcFile,0)["spectrum"];check(fx::close(d["total_power"],.0625)&&fx::close(d["bin_power"][0],.0625*2/3)&&d["dominant_bin"]==0,"DC power includes correct non-doubled endpoint");for(int n=0;n<4096;++n)dc.setSample(0,n,n%2?-.25f:.25f);const auto nyFile=folder.getChildFile("ny.wav");loudness_fixture::write(nyFile,dc,rate);const auto ny=analysis::measure(nyFile,0)["spectrum"];check(fx::close(ny["total_power"],.0625)&&fx::close(ny["bin_power"][2048],.0625*2/3)&&ny["dominant_bin"]==2048,"Nyquist endpoint is included without double counting");
    bool cancel=false;analysis::Control control{[&]{return cancel;},[]{}};analysis::Spectrum cancelled(48000,1,0,0,analysis::FeatureDomain::SourceFrames,control);cancel=true;fails([&]{cancelled.finish();},"cancelled spectrum cannot become successful evidence");
    juce::AudioBuffer<float> longData(1,8000*300);for(int n=0;n<longData.getNumSamples();++n)longData.setSample(0,n,.1f*std::sin(2*juce::MathConstants<double>::pi*300*n/8000.));const auto longFile=folder.getChildFile("long.wav");loudness_fixture::write(longFile,longData,8000);auto full=analysis::measure(longFile,0,{}, {},analysis::sourceProfile(Json::object()));check(full["spectrum"]["window_count"]==fx::ends(2400000).size()&&full["spectrum"]["bin_power"].size()==2049&&full["spectrum"].dump().size()<=64*1024&&full.dump().size()<=252*1024,"300-second real PCM executes every window and keeps complete combined receipt within fixed budgets");examples.push_back({{"case","long_actual_pcm"},{"spectrum_bytes",full["spectrum"].dump().size()},{"receipt_bytes",full.dump().size()},{"windows",full["spectrum"]["window_count"]}});
}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-spectrum-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();numerical(folder);const auto data=fx::pcm();const auto file=folder.getChildFile("mix.wav");loudness_fixture::write(file,data,48000);const auto hash=Commands::mediaHash(file);Commands c(false);c.commit(c.makePlan("human",Json::array({{{"command","track.create"},{"args",{{"name","Spectrum"},{"ref","$t"}}}},{{"command","clip.import"},{"args",{{"track","$t"},{"path",file.getFullPathName().toStdString()},{"position_samples",0}}}},{{"command","track.gain"},{"args",{{"track","$t"},{"db",-12}}}}})));const auto facts=c.query();const std::string track=facts["tracks"][0]["id"],clip=facts["tracks"][0]["clips"][0]["id"];
    c.analysisControl("master",args(c,"master"));const auto master=wait(c);check(fx::matches(master["spectrum"],data,23,48060,juce::Decibels::decibelsToGain(-12.f)),"actual Master spectrum follows real fader and independent PCM DFT");check(c.query()["tracks"]==facts["tracks"]&&c.query()["revision"]==facts["revision"],"spectral analysis does not mutate active Edit or history");
    auto request=args(c,"pre");request["track"]=track;request["tap_point"]="track_pre_inserts";c.analysisControl("track",request);const auto pre=wait(c);check(fx::matches(pre["spectrum"],data,23,48060),"real pre-insert native boundary excludes fader spectrum");request=args(c,"bus");request["track"]=track;request["tap_point"]="bus";c.analysisControl("track",request);const auto bus=wait(c);check(fx::matches(bus["spectrum"],data,23,48060,juce::Decibels::decibelsToGain(-12.f)),"actual Bus chain spectrum includes fader without mixing unrelated outputs");
    CommandQueue queue(c);Scope read;read.mode=Permission::ReadOnly;McpSession session(queue.connect("agent:spectrum",read),Commands::registry());rpc(session,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","spectrum-tests"},{"version","1"}}}});session.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());const auto reply=rpc(session,"tools/call",{{"name","query_analysis"},{"arguments",Json::object()}});check(reply["result"]["structuredContent"]["result"]["receipt"]["spectrum"]==bus["spectrum"],"real readonly MCP protocol returns same complete spectrum");
    edit(c,"plugin.insert",{{"track",track},{"type",te::EqualiserPlugin::xmlTypeName}});const std::string eq=c.query()["tracks"][0]["plugins"][0]["id"];edit(c,"plugin.parameter",{{"plugin",eq},{"parameter","Mid freq 1"},{"value",37*48000./4096}});edit(c,"plugin.parameter",{{"plugin",eq},{"parameter","Mid gain 1"},{"value",6}});edit(c,"track.gain",{{"track",track},{"db",0}});request=args(c,"post-eq");request["track"]=track;request["tap_point"]="track_post_inserts";c.analysisControl("track",request);const auto post=wait(c);check(post["spectrum"]["bin_power"][37].get<double>()>2.5*pre["spectrum"]["bin_power"][37].get<double>(),"real EQ in post-insert tap changes measured tone power");
    const auto exported=folder.getChildFile("eq-formal.wav");c.render(exported,23,48060);juce::AudioFormatManager fm;fm.registerBasicFormats();std::unique_ptr<juce::AudioFormatReader> rd(fm.createReaderFor(exported));check(rd&&rd->lengthInSamples==48037,"formal EQ render retains actual selected interval");juce::AudioBuffer<float> rendered(rd->numChannels,int(rd->lengthInSamples));check(rd->read(&rendered,0,rendered.getNumSamples(),0,true,true)&&fx::matches(post["spectrum"],rendered,0,rendered.getNumSamples()),"post EQ spectrum agrees with independent DFT of actual formal WAV");edit(c,"track.gain",{{"track",track},{"db",-12}});

    edit(c,"track.gain",{{"track",track},{"db",-18}});check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"human gain invalidates processed spectrum");c.undo();check(!c.analysisStatus()["receipt"]["current"].get<bool>()&&std::abs(c.query()["tracks"][0]["gain_db"].get<double>()+12)<1e-5,"human Undo restores fader without reviving obsolete processed spectrum");
    auto raw=args(c,"source");raw.erase("start_samples");raw.erase("end_samples");raw["clip"]=clip;raw["source_start_frame"]=23;raw["source_end_frame"]=48060;c.analysisControl("source",raw);const auto source=wait(c);check(fx::matches(source["spectrum"],data,23,48060)&&source["spectrum"]["session_start_samples"].is_null(),"raw spectrum retains native source domain and bypasses processing");edit(c,"clip.move",{{"clip",clip},{"position_samples",96000}});check(c.analysisStatus()["receipt"]["current"].get<bool>()&&c.analysisStatus()["receipt"]["spectrum"]==source["spectrum"],"raw spectrum remains attached to source after human move");const auto saved=folder.getChildFile("spectrum.tracktionedit");c.save(saved);c.open(saved);check(c.analysisStatus()["state"]=="idle"&&Commands::mediaHash(file)==hash,"actual save reopen preserves media and never revives old spectral success");const auto elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<120000,"spectrum backend keeps fixed120 second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"max_job_ms",maxJob},{"numerical",examples},{"master",master},{"pre",pre},{"bus",bus},{"post_eq",post},{"source",source},{"scope","offline actual PCM and native graph/protocol; production desktop separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("spectrum report write failed");}folder.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;folder.deleteRecursively();return 1;}}
