#include "Workspace.h"
#include <nativedaw/v2/McpSession.h>
#include <chrono>
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;
namespace {
class Storage final:public te::PropertyStorage{public:explicit Storage(juce::File f):PropertyStorage("Forma range tests"),folder(f){}juce::File getAppPrefsFolder()override{folder.createDirectory();return folder;}private:juce::File folder;};
struct Scratch{juce::File folder=juce::File("/tmp").getChildFile("forma-range-"+juce::Uuid().toString());~Scratch(){folder.deleteRecursively();}};
int checks=0;Json measurements=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,why);}
void pump(){juce::MessageManager::getInstance()->runDispatchLoopUntil(15);}
Json op(const char* command,Json args){return {{"command",command},{"args",args}};}
Json set(int64_t a,int64_t b){return op("session.range.set",{{"start_samples",a},{"end_samples",b}});}
Json run(Commands& c,Json ops){auto plan=c.makePlan("human",std::move(ops));c.commit(plan);pump();return plan;}
void fixture(const juce::File& file){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=file.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture writer failed");juce::AudioBuffer<float> b(2,96000);for(int ch=0;ch<2;++ch)for(int n=0;n<96000;++n)b.setSample(ch,n,float((ch==0?.1:.05)*(1+.2*n/96000.)*std::sin(2*juce::MathConstants<double>::pi*(ch==0?731:419)*n/48000)));if(!writer->writeFromAudioSampleBuffer(b,0,96000))throw std::runtime_error("fixture write failed");}
juce::AudioBuffer<float> pcm(const juce::File& f){juce::AudioFormatManager fm;fm.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(fm.createReaderFor(f));if(!reader)throw std::runtime_error("PCM reader failed");juce::AudioBuffer<float> b(int(reader->numChannels),int(reader->lengthInSamples));if(!reader->read(&b,0,b.getNumSamples(),0,true,true))throw std::runtime_error("PCM decode failed");return b;}
void signal(Commands& c,const juce::File& source){run(c,Json::array({op("track.create",{{"name","Range signal"},{"ref","$t"}}),op("clip.import",{{"track","$t"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}})}));}
void core(const juce::File& folder,const juce::File& source){
    Commands c(false,std::make_unique<Storage>(folder));signal(c,source);auto originalHash=Commands::mediaHash(source);auto before=c.query()["tracks"];check(c.timelineRange().is_null()&&c.querySummary()["time_selection"].is_null(),"fresh Edit and compact Agent summary have no invented range");
    auto plan=c.makePlan("human",Json::array({set(24000,72000),set(24013,71971)}));auto preview=c.preview(plan)["time_selection_changes"];check(c.timelineRange().is_null()&&preview.size()==2&&preview[0]["before"].is_null()&&preview[1]["before"]==preview[0]["after"],"ordered preview reports actual before/after without writing Edit");c.commit(plan);check(c.timelineRange()["start_samples"]==24013&&c.timelineRange()["length_samples"]==47958&&c.query()["tracks"]==before,"compound Plan commits metadata without editing original audio");c.undo();check(c.timelineRange().is_null(),"one Undo restores selection before both ordered operations");c.redo();check(c.timelineRange()["end_samples"]==71971,"one Redo restores exact sample endpoints");
    auto requested=c.exportRequest(true);auto target=folder.getChildFile("selection.wav");auto receipt=c.renderRequest(target,requested);check(receipt["frames"]==47958&&receipt["channels"]==2&&receipt["sample_rate"]==48000&&receipt["pcm_bits"]==24&&receipt["range"]==requested&&receipt["audio_verified"],"actual Tracktion render verifies unaligned selected range and WAV format");check(receipt["render_ms"].get<double>()<10000&&receipt["lufs_i"].is_number()&&receipt["true_peak_dbtp"].is_number(),"real range render meets preset ten-second budget and measured loudness/True Peak");
    auto rendered=pcm(target),input=pcm(source);double maximumError=0;for(int ch=0;ch<2;++ch)for(int n=0;n<rendered.getNumSamples();++n)maximumError=std::max(maximumError,std::abs(double(rendered.getSample(ch,n)-input.getSample(ch,n+24013))));measurements.push_back(receipt);measurements.push_back({{"maximum_pcm_error",maximumError},{"preset_tolerance",2e-5}});check(maximumError<2e-5,"unaligned non-zero source offset matches original decoded PCM within preset tolerance");
    fails([&]{c.renderRequest(target,requested);},"export never overwrites an existing file");check(Commands::mediaHash(target)==receipt["media_hash"].get<std::string>(),"failed overwrite preserves verified export bytes");
    run(c,Json::array({set(24000,72000)}));auto aligned=c.renderRequest(folder.getChildFile("aligned.wav"),c.exportRequest(true));check(aligned["frames"]==48000&&aligned["render_ms"].get<double>()<10000,"aligned selection exports exactly one second");measurements.push_back(aligned);
    auto stale=c.exportRequest(true);run(c,Json::array({op("track.rename",{{"track",before[0]["id"]},{"name","Newer human name"}})}));auto failedPath=folder.getChildFile("stale.wav");fails([&]{c.renderRequest(failedPath,stale);},"human change during file dialog rejects old render request");check(!failedPath.exists(),"rejected stale request produces no external file");
    auto stalePlan=c.makePlan("human",Json::array({set(1,24001)}));run(c,Json::array({op("session.range.clear",Json::object())}));check(c.timelineRange().is_null(),"clear removes actual persistent range");fails([&]{c.commit(stalePlan);},"interleaved human range clear rejects old Plan");fails([&]{c.exportRequest(true);},"missing selection cannot fall back silently to full project");c.undo();check(c.timelineRange()["end_samples"]==72000,"Undo clear restores range");
    auto stable=c.timelineRange();run(c,Json::array({op("tempo.set",{{"position_samples",0},{"bpm",96}})}));check(c.timelineRange()==stable,"time selection stays in session samples after Tempo edit");
    for(auto bounds:{std::pair<int64_t,int64_t>{-1,3},{3,3},{4,3},{0,std::llround(te::Edit::maximumLength*48000)+1}})fails([&]{c.makePlan("human",Json::array({set(bounds.first,bounds.second)}));},"negative empty reversed or SDK-exceeding range rejected");
    auto fractional=set(0,3);fractional["args"]["end_samples"]=3.5;fails([&]{c.makePlan("human",Json::array({fractional}));},"fractional samples cannot masquerade as integer positions");fractional["args"]["end_samples"]=std::numeric_limits<uint64_t>::max();fails([&]{c.makePlan("human",Json::array({fractional}));},"unsigned overflow rejected before sample conversion");
    Scope restricted;restricted.targets.insert(before[0]["id"]);fails([&]{c.review(c.makePlan("agent:limited",Json::array({set(0,24000)})),restricted);},"track-scoped Agent cannot modify global selection");Scope readOnly;readOnly.mode=Permission::ReadOnly;fails([&]{c.commit(c.makePlan("human",Json::array({set(0,24000)})),false,readOnly);},"read-only scope cannot commit selection");
    c.seek(24013);check(c.query()["position_samples"]==24013,"native Transport precision verified at non-block sample position");fails([&]{c.seek(-1);},"negative seek rejected");fails([&]{c.seek(std::llround(te::Edit::maximumLength*48000)+1);},"SDK-exceeding seek rejected");
    auto oldRequest=c.exportRequest(true);auto saved=folder.getChildFile("selected.tracktionedit");c.save(saved);c.open(saved);check(c.timelineRange()==stable&&c.querySummary()["time_selection"]==stable,"real save and reopen preserve exact selected range for Agent and GUI");fails([&]{c.renderRequest(folder.getChildFile("old-session.wav"),oldRequest);},"new session token rejects prior dialog even with same saved range");
    check(Commands::mediaHash(source)==originalHash,"original media hash unchanged through selection edits, Undo, export and reopen");
}
juce::Component* find(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* child:p.getChildren())if(auto* result=find(*child,id))return result;return nullptr;}
void click(juce::Component& w,const char* id){auto* b=dynamic_cast<juce::Button*>(find(w,id));if(!b||!b->isEnabled())throw std::runtime_error(std::string("GUI button unavailable: ")+id);b->triggerClick();pump();}
void input(juce::Component& w,const char* id,const char* value){auto* e=dynamic_cast<juce::TextEditor*>(find(w,id));if(!e)throw std::runtime_error("GUI field unavailable");e->setText(value,false);}
void ui(const juce::File& folder,const juce::File& source){ndaw::desktop::Workspace w(false,std::make_unique<Storage>(folder));w.setVisible(true);w.setSize(1120,700);w.prepareImport(source);click(w,"plan.accept");click(w,"timeline.range.open");check(find(w,"timeline.range.panel")&&find(w,"timeline.range.start"),"native selection panel is accessible in minimum-sized production workspace");input(w,"timeline.range.start","24013");input(w,"timeline.range.end","71971");click(w,"timeline.range.apply");check(w.query()["time_selection"]["start_samples"]==24013&&w.query()["time_selection"]["end_samples"]==71971,"production GUI callback commits same exact range as L1");input(w,"timeline.position","31415");click(w,"timeline.seek");check(w.query()["position_samples"]==31415,"native precise position field drives actual Transport");input(w,"timeline.range.end","1.5");click(w,"timeline.range.apply");check(w.query()["time_selection"]["end_samples"]==71971&&dynamic_cast<juce::Label*>(find(w,"timeline.range.result"))->getText().contains(ndaw::desktop::text("未执行")),"fractional integer input reports failure and leaves Edit unchanged");
    auto* units=dynamic_cast<juce::ComboBox*>(find(w,"timeline.range.unit"));units->setSelectedId(2);pump();input(w,"timeline.range.start","0.5");input(w,"timeline.range.end","1.5");click(w,"timeline.range.apply");check(w.query()["time_selection"]["start_samples"]==24000&&w.query()["time_selection"]["end_samples"]==72000,"seconds input maps to real 48 kHz session samples");click(w,"timeline.range.close");click(w,"history.undo");check(w.query()["time_selection"]["start_samples"]==24013,"GUI Undo restores prior selection");click(w,"history.redo");check(w.query()["time_selection"]["end_samples"]==72000,"GUI Redo restores selected duration");w.menuItemSelected(42,1);click(w,"history.undo");check(!find(w,"timeline.range.apply")->isEnabled(),"changed human revision disables stale panel commit");click(w,"timeline.range.refresh");check(find(w,"timeline.range.apply")->isEnabled(),"explicit refresh rebinds panel to actual new version");check(w.keyPressed(juce::KeyPress(juce::KeyPress::escapeKey))&&!find(w,"timeline.range.panel"),"Escape closes panel without hidden transport action");}
Json rpc(int id,const char* method,Json params=Json::object()){return {{"jsonrpc","2.0"},{"id",id},{"method",method},{"params",params}};}
Json call(McpSession& s,const Json& request){std::vector<Json> out;std::thread worker([&]{out=s.receive(request.dump());});worker.join();auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(5);while(out.empty()){if(std::chrono::steady_clock::now()>deadline)throw std::runtime_error("MCP range call timeout");pump();std::thread waiting([&]{out=s.ready();});waiting.join();}return out.at(0);}
Json tool(McpSession& s,const char* name,Json args=Json::object()){static int id=10;return call(s,rpc(id++,"tools/call",{{"name",name},{"arguments",args}}))["result"]["structuredContent"];}
void mcp(const juce::File& folder){Commands c(false,std::make_unique<Storage>(folder));CommandQueue q(c);McpSession s(q.connect("agent:range-test"),Commands::registry());call(s,rpc(1,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","range-test"},{"version","1"}}}}));s.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());auto planned=tool(s,"plan.session.range.set",{{"request_key","range-1"},{"base_revision",c.query()["revision"]},{"args",{{"start_samples",123},{"end_samples",45678}}}});check(planned["status"]=="planned"&&planned["preview"]["time_selection_changes"][0]["before"].is_null()&&c.timelineRange().is_null(),"registry-generated MCP range tool previews with actual evidence");auto planID=planned["plan"]["plan_id"];auto card=tool(s,"commit_plan",{{"plan_id",planID}});check(card["status"]=="awaiting_confirmation"&&c.timelineRange().is_null(),"external range commit remains pending local GUI authority");q.resolve(card["confirmation_id"],true);check(tool(s,"query_session_summary")["result"]["time_selection"]["start_samples"]==123,"confirmed external transaction is visible in actual compact query");auto undo=tool(s,"undo_plan",{{"plan_id",planID}});q.resolve(undo["confirmation_id"],true);check(c.timelineRange().is_null()&&tool(s,"query_plan",{{"plan_id",planID}})["status"]=="undone","confirmed external Undo restores selection with authoritative receipt");s.close();q.shutdown();}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{Scratch scratch;scratch.folder.createDirectory();auto source=scratch.folder.getChildFile("signal.wav");fixture(source);core(scratch.folder.getChildFile("core"),source);ui(scratch.folder.getChildFile("ui"),source);mcp(scratch.folder.getChildFile("mcp"));Json report{{"test","M1-RANGE-01"},{"result","passed"},{"checks",checks},{"measurements",measurements},{"scope","real Edit, PCM render/read, native production callbacks and MCP protocol; desktop acceptance separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<report.dump(2)<<std::endl;return 0;}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
