#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<"\n";}
juce::Component* visible(juce::Component& p,const juce::String& id){if(!p.isVisible())return nullptr;if(p.getComponentID()==id)return &p;for(auto* child:p.getChildren())if(auto* r=visible(*child,id))return r;return nullptr;}
void settle(){juce::MessageManager::getInstance()->runDispatchLoopUntil(100);}
void click(juce::Component& p,const juce::String& id){auto* b=dynamic_cast<juce::Button*>(visible(p,id));if(!b||!b->isEnabled())throw std::runtime_error("missing enabled button: "+id.toStdString());b->triggerClick();settle();}
juce::ComboBox& combo(juce::Component& p,const juce::String& id){auto* b=dynamic_cast<juce::ComboBox*>(visible(p,id));if(!b||!b->isEnabled())throw std::runtime_error("missing enabled chooser: "+id.toStdString());return *b;}
void choose(juce::Component& p,const juce::String& id,const juce::String& name){auto& c=combo(p,id);for(int i=0;i<c.getNumItems();++i)if(c.getItemText(i)==name){c.setSelectedId(c.getItemId(i),juce::sendNotificationSync);settle();return;}throw std::runtime_error("choice absent");}
Json find(ndaw::desktop::Workspace& w,const std::string& id){auto q=w.query();for(const auto& t:q["tracks"])if(t["id"]==id)return t;throw std::runtime_error("track absent");}
void signal(const juce::File& f){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=f.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("fixture unavailable");juce::AudioBuffer<float> b(2,48000);for(int ch=0;ch<2;++ch)for(int i=0;i<48000;++i)b.setSample(ch,i,.1f*std::sin(2*juce::MathConstants<double>::pi*440*i/48000));if(!writer->writeFromAudioSampleBuffer(b,0,48000))throw std::runtime_error("fixture write failed");}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-track-ui-"+juce::Uuid().toString());dir.createDirectory();auto pcm=dir.getChildFile("Vocal.wav");signal(pcm);auto hash=Commands::mediaHash(pcm);
    ndaw::desktop::Workspace w(false);w.setVisible(true);w.setSize(1440,950);w.prepareImport(pcm);click(w,"plan.accept");std::string source=w.query()["tracks"][0]["id"];
    combo(w,"track.type").setSelectedId(4,juce::dontSendNotification);click(w,"track.create");std::string aux=w.query()["tracks"].back()["id"],auxName=find(w,aux)["name"];
    click(w,"track.select:"+juce::String(source));click(w,"inspector.routing");choose(w,"routing.output",juce::String(auxName));choose(w,"routing.target",juce::String(auxName));click(w,"send.create");auto send=find(w,source)["sends"][0]["id"];check(find(w,source)["output"]["target"]==aux,"GUI sets native output and actual Aux send");
    click(w,"track.select:"+juce::String(aux));click(w,"inspector.group");click(w,"track.order.up");check(w.query()["tracks"][0]["id"]==aux&&find(w,aux)["order_index"]==0,"Edit up gesture changes real root order");check(!visible(w,"track.order.up")->isEnabled(),"first sibling cannot move past group boundary");click(w,"track.order.down");check(w.query()["tracks"][1]["id"]==aux,"Edit down gesture restores native position");click(w,"history.undo");check(w.query()["tracks"][0]["id"]==aux,"order Undo restores actual position");click(w,"history.redo");
    choose(w,"track.colour",ndaw::desktop::text("紫色"));check(find(w,aux)["colour"]=="#A761C2","palette writes native colour through human transaction");auto* name=dynamic_cast<juce::TextButton*>(visible(w,"track.select:"+juce::String(aux)));check(name&&name->findColour(juce::TextButton::buttonColourId)==juce::Colour(0xffa761c2).darker(.45f),"Edit track header displays actual native colour");click(w,"view.mix");name=dynamic_cast<juce::TextButton*>(visible(w,"track.select:"+juce::String(aux)));check(name&&name->findColour(juce::TextButton::buttonColourId)==juce::Colour(0xffa761c2).darker(.45f),"Mix displays same colour from shared facts");click(w,"track.order.up");check(w.query()["tracks"][0]["id"]==aux,"Mix ordering uses same command as Edit");click(w,"history.undo");click(w,"history.undo");check(find(w,aux)["colour"].is_null(),"colour Undo clears native property in both views");click(w,"history.redo");
    auto before=w.query();click(w,"track.delete.preview");auto* preview=dynamic_cast<juce::TextEditor*>(visible(w,"legacy.report"));check(preview&&preview->getText().contains(ndaw::desktop::text("外部输出 → None"))&&preview->getText().contains("Vocal")&&preview->getText().contains(ndaw::desktop::text("移除外部发送")),"delete preview names actual output and send impact");check(w.query()==before&&!visible(w,"group.parent"),"preview uses whole inspector and makes no Edit changes");click(w,"plan.reject");check(w.query()==before&&visible(w,"group.parent"),"cancel restores inspector and unchanged project");
    click(w,"track.delete.preview");click(w,"track.mute:"+juce::String(source));auto human=w.query();click(w,"plan.accept");check(w.query()==human&&visible(w,"plan.accept"),"human edit invalidates pending delete without overwriting it");click(w,"plan.reject");click(w,"history.undo");click(w,"track.select:"+juce::String(aux));click(w,"track.delete.preview");click(w,"plan.accept");check(w.query()["tracks"].size()==1&&find(w,source)["output"]["target"]=="none"&&find(w,source)["sends"].empty(),"accept deletes real Aux and disconnects external edges");check(!visible(w,"track.select:"+juce::String(aux)),"deleted strip disappears from Mix");click(w,"history.undo");check(w.query()["tracks"]==before["tracks"]&&find(w,source)["sends"][0]["id"]==send,"single GUI Undo restores exact facts and send identity");click(w,"history.redo");check(w.query()["tracks"].size()==1,"GUI Redo reapplies deletion");click(w,"history.undo");click(w,"view.edit");check(visible(w,"track.select:"+juce::String(aux)),"Edit also restores same track after Undo");
    combo(w,"track.type").setSelectedId(5,juce::dontSendNotification);click(w,"track.create");std::string folder=w.query()["tracks"].back()["id"];choose(w,"group.candidate",juce::String(auxName));click(w,"group.add");choose(w,"group.candidate","Vocal");click(w,"group.add");before=w.query();click(w,"track.delete.preview");preview=dynamic_cast<juce::TextEditor*>(visible(w,"legacy.report"));check(preview&&preview->getText().contains("Vocal")&&preview->getText().contains(juce::String(auxName)),"group preview explicitly names descendant tracks");click(w,"plan.accept");check(w.query()["tracks"].empty(),"Folder delete removes actual complete subtree");click(w,"history.undo");check(w.query()["tracks"]==before["tracks"],"Folder Undo restores media clips hierarchy and internal route");
    w.setSize(1120,700);click(w,"track.select:"+juce::String(folder));click(w,"track.delete.preview");check(visible(w,"plan.accept")&&visible(w,"plan.reject")&&visible(w,"legacy.report"),"delete preview stays operable at smaller window size");click(w,"plan.reject");check(Commands::mediaHash(pcm)==hash,"GUI lifecycle never changes source media bytes");
    Json result={{"result","passed"},{"checks",checks},{"scope","production JUCE controls and native Edit; devices closed, no hardware/model claim"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<result.dump(2)<<"\n";dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
