#include "Workspace.h"
#include <fstream>
#include <iostream>
using namespace ndaw::v2;using namespace ndaw::desktop;
namespace {
int checks=0;
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
void pump(int ms=30){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
juce::Component* find(juce::Component& parent,const juce::String& id){if(!parent.isVisible())return nullptr;if(parent.getComponentID()==id)return &parent;for(auto* child:parent.getChildren())if(auto* result=find(*child,id))return result;return nullptr;}
void click(Workspace& w,const juce::String& id){auto* button=dynamic_cast<juce::Button*>(find(w,id));if(!button||!button->isEnabled())throw std::runtime_error("native button unavailable: "+id.toStdString());auto callback=button->onClick;bool delivered=false;button->onClick=[&]{delivered=true;callback();};button->triggerClick();const auto until=juce::Time::getMillisecondCounterHiRes()+1000;while(!delivered&&juce::Time::getMillisecondCounterHiRes()<until)pump(1);button->onClick=callback;check(delivered,"actual native asynchronous callback delivered");pump();}
juce::TextEditor& field(Workspace& w,const char* id){auto* editor=dynamic_cast<juce::TextEditor*>(find(w,id));if(!editor)throw std::runtime_error(std::string("native field unavailable: ")+id);return *editor;}
juce::ComboBox& combo(Workspace& w,const char* id){auto* choice=dynamic_cast<juce::ComboBox*>(find(w,id));if(!choice)throw std::runtime_error(std::string("native chooser unavailable: ")+id);return *choice;}
void value(Workspace& w,const char* id,const char* text){auto& editor=field(w,id);static_cast<juce::Component*>(&editor)->focusGained(juce::Component::focusChangedDirectly);editor.setText(text,true);}
Json wait(Workspace& w){const auto until=juce::Time::getMillisecondCounterHiRes()+12000;while(w.queryAnalysis().value("busy",false)){if(juce::Time::getMillisecondCounterHiRes()>until)throw std::runtime_error("native track analysis exceeds twelve seconds");pump(10);}pump(300);auto state=w.queryAnalysis();if(state["state"]!="completed")throw std::runtime_error(state.dump());return state["receipt"];}
class Storage final:public te::PropertyStorage{public:explicit Storage(juce::File dir):PropertyStorage("Forma tap GUI"),dir(dir){}juce::File getAppPrefsFolder()override{dir.createDirectory();return dir;}private:juce::File dir;};
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-tap-ui-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();const auto source=folder.getChildFile("actual-tap.wav");juce::AudioBuffer<float> data(2,144000);for(int n=0;n<144000;++n)for(int ch=0;ch<2;++ch)data.setSample(ch,n,float(.8*std::sin(2*juce::MathConstants<double>::pi*10*n/48000)));
    {juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> output=source.createOutputStream();auto writer=wav.createWriterFor(output,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));if(!writer||!writer->writeFromAudioSampleBuffer(data,0,144000))throw std::runtime_error("native fixture PCM write failed");}const auto hash=Commands::mediaHash(source);
    Workspace w(false,std::make_unique<Storage>(folder.getChildFile("prefs")));w.setVisible(true);w.prepareImport(source);pump();click(w,"plan.accept");const auto track=w.query()["tracks"][0]["id"].get<std::string>(),clip=w.query()["tracks"][0]["clips"][0]["id"].get<std::string>();click(w,"clip.select:"+juce::String(clip));value(w,"clip.gain.db","6");click(w,"clip.gain");click(w,"plugin.insert");check(w.query()["tracks"][0]["plugins"].size()==1,"GUI inserts an actual EQ through L1");const auto before=w.query();
    w.showAnalysis();pump();combo(w,"analysis.tap").setSelectedId(3,juce::sendNotificationSync);pump();check(combo(w,"analysis.track").getNumItems()==1&&find(w,"analysis.track.run")&&!find(w,"analysis.delivery.run")&&!find(w,"source.silence_dbfs"),"native track chooser exposes actual target and boundary without incompatible source/delivery controls");
    field(w,"analysis.start_samples").setText("24013");field(w,"analysis.end_samples").setText("120013");click(w,"analysis.track.run");auto pre=wait(w);check(pre["binding"]["tap_point"]=="track_pre_inserts"&&pre["binding"]["object_id"]==track&&pre["peak"].get<double>()>1.59&&pre["events"].size()>0,"native pre-insert action obtains actual Clip Gain PCM and clipping-risk positions");check(field(w,"analysis.summary").getText().contains("track_pre_inserts")&&field(w,"analysis.summary").getText().contains("未包含")&&!field(w,"analysis.summary").getText().contains("Tap: Master"),"summary labels actual selected chain and fader exclusion without relabelling Master");
    check(w.query()["revision"]==before["revision"]&&w.query()["tracks"]==before["tracks"],"analysis leaves active engine facts and Undo unchanged");click(w,"analysis.locate:0");check(w.query()["position_samples"]==pre["events"][0]["start_samples"]&&!find(w,"analysis.panel"),"measured track event button locates native Transport and returns to Edit");
    w.showAnalysis();combo(w,"analysis.tap").setSelectedId(4,juce::sendNotificationSync);field(w,"analysis.start_samples").setText("24013");field(w,"analysis.end_samples").setText("120013");click(w,"analysis.track.run");auto post=wait(w);check(post["binding"]["tap_point"]=="track_post_inserts"&&std::abs(post["peak"].get<double>()-pre["peak"].get<double>())<3e-6,"native post-insert action uses actual flat EQ before target fader");
    combo(w,"analysis.tap").setSelectedId(5,juce::sendNotificationSync);field(w,"analysis.start_samples").setText("24013");field(w,"analysis.end_samples").setText("120013");click(w,"analysis.track.run");auto bus=wait(w);const auto gain=juce::Decibels::decibelsToGain(before["tracks"][0]["gain_db"].get<float>());check(bus["binding"]["tap_point"]=="bus"&&std::abs(bus["peak"].get<double>()-post["peak"].get<double>()*gain)<3e-6,"native Bus output includes actual import fader at its real value");check(field(w,"analysis.summary").getText().contains("已包含")&&combo(w,"analysis.tap").getSelectedId()==5,"GUI shows fader inclusion for Bus evidence");click(w,"analysis.close");
    auto* fader=dynamic_cast<juce::Slider*>(find(w,"track.gain:"+juce::String(track)));check(fader,"native fader available for interleaved human editing");fader->setValue(6,juce::sendNotificationSync);pump();w.showAnalysis();pump(300);check(!w.queryAnalysis()["receipt"]["current"].get<bool>()&&field(w,"analysis.summary").getText().contains("历史快照"),"human GUI gain invalidates previous processed tap evidence");click(w,"analysis.close");click(w,"history.undo");check(std::abs(w.query()["tracks"][0]["gain_db"].get<double>()-before["tracks"][0]["gain_db"].get<double>())<1e-5,"Undo restores human fader instead of deleting the analysis task");
    w.showAnalysis();click(w,"analysis.track.run");click(w,"analysis.cancel");const auto until=juce::Time::getMillisecondCounterHiRes()+12000;while(w.queryAnalysis().value("busy",false)&&juce::Time::getMillisecondCounterHiRes()<until)pump(10);check(w.queryAnalysis()["state"]=="cancelled","native track cancel waits for actual terminal cancelled receipt");combo(w,"analysis.tap").setSelectedId(1,juce::sendNotificationSync);pump();check(find(w,"analysis.master.run")&&find(w,"analysis.delivery.run")&&!find(w,"analysis.track"),"existing Master and delivery UI restored on tap switch");check(Commands::mediaHash(source)==hash,"GUI tap work preserves original media");const double elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<60000,"native tap workflow stays within fixed sixty-second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"pre",pre},{"post",post},{"bus",bus},{"scope","actual native JUCE callbacks and Tracktion; live desktop separate"}};if(argc>1){std::ofstream output(argv[1]);output<<report.dump(2);if(!output)throw std::runtime_error("report write failed");}std::cout<<report.dump(2)<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<std::endl;folder.deleteRecursively();return 1;}}
