#include <nativedaw/v2/AudioAnalysis.h>
#include <nativedaw/v2/McpSession.h>
#include <fstream>
#include <iostream>
#include <thread>
using namespace ndaw::v2;
namespace {
int checks=0;Json evidence=Json::array();
void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<std::endl;}
template<class F>void fails(F f,const char* why){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,why);}
void pump(int ms=10){juce::MessageManager::getInstance()->runDispatchLoopUntil(ms);}
Json op(const char* command,Json args){return {{"command",command},{"args",args}};}
void commit(Commands& c,Json ops){c.commit(c.makePlan("human",ops));}
Json request(Commands& c,const std::string& track,const char* tap,const std::string& key){return {{"session_token",c.sessionToken()},{"base_revision",c.querySummary()["revision"]},{"track",track},{"tap_point",tap},{"start_samples",24013},{"end_samples",120013},{"request_key",key}};}
Json wait(Commands& c){const auto until=juce::Time::getMillisecondCounterHiRes()+12000;while(true){auto status=c.analysisStatus();if(!status["busy"].get<bool>())return status;if(juce::Time::getMillisecondCounterHiRes()>until)throw std::runtime_error("track tap exceeds fixed 12 second budget");pump();}}
Json measure(Commands& c,const std::string& track,const char* tap,const std::string& key){c.analysisControl("track",request(c,track,tap,key));auto result=wait(c);if(result["state"]!="completed")throw std::runtime_error(result.dump());auto receipt=result["receipt"];if(!receipt["current"].get<bool>())std::cerr<<"STALE "<<key<<" "<<receipt.dump()<<" ACTIVE "<<c.query().dump()<<std::endl;check(receipt["current"].get<bool>()&&receipt["frames"]==96000&&receipt["file_float"].get<bool>()&&receipt["file_bits"]==32,"actual tap returns current float32 PCM of exact nonzero session range");check(receipt["binding"]["tap_point"]==tap&&receipt["binding"]["object_id"]==track&&!receipt["binding"]["tap_configuration"]["master_included"].get<bool>(),"artifact binds actual track and plugin boundary excluding Master");evidence.push_back(receipt);return receipt;}
void near(double actual,double expected,const char* why){if(std::abs(actual-expected)>3e-6)throw std::runtime_error(std::string(why)+" actual="+std::to_string(actual)+" expected="+std::to_string(expected));check(true,why);}
Json rpc(McpSession& session,const char* method,Json params){static int id=0;const int key=++id;std::vector<Json> output;std::thread worker([&]{output=session.receive(Json{{"jsonrpc","2.0"},{"id",key},{"method",method},{"params",params}}.dump());});worker.join();const auto until=juce::Time::getMillisecondCounterHiRes()+5000;while(output.empty()){if(juce::Time::getMillisecondCounterHiRes()>until)throw std::runtime_error("MCP reply exceeds five seconds");pump();output=session.ready();}for(const auto& item:output)if(item.value("id",Json(nullptr))==key)return item;throw std::runtime_error("MCP response ID mismatch");}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;const auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("forma-track-analysis-"+juce::Uuid().toString());folder.createDirectory();try{
    const auto began=juce::Time::getMillisecondCounterHiRes();auto source=folder.getChildFile("actual-1k.wav");juce::AudioBuffer<float> pcm(2,144000);for(int n=0;n<144000;++n)for(int ch=0;ch<2;++ch)pcm.setSample(ch,n,float(.2*std::sin(2*juce::MathConstants<double>::pi*1000*n/48000)));
    {juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=source.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(32));check(writer&&writer->writeFromAudioSampleBuffer(pcm,0,144000),"write real three-second stereo known PCM");}
    const auto sourceHash=Commands::mediaHash(source);Commands c(false);commit(c,Json::array({op("track.create",{{"name","Vocal"},{"ref","$v"}}),op("clip.import",{{"track","$v"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}}),op("track.gain",{{"track","$v"},{"db",-6}}),op("track.create",{{"name","Unrelated loud direct output"},{"ref","$other"}}),op("clip.import",{{"track","$other"},{"path",source.getFullPathName().toStdString()},{"position_samples",0}}),op("track.gain",{{"track","$other"},{"db",6}}),op("track.create",{{"name","Vocal Bus"},{"type","aux"},{"ref","$aux"}}),op("track.gain",{{"track","$aux"},{"db",0}}),op("send.create",{{"track","$v"},{"target","$aux"},{"db",-6},{"position","post"}})}));
    auto facts=c.query();const std::string vocal=facts["tracks"][0]["id"],other=facts["tracks"][1]["id"],aux=facts["tracks"][2]["id"],clip=facts["tracks"][0]["clips"][0]["id"];commit(c,Json::array({op("clip.gain",{{"clip",clip},{"db",6}}),op("plugin.insert",{{"track",vocal},{"type",te::EqualiserPlugin::xmlTypeName}})}));facts=c.query();const std::string eq=facts["tracks"][0]["plugins"][0]["id"];
    commit(c,Json::array({op("plugin.parameter",{{"plugin",eq},{"parameter","Mid freq 1"},{"value",1000}}),op("plugin.parameter",{{"plugin",eq},{"parameter","Mid gain 1"},{"value",6}})}));const auto before=c.query();
    auto pre=measure(c,vocal,"track_pre_inserts","pre");double expectedPeak=0,sum=0;const float clipGain=juce::Decibels::decibelsToGain(6.f);for(int n=24013;n<120013;++n){const double value=pcm.getSample(0,n)*clipGain;expectedPeak=std::max(expectedPeak,std::abs(value));sum+=value*value;}near(pre["peak"],expectedPeak,"pre-insert tap includes real Clip Gain and excludes target EQ/fader and unrelated tracks");near(pre["rms"],std::sqrt(sum/96000),"pre-insert RMS matches independent source PCM gain prediction");
    auto post=measure(c,vocal,"track_post_inserts","post");check(post["peak"].get<double>()>pre["peak"].get<double>()*1.8,"post-insert tap actually contains EQ processing");auto bus=measure(c,vocal,"bus","vocal-output");const float fader=juce::Decibels::decibelsToGain(-6.f);near(bus["peak"],post["peak"].get<double>()*fader,"Bus output includes actual target fader exactly once");near(bus["rms"],post["rms"].get<double>()*fader,"Bus RMS includes actual target fader and no other device output");auto returned=measure(c,aux,"bus","aux-output");near(returned["peak"],bus["peak"].get<double>()*fader,"Aux tap preserves upstream post send at its actual level");near(returned["rms"],bus["rms"].get<double>()*fader,"Aux tap excludes original source direct output");
    check(c.query()["tracks"]==before["tracks"]&&c.query()["revision"]==before["revision"]&&c.query()["position_samples"]==before["position_samples"],"tap snapshots do not edit active routing, plugin states, history or cursor");
    commit(c,Json::array({op("plugin.bypass",{{"plugin",eq},{"bypassed",true}})}));check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"human processing change invalidates measured track evidence");auto bypass=measure(c,vocal,"track_post_inserts","bypass");near(bypass["peak"],pre["peak"],"post-insert tap honors actual plugin bypass");near(bypass["rms"],pre["rms"],"bypassed EQ has matching pre/post PCM RMS");c.undo();check(!c.analysisStatus()["receipt"]["current"].get<bool>(),"Undo creates a new revision and cannot revive old processed evidence");
    commit(c,Json::array({op("track.output",{{"track",vocal},{"target",aux}})}));auto direct=measure(c,aux,"bus","direct-plus-send");near(direct["peak"],bus["peak"].get<double>()*(1+fader),"Aux tap sums direct upstream route and post send without severing the route");near(direct["rms"],bus["rms"].get<double>()*(1+fader),"routed and sent parallel PCM stays aligned");
    commit(c,Json::array({op("track.solo",{{"track",vocal},{"enabled",true}})}));auto solo=measure(c,aux,"bus","solo");near(solo["peak"],direct["peak"],"temporary capture is solo safe while original solo graph remains effective");c.undo();
    const auto sendID=c.query()["tracks"][0]["sends"][0]["id"].get<std::string>();commit(c,Json::array({op("send.position",{{"send",sendID},{"position","pre"}})}));auto preSend=measure(c,aux,"bus","pre-send");near(preSend["peak"],bus["peak"].get<double>()+post["peak"].get<double>()*fader,"Aux tap preserves actual pre-fader send placement");c.undo();
    commit(c,Json::array({op("automation.point.add",{{"track",vocal},{"parameter","volume"},{"ref","$first"},{"position_samples",0},{"value",-12},{"curve",0}}),op("automation.point.add",{{"track",vocal},{"parameter","volume"},{"ref","$last"},{"position_samples",143999},{"value",-12},{"curve",0}}),op("automation.mode",{{"track",vocal},{"mode","read"}})}));auto automated=measure(c,vocal,"bus","read-curve");near(automated["peak"],post["peak"].get<double>()*juce::Decibels::decibelsToGain(-12.f),"Bus tap reads actual volume automation in native offline graph");auto beforeFader=measure(c,vocal,"track_post_inserts","before-read-fader");near(beforeFader["peak"],post["peak"],"post-insert tap excludes fader automation instead of reading its base value");c.undo();pump(200);near(c.query()["tracks"][0]["gain_db"],-6,"delayed curve Undo restores original explicit fader base instead of last sampled Read value");
    commit(c,Json::array({op("track.mute",{{"track",vocal},{"enabled",true}})}));auto muted=measure(c,vocal,"bus","muted");check(muted["peak"].get<double>()==0&&muted["lufs_i"].is_null(),"native tap preserves actual muted-track semantics without inventing loudness");c.undo();
    commit(c,Json::array({op("track.create",{{"name","Actual FourOsc notes"},{"type","instrument"},{"ref","$synth"}}),op("midi.clip.create",{{"track","$synth"},{"ref","$notes"},{"name","Editable MIDI"},{"position_samples",0},{"length_samples",144000}}),op("midi.note.add",{{"clip","$notes"},{"pitch",69},{"velocity",90},{"position_samples",0},{"length_samples",120000}})}));const auto synth=c.query()["tracks"][3]["id"].get<std::string>();auto generated=measure(c,synth,"track_pre_inserts","instrument-input");check(generated["peak"].get<double>()>1e-3&&generated["binding"]["tap_configuration"]["plugin_boundary_index"].get<int>()>=1,"instrument pre-insert tap preserves actual synth audio rather than reporting pre-synth silence");
    auto args=request(c,aux,"bus","retry");auto pending=c.analysisControl("track",args,"agent:tap");check(c.analysisControl("track",args,"agent:tap")["request"]["artifact_id"]==pending["request"]["artifact_id"],"identical track analysis retries share the actual job");auto different=args;different["tap_point"]="track_pre_inserts";fails([&]{c.analysisControl("track",different,"agent:tap");},"same request key cannot change its tap boundary");c.analysisControl("cancel",{{"artifact_id",pending["request"]["artifact_id"]}},"agent:tap");check(wait(c)["state"]=="cancelled","actual track tap cancellation releases its snapshot");
    CommandQueue queue(c);Scope read;read.mode=Permission::ReadOnly;auto client=queue.connect("agent:tap",read);McpSession session(client,Commands::registry());rpc(session,"initialize",{{"protocolVersion","2025-11-25"},{"capabilities",Json::object()},{"clientInfo",{{"name","track-tap-tests"},{"version","1"}}}});session.receive(Json{{"jsonrpc","2.0"},{"method","notifications/initialized"}}.dump());auto response=rpc(session,"tools/call",{{"name","analyze_track"},{"arguments",request(c,vocal,"track_pre_inserts","mcp-pre")}});check(!response["result"]["isError"].get<bool>(),"registry-generated MCP allows read-only real track evidence");wait(c);auto external=rpc(session,"tools/call",{{"name","query_analysis"},{"arguments",Json::object()}})["result"]["structuredContent"]["result"]["receipt"];near(external["peak"],pre["peak"],"real MCP returns independently predicted pre-insert PCM");
    auto invalid=request(c,"missing","bus","invalid");fails([&]{c.analysisControl("track",invalid);},"nonexistent track cannot report successful analysis");invalid=request(c,vocal,"made_up","invalid");fails([&]{c.analysisControl("track",invalid);},"unregistered tap point is rejected");invalid=request(c,vocal,"bus","invalid");invalid["path"]="/tmp/attacker.wav";fails([&]{c.analysisControl("track",invalid);},"tap command cannot accept arbitrary output paths");
    const auto saved=folder.getChildFile("tap.tracktionedit");c.save(saved);c.open(saved);check(c.analysisStatus()["state"]=="idle"&&c.query()["tracks"].size()==4,"saved metadata does not preserve helper tracks or revive a current analysis");check(Commands::mediaHash(source)==sourceHash,"all tap analyses preserve original source hash");const auto elapsed=juce::Time::getMillisecondCounterHiRes()-began;check(elapsed<120000,"track tap qualification stays within fixed 120 second budget");Json report={{"result","passed"},{"checks",checks},{"elapsed_ms",elapsed},{"evidence",evidence},{"scope","actual Tracktion render and MCP, self-owned PCM; physical desktop and realtime qualification separate"}};if(argc>1){std::ofstream out(argv[1]);out<<report.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<report.dump(2)<<std::endl;folder.deleteRecursively();return 0;
}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<std::endl;folder.deleteRecursively();return 1;}}
