#include <nativedaw/v2/EngineCommands.h>
#include <fstream>
#include <iostream>
using namespace ndaw::v2;
namespace {
int checks=0;void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);++checks;std::cout<<"PASS "<<why<<"\n";}
template<class F>void fails(F f,const char* why){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,why);}
Json op(const char* c,Json a){return {{"command",c},{"args",a}};}
Json find(Commands& c,const std::string& id){auto q=c.query();for(const auto& t:q["tracks"])if(t["id"]==id)return t;throw std::runtime_error("track missing");}
void settle(){juce::MessageManager::getInstance()->runDispatchLoopUntil(100);}
void signal(const juce::File& f,int channel,float amp,double frequency=1000){juce::WavAudioFormat wav;std::unique_ptr<juce::OutputStream> stream=f.createOutputStream();auto writer=wav.createWriterFor(stream,juce::AudioFormatWriterOptions{}.withSampleRate(48000).withNumChannels(2).withBitsPerSample(24));if(!writer)throw std::runtime_error("PCM writer unavailable");juce::AudioBuffer<float> data(2,96000);data.clear();for(int i=0;i<96000;++i)data.setSample(channel,i,amp*std::sin(2*juce::MathConstants<double>::pi*frequency*i/48000));if(!writer->writeFromAudioSampleBuffer(data,0,96000))throw std::runtime_error("PCM write failed");}
std::array<double,2> rms(const juce::File& f){juce::AudioFormatManager fm;fm.registerBasicFormats();std::unique_ptr<juce::AudioFormatReader> r(fm.createReaderFor(f));if(!r||r->lengthInSamples!=96000||r->numChannels!=2)throw std::runtime_error("render format mismatch");juce::AudioBuffer<float> data(2,48000);if(!r->read(&data,0,48000,2048,true,true))throw std::runtime_error("PCM read failed");return {data.getRMSLevel(0,0,48000),data.getRMSLevel(1,0,48000)};}
}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI gui;try{
    auto dir=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("ndaw-tracks-"+juce::Uuid().toString());dir.createDirectory();auto left=dir.getChildFile("left.wav"),right=dir.getChildFile("right.wav"),pilot=dir.getChildFile("reference.wav");signal(left,0,.1f);signal(right,1,.2f);signal(pilot,0,.025f,250);auto hashL=Commands::mediaHash(left),hashR=Commands::mediaHash(right);
    Commands c(false);auto run=[&](Json ops){auto p=c.makePlan("human",std::move(ops));auto receipt=c.commit(p);settle();return p;};
    run(Json::array({op("track.create",{{"name","Direct"},{"ref","$direct"}}),op("clip.import",{{"track","$direct"},{"path",left.getFullPathName().toStdString()},{"position_samples",0}}),op("track.gain",{{"track","$direct"},{"db",-6}}),op("track.create",{{"name","Sender"},{"ref","$sender"}}),op("clip.import",{{"track","$sender"},{"path",right.getFullPathName().toStdString()},{"position_samples",0}}),op("track.output",{{"track","$sender"},{"target","none"}}),op("track.create",{{"name","Return"},{"ref","$aux"},{"type","aux"}}),op("track.gain",{{"track","$aux"},{"db",-6}}),op("track.output",{{"track","$direct"},{"target","$aux"}}),op("send.create",{{"track","$sender"},{"target","$aux"},{"db",0},{"position","pre"}}),op("track.create",{{"name","Group"},{"ref","$folder"},{"type","folder"}}),op("track.create",{{"name","VCA"},{"ref","$vca"},{"type","vca"}}),op("track.parent",{{"track","$vca"},{"parent","$folder"}}),op("track.parent",{{"track","$aux"},{"parent","$vca"}}),op("track.create",{{"name","Reference"},{"ref","$reference"}}),op("clip.import",{{"track","$reference"},{"path",pilot.getFullPathName().toStdString()},{"position_samples",0}})}));
    std::string direct,sender,aux,folder,vca;auto q=c.query();for(const auto& t:q["tracks"]){if(t["name"]=="Direct")direct=t["id"];if(t["name"]=="Sender")sender=t["id"];if(t["name"]=="Return")aux=t["id"];if(t["name"]=="Group")folder=t["id"];if(t["name"]=="VCA")vca=t["id"];}
    run(Json::array({op("plugin.insert",{{"track",aux},{"type","delay"}})}));auto plugin=find(c,aux)["plugins"][0]["id"];run(Json::array({op("plugin.bypass",{{"plugin",plugin},{"bypassed",true}}),op("automation.point.add",{{"track",direct},{"parameter","volume"},{"position_samples",0},{"value",-6},{"curve",0},{"ref","$p0"}}),op("automation.point.add",{{"track",direct},{"parameter","volume"},{"position_samples",96000},{"value",-6},{"curve",0},{"ref","$p1"}})}));
    int serial=0;Json renders=Json::array();double six=std::pow(10.,-6./20.);auto measure=[&](const char* label,double l,double r){auto file=dir.getChildFile("out-"+juce::String(++serial)+".wav");settle();auto receipt=c.render(file,0,96000);auto actual=rms(file);check(std::abs(actual[0]-l)<3e-6&&std::abs(actual[1]-r)<3e-6,label);renders.push_back({{"case",label},{"rms",actual},{"receipt",receipt}});};
    const double expectedLeft=std::hypot(.1/std::sqrt(2.)*six*six,.025/std::sqrt(2.)),referenceLeft=.025/std::sqrt(2.);
    measure("baseline actual routes sends automation and plugin bypass",expectedLeft,.2/std::sqrt(2.)*six);auto original=c.query()["tracks"],lane=c.automationQuery(direct);
    auto order=run(Json::array({op("track.order",{{"track",folder},{"index",0}}),op("track.colour",{{"track",aux},{"colour","#a761c2"}})}));check(c.query()["tracks"][0]["id"]==folder&&c.query()["tracks"][1]["id"]==vca&&c.query()["tracks"][2]["id"]==aux,"ordering moves entire nested subtree before root siblings");check(find(c,aux)["parent"]==vca&&find(c,aux)["order_index"]==0&&find(c,aux)["colour"]=="#A761C2","colour is canonical native fact; sibling order keeps parent");measure("ordering colouring preserve actual PCM",expectedLeft,.2/std::sqrt(2.)*six);
    juce::MessageManager::getInstance()->runDispatchLoopUntil(400);c.undo(order["plan_id"]);settle();check(c.query()["tracks"]==original,"single delayed Undo restores order colour clips plugins sends and routes");c.redo();settle();check(c.query()["tracks"][0]["id"]==folder&&find(c,aux)["colour"]=="#A761C2","Redo restores order and native colour");
    run(Json::array({op("track.colour",{{"track",aux},{"colour","default"}})}));check(find(c,aux)["colour"].is_null(),"default clears custom colour");c.undo();settle();
    auto before=c.query();fails([&]{c.makePlan("human",Json::array({op("track.delete",{{"track",aux},{"connections","reject"}})}));},"default deletion rejects incoming direct output and send");check(c.query()==before,"rejected delete is read-only");
    auto deletion=c.makePlan("agent:track-qualification",Json::array({op("track.delete",{{"track",aux},{"connections","disconnect"}})}));auto preview=c.preview(deletion);auto effect=preview["track_changes"][0];check(effect["deleted_tracks"].size()==1&&effect["disconnected_outputs"].size()==1&&effect["removed_incoming_sends"].size()==1&&!effect["media_files_deleted"].get<bool>(),"delete preview enumerates exact track output send impact and preserves media");check(effect["deleted_tracks"][0]["original_facts"]["plugins"][0]["id"]==plugin&&c.query()==before,"preview includes actual plugin snapshot without modifying Edit");fails([&]{c.commit(deletion);},"Agent deletion needs explicit preview acceptance");c.commit(deletion,true);settle();check(c.query()["tracks"].size()==5&&find(c,direct)["output"]["target"]=="none"&&find(c,sender)["sends"].empty(),"accepted delete disconnects to None and removes actual send");check(find(c,direct)["clips"]==before["tracks"][3]["clips"]&&c.automationQuery(direct)["lanes"]==lane["lanes"]&&c.automationQuery(direct)["mode"]==lane["mode"],"delete retains surviving media references and automation");measure("deleted return leaves only reference PCM without Master fallback",referenceLeft,0);
    c.undo(deletion["plan_id"]);settle();if(c.query()["tracks"]!=before["tracks"])std::cout<<"UNDO DIFF "<<Json::diff(before["tracks"],c.query()["tracks"]).dump(2)<<"\n";check(c.query()["tracks"]==before["tracks"],"delete Undo restores exact hierarchy colour plugin send IDs and routes");measure("delete Undo restores actual PCM through Aux",expectedLeft,.2/std::sqrt(2.)*six);c.redo();settle();measure("delete Redo restores reference-only PCM",referenceLeft,0);check(c.commit(deletion)["replayed"]&&c.commit(deletion)["state"]=="committed","deletion retries are idempotent");c.undo();settle();check(c.commit(deletion)["state"]=="undone","retry does not repeat an undone deletion");
    auto saved=dir.getChildFile("restored.tracktionedit");c.save(saved);{Commands reopened(false);reopened.open(saved);check(reopened.query()["tracks"]==c.query()["tracks"],"reopen preserves order colour plugins restored send and stable IDs");auto f=dir.getChildFile("reopen.wav");reopened.render(f,0,96000);auto actual=rms(f);check(std::abs(actual[0]-expectedLeft)<3e-6&&std::abs(actual[1]-.2/std::sqrt(2.)*six)<3e-6,"reopened restored route audio agrees numerically");}
    auto group=c.makePlan("human",Json::array({op("track.delete",{{"track",folder},{"connections","disconnect"}})}));check(c.preview(group)["track_changes"][0]["deleted_tracks"].size()==3,"Folder deletion preview enumerates nested VCA and Aux");c.commit(group);settle();check(c.query()["tracks"].size()==3&&find(c,direct)["output"]["target"]=="none","group delete removes whole subtree and external connections");c.undo();settle();check(c.query()["tracks"]==before["tracks"],"subtree deletion Undo restores all descendants and connections");
    auto good=c.query();auto reject=[&](Json bad,const char* why){fails([&]{c.makePlan("human",bad);},why);check(c.query()==good,"failed Plan leaves original state intact");};
    reject(Json::array({op("track.order",{{"track",aux},{"index",1}})}),"order cannot escape sibling group");reject(Json::array({op("track.order",{{"track",direct},{"index",-1}})}),"negative index rejected");reject(Json::array({op("track.colour",{{"track",direct},{"colour","#ff001122"}})}),"transparent or malformed colour rejected");reject(Json::array({op("track.delete",{{"track","master"},{"connections","disconnect"}})}),"global Master cannot be deleted");reject(Json::array({op("track.delete",{{"track",folder},{"connections","disconnect"}}),op("plugin.bypass",{{"plugin",plugin},{"bypassed",false}})}),"deleted descendant plugin cannot be used later in Plan");auto clip=find(c,direct)["clips"][0]["id"];
    reject(Json::array({op("track.delete",{{"track",direct},{"connections","disconnect"}}),op("clip.gain",{{"clip",clip},{"db",-3}})}),"deleted clip cannot be edited later in Plan");auto sid=find(c,sender)["sends"][0]["id"];reject(Json::array({op("track.delete",{{"track",aux},{"connections","disconnect"}}),op("send.level",{{"send",sid},{"db",-9}})}),"removed incoming send cannot be edited later in Plan");reject(Json::array({op("track.delete",{{"track",aux},{"connections","disconnect"}}),op("track.output",{{"track",direct},{"target",aux}})}),"deleted output destination rejected in full Plan");
    auto stale=c.makePlan("agent:old",Json::array({op("track.delete",{{"track",aux},{"connections","disconnect"}})}));run(Json::array({op("track.rename",{{"track",sender},{"name","Human rename"}})}));fails([&]{c.commit(stale,true);},"human edit invalidates deletion preview");
    run(Json::array({op("track.output",{{"track",direct},{"target","none"}}),op("send.remove",{{"send",sid}}),op("track.delete",{{"track",aux},{"connections","reject"}}),op("track.create",{{"ref","$new"},{"type","aux"},{"name","New return"}}),op("track.output",{{"track",direct},{"target","$new"}})}));check(find(c,direct)["output"]["target"]!="none"&&c.query()["tracks"].size()==6,"atomic Plan can disconnect delete create and reroute without stale targets");c.undo();settle();check(find(c,aux)["id"]==aux&&find(c,sender)["sends"][0]["id"]==sid,"compound replacement Undo restores original objects");
    check(Commands::mediaHash(left)==hashL&&Commands::mediaHash(right)==hashR,"all track edits preserve original media bytes");
    Json result={{"result","passed"},{"checks",checks},{"renders",renders},{"scope","real native Edit and renderer; 3e-6 RMS tolerance; test PCM, no microphone or AI model claim"}};if(argc>1){std::ofstream out(argv[1]);out<<result.dump(2);if(!out)throw std::runtime_error("report write failed");}std::cout<<result.dump(2)<<"\n";dir.deleteRecursively();return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
