#pragma once
// Included inside ndaw::desktop. No mutable device manager or Edit escapes L1.
class AudioDevicePanel final : public juce::Component {
public:
    using Inventory=std::function<Json(bool)>;using Capabilities=std::function<Json(const Json&)>;using Apply=std::function<void(Json)>;
    AudioDevicePanel(Inventory inventory,Capabilities capabilities,Apply apply,std::function<void()> close):inventory(std::move(inventory)),capabilities(std::move(capabilities)),apply(std::move(apply)),close(std::move(close)){
        setComponentID("audio.settings.panel");setWantsKeyboardFocus(true);
        for(auto* c:std::initializer_list<juce::Component*>{&title,&backend,&actual,&outputLabel,&output,&inputLabel,&input,&rateLabel,&rate,&bufferLabel,&buffer,&inputView,&outputView,&inputChannelsLabel,&outputChannelsLabel,&detail,&result,&refreshButton,&applyButton,&closeButton})addAndMakeVisible(c);
        title.setText(text("音频设备设置"),juce::dontSendNotification);title.setFont(juce::FontOptions(22,juce::Font::bold));outputLabel.setText(text("输出设备"),juce::dontSendNotification);inputLabel.setText(text("输入设备"),juce::dontSendNotification);rateLabel.setText(text("设备采样率"),juce::dontSendNotification);bufferLabel.setText(text("缓冲大小"),juce::dontSendNotification);inputChannelsLabel.setText(text("启用输入通道"),juce::dontSendNotification);outputChannelsLabel.setText(text("启用输出通道"),juce::dontSendNotification);
        output.setComponentID("audio.settings.output");input.setComponentID("audio.settings.input");rate.setComponentID("audio.settings.rate");buffer.setComponentID("audio.settings.buffer");applyButton.setComponentID("audio.settings.apply");refreshButton.setComponentID("audio.settings.refresh");closeButton.setComponentID("audio.settings.close");result.setComponentID("audio.settings.result");actual.setComponentID("audio.settings.actual");
        inputView.setViewedComponent(&inputRows,false);outputView.setViewedComponent(&outputRows,false);inputView.setScrollBarsShown(true,false);outputView.setScrollBarsShown(true,false);
        output.onChange=[this]{rebuildCapabilities(false);};input.onChange=[this]{rebuildCapabilities(false);};rate.onChange=[this]{updateBudget();};buffer.onChange=[this]{updateBudget();};
        refreshButton.onClick=[this]{reload(true);};closeButton.onClick=[this]{this->close();};applyButton.onClick=[this]{if(!runtimeEnabled)return;try{this->apply(request());}catch(const std::exception& e){showError(e.what());}};
    }
    void setBusy(bool pending){busy=pending;updateRuntime(facts);}
    void reload(bool rescan=false){busy=false;try{facts=inventory(rescan);baseline=facts["setup_hash"];runtimeEnabled=facts["can_apply"];output.clear(juce::dontSendNotification);input.clear(juce::dontSendNotification);outputs.clear();inputs={""};input.addItem(text("关闭音频输入"),1);
        const auto type=facts["actual"]["type"].get<std::string>();backend.setText(text("音频系统 · ")+text(type),juce::dontSendNotification);
        for(const auto& t:facts["types"])if(t["type"]==type){for(const auto& name:t["outputs"]){outputs.push_back(name);output.addItem(text(name.get<std::string>()),int(outputs.size()));}for(const auto& name:t["inputs"]){inputs.push_back(name);input.addItem(text(name.get<std::string>()),int(inputs.size()));}}
        auto choose=[](juce::ComboBox& combo,const std::vector<std::string>& names,const Json& selected){auto it=std::find(names.begin(),names.end(),selected.get<std::string>());combo.setSelectedId(it==names.end()?(names.empty()?0:1):int(it-names.begin())+1,juce::dontSendNotification);};choose(output,outputs,facts["actual"]["output"]);choose(input,inputs,facts["actual"]["input"]);
        rebuildCapabilities(true);result.setText(text("选择设备与通道后应用。设备设置独立于工程 Undo。"),juce::dontSendNotification);updateRuntime(facts);
    }catch(const std::exception& e){showError(e.what());applyButton.setEnabled(false);}}
    void updateRuntime(const Json& state){runtimeEnabled=state["can_apply"];facts["can_apply"]=runtimeEnabled;facts["input_permission"]=state["input_permission"];
        const auto& s=state["actual"];actual.setText(s["open"].get<bool>()?text("当前实际：")+text(s["output"].get<std::string>())+" · "+juce::String(s["sample_rate"].get<double>()/1000.,1)+" kHz / "+juce::String(s["buffer_frames"].get<int>())+text(" 帧"):text("当前没有打开的音频设备"),juce::dontSendNotification);
        if(!state["last_configuration"].is_null()){const auto receipt=state["last_configuration"];const auto tag=receipt.value("id",std::string{})+receipt.value("state",std::string{});if(tag!=lastReceipt&&state["last_configuration"]["state"]!="applying"){lastReceipt=tag;showReceipt(receipt);}}
        bool ready=runtimeEnabled&&!busy&&!caps.is_null()&&!rates.empty()&&!buffers.empty()&&selectedChannels(outputButtons).size()>0;
        for(auto* c:std::initializer_list<juce::Component*>{&output,&input,&rate,&buffer,&refreshButton,&inputView,&outputView})c->setEnabled(runtimeEnabled&&!busy);applyButton.setEnabled(ready);updateBudget();
    }
    void showReceipt(const Json& receipt){lastReceipt=receipt.value("id",std::string{})+receipt.value("state",std::string{});if(receipt["state"]=="preparing"){result.setText(text("实际设备正在准备 · 等待稳定音频回调回执"),juce::dontSendNotification);return;}if(receipt["state"]=="verified"){reload(false);result.setText(text(receipt.value("unchanged",false)?"已核验 · 设备设置未变":"已核验 · 实际设备、采样率、缓冲与通道一致"),juce::dontSendNotification);}else{std::string msg="应用失败："+receipt.value("error",std::string{});if(!receipt["rollback"].is_null())msg+=receipt["rollback"]["state"]=="restored"?"\n原设备设置已恢复":"\n恢复失败："+receipt["rollback"].value("error",std::string{});showError(msg);}}
    void showError(const std::string& error){result.setText(text("未完成 · ")+text(error),juce::dontSendNotification);}
    void paint(juce::Graphics& g)override{g.fillAll(juce::Colours::black.withAlpha(.8f));g.setColour(base());g.fillRoundedRectangle(card.toFloat(),8);g.setColour(juce::Colour(0xff45505e));g.drawRoundedRectangle(card.toFloat(),8,1);}
    void resized()override{card=juce::Rectangle<int>(std::min(820,getWidth()-24),std::min(660,getHeight()-24)).withCentre(getLocalBounds().getCentre());auto x=card.getX()+24,y=card.getY()+20,w=card.getWidth()-48,half=(w-20)/2;
        title.setBounds(x,y,w-180,32);closeButton.setBounds(x+w-80,y,80,29);refreshButton.setBounds(x+w-174,y,84,29);backend.setBounds(x,y+43,w,22);actual.setBounds(x,y+72,w,40);
        outputLabel.setBounds(x,y+123,half,22);inputLabel.setBounds(x+half+20,y+123,half,22);output.setBounds(x,y+151,half,30);input.setBounds(x+half+20,y+151,half,30);rateLabel.setBounds(x,y+200,half,22);bufferLabel.setBounds(x+half+20,y+200,half,22);rate.setBounds(x,y+229,half,30);buffer.setBounds(x+half+20,y+229,half,30);
        outputChannelsLabel.setBounds(x,y+281,half,22);inputChannelsLabel.setBounds(x+half+20,y+281,half,22);outputView.setBounds(x,y+311,half,108);inputView.setBounds(x+half+20,y+311,half,108);layoutRows(outputRows,outputButtons,half-16);layoutRows(inputRows,inputButtons,half-16);
        detail.setBounds(x,y+439,w,52);result.setBounds(x,y+498,w,64);applyButton.setBounds(x+w-190,card.getBottom()-54,190,30);
    }
private:
    static Json selectedChannels(const juce::OwnedArray<juce::ToggleButton>& buttons){Json result=Json::array();for(int n=0;n<buttons.size();++n)if(buttons[n]->getToggleState())result.push_back(n);return result;}
    static void layoutRows(juce::Component& rows,juce::OwnedArray<juce::ToggleButton>& buttons,int width){rows.setSize(width,std::max(108,buttons.size()*26));for(int n=0;n<buttons.size();++n)buttons[n]->setBounds(0,n*26,width,25);}
    Json selection()const{int a=output.getSelectedId()-1,b=input.getSelectedId()-1;if(a<0||a>=int(outputs.size())||b<0||b>=int(inputs.size()))throw std::runtime_error("select available audio devices");return {{"type",facts["actual"]["type"]},{"output",outputs[a]},{"input",inputs[b]}};}
    Json request()const{auto args=selection();int r=rate.getSelectedId()-1,b=buffer.getSelectedId()-1;if(r<0||r>=int(rates.size())||b<0||b>=int(buffers.size()))throw std::runtime_error("select an available device format");args.update({{"sample_rate",rates[r]},{"buffer_frames",buffers[b]},{"input_channels",selectedChannels(inputButtons)},{"output_channels",selectedChannels(outputButtons)},{"base_setup_hash",baseline}});return args;}
    void rebuildCapabilities(bool initial){try{
        caps=capabilities(selection());rates.clear();buffers.clear();rate.clear(juce::dontSendNotification);buffer.clear(juce::dontSendNotification);for(const auto& v:caps["sample_rates"]){rates.push_back(v);rate.addItem(juce::String(v.get<double>()/1000.,v.get<double>()==44100?1:0)+" kHz",int(rates.size()));}for(const auto& v:caps["buffer_sizes"]){buffers.push_back(v);buffer.addItem(juce::String(v.get<int>())+text(" 帧"),int(buffers.size()));}
        auto choose=[](juce::ComboBox& combo,const std::vector<Json>& values,const Json& actual){auto it=std::find(values.begin(),values.end(),actual);combo.setSelectedId(it==values.end()?(values.empty()?0:1):int(it-values.begin())+1,juce::dontSendNotification);};choose(rate,rates,facts["actual"]["sample_rate"]);choose(buffer,buffers,facts["actual"]["buffer_frames"]);
        auto rows=[this,initial](juce::Component& holder,juce::OwnedArray<juce::ToggleButton>& buttons,const char* side,const char* names){buttons.clear();const bool same=initial&&caps["selection"][side]==facts["actual"][side];int n=0;for(const auto& name:caps[names]){if(n>=caps["max_native_channels"].get<int>())break;auto* b=buttons.add(new juce::ToggleButton(juce::String(n+1)+" · "+text(name.get<std::string>())));b->setComponentID(text(std::string("audio.settings.")+side+".channel:"+std::to_string(n)));const auto& active=facts["actual"][std::string(side)+"_channels"];b->setToggleState(same?std::find(active.begin(),active.end(),Json(n))!=active.end():std::string(side)=="output"?n<2:true,juce::dontSendNotification);b->onClick=[this]{updateRuntime(facts);};holder.addAndMakeVisible(b);++n;}};
        rows(outputRows,outputButtons,"output","output_channel_names");rows(inputRows,inputButtons,"input","input_channel_names");resized();updateRuntime(facts);
    }catch(const std::exception& e){caps=nullptr;rates.clear();buffers.clear();rate.clear(juce::dontSendNotification);buffer.clear(juce::dontSendNotification);inputButtons.clear();outputButtons.clear();applyButton.setEnabled(false);showError(e.what());}}
    void updateBudget(){int r=rate.getSelectedId()-1,b=buffer.getSelectedId()-1;if(r<0||r>=int(rates.size())||b<0||b>=int(buffers.size())){detail.setText(text("设备能力不可用 · 请刷新"),juce::dontSendNotification);return;}auto period=1000.*buffers[b].get<int>()/rates[r].get<double>();detail.setText(text("单缓冲时长 ")+juce::String(period,2)+text(" ms；这不是实际往返延迟。\n关闭输入监听后配置；工程时间轴仍为 48 kHz。"),juce::dontSendNotification);}
    std::string lastReceipt;Inventory inventory;Capabilities capabilities;Apply apply;std::function<void()> close;Json facts,caps=nullptr,baseline;bool runtimeEnabled=false,busy=false;std::vector<std::string> outputs,inputs;std::vector<Json> rates,buffers;
    juce::Rectangle<int> card;juce::Label title,backend,actual,outputLabel,inputLabel,rateLabel,bufferLabel,inputChannelsLabel,outputChannelsLabel,detail,result;juce::ComboBox output,input,rate,buffer;juce::Component inputRows,outputRows;juce::OwnedArray<juce::ToggleButton> inputButtons,outputButtons;juce::Viewport inputView,outputView;juce::TextButton refreshButton{text("刷新")},applyButton{text("应用设备设置")},closeButton{text("关闭")};
};
