#!/usr/bin/env python3
"""Single source for the retained, evidence-linked product gap matrix."""
from pathlib import Path
import json
root=Path(__file__).resolve().parent.parent
# Status describes the whole row. Passing a subset test does not promote a full workflow.
rows=[]
def add(category,ident,feature,reference,implementation,module,acceptance,tests='',gap='',dependencies='无',status='未实现'):
 rows.append(dict(category=category,id=ident,feature=feature,reference_behavior=reference,implementation=implementation,module=module,acceptance=acceptance,test_evidence=tests or '未执行',gap=gap or '完整实现及验收仍需完成',external_dependencies=dependencies,status=status))
def pending(i,f,m,a,ref='用户最低规格；S1/S3 相应章节需继续精读',dep='无',cat=1):
 add(cat,i,f,ref,'尚无生产实现','规划：'+m,a,dependencies=dep)
def part(i,f,impl,m,a,t,g,ref='用户最低规格；S1/S3',dep='无',cat=1,status='部分实现'):
 add(cat,i,f,ref,impl,m,a,t,g,dep,status)
part('ENG-01','macOS 设备/I/O/缓冲查询与录放','直接 CoreAudio IOProc；UID/暴露通道序号与 HAL element 分离；格式/缓冲枚举；stream usage 设置并读回；GUI/CLI 共用设备配置','src/MacNativeDevice.cpp；src/CoreAudioBlock.cpp；src/Audio.cpp；include/nativedaw/NativeAudioConfig.h','枚举真实能力→选择设备及 buffer→实际多 I/O 录放，保存设备/故障/关闭回执','evidence/native-devices.json；native-controls-summary.json；native-audit-controls-summary.json；native-device-cycles.json；native-physical-input.json；native-audit-physical-input.json；HAL-01–04','真实输出/重开及单内置麦克风→两逻辑轨/私有 aggregate/清理通过；多物理输入、漂移/校准、热插拔、GUI和Windows待验收')
pending('ENG-02','Windows ASIO/WASAPI','Audio/platform','Windows x64 实机构建，双后端接口/格式/缓冲/故障/延迟验证',dep='Windows 主机、接口及 ASIO 发布许可')
part('ENG-03','44.1–192 kHz 与 mono/stereo/multichannel','六种采样率文件/离线 mono/stereo 路径','src/Session.cpp；src/Audio.cpp','各率实际文件、实际设备及所有布局录放，逐样本核对','RATE-01；AUDIO-03','多声道、异采样率导入/SRC、设备 176.4/192k 未验证',ref='S1 bit depth/sample rate；S3 PDF p319')
part('ENG-04','32-bit 处理、float64 混音精度','float64 增益/声像/淡化累加，float32 输出','src/Audio.cpp','已知信号/抵消/极端动态/多轨容差；插件精度另测','AUDIO-01/02/03','全 DSP/插件 double 路径和听感未验证；不能称音质对齐',ref='S1；S3 PDF p319 区分文件位深')
part('ENG-05','磁盘流式播放/预读/缓存','4,096-frame 源 PCM 页；pin/LRU/16-slot 请求；distinct offset 缓存与 1 GiB 配置预算','src/Realtime.cpp；src/Audio.cpp','长媒体、多盘/密集剪辑/缓存未命中、磁盘中断压力；录音不得全 RAM 缓存','RT-01/05/06；MEDIA-01','多源偏移/页生命周期/partial 页/预算/删除及非有限 PCM 已测；长时/冷热盘/大工程和吞吐恢复待测')
part('ENG-06','采样调度与 RT 安全图发布/回收','直接 IOProc/预分配 maps/scratch；transport epoch/revision；源页/float64 DSP/原子图发布/非 RT 回收/5 ms 平滑；设备操作 NRT','src/CoreAudioBlock.cpp；src/MacNativeDevice.cpp；src/Realtime.cpp；src/Audio.cpp；src/Recording.cpp','捕获应用设备回调的分配/释放/锁/文件/设备控制；播放及录音中改图零缺口','RT-01–08；HAL-01–04；RT-AUDIT-01；native-audit-controls-summary.json；native-audit-physical-input.json；native-audit-negative-control.json；历史 realtime-wrapper-audit.json','macOS绕过历史JUCE锁；真实输出/单麦克风与已列 C API 插桩通过，非所有 syscall/驱动内部证明；RTSan本机不支持；Windows/多输入/复杂拓扑/听感/耐久未完成')
part('ENG-07','插件/Bus/sidechain/hardware PDC','实际 stereo DAG/最长路径补偿；真实 lookahead 限制器延迟；实时/离线共用DSP、离线 preroll/drain','src/Routing.cpp；src/Realtime.cpp；src/Audio.cpp','不同延迟并行/级联/null-test；旁链/硬件实际相位对齐及延迟变更安全','PDC-01–04；DSP-01；BENCH-04；routing-release-tests.json','当前只覆盖已实现的内置限制器/stereo图；插件、旁链、硬件插入、低延迟旁路/位置校准和无缝延迟变更仍未完成',ref='S3 印刷 p1475–1480 / PDF p1577–1582；routing-reference-manual.json')
part('ENG-08','低延迟监听与常规混音切换','同一实时 DSP 的 off/input/auto；录音 dry tap 与监听 fader/pan/mute 分离；Auto armed 录音抑制 clip 回放','src/Realtime.cpp；src/Commands.cpp；src/Main.cpp','实际 input→output RTT；安全路径及补偿/旁路；录音/回放/停止切换逐样本及听感','MON-01；BENCH-03；evidence/capture-tests-and-benchmark-final.json','数值和生产回调测试信号通过；物理 RTT、完整插件监听/PDC、平滑模式切换与听感待实现/实测')
part('ENG-09','设备/磁盘/过载故障与监测','deadline/XRUN/队列/缺口；HAL layout/clock/属性故障原子通知→NRT停止；checksummed partial manifest/fail-stop；注销先等待 owner quiescence，超时 fault5；不确定注销保留已脱离 owner 的回调内存','src/CoreAudioBlock.cpp；src/MacNativeDevice.cpp；src/Audio.cpp；src/Recording.cpp','拔设备/变率/磁盘满/队列/回调超时；真实 UI 失败状态及可靠恢复','HAL-02/05；REC-03–08；SAVE-02；MEDIA-01；native-device-cycles.json；native-audit-device-cycles.json','已测 OS write fault、已知 layout/clock/input/队列故障及真实输出重开；物理满盘/热插拔/变率/GUI/驱动及 owner timeout 的有界恢复/磁盘无期限阻塞恢复/partial salvage 待做')
pending('ENG-10','实时渲染/有时限并行和 IPC','Audio/Graph；PluginWorker','先定预算，再测 IPC deadline/过载/超时策略；不得等待插件无限响应')
part('SES-01','Audio/MIDI/Instrument/Aux/Master/folders/VCA/分组','Audio、stereo Aux 与 main Master 实际路由/处理节点；稳定 Bus/Send ID','src/Session.cpp；src/Commands.cpp；src/Routing.cpp','各类型创建/播放/录制/路由/保存；不设商业轨数限制','CMD-01；ROUTE-01–03；MIGRATE-02','MIDI/Instrument/folders/VCA/groups、多宽度/任意路径 Master 尚缺',ref='S1 轨道容量；S3 印刷 p1425–1427')
pending('SES-02','轨道/I-O 预设、模板','Session/Presets','存取音频/MIDI/插件/路由/配置，迁移回归')
pending('SES-03','Freeze/Commit 与路由重建','Audio/Render；Session/Freeze','真实音频冻结、解冻、提交，验证插件/路由/尾音/状态',ref='S1 Freeze/Commit')
pending('SES-04','导入工程数据与跨工程媒体管理','Session/Import/Media','合并对象/媒体/冲突/丢失引用及 relink 验证')
part('REC-01','真实输入流式捕获与时间戳','暴露输入通道选择/arm→固定 roster→共享 callback counter→每轨 progressive float32 BWF→非零真实输入/文件验证；记录 input UID/格式及 acquisition 时间','src/Recording.cpp；src/Audio.cpp；src/MacNativeDevice.cpp；src/Main.cpp；scripts/verify_physical_capture.py','真实麦克风多轨 ≥5 s；实时文件增长→stop→导入→重开→回放→导出；接口延迟另测','REC-02；HAL-03/04；BENCH-03；evidence/native-physical-input.json；native-audit-physical-input.json；gui-blocker.json','两逻辑轨共享一个真实内置麦克风、私有 aggregate/清理及增长/非零 PCM/重开/回放/导出通过；多物理输入/监听 RTT/位置校准/独立 GUI 权限流程待测')
part('REC-02','多轨录音/arm/monitor/pre-post roll','arm/input/monitor domain commands；捕获 lease 固定输入；原生 HAL acquisition timestamp/独立 output timestamp；一次可撤销附件事务和幂等恢复','src/Commands.cpp；src/Recording.cpp；src/Realtime.cpp；src/CoreAudioBlock.cpp；src/Main.cpp','真实多输入同步录制、预/后录、时间戳/缺口/持续写入；GUI 和 AI命令一致','REC-01/02/04/06/08；MON-01；HAL-03/04；RT-AUDIT-01；native-physical-input.json；native-audit-physical-input.json','4-track 映射、65-track附件及 HAL→生产 engine/monitor/BWF test-only PCM 已过；单麦克风两逻辑轨真实录音过；pre/post roll未实现；多物理输入/aggregate 漂移/GUI/物理延迟未验证')
pending('REC-03','Loop/Punch/连续捕获模式','Recording/Punch','明确模式及整个前后捕获范围；只替换选区且原始媒体保留')
pending('REC-04','Take/Playlist/Comp/录音安全','Session/Playlist；Recording/Comp','多次录音保留 Take；候选 Comp 可试听/接受/撤销并恢复原 Playlist')
part('EDIT-01','采样/秒时间线与基本非破坏性剪辑','move/trim/split/delete/clip gain/linear fades/lock','src/Commands.cpp；src/Main.cpp','真实文件导入→GUI 剪辑→Undo→保存→重开→导出；AI Actor 同操作比较','CMD-02；AUDIO-04；MEDIA-01','复制粘贴/滑移/微移/批量/吸附/交叉淡化/曲线/合并整理均缺失')
pending('EDIT-02','音乐/时间码/多帧率/Tempo-Meter/范围/记忆位置','Session/TimeMaps；UI/Rulers','不同单位转换及起始偏移可逆，速度/拍号变更与视频帧定位一致')
pending('EDIT-03','瞬态/节拍/相位关联编辑','Analysis/Transients；Edit/Groups','多麦克风真实材料，相位一致且可逆地整理节奏')
pending('EDIT-04','Clip FX、stretch/pitch 实时/高质量离线','DSP/ClipFX；Media/Derivation','原媒体哈希不变；派生 hash/算法参数/时间映射及数值/听感验证')
part('MIX-01','Gain/polarity/pan tools 与 pan law','增益及 mono constant-power、stereo balance','src/Audio.cpp；src/Main.cpp','已知 mono/stereo 信号端点/中点/抵消与控制值保存','AUDIO-01/02/03；RT-08','可选 pan law/极性 UI/声道工具/听感检查尚缺失')
part('MIX-02','insert/send/pre-post/Aux/bus/sidechain/multi-out','真实 output/send、独立 send pan、pre/post tap、Aux/Master 与内置处理器链；循环/锁/安全删除校验','src/Routing.cpp；src/Commands.cpp；include/nativedaw/NativeRoutingEditor.h','原输出保持；循环拒绝；实际tap/PCM/PDC/保存撤销；完整侧链/多输出','ROUTE-01–03；PDC-01–04；GUI-ROUTE-01；routing-controls-summary.json','stereo/main master 子集；send pan link/更多宽度、第三方插入/sidechain/multiout和实际鼠标工作流未完成',ref='S3 印刷 p1432/1443/1445；routing-reference-manual.json')
pending('MIX-03','硬件插入/VCA/solo safe/AFL-PFL/监控/分组','Audio/Monitoring；Routing','真实接口回环及复杂 Solo/组联动，验证安全监听及延迟',dep='多 I/O 音频接口')
part('DSP-01','参数 EQ/压缩/限幅/gate/expander','实际 linked discrete-sample lookahead limiter（真实FIFO/最大树/包络，float64）','src/Routing.cpp；tests/RoutingTests.h','每种DSP数值/频响/包络/失真/非有限值与听感','DSP-01；PDC-01/02/04；routing-release-tests.json','仅 limiter 数值通过；听感/true peak/mastering未验收；EQ/压缩/gate/expander仍未实现')
pending('DSP-02','De-esser/delay/reverb/saturation','DSP/Builtins','频率/时域/反馈/尾音/增益匹配/听感检查')
pending('AUTO-01','采样级内部 automation/全部目标','Session/Automation；Audio/Scheduler','volume/pan/mute/send/plugin/spatial 实际音频变化位置及单位转换')
pending('AUTO-02','Read/Touch/Latch/Write/Trim/Preview/Capture/写选区','Automation/Modes；UI','每模式触摸、回归、预览捕获和区间写入；对照 S3 具体行为')
pending('AUTO-03','automation follows edits/复制/曲线/削点','Edit/Automation','移/切/贴/拉伸后曲线与音频时间一致')
pending('MIDI-01','MIDI I/O/录放/回溯','MIDI/Devices/Scheduler','真实 MIDI 输入与多输出乐器，录制/回放时间容差',dep='实体 MIDI 设备和合法乐器')
pending('MIDI-02','piano roll/notation/notes/velocity/CC/bend/aftertouch/program','UI/MIDI；Session/MIDI','可编辑音符/控制事件全部保存/重开/导出')
pending('MIDI-03','quantize/groove/humanize/transpose/MIDI FX/sync','MIDI/Effects；TempoMap','可逆 MIDI 变换、tempo sync 和定量随机性回归')
pending('MIDI-04','Audio-to-MIDI 与乐谱互操作','Analysis/Pitch；MIDI/ImportExport；Notation','真实单音/多音材料转成可编辑 MIDI，区分估计/事实；乐谱交换报告音符/CC/tempo 损失',ref='S1 Audio-to-MIDI（依赖 ARA plugin）/Sibelius interop；S2 2024.3 剪贴板互操作',dep='实际转录模型/插件、公开交换格式或合法互操作规格')
pending('MUSIC-01','片段触发/Sketch 类音乐草稿到时间线','Session/ClipLauncher；MIDI；UI','音频和 MIDI 草稿可同步触发并转为可编辑时间线；明确保留原处理链与来源',ref='S1 Sketch Window；S2 2023.12 Sketch→timeline 的 MIDI/音频选择',cat=1)
pending('SYNC-01','Ableton Link 类音乐时钟同步','Transport/ExternalClock','与实际独立 peer 同步 tempo/start/stop，验证漂移、退出与会话保存',ref='S1 Ableton Link support',dep='Link 组件许可证及合法同步 peer')
pending('IO-01','Aux I/O 类应用/外部音频桥接','Audio/ExternalIO；Routing','真实跨应用音频输入输出、漂移/延迟补偿/设备断开/授权与反馈风险验证',ref='S1 Ultimate Aux I/O inputs/outputs unlimited；具体行为需继续精读 S3',dep='实际 OS 音频桥接后端及设备')
pending('POST-01','视频导入/窗口/帧导航/同步/时码/偏移/4K','Video/Worker；UI/Video','真实含校准闪帧视频与音频点击对齐，独立解码线程')
pending('POST-02','ADR cue/场录 metadata/Reconform','Post/ADR/FieldRecorder/Reconform','真实场录+剪辑表，多剪辑/automation 位置与错误信息验证')
pending('POST-03','surround/object data/routing/panner/automation','Session/Spatial；Audio/Spatial','多声道已知信号、对象位置及 automation 保存和实际交付')
pending('POST-04','Ambisonics 高阶制作与交付','Session/Ambisonics；Audio/Spatial','最高七阶布局、通道顺序/归一化/旋转/解码/自动化以已知空间信号及实际文件核对',ref='S1 Ultimate up to seventh-order Ambisonics；仅音乐/影视声音制作范围',dep='验证用解码器与多声道监听环境')
pending('EXPORT-02','ADM 及 single-file multistem 交付','Interop/ADM；Render/Multistem','实际对象/床/元数据 ADM 往返；单文件多 stem 命名/布局/尾音/校验与信息损失报告',ref='S1 ADM Export / Single file multi-stem bounce',dep='ADM 格式组件及对应渲染器条件')
pending('CODEC-01','AAC 编解码与压缩交付','Media/Codecs；Render','实际文件编码解码/声道/时长/标签/取消/发布许可证核验',ref='S1 AAC encode decode support',dep='所选平台编码器/解码器及发布条件')
part('EXPORT-01','Offline/range WAV/BWF export + validation','实际双声道 float32 新文件渲染及 reopen/PCM 峰值/RMS','src/Audio.cpp；src/CLI.cpp','源范围与格式/声道/帧数/哈希/实际样本一致；冲突与取消不提交','EXPORT-01；真实媒体回执','实时 Bounce、Stems、多版本/尾音/SRC/抖动/AIFF-FLAC 编码未实现')
part('METER-01','Peak/RMS/削波测量','source tap 逐样本峰值/RMS/削波区间及 hash','src/Session.cpp','已知削波区间移动/切分后定位准确；区分 RMS/LUFS/true peak','ANALYSIS-01；EXPORT-01','LUFS-I/S/M、true peak、phase、spectrum、尾音截断仍缺失')
pending('UI-01','controller/custom keys/workspaces/multidisplay','UI/Preferences/Controllers','物理控制器、快捷键编辑、布局重启/多屏恢复',dep='实际控制器、多显示器')
part('MODEL-01','稳定 ID 和版本化对象/时间映射','schema 3 Session/Audio/Aux/Master/Source/Clip/Bus/Send/builtin processor/Marker/Analysis/Transaction；捕获与呈现位置分离','src/Session.cpp；src/Commands.cpp；src/Routing.cpp；src/Recording.cpp','source/clip/sample/beat/frame 坐标和旧工程/历史迁移；媒体保持','CMD-01；ANALYSIS-01；MIGRATE-01/02；PDC-03；REC-02','schema1/2→3与小工程已测；Take/Playlist/Region/third-party Plugin/Parameter/Automation/Tempo/Video和完整迁移仍缺')
part('MODEL-02','facts/measurements/AI inference/preferences 分离','facts 查询与 provenance 标记的测量；模型建议是 Plan','src/AI.cpp；src/Session.cpp','处理链/媒体变更后失效缓存，分析模型参数版本及区间可追溯','AI-02；ANALYSIS-01','处理链 tap/缓存、持久化偏好/清理/推断层未完成')
part('STORE-01','原子保存/校验/日志/快照/崩溃恢复','envelope/save/backup/journal；v1/v2 snapshot/history→v3；partial capture manifest','src/Session.cpp；src/Commands.cpp；src/Recording.cpp；src/CLI.cpp','异常退出恢复有效 journal；backup；Undo/Redo及旧 schema；录音异常 salvage','SAVE-01/02/03；MIGRATE-01/02；REC-08；ROUTE-01','自动保存/UI、journal压缩、长期工程迁移和中断录音partial salvage仍未完成')
pending('STORE-02','媒体 relink/缺失插件引用原状态','Session/Media；PluginState','缺失内容完整保留，hash/路径匹配/插件原始 state 重连；不静默删除')
part('CMD-01','统一 GUI/CLI/AI command 验证/事务','同一 registry、dry run/diff/version/schema/risk/approval/commit/history','src/Commands.cpp；src/Main.cpp；src/CLI.cpp','同一编辑经 GUI/CLI/AI Actor 结果与撤销一致；实际模型另验收','CMD-01/02/03/04；AI-01/02','正式所有产品操作命令、controller/scripts/event/live CLI-MCP 尚不齐')
part('CMD-02','并发/幂等/可逆性/恢复/停止','版本冲突、canonical Plan retry、持久化 capture retry、lease、选择性 Undo、文件无覆盖及进程 ownership','src/Commands.cpp；src/Recording.cpp；src/AI.cpp','交错/过期/重试/锁/取消/进程竞争/副作用分类；重试不反转已做Undo','CMD-03/04；SAVE-03；REC-01/08；AI-01','完整 live network/API恢复、更细粒度冲突恢复及外部副作用事务未完成')
part('AI-01','Provider/capability/budget/cancel/resource yield','实际 Ollama API；运行时 model；有限工具 loop；loopback/不传音频','src/AI.cpp；src/Main.cpp','真实模型 query→plan→preview→commit→Undo；断网制作；播放/录音优先','AI-03；真实模型 E2E 未执行','适配器代码已实现，服务/模型缺失；额外 Provider/云授权/安全凭据未完成',dep='本地模型服务或用户授权的 Provider',status='外部依赖阻塞')
part('AI-02','音频证据/ASR/breath/beat/pitch/key/structure/take检索','仅 source PCM peak/RMS/削波证据','src/Session.cpp','真实音频与人工标签核对；无音频不声称听到，无 ASR 不推断音色','ANALYSIS-01','转写/对齐/呼吸/静音/噪声/BPM/调性/结构/Take 比较未实现')
pending('AI-03','source separation/repair/generation + editable timeline','AI/Adapters；Media/Derivation；MIDI','真实模型输入范围/上下文/输出能力和来源验证；mixed audio 不声称 stems/MIDI',dep='模型/素材合法条件，可能需要授权付费调用')
pending('AI-WF-A','自然语言创建混响 Aux/send 且输出路由不变','AI/Planner；Commands；DSP/Reverb','实际选中轨道→真实可用插件→Aux/send→render→单事务 Undo')
pending('AI-WF-B','工程理解/第二副歌削波/Bus ancestry/无声诊断','AI/Queries；Analysis；Routing','真实对象/区间/测量/路由证据并点击定位')
pending('AI-WF-C','保留呼吸的静音整理/候选 Comp','AI/Editing；Session/Comp','切点/fade/Take 候选试听、局部接受、保留原 Playlist')
pending('AI-WF-D','副歌限定混音/相位检查/响度匹配 AB','AI/Mix；Audio/Compare','锁定及区间保护、真实参数/路由、两版本响度匹配后试听')
pending('AI-WF-E','音乐补写/延展/局部 MIDI-audio 变换/候选','AI/Music；MIDI；Session/Take','实际 MIDI 可编辑与节拍/速度/调性上下文、来源可追溯')
pending('AI-WF-F','真实 QC→主混/伴奏/纯人声/stems','AI/Delivery；Render；Meters','信号/范围/链/尾音→新文件→格式/时长/声道/响度二次校验')
part('AI-UI','global/context/tasks/locate/preview/audition/accept/reject/undo/history','全局 AI 面板/三权限模式/plan 预览/接受拒绝/cancel；Undo 为共同历史','src/Main.cpp','所有 AI 入口/任务终态/版本冲突/定位/试听/分项接受/历史验证','核心权限测试；evidence/gui-blocker.json：GUI 验收未执行','context入口/问题标记/局部接受/AB试听/完整历史 UI 未实现')
pending('AI-SEC','cloud/credential/log/preferences/security consent','AI/Security；OS Keychain/CredentialManager','默认无上传；明确接收方/目的/范围；恶意数据不能权限升级，凭据日志脱敏',dep='云 Provider 与 OS 安全存储实机验证')
part('PERF-01','128/256/512/更大工作负载与 AI 三模式','offline/RT 源页与4/64-route并发录音监听已知信号基准；真实 IOProc 短测；固定预算','tests/CoreTests.cpp；docs/VERIFICATION.md','复杂 clip/automation/long capture/plugins/multichannel/video/AI off-on-stress，原标准逐项实测','native-tests-and-benchmark.json；native-controls-summary.json；native-audit-controls-summary.json；native-physical-input.json','RT DSP/录音测试信号、短时真实输出和单麦克风不是大型设备容量/物理 input RTT；已列 API 审计有边界；其他负载/AI压力/耐久及 Pro Tools 对照缺失')
pending('QA-01','插件/GUI/音频回归/迁移/故障/真实制作/耐久','tests；evidence；CI','完整安装录音制作+真实第三方插件/MIDI/视频；至少预设耐久时长跑完')
part('REL-01','跨平台可复现 installer/update/uninstall/preferences/manual','AGPLv3 原创源码；macOS 固定依赖构建、含源码开发 DMG、ad hoc 及 relocation CLI 检查','CMakeLists.txt；scripts/package_macos.sh','两平台 clean build→安装/配置/卸载/更新/诊断/离线制作→完整验收','evidence/ctest-capture-clean.log；evidence/package.json','GUI安装、updater/preferences/manual、Windows、发布签名/公证和完整许可证审计未完成',dep='Windows、签名/公证/账户、发布许可与实机')
# Specific PT workflows are tracked separately from generic functionality.
pending('PT-01','Slip/Absolute-Relative Grid/Shuffle/Spot','Edit/Modes','按 S3 四种模式的实际移动/trim/delete/paste 规则逐项对照',ref='S3 PDF p959：四类编辑模式及 Relative/Absolute Grid',cat=2)
pending('PT-02','QuickPunch/TrackPunch/DestructivePunch','Recording/Punch','对照每轨待命/continuous capture/punch，破坏模式备份及恢复',ref='S3 PDF p920；S1 Ultimate TrackPunch/DestructivePunch',cat=2)
pending('PT-03','Main/Alternate/Target Playlist、Comp','Session/Playlist；UI/Comp','建/复制/分配/选择/comp 不改原 Take，automation 与编辑 Playlist 区分',ref='S3 PDF p1053 Playlists',cat=2)
pending('PT-04','Trim coalesce/Touch AutoMatch/advanced automation','Automation/Modes','逐项核对 coalesce 时机、touch 回归时间、Preview/Capture/写入选区',ref='S3 PDF p262 Preferences；S1 Advanced automation',cat=2)
pending('PT-05','field-recorder/Beat Detective/Import Session Data','Post/FieldRecorder；Edit/Beat','使用合法基准工程逐字段/逐编辑行为比对；继续精读 S3 相应章节',ref='S1；S3 outline 已定位，详细行为待逐项核验',cat=2)
pending('PT-06','2026 Track Pin/Batch File Rename/STT follow edits','UI/TrackPin；Media/Rename；Analysis/ASR','固定轨可见、批量命名冲突、转写跟随剪辑时间映射',ref='S2 2026.4/2026.4.1 新增能力',cat=2)
pending('PT-07','Disk Cache/Memory Locations/link selections/Smart Tool','UI/Edit；Audio/Cache','合法 PT 实机行为及操作轨迹比对；不能只按名称判断对齐',ref='S1/S3；详细行为尚未全部精读',cat=2)
pending('PT-08','Track Markers/多个 marker ruler 与排序过滤','Session/Markers；UI/Rulers','轨道注释/颜色/独立 ruler；保存恢复并通过记忆位置过滤定位',ref='S2 2023.12 Track Markers；S3 详细行为待精读',cat=2)
pending('PT-09','多视频轨与高级视频剪辑工作流','Video/Timeline；Session/Video','64 视频轨参考负载；帧级剪辑、离线/在线媒体、音画同步和错误报告',ref='S1 Ultimate 64 video tracks / advanced video editing',cat=2)
part('PT-10','Aux/send/master 信号次序和 PDC/录音例外','Audio/Aux pre-fader inserts、Master post-fader inserts且无send/pan/mute；独立send pan和实际PDC','src/Routing.cpp；src/Commands.cpp；include/nativedaw/NativeRoutingEditor.h','官方手册信号顺序逐项核验，再与合法 PT 工程/设备实际比较','ROUTE-02；DSP-01；PDC-01–04；routing-reference-manual.json','仅 stereo main master；任意bus/path master、link-main pan/默认偏好、低延迟录音例外和 PT 实机对照未验证',ref='S3 印刷 p1425–1427/1432/1443/1445/1475–1480',cat=2)
part('PLUG-01','AU(macOS)/VST3(macOS,Windows) 正式宿主','实际 SDK 隔离 discovery/scan；AULowpass stereo float32 文件处理/状态恢复；Serum VST3 实例检查','src/PluginHost.cpp；src/PluginWorker.cpp；src/Plugins.cpp','真实第三方插件的 scan/state/preset/sidechain/multiout/automation/PDC/offline/editor lifecycle','PLUGIN-REAL-01–04；plugins-real-host.json；plugins-sdk-review.json','AU 离线数值/真实音乐和 VST3 检查已测；实时工程 inserts、插件编辑器/MIDI/automation/sidechain/multiout/ARA/听感和 Windows 未完成',ref='NativeDAW 正式格式要求；PT S1 为 AAX 而非 AU/VST3；Steinberg 官方 API 和 pinned JUCE 8.0.12',dep='合法实际插件；Windows；ARA 独立 SDK',cat=3)
part('PLUG-02','隔离扫描/timeout/blacklist/version/rescan','原生 posix_spawn/exit/signal/回收；有界 deadline/cancel/响应/RSS；持久 checksum inventory/blacklist/rescan/旧成功','src/Plugins.cpp；include/nativedaw/NativePluginBrowser.h','挂起/崩溃/错误版本/重复扫描；绝不作为成功','PLUGIN-PROC-01–05；PLUGIN-SCAN-01–03；GUI-PLUGIN-01；plugins-supervisor-*.json','已测独立故障进程/真实 AU/VST3；父进程异常退出 orphan、全 VST3 class ID/升级重定位、注册 AU binary hash、Windows和手工 GUI 未验证；RSS仅轮询采样',cat=3)
part('PLUG-03','插件隔离/崩溃恢复/缺失 state/editor lifecycle','子进程实例销毁/正常退出才接受；失败 rescan 保留旧 state；实际 AU changed state fresh-child 恢复','src/PluginHost.cpp；src/Plugins.cpp','真实插件崩溃/重载/窗口关闭/版本替换、原 state 保留；测 IPC 性能','PLUGIN-PROC-01/04；PLUGIN-SCAN-01/03；PLUGIN-REAL-02/04','无生产插件 realtime IPC 或 Session PluginInstance/missing-plugin Undo；编辑器/preset/所有厂商 state、真实 vendor 崩溃和 IPC 性能未测；测试-only worker 不算真实 vendor',cat=3)
part('PLUG-04','真实参数 ID/range/unit/enum 与 AI 映射','实际 hosted parameter ID/0..1 ranges/labels/display/有限 enums；blank ID不可编辑；offline未知参数/state 拒绝','src/PluginHost.cpp；src/Plugins.cpp；src/CLI.cpp','枚举实际 instance/parameter，语义映射可检查；unsupported/private state 明确拒绝','PLUGIN-REAL-01/02/04；PLUGIN-ADMISSION-01','catalog实例元数据不是工程实例；plain-unit mapping 未推断；Session/AI第三方参数命令、语义适配器和真实模型端到端未完成；opaque不代表可理解私有状态',cat=3)
pending('PLUG-05','ARA host','Plugin/ARA','采用 tagged SDK 实构建，与实际 ARA 插件联动 source/edit/tempo/state/lifecycle',ref='S1 ARA2；Celemony official SDK reviewed',dep='ARA SDK 与合法 ARA 插件',cat=3)
add(3,'COMP-PTX','PTX 原生读写','格式兼容与交换格式分开','未获得可实现的授权规格','规划：Interop/PTX','合法真实 PTX 往返，每字段/插件/时间/媒体损失报告','未执行','未实现；AAF/OMF 不能当 PTX 无损兼容','Avid 原生格式规格/许可及合法基准','外部依赖阻塞')
add(3,'COMP-AAX','AAX hosting','S4 明确是 plugin creation SDK','未取得 AAX host 能力/许可','规划：Plugin/AAX','证明宿主许可和真实 AAX instance/state/processing 流程','未执行','插件开发支持不等于宿主支持','Avid host 许可/API','外部依赖阻塞')
pending('COMP-AAF','AAF/OMF/MXF interchange + loss report','Interop/AAF/OMF/MXF','真实跨 DAW 工程；逐字段/替代映射/损失、源媒体/自动化验证',ref='S1 interchange；不同于 PTX',dep='格式组件许可与合法基准工具',cat=3)
pending('COMP-MC','Media Composer session exchange','Interop/MediaComposer','实际音量/声像 automation、markers 与媒体时间的交换；所有不支持字段报告',ref='S2 2024.6 Ultimate session export for Media Composer',dep='合法格式文档/基准 Media Composer 环境',cat=3)
pending('HW-HUI','HUI 控制表面','Controllers/HUI','实际表面的 transport/fader/pan/touch/反馈/断开、映射和工作区保存',ref='S1 HUI-compatible control surfaces',dep='合法协议/组件与物理 HUI 设备',cat=4)
add(4,'HW-AV','DNx 专用视频接口和其他 Avid 音频接口','S1 DNxIQ/IV/IP/ID、MBOX、HD Native/HD I/O 等兼容列表','未实施厂商特定后端或认证','规划：Audio/Devices；Video/ExternalOutput','取得合法驱动/SDK后，用实际接口核验视频输出、时钟、漂移、恢复；可用 CoreAudio 不等于专用认证','未执行','未实现；不借用 Avid 品牌资产或宣称认证','设备/厂商 SDK/驱动/认证条件','外部依赖阻塞')
for ident,feature,dependency,acceptance in [
 ('HW-HDX','HDX/HD Native/Carbon DSP/monitor paths','专用硬件、驱动、授权 API','CPU 和专用 DSP 路径分别实测；不称硬件等价'),
 ('HW-SYNC','Sync X/MTRX/A-V devices/Satellite proprietary sync','硬件、同步协议许可','时钟、LTC/MTC、跨系统/视频 offset、实际故障验证'),
 ('HW-EUCON','EUCON/Avid surfaces','S6 EUCON SDK 商业访问、实体 surface','合法 SDK 接入并测真实控制映射/自动化/双向反馈'),
 ('IMM-DOLBY','Dolby Atmos/ADM/headphone personalization','合法 renderer/API/认证及多声道设备','beds/objects/automation→实时/离线 renderer→有效 ADM/交付检查'),
 ('IMM-OTHER','MPEG-H/360 Reality Audio/Audio Vivid/ambisonics','各 renderer/SDK/codec 使用许可','分别验证 native spatial 和每种实际 renderer/格式输出')]:
 add(4,ident,feature,'S1/S2 对应专用能力','未获得依赖且无完成实现','规划：Hardware/Spatial/Interop',acceptance,'未执行','持续保留于完整验收差距表',dependency,'外部依赖阻塞')
for ident,feature,dependency,acceptance in [
 ('BUNDLE-01','bundled plugins/instruments/Massive X/Kontakt/RX/Melodyne等','各第三方再分发授权','逐产品合法再分发或明确原生等效功能差距，不拷贝插件资产'),
 ('BUNDLE-02','Sonic Drop/Inner Circle/premium content','素材许可与订阅条件','清晰列示不随 NativeDAW 授权的内容；合法替代资产审核'),
 ('BUNDLE-03','SoundFlow/Bounce Factory/Forte/Splice integrations','服务 API/使用授权/账户','实际工作流/工具回执/费用与上传范围核验，不能用固定宏冒充 AI'),
 ('BUNDLE-04','cloud collaboration/storage/Sketch/Sibelius/Ableton Link','第三方 API/服务许可和账号','分别实现独立制作能力与可选互操作，断网不影响核心制作')]:
 add(5,ident,feature,'S1/S2 bundling/online/interop 独立分类','未集成/未再分发','规划：Integrations/Content',acceptance,'未执行','不将捆绑授权隐藏成实现完成',dependency,'外部依赖阻塞' if ident!='BUNDLE-04' else '未实现')
assert len({r['id'] for r in rows})==len(rows)
# Iteration 7 keeps each full acceptance row and records only the implemented subset.
updates={
 'ENG-10':dict(implementation='生产隔离 SDK stereo effect；256-frame/16-slot pinned shared IPC；1024-frame管线；callback不等待，late/crash/nonfinite终止；离线有界等待',module='src/PluginIPC.cpp；src/PluginHost.cpp；src/Routing.cpp',test_evidence='PLUGIN-IPC-01–04；PLUGIN-REAL-FAILURE-01；plugin-project-device-{release,audit}.json；plugin-session-*-tests.json',gap='首个真实 AU 与短时设备门槛；多插件/其他SDK、真正低延迟监听、长时间/AI压力、父进程异常与NRT存储/关闭有界性未完成',status='部分实现'),
 'MODEL-01':dict(implementation='schema 4 stable Session/Audio/Aux/Master/Source/Clip/Bus/Send/PluginInstance/Parameter/builtin/Marker/Analysis/Transaction；desired参数与actual回执分离',module='src/Session.cpp；src/SessionPlugins.cpp；src/Commands.cpp；src/Routing.cpp',test_evidence='CMD-01；ANALYSIS-01；MIGRATE-01–03；PLUGIN-SESSION-01/02；GUI-PLUGIN-02',gap='schema1/2/3→4与小工程已测；Take/Playlist/Region/Automation/Tempo/Video、全部坐标与长期迁移仍缺'),
 'STORE-01':dict(implementation='原子 envelope/backup/journal；v1/v2/v3 snapshot/history→v4；session-local hash-bound opaque state保留；partial capture manifest',test_evidence='SAVE-01–03；MIGRATE-01–03；PLUGIN-SESSION-01；REC-08',gap='自动保存/UI、journal压缩、长期迁移、所有厂商内部state一致性与中断录音salvage未完成'),
 'STORE-02':dict(implementation='缺失插件或state仍保存原始引用/opaque hash/参数；处理明确失败；remove/Undo恢复引用；源媒体已有missing-reference保留',module='src/SessionPlugins.cpp；src/Session.cpp；src/PluginIPC.cpp；src/Commands.cpp',test_evidence='PLUGIN-MISSING-01；SAVE-02；MEDIA-01',gap='重定位/relink/版本替换适配与缺失插件可试听bypass/重载恢复仍未完成',status='部分实现'),
 'CMD-01':dict(implementation='统一 registry/dry-run/diff/version/risk/acceptance/commit/Undo；新增insert_plugin/set_plugin_parameter与配置catalog查询',test_evidence='CMD-01–04；AI-01/02；PLUGIN-SESSION-01/02；GUI-PLUGIN-02',gap='GUI/AI Actor真实SDK工程结果已测，真实模型未执行；全部产品命令/controller/scripts/event/live SDK-MCP不齐'),
 'PLUG-01':dict(implementation='AU/VST3真实SDK隔离scan；Serum VST3检查；AU工程 stereo float32实时/离线 IPC 与参数/state/PDC；统一GUI命令',module='src/PluginHost.cpp；src/PluginIPC.cpp；src/SessionPlugins.cpp；src/Routing.cpp',test_evidence='PLUGIN-REAL-01–04；PLUGIN-PDC-05/06；GUI-PLUGIN-02；plugin-project-device-{release,audit}.json',gap='只资格测试首个Apple AU；VST3 effect实际音频、更多厂商/非零SDK延迟、Apple AU停机原生editor已局部验证；preset/VST3 editor/sidechain/multioutput/MIDI/automation/ARA/听感/Windows未完成'),
 'PLUG-03':dict(implementation='正常销毁/exit/reap才接受导出；真实AU SDK进程注入kill被判失败；missing PluginInstance/状态hash与Undo保留；live原子失败与静音',module='src/PluginIPC.cpp；src/PluginHost.cpp；src/SessionPlugins.cpp；src/Commands.cpp',test_evidence='PLUGIN-REAL-FAILURE-01；PLUGIN-MISSING-01；PLUGIN-IPC-01–04；PLUGIN-PDC-05；plugin-project-device-{release,audit}.json',gap='外部kill不是自发vendor crash/成功重载；editor/preset/厂商全state、自动失效恢复、parent orphan与关闭/storage-stall仍缺；fixture明确单列'),
 'PLUG-04':dict(implementation='实际SDK IDs/ranges/labels/enums变成稳定Parameter对象；归一化命令/锁/权限/版本/Undo；Provider query_plugin_catalog/query_session；prepare/final SDK值实际核验',module='src/SessionPlugins.cpp；src/Commands.cpp；src/AI.cpp；src/PluginIPC.cpp；include/nativedaw/NativeRoutingEditor.h',test_evidence='PLUGIN-SESSION-02；GUI-PLUGIN-02；PLUGIN-REAL-01/02/04；PLUGIN-ADMISSION-01',gap='真实模型阻塞；语义适配/plain-unit映射、运行期automation和editor状态交易未完成；opaque内部不可理解'),
}
# Iteration 8 qualifies ordinary cancellable admission/retirement, retaining each full row.
updates['ENG-10'].update(implementation='生产隔离SDK stereo effect；256-frame/16-slot pinned IPC；1024-frame管线；callback不等；共享10 s graph admission/cancel；单NRT reclaimer与native exit/reap资源归还',test_evidence='PLUGIN-IPC-01–04；PLUGIN-LIFETIME-01–08；plugin-lifecycle-parallel-{release,audit}.json；plugin-lifecycle-device-{release,audit}.json',gap='同一Apple AU八实例短测通过；其他SDK/长链、低延迟监听、耐久/AI压力、完整app quit、父FS/driver/内存/不确定退出恢复与Windows未完成')
updates['PLUG-01'].update(test_evidence='PLUGIN-REAL-01–04；PLUGIN-PDC-05/06；GUI-PLUGIN-02；PLUGIN-LIFETIME-01–08；plugin-lifecycle-parallel-{release,audit}.json',gap='只资格测试Apple AU（含八并行实例）；VST3 effect音频、更多厂商/非零SDK延迟、Apple AU停机原生editor已局部验证；preset/VST3 editor/sidechain/multioutput/MIDI/automation/ARA/听感/Windows未完成')
updates['PLUG-02']=dict(test_evidence='PLUGIN-PROC-00–05；PLUGIN-SCAN-01–03；GUI-PLUGIN-01；PLUGIN-LIFETIME-04；plugin-lifecycle-owner-exit.json',gap='实际native stopped-child误判已修正并保留失败证据；受控AU父进程终止已测；全厂商/descendants/中断job recovery、VST3 class ID/升级、注册AU binary hash、Windows/手工GUI未完成；RSS仅采样')
updates['PLUG-03'].update(implementation='真实AU IPC失败静音、missing/state/Undo保留；正常销毁/exit/reap才接受；final close失败重试保持失败；cancellable aggregate admission/async last-owner与native保留资源',test_evidence='PLUGIN-REAL-FAILURE-01；PLUGIN-MISSING-01；PLUGIN-IPC-01–04；PLUGIN-LIFETIME-01–08；plugin-lifecycle-parallel-{release,audit}.json；plugin-lifecycle-owner-exit.json',gap='受控kill/stop不是自发vendor crash/成功重载；editor/preset/全部厂商state、自动恢复、完整quit、父FS/kernel stall/未知native退出quarantine与Windows仍缺')
updates['CMD-01'].update(test_evidence='CMD-01–04；AI-01/02；PLUGIN-SESSION-01/02；GUI-PLUGIN-02；plugin-lifecycle-gui-workflow.json',gap='原生鼠标增益/Undo/Redo/保存重开/AU导出与CLI实际文件一致已测；AI Actor不是模型，真实模型未执行；全部产品命令/controller/scripts/event/live SDK-MCP不齐')
updates['AI-UI']=dict(test_evidence='核心权限测试；plugin-lifecycle-gui-workflow.json：原生Plan/query无模型正确失败、Accept禁用、revision不变；旧gui-blocker为历史',gap='真实模型preview/accept/音频验证/Undo待执行；context入口/问题标记/局部接受/AB试听/完整历史UI未实现')
# Iteration 9 keeps complete workflow gaps while qualifying bounded playback controls.
updates['PLUG-04'].update(implementation='实际SDK稳定ID/normalized命令；同一SDK进程的完整SHA256控制快照/finite DSP后readback/返回PCM回执；GUI与AI Actor共用事务/Undo',test_evidence='PLUGIN-PARAM-01–06；PLUGIN-SESSION-02；GUI-PLUGIN-02；plugin-parameters-device-{release,audit}.json；plugin-parameters-gui.json',gap='真实模型阻塞；实际VST3 effect/更多厂商、8192参数成本、sample-accurate automation/平滑、plain-unit/语义适配、editor/preset/state capture交易、录音并发参数/动态延迟仍未验证')
updates['ENG-10'].update(test_evidence='PLUGIN-IPC-01–04；PLUGIN-LIFETIME-01–08；PLUGIN-PARAM-01–06；plugin-parameters-device-{release,audit}.json；plugin-parameters-parallel-{release,audit}.json')
updates['CMD-01'].update(test_evidence='CMD-01–04；AI-01/02；PLUGIN-SESSION-01/02；GUI-PLUGIN-02；PLUGIN-PARAM-02/06；plugin-parameters-gui.json')
updates['PLUG-01'].update(test_evidence='PLUGIN-REAL-01–04；PLUGIN-PDC-05/06；PLUGIN-LIFETIME-01–08；PLUGIN-PARAM-01–06；plugin-parameters-device-{release,audit}.json')
# Iteration 10 adds genuine stopped resident state transactions; full vendor/editor scope stays partial.
updates['PLUG-03'].update(implementation='实际resident SDK停止态capture；AU原生SDK窗口/临时候选/完整opaque与参数restore；保留其他驻留SDK；统一preview/adopt/version/permission/Undo/恢复；missing与失败状态保留',module='PluginState.cpp；PluginIPC.cpp；Commands.cpp；Audio.cpp；NativeRoutingEditor.h；Main.cpp',test_evidence='PLUGIN-EDITOR-01–03；PLUGIN-STATE-01–05；PLUGIN-LIFETIME-01–08；evidence/plugin-editor/；plugin-state-device-{release,audit}.json；原生GUI/包见VERIFICATION',gap='停止态Apple AU原生鼠标/拒绝/提交/Undo及两个真实驻留AU保留已测；该AU不公开SDK programs，实际预设仍待实测；VST3 effect/其他厂商/任意私有状态、播放监听录音编辑、OS stall/Windows/完整故障与压力耐久未完成')
updates['PLUG-04'].update(test_evidence='PLUGIN-PARAM-01–06；PLUGIN-STATE-01–05；plugin-parameters-device-{release,audit}.json；plugin-state-device-{release,audit}.json；原生GUI见VERIFICATION',gap='真实模型阻塞；VST3 effect/更多厂商、8192参数成本、任意sample-accurate automation/平滑、plain-unit/语义适配、editor/preset/录音并发参数/动态延迟未验证；停止态单AU完整opaque交易已测')
updates['CMD-01'].update(test_evidence='CMD-01–04；AI-01/02；PLUGIN-SESSION-01/02；PLUGIN-PARAM-01–06；PLUGIN-STATE-01–05；原生GUI见VERIFICATION')
updates['EDIT-01']=dict(implementation='真实源波形；Select/Grab/Trim/采样选区/秒Grid；move/trim/split/delete/copy/paste/names/clip gain/linear fades/lock；统一单事务Undo',module='include/nativedaw/NativeWorkstation.h；include/nativedaw/EditorGeometry.h；src/Main.cpp；src/Commands.cpp',test_evidence='EDIT-UI-01–04；AUDIO/SAVE/CMD 回归；evidence/ui-refactor/；原生鼠标完整回执见VERIFICATION',gap='音乐/时码/relative grid/Shuffle/Spot/nudge/groups/consolidate/crossfade曲线、Clip FX/stretch/pitch/comp未齐；当前Grid为秒数，波形为源PCM')
updates['ENG-05']=dict(implementation='4096帧原PCM页/pin/LRU/16-slot请求；按同一file/hash/decoded facts合并所有Source ID的offset预算；预读请求保留未来片段；1GiB显式预算',test_evidence='RT-01/05/06/09；MEDIA-01；evidence/ui-refactor/workstation-stream-{release,audit}.json',gap='六源对象同媒体偏移真实设备短测；独立媒体/最大偏移密度/冷热盘/长时/故障恢复与Windows仍待资格测试')
updates['UI-01']=dict(implementation='原生Edit/Mix互补工作区、固定track headers/传输/选区、track/clip列表、inspector、真实推子/峰值、固定快捷键和可收起AI面板',module='src/Main.cpp；include/nativedaw/NativeWorkstation.h',test_evidence='EDIT-UI-01–04；evidence/ui-refactor/原生屏幕与工作流回执',gap='controller、快捷键编辑器、布局持久化/多屏、独立可分离Edit/Mix窗口、完整专业编辑/混音控件与GUI性能仍缺',status='部分实现')
updates['PT-01']=dict(implementation='原生Slip及秒数绝对Grid、Grab/Trim、精确采样起止输入；默认非破坏编辑',module='src/Main.cpp；include/nativedaw/EditorGeometry.h；include/nativedaw/NativeWorkstation.h',test_evidence='EDIT-UI-03/04；原生GUI回执见VERIFICATION',gap='仅秒数Grid；bars/beats、relative Grid、Shuffle、Spot框和完整PT模式行为仍未实现',status='部分实现')
updates['CMD-01'].update(test_evidence='CMD-01–04；AI-01/02；PLUGIN-SESSION/PARAM/STATE；EDIT-UI-01–04；原生GUI见VERIFICATION')
updates['AI-UI'].update(implementation='可收起任务面板、三权限模式、共同版本/plan/接受拒绝/取消/Undo；时间线右键上下文入口',module='src/Main.cpp；include/nativedaw/NativeWorkstation.h',gap='真实模型preview/accept/音频验证/Undo阻塞；问题标记/局部接受/AB试听/完整历史UI仍未实现')
add(2,'PT-11','Edit/Mix窗口、固定传输/编辑工具/选区/轨道/clip-list逻辑','S3 PDF356/358/359/360/367/370，印刷254/256/257/258/265/268；互补Edit/Mix和Start/End/Length选择','原生可切换Edit/Mix工作区与已实现编辑/混音操作；原创视觉','src/Main.cpp；include/nativedaw/NativeWorkstation.h','实际媒体导入/播放→精确选区/拖动修剪/Undo→Mix同轨推子/路由→导出/保存/重开；不使用假音频或装饰按钮','EDIT-UI-01–04；evidence/ui-refactor/，鼠标验证见VERIFICATION','工作区并非所有PT窗口行为：独立可分離窗口、pin/ruler/多选/专业工具模式、布局持久化、多屏、完整混音/自动化还未完成','无','部分实现')
# Iteration 13: canonical Playlists/immutable Takes, explicit range Comp.
updates['REC-04']=dict(implementation='schema5 稳定Take/Playlist；armed目标ID与内容租约；真实写盘附件一次事务注册源区间Take；候选Comp保持inactive直到select',module='src/Playlists.cpp；src/Session.cpp；src/Commands.cpp；src/Audio.cpp；include/nativedaw/NativePlaylistEditor.h',test_evidence='PLAYLIST-01–03；TAKE-01；COMP-01/02；MIGRATE-01–04；RT-10；GUI-PLAYLIST-01；REC-02/06/08；evidence/playlist-comp/',gap='手选区间线性fade；循环/punch/quickpunch/评级/组关联comp/覆盖安全与呼吸/表演质量分析、实际模型均未完整；本轮实机状态见VERIFICATION',status='部分实现')
updates['MODEL-01'].update(implementation='schema5 Session/Audio/Aux/Master/Source/Clip/Take/Playlist/Bus/Send/Plugin/Parameter/Marker/Analysis/Transaction；clips只归属Playlist；active与target分离；source-time分析映射含Playlist ID/audible',module='src/Session.cpp；src/Playlists.cpp；src/Commands.cpp；src/Routing.cpp；src/Audio.cpp',test_evidence='MIGRATE-01–04；PLAYLIST-01–03；TAKE-01；COMP-01/02；ANALYSIS-01；REC-08',gap='schema1–4→5 已测，原文件不覆盖；Region/Automation/Tempo/Video、多坐标和长期迁移/性能仍未完成')
updates['PT-03']=dict(implementation='Main/Alternate/Comp稳定ID；Playback与Target独立；新建/复制/重命名/选择/锁定；copy-range保留源与目标两侧；原生实际源波形lane和轨头PL入口',module='src/Playlists.cpp；src/Session.cpp；include/nativedaw/NativePlaylistEditor.h；include/nativedaw/NativeWorkstation.h',reference_behavior='S3 PDF1053/1054/1055/1059/1060/1062/1077/1078/1079，印刷951起/975/977；本轮逐页核验',test_evidence='PLAYLIST-01–03；COMP-01/02；RT-10；GUI-PLAYLIST-01；evidence/playlist-comp/reference-playlist-sections.json',gap='跨轨分配/批量删除/快捷前后切换/solo-alt/评级/组关联/多选与原生inline lane高度/高级fade未完整；automation尚未实现，不宣称PT工作流全对齐',status='部分实现')
updates['AI-WF-C']=dict(implementation='真实统一命令可生成inactive候选Comp，显式源对象/样本区间/fade，支持preview/accept/Undo；无表演质量推断',module='src/Playlists.cpp；src/AI.cpp；src/Commands.cpp；include/nativedaw/NativePlaylistEditor.h',test_evidence='COMP-01/02；PLAYLIST-03；GUI-PLAYLIST-01；真实Provider端到端未执行',gap='真实模型/语音/呼吸检测与Take评分证据、自然语言comp/局部候选排序仍未完成；AI Actor测试不是实际模型',status='部分实现')
updates['STORE-01'].update(implementation='原子envelope/save/backup/journal；schema1–4 snapshot/history→5确定性主Playlist；旧文件原地不改；录音附件旧fingerprint保留',test_evidence='SAVE-01–03；MIGRATE-01–04；REC-08；COMP-02')
# Iteration 14 retains every original gap while qualifying continuous loop takes.
updates['REC-03']=dict(reference_behavior='S3 PDF860/888/889，印刷758/786/787；最小1秒、所有循环单连续文件、末轮超过半长保留、按偏好独立Playlist；Punch仍单独验收',implementation='原生Normal/Loop配置经统一命令；精确sample wrap；连续BWF逐步写盘；每轮源区间Take/Playlist，单事务Undo/幂等恢复；保留所有短末轮为明确非破坏差异',module='src/Recording.cpp；src/Audio.cpp；src/Commands.cpp；include/nativedaw/NativeRecordingSetup.h；src/Main.cpp',test_evidence='REC-LOOP-01–03；GUI-REC-01；evidence/loop-recording/reference-sections.json；physical-{release,audit}.json；desktop权限状态见VERIFICATION',gap='实际单麦克风4.5秒循环CLI已测；独立原生配置已测，GUI录音系统授权等待用户；pre/post-roll、QuickPunch/TrackPunch/DestructivePunch/循环偏好与全PT行为、多物理输入/RTT/位置校准、长时/插件/AI压力未完成',status='部分实现')
updates['REC-04'].update(implementation=updates['REC-04']['implementation']+'；循环连续源按精确样本区间生成独立Take/Playlist并保留全部partials',test_evidence=updates['REC-04']['test_evidence']+'；REC-LOOP-01–03；evidence/loop-recording/physical-{release,audit}.json',gap='手选区间线性fade及循环Take保留已测；Punch/QuickPunch/评级/组关联phase-comp/覆盖安全、呼吸/表演质量分析、真实模型未完成；GUI循环录音授权仍待验收')
updates['ENG-06']=dict(test_evidence='RT-01–10；HAL-01–04；RT-AUDIT-01；REC-LOOP-02；evidence/loop-recording/physical-audit.json；既有native-audit回执')
updates['CMD-01'].update(test_evidence=updates['CMD-01']['test_evidence']+'；REC-LOOP-01/02；GUI-REC-01')
updates['STORE-01'].update(test_evidence=updates['STORE-01']['test_evidence']+'；REC-LOOP-02（真实durable manifest/Undo后重试/重开）')
# Iteration 15: sample selection Punch is distinct from manual QuickPunch/TrackPunch.
updates['REC-02']=dict(implementation='统一arm/input/monitor/record-mode/roll命令；捕获租约固定路由及active Playlist；Punch预/后录与区间监听采样边界；干声连续BWF与单事务附件',module='src/Commands.cpp；src/Recording.cpp；src/Realtime.cpp；src/Audio.cpp；include/nativedaw/NativeRecordingSetup.h',test_evidence='REC/HAL/MON回归；REC-PUNCH-01–06；GUI-REC-02；evidence/punch-recording/physical-{release,audit}.json',gap='实际单麦克风两逻辑轨与Punch前后录短测；Normal/Loop前后录偏好、全部监听/PDC/drain、校准位置/RTT、多物理输入漂移/独立GUI录音、长期压力仍待资格验证',status='部分实现')
updates['REC-03'].update(reference_behavior=updates['REC-03']['reference_behavior']+'；S3 PDF883/884印刷781/782选区自动Punch与pre/post-roll；PDF926说明QuickPunch行为另列',implementation=updates['REC-03']['implementation']+'；选区Punch独立连续acquisition与record gate，按精确边界自动结束；全源handles/原Playlist保留，clone结果只替换实际录入交集',test_evidence=updates['REC-03']['test_evidence']+'；REC-PUNCH-01–06；GUI-REC-02；evidence/punch-recording/',gap='短实机CLI选区Punch与前后录已测；原生系统授权/实际鼠标录音待用户；QuickPunch/TrackPunch/DestructivePunch、Normal/Loop rolls/循环偏好、监控尾部PDC drain/位置校准、多个物理输入及耐久/插件/AI压力未完成')
updates['REC-04'].update(implementation=updates['REC-04']['implementation']+'；Punch全源Take+独立结果，原active/target保留；early-stop只替换实际交集/前录only保留inactive',test_evidence=updates['REC-04']['test_evidence']+'；REC-PUNCH-02–06；punch-recording/physical-{release,audit}.json',gap='手选区间线性fade、循环及选区Punch保留已测；自动交叉fade/包络切片、QuickPunch/评级/组关联phase-comp/破坏覆盖安全、呼吸/表演质量分析及真实模型仍未完成；GUI录音授权待验收')
updates['PT-02']=dict(test_evidence='官方PDF926/印刷824行为核验，evidence/punch-recording/reference-sections.json；选区Punch证据不算本行验证',gap='手动QuickPunch/逐轨TrackPunch/DestructivePunch均未实现；continuous handles是已测选区Punch策略，不冒充上述模式')
updates['ENG-06'].update(test_evidence=updates['ENG-06']['test_evidence']+'；REC-PUNCH-02/05；evidence/punch-recording/physical-audit.json')
updates['CMD-01'].update(test_evidence=updates['CMD-01']['test_evidence']+'；REC-PUNCH-01/04/06；GUI-REC-02')
updates['STORE-01'].update(test_evidence=updates['STORE-01']['test_evidence']+'；REC-PUNCH-04/06（首次冲突/Undo后人类编辑/durable restart）')
updates['QA-01']=dict(implementation='真实数值音频/工程迁移/事务/SDK故障和GUI部分鼠标回执；Release/audit/ASan-UBSan；真实AU及单麦克风短录音/文件验证',module='tests/CoreTests.cpp；tests/PunchRecordingTests.h；tests/PluginSessionTests.cpp；scripts/verify_punch_recording.py；evidence/',test_evidence='各迭代VERIFICATION与完整suite JSON/XML；punch-recording/test-builds-summary.json和physical回执',gap='完整安装制作/独立GUI输入、真实MIDI/视频/多声道/Provider、全部平台和预声明长期耐久均未通过；局部自动/实机通过不提升为完整产品验收',status='部分实现')
# Iteration16 qualifies bounded explicit linked Comp/envelopes, not general group/curve parity.
updates['EDIT-01'].update(implementation=updates['EDIT-01']['implementation']+'；schema6切片保留旧fade增益；真实共享linear/equal-power重叠交叉fade；原生包络曲线',module=updates['EDIT-01']['module']+'；src/GainEnvelope.cpp；src/CompSets.cpp',test_evidence=updates['EDIT-01']['test_evidence']+'；ENVELOPE-01/02；LINKED-COMP-01–04；evidence/linked-comp/',gap='音乐/时码/relative grid/Shuffle/Spot/nudge/通用groups/consolidate/任意交叉fade形状与编辑、Clip FX/stretch/pitch/完整comp未齐；当前仅明确源配对的关联Comp')
updates['EDIT-03']=dict(implementation='明确对象配对的关联Comp共用切点/中心fade区间；整组move不改source offsets；成员单独timing/capture拒绝',module='src/CompSets.cpp；src/GainEnvelope.cpp；src/Session.cpp；include/nativedaw/NativePlaylistEditor.h',test_evidence='LINKED-COMP-01–04；ENVELOPE-01/02；GUI-LINKED-COMP-01；evidence/linked-comp/',gap='已测已知反相数值与单麦克风双逻辑轨PCM；真实独立多麦克风、瞬态/节拍检测、Beat Detective类整理/伸缩、通用edit/mix groups未完成',status='部分实现')
updates['REC-04'].update(implementation=updates['REC-04']['implementation']+'；schema6显式多轨关联inactive Comp/linear与equal-power中心交叉fade/原包络切片',module=updates['REC-04']['module']+'；src/CompSets.cpp；src/GainEnvelope.cpp',test_evidence=updates['REC-04']['test_evidence']+'；REC-PUNCH-07；LINKED-COMP/ENVELOPE/MIGRATE-05；evidence/linked-comp/',gap='有限源配对关联Comp已测；QuickPunch/评级/通用groups/任意fade形状/独立多麦克风/组录音/覆盖安全、呼吸/表演质量分析、实际模型及GUI完整制作未完成')
updates['PT-03'].update(implementation=updates['PT-03']['implementation']+'；关联候选整组audition/restore，显式来源与revision暂存',test_evidence=updates['PT-03']['test_evidence']+'；GUI-LINKED-COMP-01；LINKED-COMP-01–04',gap='跨轨完整分配/批量删除/快捷切换/solo-alt/评级/通用组/多选/inline lane高度、任意fade与automation未完整；16原生鼠标因Mac锁定未执行')
updates['MODEL-01'].update(implementation=updates['MODEL-01']['implementation']+'；schema6 CompSet/Clip增益包络；明确源时间与共同transition区间',module=updates['MODEL-01']['module']+'；src/CompSets.cpp；src/GainEnvelope.cpp',test_evidence=updates['MODEL-01']['test_evidence']+'；ENVELOPE/LINKED-COMP；MIGRATE-05',gap='schema1–5→6保留原文件与PCM/历史已测；Region/Automation/Tempo/Video、多坐标与长期迁移/性能仍未完成')
updates['STORE-01'].update(implementation=updates['STORE-01']['implementation']+'；schema1–5→6保留插件opaque与事务lineage；关联Comp/envelope稳定ID',test_evidence=updates['STORE-01']['test_evidence']+'；MIGRATE-05；LINKED-COMP-01/04')
updates['CMD-01'].update(test_evidence=updates['CMD-01']['test_evidence']+'；LINKED-COMP-01–04；GUI-LINKED-COMP-01')
updates['AI-WF-C'].update(implementation=updates['AI-WF-C']['implementation']+'；关联Comp实际create/select/restore/move、共同中心交叉fade与source revision',module=updates['AI-WF-C']['module']+'；src/CompSets.cpp；src/GainEnvelope.cpp',test_evidence=updates['AI-WF-C']['test_evidence']+'；LINKED-COMP-04；原生widget与PCM见evidence/linked-comp/',gap='真实Provider/呼吸与表演质量分析、自然语言规划/听感/局部排序仍未完成；AI Actor及原生暂存不是真实模型')
updates['QA-01'].update(test_evidence=updates['QA-01']['test_evidence']+'；linked-comp/test-builds-summary.json与physical回执',module=updates['QA-01']['module']+'；tests/LinkedCompTests.h；scripts/verify_linked_comp.py')
# Iteration17: actual groups/multi-selection subset; no broad parity claim.
updates['SES-01']=dict(implementation='实际Audio/stereo Aux/main Master与schema7稳定Edit/Mix/Edit-Mix groups；真实成员/顺序/启用/暂停；实际volume/pan/mute/record/monitor links',module='src/Session.cpp；src/TrackGroups.cpp；src/Commands.cpp；include/nativedaw/NativeGroupEditor.h',test_evidence='GROUP-01；GROUP-MIX/BOUNDS；GUI-GROUP-01；MIGRATE-01–05；evidence/edit-groups/',gap='MIDI/Instrument/folders/VCA、多宽度/任意Master与完整组属性/区域/视图/automation/hidden-track/All group仍缺；原生17鼠标因Mac锁定未执行',reference_behavior='S1轨道范围；S3 PDF512–526/印刷410–424明确分组类型、可选属性、相对联动与parent顺序',status='部分实现')
updates['EDIT-01'].update(implementation=updates['EDIT-01']['implementation']+'；多轨/片段稳定ID选区；批量move/trim/split/gain/fades/delete与Edit group closure；真实inline inactive源Playlist',module=updates['EDIT-01']['module']+'；src/TrackGroups.cpp；include/nativedaw/EditSelection.h；include/nativedaw/NativeWorkstation.h',test_evidence=updates['EDIT-01']['test_evidence']+'；GROUP-EDIT/PHASE/BOUNDS/AI；GUI-SELECTION-01；GROUP-BENCH-01；evidence/edit-groups/',gap='全区域edit/快照剪贴板/多目标粘贴/滑移/spot/ripple/shuffle/合并整理与高级曲线/automation未完整；17鼠标/听感待验证')
updates['EDIT-03'].update(implementation=updates['EDIT-03']['implementation']+'；通用Edit组whole-clip移动/修剪与source phase/envelope保持；关联Comp完整move或显式detach后独立edit',module=updates['EDIT-03']['module']+'；src/TrackGroups.cpp',test_evidence=updates['EDIT-03']['test_evidence']+'；GROUP-PHASE-01；GROUP-COMP-01；GROUP-EDIT-01',gap='已知信号/单物理麦克风两个逻辑文件范围；独立多麦克风相位制作、瞬态/节拍整理/stretch和完整groups仍未完成')
updates['MIX-03']=dict(implementation='真实Mix group相对volume/pan及mute/record/monitor可选links；上下限记住unclipped offsets并恢复；显示顺序parent优先与单轨isolate/suspend',module='src/TrackGroups.cpp；include/nativedaw/NativeGroupEditor.h；include/nativedaw/NativeWorkstation.h；src/Main.cpp',test_evidence='GROUP-MIX-01；GROUP-BOUNDS-01；GROUP-EDIT-02；GUI-GROUP-01',gap='硬件插入/VCA/solo safe/AFL-PFL/完整monitoring、send/plugin/automation/spatial/hidden-track/All group属性与听感未实现/实测',reference_behavior='S3 PDF512–526/印刷410–424，尤其PDF524–526 group priority/offset retention；本产品group deletion可Undo，与PT明确不同',status='部分实现')
updates['PT-03'].update(implementation=updates['PT-03']['implementation']+'；Edit轨下真实inactive源lane与明确范围audition/copy-to-target入口；多选与通用groups',test_evidence=updates['PT-03']['test_evidence']+'；GUI-SELECTION-01；GROUP-EDIT/COMP',gap='批量playlist分配/删除/评级/solo-alt/完整region comp与任意fade/automation/MIDI lanes仍缺；17实际inline鼠标与试听未验证')
updates['MODEL-01'].update(implementation=updates['MODEL-01']['implementation']+'；schema7 TrackGroup/retained mix values、稳定ID选择与computed target expansion',module=updates['MODEL-01']['module']+'；src/TrackGroups.cpp；include/nativedaw/EditSelection.h',test_evidence=updates['MODEL-01']['test_evidence']+'；GROUP-01/EDIT/BOUNDS；GUI-GROUP/SELECTION',gap='schema1–6→7保留原文件/PCM/opaque/history；Region/Automation/Tempo/Video、多坐标和长期迁移仍未完成')
updates['STORE-01'].update(implementation=updates['STORE-01']['implementation']+'；schema7原子保存/重开、group relative offsets与canonical child/target IDs保留',test_evidence=updates['STORE-01']['test_evidence']+'；GROUP-01/EDIT/AI；physical-release/audit/package receipts')
updates['CMD-01'].update(implementation=updates['CMD-01']['implementation']+'；组metadata/控制/多clip命令统一解析targets、权限/资源/locks/capture/source bounds；native session identity+revision pin',module=updates['CMD-01'].get('module','src/Commands.cpp；src/AI.cpp；src/Main.cpp')+'；src/TrackGroups.cpp；include/nativedaw/NativeGroupEditor.h',test_evidence=updates['CMD-01']['test_evidence']+'；GROUP-EDIT-02；GROUP-AI-01；GUI-GROUP/SELECTION',gap='已测canonical GUI/approved AI Actor batch PCM/Undo一致，不是真实Provider；完整能力命令化、SDK/外部side-effects/人机复杂并发仍未完成')
updates['QA-01'].update(test_evidence=updates['QA-01']['test_evidence']+'；edit-groups/test-builds-summary.json、physical/source/package回执与固定128/256/512×4 NRT预算',module=updates['QA-01']['module']+'；tests/TrackGroupTests.h；tests/TrackGroupGuiTests.h；scripts/verify_edit_groups.py')
for r in rows:
 if r['id'] in updates:r.update(updates[r['id']])
(root/'docs/requirements.json').write_text(json.dumps({'version':1,'verified_on':'2026-10-05','requirements':rows},ensure_ascii=False,indent=2))
refs='''# Pro Tools parity baseline and gap matrix

核验日：2026-10-04（引擎/插件），2026-10-05（官方页面及Edit/Mix/Transport界面章节）。参考：**Pro Tools Ultimate 2026.4.1**（S2 页面列为 2026 年 7 月补丁），行为手册为 **2026.4**。S1/S2 是动态页面，资料日期未声明的部分记为核验当天页面，不推断对应未来版本。手册已下载并解析标题/目录，重点读取 PDF p319、262、860、920、959、1053；本轮精读 Aux/Master/inserts/send/PDC 的印刷 p1425–1427/1432/1443/1445/1448/1475–1480（PDF +102）；2026-10-05进一步精读PDF356/358/359/360/367/370，印刷254/256/257/258/265/268的Edit/Mix、编辑工具、Transport、数值选区；见evidence/ui-refactor/reference-window-sections.json；本轮进一步逐页读取Playlists与Target章节PDF1053/1054/1055/1059/1060/1062/1077/1078/1079，证据evidence/playlist-comp/reference-playlist-sections.json。2026-10-05另实际读取PDF1035/1036/1046（印刷933/934/944）equal-gain/equal-power与跨轨fade编辑，见evidence/linked-comp/reference-sections.json。迭代17进一步实际读取分组PDF512–526（印刷410–424），记录类型/属性/parent优先/上下限relative offsets；evidence/edit-groups/reference-sections.json。其余行为继续逐章核验，目录定位不等于已精读。资料与运行行为验证分开。

| 来源 | 资料版本/日期 | 链接和核验结果 |
|---|---|---|
| S1 comparison | 页面未明确版本；2026-10-05 核验 | [官方 comparison](https://www.avid.com/pro-tools/comparison)，确认五类范围及特定 Ultimate 能力 |
| S2 what's new | 2026.4.1 / July 2026；2026.4 / April 2026 | [官方 what's new](https://www.avid.com/pro-tools/whats-new)，与 comparison 中新增沉浸式/STT 能力交叉核验 |
| S3 reference guide | version 2026.4，2221 PDF pages | [官方 2026.4 手册](https://resources.avid.com/SupportFiles/PT/Pro_Tools_Reference_Guide_2026.4.pdf)；SHA256 `884307db872723dbddf8cad3897b47d9b36fface96636ecc8bc49de46792f8a8`；章节页码见 `evidence/reference-manual-sections.json` 和 `evidence/routing-reference-manual.json`。PDF 页码与印刷页码有偏移 |
| S4 AAX development | 页面未声明版本；2026-10-04 核验 | [AAX SDK](https://developer.avid.com/aax/)，公开页面描述插件开发；未下载或接受 click-through 许可 |
| S5 scripting development | 页面未声明版本；2026-10-04 核验 | [Scripting SDK](https://developer.avid.com/scripting/)，运行中的 PT 自动化 API；不是独立 DAW 底座；详细 SDK 文档在许可入口后，未取得 |
| S6 EUCON development | 页面未声明版本；2026-10-04 核验 | [EUCON Application SDK](https://developer.avid.com/eucon/)，官方评价工具入口；详细文档/商业授权未取得 |

状态仅使用：**未实现 / 部分实现 / 待实测 / 已验证 / 外部依赖阻塞**。测试编号链接 `tests/CoreTests.cpp` / `tests/RoutingTests.h`，实测回执链接 `docs/VERIFICATION.md` 及 `evidence/`。单个单元测试通过不提升整行专业工作流状态。未实现项的“规划”模块是分工位置，不是已存在的代码。没有合法运行的 Pro Tools 基准；尚无性能、音质、兼容性已对齐的结论。

循环录音基线精读 PDF860/888/889（印刷758/786/787），证据 `evidence/loop-recording/reference-sections.json`。迭代15进一步精读 PDF883/884（印刷781/782）选区自动Punch/pre-post-roll和PDF926（印刷824）QuickPunch/TrackPunch区别，见 `evidence/punch-recording/reference-sections.json`。真实模型、原生麦克风授权流程、手动Punch/破坏模式、Normal/Loop rolls与完整录音偏好仍列差距；已测选区Punch不等于全部PT模式对齐。

本文件由 `scripts/update_parity.py` 与 `docs/requirements.json` 同源生成。所有未完成要求保留于最终验收，阶段成果不算最终交付。
'''
headers={1:'1. 通用专业 DAW 能力（含用户追加的 AI-native 要求）',2:'2. Pro Tools 具体工作流行为',3:'3. 专有工程格式与插件生态兼容',4:'4. 专用硬件、第三方授权和认证',5:'5. 捆绑软件、素材及在线服务'}
text=refs
for category,title in headers.items():
 text+='\n## '+title+'\n\n| ID / 工作流 | 参考行为 | 实现方式 / 模块 | 验收步骤 | 测试证据 | 当前差距 | 外部依赖 | 状态 |\n|---|---|---|---|---|---|---|---|\n'
 for r in rows:
  if r['category']==category:
   cells=[r['id']+' '+r['feature'],r['reference_behavior'],r['implementation']+'；'+r['module'],r['acceptance'],r['test_evidence'],r['gap'],r['external_dependencies'],r['status']]
   text+='| '+' | '.join(str(c).replace('|',' / ').replace('\n',' ') for c in cells)+' |\n'
(root/'docs/PRO_TOOLS_PARITY.md').write_text(text)
print(f'Wrote {len(rows)} retained requirements across five categories')
